Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2018-11, with the labels that each got.

#2296 Removed the preview from the master node
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/MasterNode.cs
Labels: Shader Graph

#2181 LWRP docs repo merge
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Documentation~/Configuring-LWRP-for-use.md
  com.unity.render-pipelines.lightweight/Documentation~/Getting-started-with-LWRP.md
  com.unity.render-pipelines.lightweight/Documentation~/GettingStarted.md
  com.unity.render-pipelines.lightweight/Documentation~/Images/AssetShots/Beauty/Overview.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/StdPhysicallyBased.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/StdSimpleLighting.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/StdUnlit.png
  com.unity.render-pipelines.lightweight/Documentation~/Installing-LWRP-into-an-existing-Project.md
  com.unity.render-pipelines.lightweight/Documentation~/LWRP-builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/Lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/Simple-Lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/TableOfContents.md
  com.unity.render-pipelines.lightweight/Documentation~/Unlit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/autodesk-interactive-masked-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/autodesk-interactive-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/autodesk-interactive-transparent-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/baked-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/camera-inspector.md
  com.unity.render-pipelines.lightweight/Documentation~/camera.md
  com.unity.render-pipelines.lightweight/Documentation~/creating-a-new-project-with-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/faq.md
  com.unity.render-pipelines.lightweight/Documentation~/forward-renderer.md
  com.unity.render-pipelines.lightweight/Documentation~/images/GraphicsSettings_LW.jpg
  com.unity.render-pipelines.lightweight/Documentation~/images/LWPipelineAsset.jpg
  com.unity.render-pipelines.lightweight/Documentation~/images/LWPipelineShaders.png
  com.unity.render-pipelines.lightweight/Documentation~/images/MaterialUpgraders.png
  com.unity.render-pipelines.lightweight/Documentation~/images/Nightmares.png
  com.unity.render-pipelines.lightweight/Documentation~/index.md
  com.unity.render-pipelines.lightweight/Documentation~/inside-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/integration-with-post-processing.md
  com.unity.render-pipelines.lightweight/Documentation~/integration-with-terrain.md
  com.unity.render-pipelines.lightweight/Documentation~/integrations-with-shader-graph.md
  com.unity.render-pipelines.lightweight/Documentation~/light-inspector.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-asset.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-internal-flowchart.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp.builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-baked-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-simple-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/shader-stripping-keywords.md
  com.unity.render-pipelines.lightweight/Documentation~/shader-stripping.md
  com.unity.render-pipelines.lightweight/Documentation~/shaders-in-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/shading-model.md
  com.unity.render-pipelines.lightweight/Documentation~/upgrading-your-shaders.md
  com.unity.shadergraph/Editor/Data/Nodes/Graphics.meta
Labels: docs, lwrp

#2327 Show and Hide blackboard and main preview
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph

#2336 Remove Graphics.meta
  com.unity.shadergraph/Editor/Data/Nodes/Graphics.meta
Labels: Shader Graph, high-priority

#2341 Fixed broken link
  com.unity.render-pipelines.lightweight/Documentation~/autodesk-interactive-masked-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/autodesk-interactive-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/autodesk-interactive-transparent-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/baked-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/camera-inspector.md
  com.unity.render-pipelines.lightweight/Documentation~/camera.md
  com.unity.render-pipelines.lightweight/Documentation~/forward-renderer.md
  com.unity.render-pipelines.lightweight/Documentation~/integration-with-post-processing.md
  com.unity.render-pipelines.lightweight/Documentation~/integration-with-terrain.md
  com.unity.render-pipelines.lightweight/Documentation~/integrations-with-shader-graph.md
  com.unity.render-pipelines.lightweight/Documentation~/light-inspector.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-internal-flowchart.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-baked-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-simple-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/shader-stripping-keywords.md
Labels: docs, lwrp

#2326 Lw/respect mobile player settings
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/Passes/AdditionalLightsShadowCasterPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/MainLightShadowCasterPass.cs
  com.unity.render-pipelines.lightweight/Runtime/ShadowUtils.cs
Labels: lwrp

#2346 Fix shader include path causing compilation error in BoatAttack
  com.unity.render-pipelines.lightweight/Shaders/Utils/CopyDepth.shader
Labels: lwrp

#2332 Made shadowcascadegui internal to lwrp
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineEditorUtils.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineEditorUtils.cs.meta
  com.unity.render-pipelines.lightweight/Editor/Shadow.meta
  com.unity.render-pipelines.lightweight/Editor/Shadow/ShadowCascadeSplitGUI.cs
  com.unity.render-pipelines.lightweight/Editor/Shadow/ShadowCascadeSplitGUI.cs.meta
Labels: lwrp

#2304 Sg/exposed property ui enhancements
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
Labels: Shader Graph

#2343 Fixing compilation error on the fabric shader graph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/M_CottonWoolShaderGraph.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/M_CottonWoolShaderGraphCutoff.ShaderGraph
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
Labels: Shader Graph, bug-fix

#2315 Screen space refraction settings cleanup and share fade function with SSR
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1101_Unlit.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1203_Lit_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1206_Lit_Transparent_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Refraction.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ScreenSpaceLightingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ScreenSpaceLightingEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ScreenSpaceRefractionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceRefraction.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ShaderVariablesScreenSpaceLighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, backport-2018.3

#2347 Fix generate header hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitReference.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
Labels: HDRP

#2328 Add version control checkout to Shader Graph
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
Labels: Shader Graph, bug-fix

#2333 Fix color pyramid MIP count computation & expose a problem with MIP chains and viewport scale
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1206_Lit_Transparent_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1206_Lit_Transparent_Distortion.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
Labels: HDRP

#2338 C# shader variables
  com.unity.render-pipelines.high-definition/Editor/Core/ShaderGenerator/ShaderTypeGeneration.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/ShaderGenerator/ShaderGeneratorAttributes.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ShaderVariablesAtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ShaderVariablesAtmosphericScattering.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ShaderVariablesAtmosphericScattering.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ShaderVariablesAtmosphericScattering.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ShaderVariablesAtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ShaderVariablesScreenSpaceLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ShaderVariablesScreenSpaceLighting.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ShaderVariablesScreenSpaceLighting.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ShaderVariablesScreenSpaceLighting.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ShaderVariablesScreenSpaceLighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/ShaderVariablesSubsurfaceScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/ShaderVariablesSubsurfaceScattering.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/ShaderVariablesSubsurfaceScattering.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/ShaderVariablesSubsurfaceScattering.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/ShaderVariablesSubsurfaceScattering.hlsl
Labels: HDRP

#2334 Restructure how async compute is handled and move SSR+SSAO to Async
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDGPUAsyncTask.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDGPUAsyncTask.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#2361 LW enable postprocessing for XR (case 1087137)
  com.unity.render-pipelines.lightweight/Runtime/DefaultRendererSetup.cs
Labels: XR, lwrp

#2362 Move a variable unused in player inside #if EDITOR branch
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
Labels: HDRP

#2364 Removed hack done for multi camera support.
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/CamRT_1.renderTexture
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/CamRT_1.renderTexture.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/CamRT_2.renderTexture
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/CamRT_2.renderTexture.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/Mat_RT1.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/Mat_RT1.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/Mat_RT2.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/Mat_RT2.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/PostProcessVolume_Layer1 Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/PostProcessVolume_Layer1 Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/PostProcessVolume_Layer2 Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/PostProcessVolume_Layer2 Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/PostProcessVolume_Layer3 Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9202_Multi-Cam-RT/PostProcessVolume_Layer3 Profile.asset.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2370 Fix script compilation error happening in stand-alone
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
Labels: lwrp

#2371 PCSS sampling improvements
  com.unity.render-pipelines.core/ShaderLibrary/Random.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/HDShadow.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDPCSS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/PCSS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#2365 Fix d3d warnings
  com.unity.render-pipelines.core/ShaderLibrary/API/D3D11.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Vulkan.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ShadowClear.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalNormalBuffer.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDepthOnly.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/CopyStencilBuffer.shader
Labels: HDRP, backport-2018.3

#2357 Backport Fix color pyramid mip (#2333)
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png.orig
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png.orig
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png.orig
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1206_Lit_Transparent_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1206_Lit_Transparent_Distortion.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png.orig
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
Labels: HDRP, backport-2018.3

#2374 fix simple lit shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
Labels: HDRP

#2375 Fabric Shader Graph Fix
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
Labels: HDRP, bug-fix

#2380 merge Hdrp/staging
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDPCSS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, backport-2018.3

#2356 Evaluate fog using distance rather than depth
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/SkySettings/HDRP_Default_Sky_LinearFog.asset
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8104_Unlit.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8201_VertexAnimation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8201_VertexAnimation.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8204_CustomSpecOcclusion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9101_Density-volumes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/VolumeRendering.hlsl
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/AtmosphericScatteringEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/ExponentialFogEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/LinearFogEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ShaderVariablesAtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ShaderVariablesAtmosphericScattering.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/VolumetricFog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-clustered.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLightingController.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/VisualEnvironment.cs
Labels: HDRP

#2384 Lightloop scalarization rebased on master
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
Labels: HDRP

#2389 Backport of 2356 (depth for fog) + 2384 (scalarization of lightloop)
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/SkySettings/HDRP_Default_Sky_LinearFog.asset
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8201_VertexAnimation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9101_Density-volumes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/VolumeRendering.hlsl
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/StandardsToHDLitMaterialUpgrader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/AtmosphericScatteringEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/ExponentialFogEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/LinearFogEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ShaderVariablesAtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ShaderVariablesAtmosphericScattering.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/VolumetricFog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-clustered.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLightingController.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/VisualEnvironment.cs
Labels: HDRP

#2388 Hdrp/better fix EnumField in DebugMenu
  com.unity.render-pipelines.high-definition/Editor/Core/Debugging/DebugUIDrawer.Builtins.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/DebugUI.Fields.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/Prefabs/Scripts/DebugUIHandlerEnumField.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/MaterialDebug.cs
Labels: HDRP

#2393 Transparent MSAA Support
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/MSAATestPrefab.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/M_TransparentBlueLit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/M_TransparentBlueLit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardBoth/HDRP_Test_Def_MSAABoth.asset
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backport-2018.3

#2399 Lwrp documentation changes
  com.unity.render-pipelines.lightweight/Documentation~/configuring-lwrp-for-use.md
  com.unity.render-pipelines.lightweight/Documentation~/creating-a-new-project-with-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/getting-started-with-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/inside-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/installing-lwrp-into-an-existing-project.md
  com.unity.render-pipelines.lightweight/Documentation~/lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-asset.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp.builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-unlit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/realtime-lighting-in-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/rendering-in-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/shader-stripping.md
  com.unity.render-pipelines.lightweight/Documentation~/shaders-in-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/shading-model.md
  com.unity.render-pipelines.lightweight/Documentation~/simple-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/unlit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/upgrading-your-shaders.md
Labels: docs, lwrp

#2396 Lw/bugfix/1097497
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: lwrp, needs-backport-2018.3

#2335 Fix instancing defines in HD ShaderGraph shaders
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/UnityInstancing.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
Labels: HDRP, Shader Graph, bug-fix

#2401 Wave intrinsics renaming to match SM 6.0
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/GGXConvolution/BuildProbabilityTables.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScattering.compute
Labels: HDRP

#2405 Backport: Fix Shader Graph UV dimension when used in VS
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/VertexAnimation.template.hlsl
Labels: HDRP, Shader Graph, backport-2018.3, bug-fix

#2403 Backport: Fix instancing defines in HD Shader Graph Shaders
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/UnityInstancing.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
Labels: HDRP, Shader Graph, backport-2018.3, bug-fix

#2404 Fix Shader Graph UV dimension when used in VS
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/VertexAnimation.template.hlsl
Labels: HDRP, Shader Graph, bug-fix

#2366 Multiple Fixes
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightPBRExtraPasses.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightUnlitExtraPasses.template
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.lightweight/ShaderLibrary/MetaInput.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/Shadows.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Lit.shader
  com.unity.render-pipelines.lightweight/Shaders/ShadowCasterPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitBase.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitPasses.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Utils/Blit.shader
  com.unity.testing.srp.lightweight/Tests/CommonAssets/LightweightRenderPipelineAsset.asset
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/005_LitBakedEmission.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/028_PostProcessing_Custom.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/040_UpgradeScene.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/046_Camera_OpaqueTexture.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/052_LWCallbacks.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/052_LWCallbacks.png.meta
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/054_Lighting_Attenuation.png.meta
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/005_LitBakedEmission.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/040_UpgradeScene.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/046_Camera_OpaqueTexture.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/052_LWCallbacks.png
  com.unity.testing.srp.lightweight/Tests/Scenes/005_LitBakedEmission.unity
  com.unity.testing.srp.lightweight/Tests/Scenes/005_LitBakedEmission.unity.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/050_Shader_Graphs/Graphs/Unlit_Cutout.ShaderGraph
  com.unity.testing.srp.lightweight/Tests/Scenes/050_Shader_Graphs/Graphs/Unlit_Maps.ShaderGraph
  com.unity.testing.srp.lightweight/Tests/Scenes/052_LWCallbacks.unity.meta
Labels: lwrp

#2410 WaveActive[All/Any]True and improve scalarized lightloop fast path decision making
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
Labels: HDRP

#2411 Wait on start fence only if it has been pushed on <19.1 as well
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDGPUAsyncTask.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backport-2018.3

#2412 Hdrp/clean hdlighteditor
  com.unity.render-pipelines.core/Editor/CoreEditorDrawers.cs
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/Resources.meta
  com.unity.render-pipelines.core/Editor/Resources/Advanced_Pressed_mini.png
  com.unity.render-pipelines.core/Editor/Resources/Advanced_Pressed_mini.png.meta
  com.unity.render-pipelines.core/Editor/Resources/Advanced_UnPressed_mini.png
  com.unity.render-pipelines.core/Editor/Resources/Advanced_UnPressed_mini.png.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.ContextualMenu.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.ContextualMenu.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/ProxyVolumeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/ReflectionProxyVolumeComponentUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/CaptureSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDecalSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/LightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
Labels: HDRP

#2417 Disable SG transparent test scene (shadey keywords overload)
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#2420 Remove Expression.Variable not existing yet in .Net3.5
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP, backport-2018.3

#2421 Fix displayed FrameSettings in HDRPAsset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
Labels: HDRP

#2423 Fix mirror gizmo rotaion
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeUI.Handles.cs
Labels: HDRP

#2424 Remove false dependency between all HDRP materials and shaders
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPassForward.template
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewMaterialGBuffer.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Deferred.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/builddispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/materialflags.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Lighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Material.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialGBufferMacros.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialGBufferMacros.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXLit.cginc
Labels: HDRP

#2360 Fix terrain tangent frame
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal/1602 Terrain.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal/1602 Terrain.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal/FourShapesLayer.terrainlayer
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal/FourShapesLayer.terrainlayer.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal/FourShapesMaterial.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal/FourShapesMaterial.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1601_TerrainLit.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1602_TerrainLit_Normal.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1602_TerrainLit_Normal.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitDataMeshModification.hlsl
Labels: HDRP, backport-2018.3

#2427 Merge Hdrp/staging
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.visualeffectgraph/Editor/Resources/VFXLabeledField.uss
Labels: HDRP, backport-2018.3

#2425 Backport: Remove false dependency between all HDRP materials and shaders (#2402)
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2401_Light_on_Tesselation/Tess_Displace.mat
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Light_on_Tesselation.png
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPassForward.template
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewMaterialGBuffer.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Deferred.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/builddispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/materialflags.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Lighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Material.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialGBufferMacros.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialGBufferMacros.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXLit.cginc
Labels: HDRP

#2416 Lw/bugfix/1097667
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/ShaderLibrary/MetaInput.hlsl
Labels: lwrp

#2299 Physical camera fixes
  com.unity.render-pipelines.high-definition/Editor/Core/CameraEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraEditor.Handlers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/SerializedHDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Utilities/GeometryUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/ReflectionSystemInternal.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/IBLFilterCharlie.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/GGXConvolution/IBLFilterGGX.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
Labels: HDRP, needs-backport-2018.3

#2408 Internalize Scriptable Render Passes
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/AssemblyInfo.cs
  com.unity.render-pipelines.lightweight/Runtime/AssemblyInfo.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/Passes/AdditionalLightsShadowCasterPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/BeginXRRenderingPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CopyColorPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CopyDepthPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CreateColorRenderTexturesPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CreateLightweightRenderTexturesPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/DepthOnlyPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/DrawSkyboxPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/EndXRRenderingPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/MainLightShadowCasterPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderOpaqueForwardPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderTransparentForwardPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/SceneViewDepthCopy.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/ScreenSpaceShadowResolvePass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/SetupForwardRenderingPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/SetupLightweightConstanstPass.cs
Labels: lwrp

#2435 disabled test 045 and removed custom LW script from scene.
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe.unity
Labels: lwrp

#2395 Fix folder exception
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporterEditor.cs
Labels: Shader Graph, bug-fix

#2390 PBR Node cleanup
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
Labels: HDRP, Shader Graph, needs-backport-2018.3

#2433 Review of HDRP changelog
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#2446 Reverted custom-renderer-asset branch.
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRendererSetup.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/LWRPAdditionalCameraData.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipelineCore.cs
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe.unity
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomLWPipe.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomLWPipe.asset.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomLWPipe.cs
Labels: lwrp

#2454 Hdrp/fix pyramid spotlight gizmo
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Core/Lighting/CoreLightEditorUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs
Labels: HDRP

#2436 VFX fix exposed behavior *Waiting for PR (in trunk merge queue...)* (CreateComponentWithAllBasicTypeExposed)
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXComponentTest.cs
  com.unity.visualeffectgraph/Editor/Inspector/VisualEffectEditor.cs
Labels: vfx

#2457 Fix for Exception when opening unity after having closed it with a vf…
  com.unity.visualeffectgraph/Editor/Utils/VFXResources.cs
Labels: vfx

#2463 Remove shadow map variant (change directional shadow + punctual to si…
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/BaseShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDShadowInitParameters.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassForward.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Quad/PassForward.template
Labels: HDRP

#2474 backport: Remove shadow map variant (#2458)
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/BaseShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDShadowInitParameters.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassForward.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Quad/PassForward.template
Labels: HDRP

#2438 Hdrp/fix debug drawline ztest
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessBuild.cs
  com.unity.render-pipelines.high-definition/Editor/Material/DiffusionProfile/DiffusionProfileSettingsEditor.Styles.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/CopyDepthBuffer.shader
Labels: HDRP

#2456 Refraction misc fixes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceRefraction.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitDataIndividualLayer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#2376 Group node
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/AbstractMaterialGraph.cs
  com.unity.shadergraph/Editor/Data/Graphs/GroupData.cs
  com.unity.shadergraph/Editor/Data/Graphs/GroupData.cs.meta
  com.unity.shadergraph/Editor/Data/Graphs/NodeGroupChange.cs
  com.unity.shadergraph/Editor/Data/Graphs/NodeGroupChange.cs.meta
  com.unity.shadergraph/Editor/Data/Interfaces/Graph/IGraph.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ShaderGroup.cs
  com.unity.shadergraph/Editor/Drawing/Views/ShaderGroup.cs.meta
  com.unity.shadergraph/Editor/Util/CompatibilityExtensions.cs
  com.unity.shadergraph/Editor/Util/CopyPasteGraph.cs
  com.unity.shadergraph/Tests/Editor/UnitTests/SerializedGraphTests.cs
Labels: Shader Graph

#2329 Lw/batcherimprovements [DO NOT MERGE YET]
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightPBRSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightUnlitSubShader.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderOpaqueForwardPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderTransparentForwardPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/ScriptableRenderPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/SetupLightweightConstanstPass.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/UnityInput.hlsl
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomLWPipe.cs
Labels: lwrp

#2460 HDRP stereo fixes for refraction, SSS and atmospheric scattering
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, XR

#2484 Save Debug Menu enum resetting
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Camera/CameraSwitcher.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/DebugUI.Fields.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#2472 Change VBuffer depth parametrization
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9101_Density-volumes/Scene Settings Profile.asset
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLightingController.cs
Labels: HDRP

#2479 Contact shadows and volumetric to async
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#2462 Camera freeze debug mode
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2455 Postprocessed gizmos
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/GizmoRenderingPass.cs
Labels: HDRP, lwrp

#2471 Add more shader stripping opportunities
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/Material/BaseShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
Labels: HDRP

#2487 Fix ordering of args in bitfield wave intrinsics on xbox
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
Labels: HDRP

#2354 LW Handle final blit in SRP
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipelineCore.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.lightweight/Shaders/Utils/Blit.shader
Labels: lwrp

#2480 Merge Hdrp/staging
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/VisualEnvironmentEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Camera/CameraSwitcher.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/DebugUI.Fields.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitDataIndividualLayer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap_Gen.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.shader
Labels: HDRP

#2489 fix compiler errors
  com.unity.render-pipelines.lightweight/Runtime/Passes/GizmoRenderingPass.cs
Labels: lwrp

#2481 new manifests for test projects with all needed dependencies
  TestProjects/HDRP_Tests/Packages/manifest.json
  TestProjects/LWGraphicsTest/Packages/manifest.json
  TestProjects/PostProcessing/Packages/manifest.json
  TestProjects/ShaderGraph/Packages/manifest.json
  TestProjects/VisualEffectGraph/Assets/NewBehaviourScript.cs
  TestProjects/VisualEffectGraph/Packages/manifest.json
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/ChangeSpace.cs
  com.unity.visualeffectgraph/Editor/Utilities/pCache/BakeTool/PointCacheBakeTool.Mesh.cs
  com.unity.visualeffectgraph/Utilities/Playables/VisualEffectActivation/VisualEffectActivationBehaviour.cs
Labels: HDRP, Shader Graph, lwrp, vfx

#2492 HDRP - add support for LuxAt unit for punctual light + misc fix
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightUtils.cs
Labels: HDRP, backport-2018.3

#2495 udpated test scene 013 to fix katana
  com.unity.testframework.graphics/Editor/SetupGraphicsTestCases.cs
  com.unity.testing.srp.lightweight/Tests/Scenes/013_CameraMulti_Splitscreen.unity
Labels: lwrp

#2497 Fix Overridden State
  com.unity.visualeffectgraph/Editor/Inspector/VisualEffectEditor.cs
Labels: bug-fix, vfx

#2500 make timeline great again.
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXContextTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXConverterTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXDebugExpressionTest.cs
  TestProjects/VisualEffectGraph/Assets/NewBehaviourScript.cs
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/HDRPFogVolumetric.png.meta
  TestProjects/VisualEffectGraph/Packages/manifest.json
  com.unity.visualeffectgraph/Editor/Unity.VisualEffectGraph.Editor.asmdef
  com.unity.visualeffectgraph/Editor/Utilities/VisualEffectActivationBehaviourInspector.cs
  com.unity.visualeffectgraph/Unity.VisualEffectGraph.Runtime.asmdef
  com.unity.visualeffectgraph/Utilities/Playables/VisualEffectActivation/VisualEffectActivationBehaviour.cs
  com.unity.visualeffectgraph/Utilities/Playables/VisualEffectActivation/VisualEffectActivationClip.cs
  com.unity.visualeffectgraph/Utilities/Playables/VisualEffectActivation/VisualEffectActivationMixerBehaviour.cs
  com.unity.visualeffectgraph/Utilities/Playables/VisualEffectActivation/VisualEffectActivationTrack.cs
Labels: bug, vfx

#2499 Fix forward clustered lighting with stereo rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForward.hlsl
  com.unity.visualeffectgraph/Editor/Resources/VFXLabeledField.uss
Labels: HDRP, XR

#2505 Fix FrameSettings broke the hdrpAssetInspector
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
Labels: HDRP

#2431 Renable 01_animator *Waiting for PR*
  TestProjects/VisualEffectGraph/ProjectSettings/EditorBuildSettings.asset
Labels: vfx

#2504 fix for capacity not updated.
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXBasicInitialize.cs
Labels: bug, vfx

#2509 Minor Changes in VFXAsset Inspector
  com.unity.visualeffectgraph/Editor/Inspector/VFXAssetEditor.cs
Labels: enhancement, vfx

#2501 contexts offset when mousereleased and other misc pixelfucking
  com.unity.visualeffectgraph/Editor/GraphView/Elements/VFXContextUI.cs
  com.unity.visualeffectgraph/Editor/GraphView/Elements/VFXNodeUI.cs
  com.unity.visualeffectgraph/Editor/Resources/GradientBorder.shader
  com.unity.visualeffectgraph/Editor/Resources/GradientDashedBorder.shader
  com.unity.visualeffectgraph/Editor/Resources/PropertyRM.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXContext.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXControls.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXDataAnchor.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXNode.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXParameter.uss
  com.unity.visualeffectgraph/Editor/Templates/Empty Particle System.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Particle System.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Static Mesh.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Swarm Particle System.vfx
Labels: vfx

#2381 Error Handling for Shader Graph
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/AbstractMaterialGraph.cs
  com.unity.shadergraph/Editor/Data/Graphs/MaterialGraphAsset.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphAssetPostProcessor.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Util/MessageManager.cs
  com.unity.shadergraph/Editor/Util/MessageManager.cs.meta
  com.unity.shadergraph/Tests/Editor/UnitTests/MessageManagerTests.cs
  com.unity.shadergraph/Tests/Editor/UnitTests/MessageManagerTests.cs.meta
  com.unity.shadergraph/Tests/Editor/UnitTests/SerializedGraphTests.cs
Labels: Shader Graph

#2324 Making it possible for recorder to capture camera rendering with SRP.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/CameraCaptureBridge.cs
  com.unity.render-pipelines.lightweight/Runtime/CameraCaptureBridge.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipelineCore.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CapturePass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CapturePass.cs.meta
Labels: lwrp

#2517 Removed canvas from shader graph test scenes
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Scripts/ShaderGraphTestSceneController.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Scripts/TestSceneCanvasController.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Scripts/TestSceneCanvasController.cs.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8104_Unlit.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8202_BentNormals.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8203_Emission.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/Common/CanvasUI.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/Common/CanvasUI.prefab.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/ReadMe.txt
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8203_Emission.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8203_Emission.png.meta
Labels: HDRP

#2344 Minor Shader Graph fixes #2
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Utility/ColorspaceConversion.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
  com.unity.shadergraph/Editor/Drawing/Controls/SliderControl.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ColorControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/SliderControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/MaterialNodeView.uss
Labels: Shader Graph, bug-fix

#2426 Fix for [case 1098749] and addition of stereo macros to templates
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/Blit.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.shader
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightPBRExtraPasses.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightPBRForwardPass.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightUnlitExtraPasses.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightUnlitPass.template
  com.unity.render-pipelines.lightweight/Shaders/Utils/CopyDepthPass.hlsl
Labels: HDRP, Shader Graph

#2516 Fix and cleanup pass on HDRP master node (Unlit, Fabric, lit, stacklit, PBR)
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/CreateHDLitShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPassForward.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData_Basemap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/VaryingMesh.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
  com.unity.shadergraph/Editor/Data/MasterNodes/UnlitMasterNode.cs
Labels: HDRP, backport-2018.3

#2514 Switch support
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/ColorPyramidPS.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/ColorPyramidPS.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#2524 Fix for Mac : return float4 in frag shader function even for depth pr…
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleLines/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleLinesSW/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleQuads/PassDepth.template
Labels: vfx

#2406 Lw/saved bool
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Editor/SavedBool.cs
  com.unity.render-pipelines.lightweight/Editor/SavedBool.cs.meta
Labels: lwrp

#2528 Backport: Fix and cleanup pass on HDRP master node (Unlit, Fabric, lit, stacklit, PBR)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/CreateHDLitShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPassForward.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData_Basemap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/VaryingMesh.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
  com.unity.shadergraph/Editor/Data/MasterNodes/UnlitMasterNode.cs
Labels: HDRP

#2534 PCSS and Debug Light Volumes fix
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
Labels: HDRP, backport-2018.3

#2523 Vfx/fix/float4 depth prepass
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleLines/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleLinesSW/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleQuads/PassDepth.template
Labels: vfx

#2531 Fixup relative paths in HDRP
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/EntityLighting.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/ImageBasedLighting.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/SampleUVMapping.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/SampleUVMappingInternal.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/Sampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/SimpleLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-clustered.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowContext.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Builtin/BuiltinData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalNormalBuffer.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/GGXConvolution/GGXConvolve.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/PreIntegratedFGD/PreIntegratedFGD.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/PreIntegratedFGD/preIntegratedFGD_GGXDisneyDiffuse.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScattering.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData_Basemap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitSplatCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap_Gen.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDepthOnly.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDistortion.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForwardUnlit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassGBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassLightTransport.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassVelocity.hlsl
Labels: HDRP

#2355 Forward Opaque pass LoadActions
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/Passes/CreateLightweightRenderTexturesPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderOpaqueForwardPass.cs
Labels: lwrp, needs-backport-2018.3

#2530 Lw/fix gizmos error
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/Passes/GizmoRenderingPass.cs.meta
Labels: lwrp

#2515 Use ERROR_ON_UNSUPPORTED_FUNCTION instead of ERROR_ON_UNSUPPORTED_FUNC
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES2.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.lightweight/CHANGELOG.md
Labels: lwrp

#2527 Fix and cleanup pass on HDRP master node (Unlit, Fabric, lit, stacklit, PBR)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/CreateHDLitShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPassForward.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData_Basemap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/VaryingMesh.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
  com.unity.shadergraph/Editor/Data/MasterNodes/UnlitMasterNode.cs
Labels: HDRP, backport-2018.3
