Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2018-10, with the labels that each got.

#1943 OcclusionMesh for SRP VR + HDRP XRGraphicsConfig hookup fix
  com.unity.render-pipelines.core/Editor/XRGraphicsConfigDrawer.cs
  com.unity.render-pipelines.core/Runtime/Common/XRGraphicsConfig.cs
  com.unity.render-pipelines.core/Runtime/Utilities.meta
  com.unity.render-pipelines.core/Runtime/Utilities/XRUtils.cs
  com.unity.render-pipelines.core/Runtime/Utilities/XRUtils.cs.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/Passes/DepthOnlyPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderOpaqueForwardPass.cs
Labels: HDRP, lwrp

#2029 Screen Space Shadows Improvements
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2304_Contact_Shadow_DirectionalLight.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2304_Contact_Shadow_DirectionalLight/ContactShadowsProfile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2305_Contact_Shadow_PointLight.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2306_Contact_Shadow_SpotLight.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2304_Contact_Shadow_DirectionalLight.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2305_Contact_Shadow_PointLight.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2306_Contact_Shadow_SpotLight.png
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2065 Tests/framework/fixes
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/TestRunner/HDRP_GraphicTestRunner.cs
  com.unity.testframework.graphics/Editor/TestResultWindow.cs
  com.unity.testframework.graphics/Runtime/EditorGraphicsTestCaseProvider.cs
  com.unity.testframework.graphics/Runtime/IGraphicsTestCaseProvider.cs
  com.unity.testframework.graphics/Runtime/ImageAssert.cs
  com.unity.testframework.graphics/Runtime/RuntimeGraphicsTestCaseProvider.cs
  com.unity.testframework.graphics/Runtime/UseGraphicsTestCasesAttribute.cs
Labels: HDRP

#2071 Send missing stereo informations to compute shaders
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesMatrixDefsHDCamera.hlsl
Labels: HDRP

#2093 Fix shadow near plane limit
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
Labels: HDRP

#2100 Add guard for 2019.1 function to stay compatible with 2018.3
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: SRP

#2086 Hdrp/add reflection profile
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Toolbar.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Toolbar.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditorUtility.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedHDProbe.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedHDReflectionProbe.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedPlanarReflectionProbe.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/CaptureSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/CaptureSettingsUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/LightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableSettingsArea.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableSettingsArea.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedCaptureSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedCaptureSettings.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedLightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/ReflectionSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/ReflectionSystemInternal.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/CaptureSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/CaptureSettings.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#2101 Add instancing support on unlit shader graph
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPassForward.template
Labels: HDRP, SRP

#2079 Hdrp/fix/material colapsed state serialized
  com.unity.render-pipelines.high-definition/Editor/Material/AxF/AxFUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/ExpendableAreaMaterial.cs
  com.unity.render-pipelines.high-definition/Editor/Material/ExpendableAreaMaterial.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/FabricUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/BaseLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/BaseMaterialUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/StackLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/TerrainLit/TerrainLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
Labels: HDRP

#2108 Fix sorting on PS4
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#2107 fix light gizmo when inspector locked
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
Labels: HDRP

#2105 Add missing area light handle
  com.unity.render-pipelines.high-definition/Editor/Core/Lighting/CoreLightEditorUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
Labels: HDRP

#2110 Hdrp/check caches size in hdrp asset
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbeCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/ReflectionProbeCache.cs
Labels: HDRP

#2102 Add a debug mode to display only one shadow at once
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#2103 Replace ExecuteInEditMode by ExecuteAlways
  com.unity.render-pipelines.core/Runtime/Volume/Volume.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Camera/FreeCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/MousePositionDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/Prefabs/Scripts/UIFoldout.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Utilities/SceneRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/BakingSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Wind/ShaderWindSettings.cs
Labels: HDRP

#2104 Hdrp/fix layered lit material reference
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitUI.cs
Labels: HDRP

#2117 Fix orverriding of frame settings broken debug menu
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#1953 Fix meta for HD and LW PBR master
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightPBRSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightPBRExtraPasses.template
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/ShaderGUI.meta
  com.unity.shadergraph/Editor/ShaderGUI/PBRMasterGUI.cs
  com.unity.shadergraph/Editor/ShaderGUI/PBRMasterGUI.cs.meta
Labels: Shader Graph, bug-fix

#2109 Cleanup of reflection/refraction code
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/LightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceTracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#2120 Removed unusued files from HDRP (move to scriptable render pipeline data)
  com.unity.render-pipelines.high-definition/Editor/Core/CoreResources.meta
  com.unity.render-pipelines.high-definition/Editor/Core/CoreResources/GPUCopyAssetEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Core/CoreResources/GPUCopyAssetEditor.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/GPUCopyAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/GPUCopyAsset.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/GPUCopyDefinition.asset
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/GPUCopyDefinition.asset.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/TexturePadding.compute
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/TexturePadding.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/TexturePadding.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/TexturePadding.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP

#2123 Cleaning FrameSettings and HDRenderPipeline names and display
  com.unity.render-pipelines.core/Editor/CoreEditorDrawers.cs
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/CaptureSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDecalSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/LightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
Labels: HDRP

#2081 Refactor directional and punctual light evaluation
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1301_SubSurfaceScattering.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1301_SubSurfaceScattering.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1301_SubSurfaceScattering.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1501_Fabric.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1501_Fabric.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9101_Density-volumes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9101_Density-volumes.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/CommonLighting.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/VolumeRendering.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.Styles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/HDShadow.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitReference.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#2128 Add FrameSettings to control real time planar reflection
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/CaptureSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.shadergraph/Editor/ShaderGUI/PBRMasterGUI.cs
Labels: HDRP

#2099 fix decal draw order on transparent materials
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9005_Decals-stress-test.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
Labels: HDRP

#2138 Hdrp/staging
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9005_Decals-stress-test.png
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/Material/AxF/AxFUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/ExpendableAreaMaterial.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/FabricUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/StackLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/TerrainLit/TerrainLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/CaptureSettingsUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.shader
  com.unity.shadergraph/Editor/ShaderGUI/PBRMasterGUI.cs
Labels: HDRP

#1912 Add SRP batcher support
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/AbstractShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/BooleanShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/ColorShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/CubemapShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/IShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture3DShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/TextureShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Util/PropertyCollector.cs
Labels: Shader Graph, new-functionality

#2092 Lw/bugfixes
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
Labels: lwrp

#2137 Clean several unused code for screen space reflection / refraction
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceTracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.shadergraph/Editor/ShaderGUI/PBRMasterGUI.cs
Labels: HDRP

#2133 Lw/shadow fixes
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineLightEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/LWRPAdditionalLightData.cs
  com.unity.render-pipelines.lightweight/Runtime/LWRPAdditionalLightData.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipelineCore.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/AdditionalLightsShadowCasterPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/MainLightShadowCasterPass.cs
  com.unity.render-pipelines.lightweight/Runtime/ShadowUtils.cs
  com.unity.render-pipelines.lightweight/Shaders/ShadowCasterPass.hlsl
Labels: lwrp

#2140 HDRP shadows fixes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDShadowInitParameters.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShadowContext.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShadowContext.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/DebugDisplayHDShadowMap.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#2149 SSR Debug view + fixes to contact shadow / depth pyramid debug view
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.shadergraph/Editor/ShaderGUI/PBRMasterGUI.cs
Labels: HDRP

#2151 Fix graphic API when switching to a platform that doesn't have the OS…
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
Labels: HDRP

#2156 Add an error message when exceeding the max shadow requests
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#2160 Improve the light volume debuging tool
  com.unity.render-pipelines.high-definition/Runtime/Debug/ColorGradient.png
  com.unity.render-pipelines.high-definition/Runtime/Debug/ColorGradient.png.meta
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolume.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.compute
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#2145 Don't apply coat mask if slot not connected and value is 0.
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
Labels: HDRP, Shader Graph, backport-2018.3

#2158 Xbox intrinsics support
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
Labels: SRP

#2164 Minor fixes to Autodesk Interactive shaders
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/ShaderGraph/AutodeskInteractive.ShaderGraph
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/ShaderGraph/AutodeskInteractiveMasked.ShaderGraph
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/ShaderGraph/AutodeskInteractiveTransparent.ShaderGraph
  com.unity.render-pipelines.lightweight/Shaders/Autodesk Interactive/Autodesk Interactive Masked.shadergraph
  com.unity.render-pipelines.lightweight/Shaders/Autodesk Interactive/Autodesk Interactive Transparent.shadergraph
  com.unity.render-pipelines.lightweight/Shaders/Autodesk Interactive/Autodesk Interactive.shadergraph
Labels: HDRP, backport-2018.3

#2167 Hdrp/tmp fix cone light gizmo
  com.unity.render-pipelines.high-definition/Editor/Core/Lighting/CoreLightEditorUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
Labels: HDRP

#2166 Hdrp/fix debug menu materials
  com.unity.render-pipelines.high-definition/Editor/Core/Debugging/DebugWindow.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/DebugUI.Fields.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/Prefabs/Scripts/DebugUIHandlerEnumField.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Utilities/CoreUnsafeUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/MaterialDebug.cs
Labels: HDRP

#2177 Add more gpu intrinsics for GCN consoles
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/GGXConvolution/BuildProbabilityTables.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScattering.compute
Labels: HDRP

#2185 Fix HD include paths
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
Labels: HDRP, Shader Graph, bug-fix, high-priority

#2178 Fix filtering of distortion effect
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1206_Lit_Transparent_Distortion.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistorsion.compute
Labels: HDRP

#2186 Cheery pick - Fix filtering of distortion effect (#2178)
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1206_Lit_Transparent_Distortion.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistorsion.compute
Labels: HDRP, backport-2018.3

#2189 Fix issues with katana graphic test LW
  com.unity.testing.srp.lightweight/Tests/Scenes/028_PostProcessing_Custom/Scripts/HalftoneOpaque.shader
  com.unity.testing.srp.lightweight/Tests/Scenes/028_PostProcessing_Custom/Scripts/InvertOpaque.shader
Labels: backport-2018.3, lwrp

#2191 fix warnings
  com.unity.render-pipelines.high-definition/Editor/Core/Lighting/CoreLightEditorUtilities.cs
Labels: HDRP

#2192 Fix compilation issue with on non editor build in HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
Labels: HDRP

#2161 Fix shader variant stripping in cloud build.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipelineCore.cs
Labels: lwrp

#2182 Volumetric height fog
  com.unity.render-pipelines.core/ShaderLibrary/VolumeRendering.hlsl
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/VolumetricFog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#2190 Hdrp/upgrade data migration probe
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/IVersionable.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/IVersionable.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/MigrationDescription.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/MigrationDescription.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/MigrationStep.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/MigrationStep.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.Migration.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbe.Migration.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.Migration.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.cs
Labels: HDRP

#2080 2019.1/upgrade sceneview api
  com.unity.render-pipelines.core/Editor/Shadow/ShadowCascadeSplitGUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/MousePositionDebug.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineLightEditor.cs
Labels: HDRP, SRP

#2197 Fix build failure caused by warning as error.
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
Labels: lwrp

#2130 Revamp of XR/SRP hookup + Full screen blit fix for single-pass stereo
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/XRGraphicsConfigDrawer.cs
  com.unity.render-pipelines.core/Editor/XRGraphicsConfigDrawer.cs.meta
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs.meta
  com.unity.render-pipelines.core/Runtime/Common/XRGraphicsConfig.cs
  com.unity.render-pipelines.core/Runtime/Utilities/XRUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/Blit.shader
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipelineCore.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/DrawSkyboxPass.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: HDRP, XR

#2132 Tests/hdrp/shadergraph hdrp automated
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/TestRunner/HDRP_GraphicTestRunner.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/DS_EnabledStandard.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/DS_Flipped.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/DS_MirroredSpec.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/DS_None.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/GSAA.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpAlphaCutoff.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpAnisoTangent.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpIrideMask.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpSpecular.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpStandard.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpSubS.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpTransNormal.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BI_DistortionSimpleAdd.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BI_DistortionVectorMap.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BI_DistortionVectorMapDepthTest.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BI_DistortionVectorMapNoDepthTest.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BlendPerserveSpecularOff.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BlendPerserveSpecularOn.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DS_BackThenFront.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DistortionMultiply.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DistortionSimpleAdd.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DistortionVectorMap.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DistortionVectorMapDepthTest.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/FogOn.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/Lit_Additive.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/Lit_Alpha.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/Lit_Premultiply.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/PostRefraction.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/PreRefraction.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/RefractionPlaneHiZNormal.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/RefractionPlaneProxy.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/RefractionSphereHiZ.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/RefractionSphereProxy.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/SG_DistortionVectorMapDepthTest.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/SG_DistortionVectorMapNoDepthTest.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PostPass.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PostPass2.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PrePass.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PrePass2.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PrePostPass.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PrePostPass2.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8201_VertexAnimation.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8201_VertexAnimation/SGVertexRotation.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8201_VertexAnimation/SGVertexWave.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8202_BentNormals/BentNorm.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8203_Emission.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8203_Emission/Emission.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8203_Emission/EmissionAlbedoNoAffects.ShaderGraph
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8201_VertexAnimation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8201_VertexAnimation.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#2217 Backport: Hdrp/fix normalblend and blend for sphere influence (#2211)
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2202_ReflectionProbes_Volume.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2203_PlanarProbes.png
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.Migration.cs
Labels: HDRP

#2219 Move FrameSettings inspector position
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/CaptureSettingsUI.cs
Labels: HDRP

#2218 Fix capture settings usage for baked probes
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/CaptureSettingsUI.cs
Labels: HDRP

#2224 Exposed max LightLoop settings in hd asset
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDecalSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedGlobalLightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/GlobalLightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP

#2173 Fix 2 bugs in ShaderSourceMap's binary search
  TestProjects/ShaderGraph/Assets/Testing/Editor/UnitTests/ShaderSourceMapTests.cs
  TestProjects/ShaderGraph/Assets/Testing/Editor/UnitTests/ShaderSourceMapTests.cs.meta
  com.unity.shadergraph/Editor/Data/Util/ShaderSourceMap.cs
Labels: Shader Graph

#2215 Backport: Tests/hdrp/shadergraph hdrp automated (#2132)
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/TestRunner/HDRP_GraphicTestRunner.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/DS_EnabledStandard.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/DS_Flipped.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/DS_MirroredSpec.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/DS_None.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/GSAA.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpAlphaCutoff.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpAnisoTangent.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpIrideMask.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpSpecular.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpStandard.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpSubS.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque/OpTransNormal.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BI_DistortionSimpleAdd.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BI_DistortionVectorMap.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BI_DistortionVectorMapDepthTest.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BI_DistortionVectorMapNoDepthTest.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BlendPerserveSpecularOff.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/BlendPerserveSpecularOn.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DS_BackThenFront.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DistortionMultiply.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DistortionSimpleAdd.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DistortionVectorMap.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/DistortionVectorMapDepthTest.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/FogOn.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/Lit_Additive.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/Lit_Alpha.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/Lit_Premultiply.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/PostRefraction.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/PreRefraction.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/RefractionPlaneHiZNormal.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/RefractionPlaneProxy.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/RefractionSphereHiZ.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/RefractionSphereProxy.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/SG_DistortionVectorMapDepthTest.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent/SG_DistortionVectorMapNoDepthTest.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PostPass.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PostPass2.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PrePass.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PrePass2.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PrePostPass.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass/PrePostPass2.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8201_VertexAnimation.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8201_VertexAnimation/SGVertexRotation.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8201_VertexAnimation/SGVertexWave.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8202_BentNormals/BentNorm.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8203_Emission.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8203_Emission/Emission.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8203_Emission/EmissionAlbedoNoAffects.ShaderGraph
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8201_VertexAnimation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8201_VertexAnimation.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#2202 Lw/fix simplelit vertexlighting
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Shaders/SimpleLitForwardPass.hlsl
Labels: lwrp, needs-backport-2018.3

#2225 Changed planar mapping to match terrain convention (XZ instead of ZX)
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1201_Lit_Features.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1601_TerrainLit.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2101_GI_Metapass.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9201_Camera-relative-rendering.png
  com.unity.render-pipelines.core/ShaderLibrary/CommonMaterial.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/SampleUVMappingNormalInternal.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#2220 [LWRP]Fixed Cast Shadows overlapping with other UI elements in the Inspector for Area Light
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineLightEditor.cs
Labels: bug-fix, lwrp

#2222 Update CHANGELOG.md in regards to PR #2220
  com.unity.render-pipelines.lightweight/CHANGELOG.md
Labels: lwrp

#2172 Shadow Fixes for XR
  com.unity.render-pipelines.lightweight/Runtime/Passes/DepthOnlyPass.cs
  com.unity.render-pipelines.lightweight/Shaders/LitForwardPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/SimpleLitForwardPass.hlsl
Labels: XR, lwrp

#2198 Lw/lwrp asset inspector
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
Labels: lwrp, needs-backport-2018.3

#2242 Merge Hdrp/staging
  com.unity.render-pipelines.high-definition/Editor/Core/Gizmo/HierarchicalSphere.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.Gizmos.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeEditor.cs
Labels: HDRP

#2245 Use the "mean height" fog parametrization
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/VolumetricFog.cs
Labels: HDRP

#2234 Fix SSR for multiple views
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/BufferedRTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#2244 Initial implementation of the shader graph for the fabric
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolDetailNormalCutout_Graph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolDetailNormalCutout_Graph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolDetailNormalFuzzDouble_Graph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolDetailNormalFuzzDouble_Graph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolDetailNormal_Graph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolDetailNormal_Graph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolDetail_Graph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolDetail_Graph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolNormal_Graph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWoolNormal_Graph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWool_Graph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/CottonWool/M_CottonWool_Graph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/M_CottonWoolShaderGraph.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/M_CottonWoolShaderGraph.ShaderGraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/M_CottonWoolShaderGraphCutoff.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/M_CottonWoolShaderGraphCutoff.ShaderGraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/interpolateDetail.shadersubgraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/interpolateDetail.shadersubgraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/normalBlend.shadersubgraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/normalBlend.shadersubgraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/uvCombine.shadersubgraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1501_Fabric/ShaderGraph/uvCombine.shadersubgraph.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/FabricUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/IFabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/IFabricSubShader.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/AssetCallbacks/CreateFabricShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/AssetCallbacks/CreateFabricShaderGraph.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.shader
  com.unity.shadergraph/Editor/Data/Nodes/Graphics/BlendNormalRNM.cs
  com.unity.shadergraph/Editor/Data/Nodes/Graphics/BlendNormalRNM.cs.meta
Labels: HDRP

#2257 Fully initialised the output structs for LWRP particle shaders
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesLit.shader
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesSimpleLit.shader
Labels: lwrp, needs-backport-2018.3

#2246 Enable motion vector pass after depth prepass
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2205 Allow custom specular occlusion.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.shadergraph/Editor/Data/MasterNodes/SpecularOcclusionMode.cs
Labels: HDRP, Shader Graph

#2248 Add Both mode for Supported LitShaderMode
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDecalSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SharedRTManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
Labels: HDRP

#2268 Fix shadow request error when further than shadow fade distance
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#2272 Fixed build error caused by Editor class being referenced in runtime
  com.unity.render-pipelines.lightweight/Editor/LWRPAdditionalLightDataEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/LWRPAdditionalLightData.cs
Labels: lwrp, needs-backport-2018.1

#2267 Add an explicit call to VFXManager.ProcessCamera
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, vfx

#2171 Improve IAfterRender
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.lightweight/Runtime/DefaultRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/IAfterRender.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipelineCore.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CreateColorRenderTexturesPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CreateColorRenderTexturesPass.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/Passes/OpaquePostProcessPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/PostProcessPass.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/Passes/TransparentPostProcessPass.cs
  com.unity.render-pipelines.lightweight/Runtime/RenderTargetHandle.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
  com.unity.testframework.graphics/Runtime/ImageAssert.cs
  com.unity.testframework.graphics/Tests/Runtime/ImageAssertTests.cs
  com.unity.testing.srp.lightweight/Tests/CommonAssets/Scripts/LWGraphicsTests.cs
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/013_CameraMulti_Splitscreen.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/014_CameraMulti_MiniMap.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/015_CameraMulti_FPSCam.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/040_UpgradeScene.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/052_LWCallbacks.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/052_LWCallbacks.png.meta
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/013_CameraMulti_Splitscreen.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/014_CameraMulti_MiniMap.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/015_CameraMulti_FPSCam.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/040_UpgradeScene.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/052_LWCallbacks.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/052_LWCallbacks.png.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/052_LWCallbacks/CameraCallbackTests.cs
Labels: lwrp

#2253 Fix rendering with MSAA on GLES 3.0
  com.unity.render-pipelines.lightweight/Runtime/Passes/CreateLightweightRenderTexturesPass.cs
Labels: lwrp, needs-backport-2018.3

#2252 Merge: Hdrp/staging
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1203_Lit_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1206_Lit_Transparent_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  com.unity.render-pipelines.core/ShaderLibrary/AreaLighting.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/CommonLighting.hlsl
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/BufferedRTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/VolumetricFog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistorsion.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#2263 Expose "Receives SSR" to shadergraph
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
Labels: HDRP

#2273 Refraction/Distortion bug fixes
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1206_Lit_Transparent_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistorsion.compute
Labels: HDRP, backport-2018.3

#2278 MSAA and Lit ShaderGraph Corrections
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/MSAATestPrefab.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/MSAATestPrefab.prefab.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/M_GreenLit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/M_GreenLit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/M_RedLit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/M_RedLit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/M_TransparentRefractive.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAA/M_TransparentRefractive.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardBoth.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardBoth.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardBoth.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardBoth/HDRP_Test_Def_MSAABoth.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardBoth/HDRP_Test_Def_MSAABoth.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardBoth/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardBoth/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly/HDRP_Test_Def_MSAAForward.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly/HDRP_Test_Def_MSAAForward.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly_Profiles.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly_Profiles/HDRP_Test_Camera Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly_Profiles/HDRP_Test_Camera Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/SharedRTManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, Shader Graph

#2282 Hdrp/fix probe sphere influence gizmo clamp
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Handles.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.Migration.cs
Labels: HDRP

#2285 HDRP: Fix null assert in resource editor creation (fix katana)
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.Migration.cs
Labels: HDRP, backport-2018.3

#2254 Fixed an floatfield be parsed according to OS locale settings
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/FloatField.cs
Labels: needs-backport-2018.3

#2289 Various fixes in the LIt Shader Graph and the Fabric Shader Graph
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
Labels: HDRP

#2290 Emissive colour override debug option
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#2293 fix build player not building in HDRP
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
Labels: HDRP, backport-2018.3

#2297 Add dalayedfields for tesselation min max distance
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/BaseLitUI.cs
Labels: HDRP

#2302 Hdrp/rename line to tube light
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.Styles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIlluminationUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightUtils.cs
Labels: HDRP

#2305 fix layered lit with scrollbar
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitUI.cs
Labels: HDRP

#2298 force shadow qualities and restore them when exiting hdrp
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2276 Lw/camera override
  com.unity.render-pipelines.lightweight/Editor/LWRPAdditionalCameraDataEditor.cs
  com.unity.render-pipelines.lightweight/Editor/LWRPAdditionalCameraDataEditor.cs.meta
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/AdditionalCameraData.cs
  com.unity.render-pipelines.lightweight/Runtime/LWRPAdditionalCameraData.cs
  com.unity.render-pipelines.lightweight/Runtime/LWRPAdditionalCameraData.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: lwrp, needs-backport-2018.3

#2313 Make Blend Mode reappear in UI if "Pre Refraction Pass" is set.
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
Labels: HDRP

#2314 Add a check when building a player for OSX version
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessBuild.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#2213 Backport: Various small Shader Graph bug fixes
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/AssetCallbacks/CreateHDLitShaderGraph.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightPBRExtraPasses.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightUnlitExtraPasses.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightUnlitPass.template
  com.unity.render-pipelines.lightweight/ShaderLibrary/ShaderGraphFunctions.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Camera-Node.md
  com.unity.shadergraph/Documentation~/Dielectric-Specular-Node.md
  com.unity.shadergraph/Documentation~/Matrix-Construction-Node.md
  com.unity.shadergraph/Documentation~/Object-Node.md
  com.unity.shadergraph/Documentation~/Sample-Cubemap-Node.md
  com.unity.shadergraph/Documentation~/Scene-Color-Node.md
  com.unity.shadergraph/Documentation~/Scene-Depth-Node.md
  com.unity.shadergraph/Documentation~/Texel-Size-Node.md
  com.unity.shadergraph/Editor/AssetCallbacks/CreatePBRShaderGraph.cs
  com.unity.shadergraph/Editor/AssetCallbacks/CreateShaderSubGraph.cs
  com.unity.shadergraph/Editor/AssetCallbacks/CreateUnlitShaderGraph.cs
  com.unity.shadergraph/Editor/Data/Graphs/AbstractMaterialGraph.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PBR/DielectricSpecularNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/CameraNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/ObjectNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneColorNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneDepthNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleCubemapNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/TexelSizeNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixConstructionNode.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelEnumMaskControlView.uss
Labels: HDRP, Shader Graph, backport-2018.3, bug-fix, lwrp

#2320 Fix HD Unlit include path
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
Labels: high-priority

#2321 Backport: Fix HD Unlit include path
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
Labels: high-priority

#2310 Merge Hdrp/staging (Batch of bugfix)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessBuild.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/BaseLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/SharedRTManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#2300 Implement distant (fallback) volumetric fog, fix refraction and distortion, add an option to reflect the sky in SSR
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1101_Unlit.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1101_Unlit.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1203_Lit_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1203_Lit_Transparent.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/VolumeRendering.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/AtmosphericScatteringEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/ExponentialFogEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/LinearFogEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/VolumetricFog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/CharlieConvolve.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/GGXConvolution/GGXConvolve.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Material.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistorsion.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForwardUnlit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#2319 Fix for specular AO when slot is connected (Lit Master Node).
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
Labels: HDRP, Shader Graph

#2317 Move NormalRNM node to an option on Normal Blend node
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Normal-Blend-Node.md
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Normal/NormalBlendNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Graphics/BlendNormalRNM.cs
  com.unity.shadergraph/Editor/Data/Nodes/Graphics/BlendNormalRNM.cs.meta
Labels: Shader Graph, bug-fix, high-priority

#2318 Backport: Move NormalRNM node to an option on Normal Blend node
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Normal-Blend-Node.md
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Normal/NormalBlendNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Graphics.meta
  com.unity.shadergraph/Editor/Data/Nodes/Graphics/BlendNormalRNM.cs
  com.unity.shadergraph/Editor/Data/Nodes/Graphics/BlendNormalRNM.cs.meta
Labels: Shader Graph, backport-2018.3, bug-fix, high-priority

#2322 Mark @Katstodian as code owner of LWRP and SG change logs
  .github/CODEOWNERS
Labels: Shader Graph, lwrp

#2212 Backport: Fix Shader Graph pipeline specific nodes
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPassForward.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderGraphFunctions.hlsl
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightUnlitPass.template
  com.unity.render-pipelines.lightweight/ShaderLibrary/ShaderGraphFunctions.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Ambient-Node.md
  com.unity.shadergraph/Documentation~/Baked-GI-Node.md
  com.unity.shadergraph/Documentation~/Fog-Node.md
  com.unity.shadergraph/Documentation~/Light-Probe-Node.md
  com.unity.shadergraph/Documentation~/Object-Node.md
  com.unity.shadergraph/Documentation~/Reflection-Probe-Node.md
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting.meta
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/AmbientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/AmbientNode.cs.meta
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/BakedGINode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/BakedGINode.cs.meta
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/ReflectionProbeNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/ReflectionProbeNode.cs.meta
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/FogNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/LightProbeNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/ObjectNode.cs
  com.unity.shadergraph/ShaderGraphLibrary/Functions.hlsl
Labels: HDRP, Shader Graph, backport-2018.3, bug-fix, lwrp

#2143 Fix Shader Graph pipeline specific nodes
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPassForward.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderGraphFunctions.hlsl
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightUnlitPass.template
  com.unity.render-pipelines.lightweight/ShaderLibrary/ShaderGraphFunctions.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Ambient-Node.md
  com.unity.shadergraph/Documentation~/Baked-GI-Node.md
  com.unity.shadergraph/Documentation~/Fog-Node.md
  com.unity.shadergraph/Documentation~/Light-Probe-Node.md
  com.unity.shadergraph/Documentation~/Object-Node.md
  com.unity.shadergraph/Documentation~/Reflection-Probe-Node.md
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting.meta
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/AmbientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/AmbientNode.cs.meta
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/BakedGINode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/BakedGINode.cs.meta
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/ReflectionProbeNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/ReflectionProbeNode.cs.meta
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/FogNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/LightProbeNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/ObjectNode.cs
  com.unity.shadergraph/ShaderGraphLibrary/Functions.hlsl
Labels: HDRP, Shader Graph, bug-fix, lwrp
