Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2018-12, with the labels that each got.

#2548 Fix decals with stereo rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDBuffer.hlsl
Labels: HDRP, XR

#2549 Fixed PP flip logic for VR
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, XR

#2522 SimpleLightLoop removal
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/SimpleLightLoop.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXLit.cginc
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXLit.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXLitPixelOutput.cginc
Labels: HDRP

#2506 added one rendering frame delay for test
  com.unity.testframework.graphics/Runtime/ImageAssert.cs
Labels: HDRP

#2567 update reference screenshot for hair shader graph + test + fix flip issue
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1701_HairGraph/1701_HairGraph.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1701_HairGraph.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2564 Simple lit and vfx fixes
  TestProjects/VisualEffectGraph/Assets/AllTests/Runtime/VFXGraphicsTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/SimpleLit.unity
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/SimpleLitShadow.vfx
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/SimpleLit.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/SimpleLit.png.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/HDRP/VFXAbstractParticleHDRPLitOutput.cs
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassForward.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Quad/PassForward.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/VFXParticleLitMesh.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/VFXParticleLitQuad.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXLitPixelOutput.cginc
Labels: HDRP, vfx

#2569 Hdrp/fix hdrp stripper
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#2486 Hdrp/resolve tech dept due to new CED
  .gitignore
  com.unity.render-pipelines.high-definition/Editor/Core/CoreEditorDrawers.cs
  com.unity.render-pipelines.high-definition/Editor/Core/EditorPrefBoolFlags.cs
  com.unity.render-pipelines.high-definition/Editor/Core/ExpandedState.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/CameraSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/CameraSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.ContextualMenu.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.Gizmos.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Gizmos.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/ProxyVolumeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/ReflectionProxyVolumeComponentEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/ReflectionProxyVolumeComponentUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Drawer.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Drawer.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Skin.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/SerializedDensityVolume.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/SerializedDensityVolume.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDecalSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.Skin.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/LightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
Labels: HDRP

#2558 Fix blit pass for stereo rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/Blit.shader
Labels: HDRP, XR

#2559 Hdrp stacklit better dualnormalmaps
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
Labels: HDRP

#2554 Hdrp/reset debugmenu
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Scripts/DebugViewController.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Core/Debugging/DebugWindow.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/DebugManager.Actions.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/DebugManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/DebugUpdater.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/Prefabs/Scripts/DebugUIHandlerCanvas.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DecalsDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassLightTransport.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
Labels: HDRP

#2571 Fix player compile issue
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeSystem.cs
Labels: HDRP

#2485 Lw/feature/expose ibeforerender
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/IAfterDepthPrePass.cs
  com.unity.render-pipelines.lightweight/Runtime/IBeforeRender.cs
  com.unity.render-pipelines.lightweight/Runtime/IBeforeRender.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderOpaqueForwardPass.cs
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/052_LWCallbacks.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/052_LWCallbacks.png
  com.unity.testing.srp.lightweight/Tests/Scenes/052_LWCallbacks/CameraCallbackTests.cs
Labels: lwrp, needs-backport-2018.3

#2575 Updated scripts to ExecuteAlways
  com.unity.testing.srp.lightweight/Tests/Scenes/013_CameraMulti_Splitscreen/Scripts/AutoSizeGrid.cs
  com.unity.testing.srp.lightweight/Tests/Scenes/029_Particles/PlaySystems.cs
  com.unity.testing.srp.lightweight/Tests/Scenes/040_UpgradeScene/Scripts/RandomAnimationPoint.cs
Labels: lwrp

#2573 Fix Runtime tests.
  com.unity.render-pipelines.lightweight/Tests/Editor/EditorTests.cs
  com.unity.render-pipelines.lightweight/Tests/Runtime/RuntimeTests.cs
Labels: lwrp

#2551 HDRP metal fixes
  TestProjects/HDRP_Tests/OSXBatchMode.sh
  TestProjects/HDRP_Tests/RunAllTests_OSX.sh
  com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/HDShadow.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowContext.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#2552 backport of HDRP metal fixes #2551
  TestProjects/HDRP_Tests/OSXBatchMode.sh
  TestProjects/HDRP_Tests/RunAllTests_OSX.sh
  com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/HDShadow.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowContext.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#2579 HDRP: Fix an issue with wrong flipped depth during Postprocess
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2585 Reverted IBeforeCameraRender removal as BoatAttack depend on it.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: lwrp

#2584 Fix runtime tests and fixed use linear light intensity usage.
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Tests/Editor/EditorTests.cs
  com.unity.render-pipelines.lightweight/Tests/Runtime/RuntimeTests.cs
Labels: lwrp

#2482 Sg/fix gradient node
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Input/Gradient/GradientNode.cs
Labels: Shader Graph

#2593 Add versionning to HDRP
  com.unity.render-pipelines.high-definition/Editor/Unity.RenderPipelines.HighDefinition.Editor.asmdef
  com.unity.render-pipelines.high-definition/Runtime/Unity.RenderPipelines.HighDefinition.Runtime.asmdef
Labels: HDRP

#2520 Hdrp/add default scene and wizard
  com.unity.render-pipelines.core/Runtime/Volume/Volume.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/Wizard.png
  com.unity.render-pipelines.high-definition/Editor/DefaultScene.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultPostprocessingSettings.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultPostprocessingSettings.asset.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultRenderingSettings.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultRenderingSettings.asset.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultSceneRoot.prefab
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultSceneRoot.prefab.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDProjectSettings.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDProjectSettings.cs.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDSceneManagement.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDSceneManagement.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/HDRenderPipelineEditorResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
Labels: HDRP

#2582 Fix for all zero densities causing black spots -- default to whatever…
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitSplatCommon.hlsl
Labels: HDRP

#2596 Hdrp/separate fullscreenpassthrough
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/CameraSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedCameraSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/SerializedHDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/CaptureSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettingsUtilities.cs
Labels: HDRP

#2603 Hdrp/add cascade shadow visualisation
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/HDShadowSettingsEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2595 Packing attribute for hlsl structs
  com.unity.render-pipelines.high-definition/Editor/Core/ShaderGenerator/CSharpToHLSL.cs
  com.unity.render-pipelines.high-definition/Editor/Core/ShaderGenerator/ShaderTypeGeneration.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/ShaderGenerator/ShaderGeneratorAttributes.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/MaterialDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Builtin/BuiltinData.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.cs
Labels: HDRP

#2606 fix migration call and migration test
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/CameraSettingsUtilitiesTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/HDAdditionalReflectionData.MigrationTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/PlanarReflectionProbe.MigrationTests.cs
Labels: HDRP

#2608 Merge Hdrp master
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/HDShadowSettingsEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/CameraSettingsUtilitiesTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/HDAdditionalReflectionData.MigrationTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/PlanarReflectionProbe.MigrationTests.cs
Labels: HDRP

#2610 Shader graph add shader to project
  com.unity.shadergraph/ShaderGraphLibrary/DummyShaderGraphLibrary.cs
  com.unity.shadergraph/ShaderGraphLibrary/DummyShaderGraphLibrary.cs.meta
  com.unity.shadergraph/ShaderGraphLibrary/Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.asmdef
  com.unity.shadergraph/ShaderGraphLibrary/Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.asmdef.meta
Labels: Shader Graph

#2590 Lw/optimizations
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CreateLightweightRenderTexturesPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/DepthOnlyPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/DrawSkyboxPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/MainLightShadowCasterPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/ScriptableRenderPass.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/ShadowUtils.cs
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/052_LWCallbacks.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/052_LWCallbacks.png
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe.unity
Labels: lwrp

#2616 Add icons for hdrp assets and core VolumeProfile asset
  com.unity.render-pipelines.core/Runtime/Volume/VolumeProfile.cs.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/DiffusionProfileSettingsAsset.png
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/DiffusionProfileSettingsAsset.png.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineAsset.png
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineAsset.png.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineEditorResourcesAsset.png
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineEditorResourcesAsset.png.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineResourcesAsset.png
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineResourcesAsset.png.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/VolumeProfileAsset.png
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/VolumeProfileAsset.png.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs.meta
Labels: HDRP

#2617 Deprecate CoreEditorUtils.GetContent
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/Volume/VolumeComponentEditor.cs
  com.unity.render-pipelines.core/Editor/Volume/VolumeComponentListEditor.cs
  com.unity.render-pipelines.core/Editor/Volume/VolumeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Core/CoreEditorDrawers.cs
  com.unity.render-pipelines.high-definition/Editor/Core/Debugging/DebugUIDrawer.Builtins.cs
  com.unity.render-pipelines.high-definition/Editor/Core/Debugging/DebugWindow.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/IndirectLightingControllerEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/CameraSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ScreenSpaceRefractionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/ProxyVolumeUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/ContactShadowsEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/HDShadowSettingsEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraEditor.Handlers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDecalSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/LightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableSettingsArea.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/BakingSkyEditor.cs
Labels: HDRP

#2613 Hdrp/add material renderqueues
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderQueue.cs
Labels: HDRP

#2635 Fix integration issue on render queue
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
Labels: HDRP

#2634 Fixing convolution problem on the fabric shader with probes
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
Labels: HDRP

#2476 Fix HasFocus() function when the target is a TextInputBaseField.
  com.unity.visualeffectgraph/Editor/Controls/VFXSliderField.cs
  com.unity.visualeffectgraph/Editor/VisualElementExtensions.cs
Labels: vfx

#2483 Sg/highlight properties from blackboard
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Resources/Styles/GraphEditorView.uss
  com.unity.shadergraph/Editor/Resources/Styles/MaterialNodeView.uss
Labels: Shader Graph

#2640 Small sky refactor to fix stereo issues
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/ProceduralSky/ProceduralSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyUtils.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyUtils.hlsl.meta
Labels: HDRP, XR

#2651 Various fix (typo, rename, test)
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9201_Camera-relative-rendering.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9201_Camera-relative-rendering.png
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Material/AxF/AxFUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/BaseLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPassForward.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/ShaderGraph/AutodeskInteractive.ShaderGraph
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/ShaderGraph/AutodeskInteractiveMasked.ShaderGraph
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/ShaderGraph/AutodeskInteractiveTransparent.ShaderGraph
Labels: HDRP

#2597 Add WaveIsFirstLane and WaveGetLaneIndex intrinsic
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
Labels: HDRP

#2659 Hide material render queue [Require C++ Ono 79736: in trunk 2019.1.0a13] v2
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2636 Fixed - scaled objects render shadows incorrectly
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightPBRExtraPasses.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightUnlitExtraPasses.template
  com.unity.render-pipelines.lightweight/Shaders/ShadowCasterPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitPasses.hlsl
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/OSXEditor/Metal/026_Shader_PBRscene.png
  com.unity.testing.srp.lightweight/Tests/ReferenceImages/Linear/WindowsEditor/Direct3D11/026_Shader_PBRscene.png
  com.unity.testing.srp.lightweight/Tests/Scenes/026_Shader_PBRscene.unity
Labels: lwrp, needs-backport-2018.3

#2643 Lw/bugfix/case 1105552
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.testing.srp.lightweight/Tests/CommonAssets/LightweightRenderPipelineAsset.asset
Labels: lwrp

#2647 Lw/bugfix/case 1087251
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderPreprocessor.cs
Labels: lwrp, needs-backport-2018.3

#2653 Lw/bugfix/fix framedebugger
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: lwrp, needs-backport-2018.3

#2657 Lw/optimize mssa copy color
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/Passes/CopyColorPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/ScreenSpaceShadowResolvePass.cs
Labels: lwrp, needs-backport-2018.3

#2652 Add right eye bounds and volumes to lightlist (stereo rendering)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, XR

#2656 Implement basic distance fade for density volumes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Drawer.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/SerializedDensityVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs.hlsl
Labels: HDRP

#2654 Switch the density buffer back to FP16
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9101_Density-volumes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9101_Density-volumes.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
Labels: HDRP

#2661 Perform renaming in HDRP asset + Update MSAA control
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
Labels: HDRP

#2437 Autodesk interactive material upgrade
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/StandardsToHDLitMaterialUpgrader.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineMaterialUpgrader.cs
Labels: HDRP, lwrp

#2669 Fixed build error
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
Labels: lwrp, needs-backport-2018.3

#2670 fix missing directive in ogl core api
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
Labels: SRP

#2631 Add support to realtime probes in HDRP
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingSample.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/CameraSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.Gizmos.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedCameraSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/SerializedHDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Common/ObjectPools.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Common/ObjectPools.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeCullState.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeCullState.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeCullingResults.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeCullingResults.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/ReflectionProbeCullResults.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettingsUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP

#2629 Improved Moment Shadows
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Fwd_Shadow_VeryHigh.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Fwd_Shadow_VeryHigh.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh/HoledPlane.fbx
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh/HoledPlane.fbx.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh/ShadowTestMaterial.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh/ShadowTestMaterial.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2307_ShadowVeryHigh.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2307_ShadowVeryHigh.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/Material/BaseShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/ReflectionProbeCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDIMS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDIMS.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/MomentShadows.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/MomentShadows.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassForward.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Quad/PassForward.template
Labels: HDRP

#2676 Hdrp decal shader graph 3
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/CreateDecalShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/CreateDecalShaderGraph.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalGUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalMasterNode.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSettingsView.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/IDecalSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/IDecalSubShader.cs.meta
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/SharedCode.template.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProperties.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDBuffer.hlsl
Labels: HDRP

#2588 CBUFFER support on GLCore and ES3 [DO NOT MERGE]
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
Labels: SRP

#2443 Set the tags in an pipeline agnostic way.
  TestProjects/HDRP_Tests/OSXBatchMode.sh
  TestProjects/HDRP_Tests/RunAllTests_OSX.sh
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightPBRSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightUnlitSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.shadergraph/Editor/Data/SurfaceModel/SurfaceMaterialTags.cs
Labels: Shader Graph, backport-2018.3
