Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-04, with the labels that each got.

#3325 Leave light lists in a clean state when we don't need to build them anymore
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, needs-backport-2019.1

#3281 Shader Graph bug fixes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/SerializableCubemap.cs
  com.unity.shadergraph/Editor/Data/Graphs/SerializableMesh.cs
  com.unity.shadergraph/Editor/Data/Graphs/SerializableTexture.cs
  com.unity.shadergraph/Editor/Data/Graphs/SerializableTextureArray.cs
  com.unity.shadergraph/Editor/Data/Implementation/GraphObject.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporterEditor.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3328 Fixed compile errors in XRGraphics.cs when ENABLE_VR is not defined
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs
Labels: HDRP, XR

#3275 changing VertexNormalInput and TransformObjectToWorldNormal to use fl…
  com.unity.render-pipelines.core/ShaderLibrary/SpaceTransforms.hlsl
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl
Labels: lwrp, needs-backport-2019.1

#3339 fix serialized data not existing in runtime
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.Migration.cs
Labels: HDRP

#3260 Reworked resource management [2019.2]
  com.unity.render-pipelines.core/Runtime/Utilities/ResourceReloader.cs
  com.unity.render-pipelines.core/Runtime/Utilities/ResourceReloader.cs.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDAssetFactory.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.lightweight/Editor/ForwardRendererDataEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineEditorResources.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
Labels: HDRP, lwrp

#3291 Updated post-processing in LWRP
  TestProjects/PostProcessing/Packages/manifest.json
  com.unity.render-pipelines.lightweight/package.json
Labels: lwrp

#3294 Backport of #3275
  com.unity.render-pipelines.core/ShaderLibrary/SpaceTransforms.hlsl
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl
Labels: lwrp

#3345 Fixing a copy/paste issue relative to opaque objects primary vis
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
Labels: HDRP, dxr

#3336 VGPR usage optimizations (reorganizing + force shadow data to scalar)
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/HDShadow.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl
Labels: HDRP

#3335 Fix for Unlit nodes not calling OnGeneratePass on pass generation
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
Labels: HDRP, needs-backport-2019.1

#3348 Allow normalWS be directly written for TerrainLit shader [2019.2]
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_BasemapGen.shader
Labels: HDRP

#3357 Fixed an issue where baked probe file was not copied correctly
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
Labels: HDRP, needs-backport-2019.1

#3354 Fix diffusion profile upgrade crash with verifying asset enabled
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/defaultDiffusionProfile.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/defaultDiffusionProfile.asset.meta
Labels: HDRP

#3356 Fix very high shadows settings displayed on punctual lights instead of high
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#3329 Add ViewConstants StructuredBuffer to simplify XR rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Utilities/GeometryUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesMatrixDefsHDCamera.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
Labels: HDRP, XR

#3358 Making the raytracing work on the hdrp/staging branch
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/RaytracingAreaShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuseAccumulation.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingMacros.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP, dxr

#3361 Fix exposure to support TEXTURE2D_X
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/Exposure.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, needs-backport-2019.1

#3363 Updated both OSX and Windows test images for test 029-Particles
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/029_Particles.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/029_Particles.png
Labels: lwrp

#3368 Fixing sample direction going under the surface for raytracing reflections
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
Labels: HDRP, dxr

#3372 added bake tag for test 017
  TestProjects/LWGraphicsTest/Assets/Scenes/017_Lighting_Scene_DirectionalBaked.unity.meta
Labels: lwrp

#3375 Updated post-processing
  TestProjects/PostProcessing/Packages/manifest.json
  com.unity.render-pipelines.lightweight/package.json
Labels: lwrp

#3314 Update LOD Bias settings in FrameSettings [2019.2]
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9801_FrameSettings_LOD.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9801_FrameSettings_LOD/9801_Viewer.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9801_FrameSettings_LOD/9801_Viewer.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9801_FrameSettings_LOD.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9801_FrameSettings_LOD.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#3373 Fix HDRP re-allocating all resources at each frame in the editor in case of a compute shader was not compiling
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP, needs-backport-2019.1

#3359 Add support for negative mean height values to the height fog
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/VolumetricFog.cs
Labels: HDRP, needs-backport-2019.1

#3322 [HDRP] Fix Stereo MotionVectors
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
Labels: HDRP, needs-backport-2019.1

#3376 Fix colormip shift
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2203_PlanarProbes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8205_SceneDepthColorNodes.png
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
Labels: HDRP

#3369 Remove shift of near plane for area light shadows
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2308_Shadow_AreaLight.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/2308_Shadow_AreaLight.png
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#3377 Re-enable animated cookie test and fog fallback test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2004_AnimatedCookie/AnimatedCookie_CRT.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2004_AnimatedCookie/AnimatedCookie_CRT2.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2004_AnimatedCookie/AnimatedCookie_CRT3.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2007_FogFallback/MultiCam.cs
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2007_FogFallback.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2007_FogFallback.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#3380 Enable SSR test + simplify test scene
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Mirror.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0CC.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1CC.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough2CC.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2801_SSR.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2801_SSR.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#3383 Vfx/fix/copy tests fix
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXComponentTest.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXControllerTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXCopyPastGlobalTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXCopyPasteTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXDebugExpressionTest.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXGUITests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXPrefabTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSerializationTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXShaderGenerationTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpaceBoundTest.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXVariableOperatorControllerTests.cs
  com.unity.visualeffectgraph/Editor/VFXAssetEditorUtility.cs
Labels: vfx

#3379 Update Baked Spot shape test, disabled because GI still don't know HD…
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2602_BakedSpotShape.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2602_BakedSpotShape.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2602_BakedSpotShape.png.meta
Labels: HDRP

#3389 Push motion vector debug texture after transparent
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#3378 Backport of PR 3369 (area light shadow near plane shift)
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2308_Shadow_AreaLight.png
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#3352 RTHandle refactoring
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/BufferedRTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.RTHandle.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandles.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugColorPicker.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SharedRTManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoCReproject.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCombine.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FXAA.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/RTUpscale.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuseAccumulation.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/ProceduralSky/ProceduralSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#3392 Disabled test 017
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
Labels: lwrp

#3401 Resources & Post-processing fixes for LWRP
  TestProjects/PostProcessing/Packages/manifest.json
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.lightweight/package.json
Labels: lwrp

#3400 [VFX] Update reference images for 2019.3
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/09_AttributeMaps.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/15_CubeAndMesh.png
Labels: bug, vfx

#3405 Fix compile error using old SetViewport signature in non-editor builds
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#3385 Refactor PixelCoordToViewDirWS to be VR compatible
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/ProceduralSky/ProceduralSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyUtils.hlsl
Labels: HDRP, XR, backported-2019.2

#3399 Update diffusion profile reference screenshot
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1218_Lit_DiffusionProfiles.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1218_Lit_DiffusionProfiles.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1218_Lit_DiffusionProfiles.png.meta
Labels: HDRP, backported-2019.1, backported-2019.2

#3397 Microshadows test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows/MicroShadowMaterial.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows/MicroShadowMaterial.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows/Moss_01_MSK.tga
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows/Moss_01_MSK.tga.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows/Moss_01_N.tga
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows/Moss_01_N.tga.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2310_Microshadows/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2310_Microshadows.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2310_Microshadows.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#3403 Fix SMAA bug with RTHandle scale different than 1
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.hlsl
Labels: HDRP, needs-backport-2019.2

#3402 Hdrp docs reflection
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Density-Volume.md
  com.unity.render-pipelines.high-definition/Documentation~/Glossary.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/DecalShader1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/DensityVolume1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricFogQuality1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricLightingController1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/RendererAndMaterialPriority1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/RendererAndMaterialPriority5.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UnlitShader1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/VolumetricLighting1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/VolumetricLighting2.png
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Contact-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exponential-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Gradient-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-HDRI-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Indirect-Lighting-Controller.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Linear-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Micro-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Procedural-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Visual-Environment.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog-Quality.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Lighting-Controller.md
  com.unity.render-pipelines.high-definition/Documentation~/Planar-Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumetric-Lighting.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/BaseLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
Labels: HDRP, docs, needs-backport-2019.1

#3398 Added ShaderGraph an disabled SSR mateials ni SSR test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.5_SG.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.5_SG.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.5_SG_NoSSR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.5_SG_NoSSR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.8_SG.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.8_SG.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.8_SG_NoSSR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.8_SG_NoSSR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0CC_NoSSR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0CC_NoSSR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0_NoSSR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0_NoSSR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1CC_NoSSR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1CC_NoSSR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1_NoSSR.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1_NoSSR.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1_SG.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1_SG.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1_SG_NoSSR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1_SG_NoSSR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1_SSR.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1_SSR.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough2CC_NoSSR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough2CC_NoSSR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough_0.5.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough_0.5.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough_0.5_NoSSR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough_0.5_NoSSR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough_0.8.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough_0.8.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough_0.8_NoSSR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough_0.8_NoSSR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/SSR_CubeTest.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/SSR_CubeTest.prefab.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2801_SSR.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2801_SSR.png.meta
Labels: HDRP

#3395 Fix terrain basemap rendering
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1603_TerrainLit_BaseMap.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1603_TerrainLit_BaseMap.unity.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1603_TerrainLit_BaseMap.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1603_TerrainLit_BaseMap.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/1603_TerrainLit_BaseMap.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/1603_TerrainLit_BaseMap.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_BasemapGen.shader
Labels: HDRP, backported-2019.1

#3391 Added user documentation for HDRP debug menu
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Camera.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Decals.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Lighting.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Material.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Overview.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Rendering.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP

#3407 New version of fog test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/TestRunner/TextMeshPixelSize.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/1204_Lit_Fog_RT.renderTexture
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/1204_Lit_Fog_RT.renderTexture.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/ExponentialFogVolume Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/ExponentialFogVolume Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/FogTest.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/FogTest.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/LinearFogVolume Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/LinearFogVolume Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Fog.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Fog.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Additive_Fog_Off.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Additive_Fog_Off.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Additive_Fog_On.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Additive_Fog_On.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Fog_Off.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Fog_Off.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Fog_On.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Fog_On.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Premultiply_Fog_Off.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Premultiply_Fog_Off.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Premultiply_Fog_On.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Premultiply_Fog_On.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Refraction_Fog_Off.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Refraction_Fog_Off.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Refraction_Fog_On.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/Lit_Transparent_Refraction_Fog_On.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/VolumetricFogVolume Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Fog/VolumetricFogVolume Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1204_Lit_Transparent_Fog.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/1204_Lit_Fog.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/1204_Lit_Fog.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1204_Lit_Fog.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1204_Lit_Fog.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/1204_Lit_Fog.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/1204_Lit_Fog.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/1204_Lit_Transparent_Fog.png
Labels: HDRP

#3248 Enable contact shadow for multiple lights [2019.2]
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
Labels: HDRP

#3411 Add material classification test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_Anisotropy.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_Anisotropy.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_ClearCoat.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_ClearCoat.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_Diffusion.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_Diffusion.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_Iridescence.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_Iridescence.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_SSS.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_SSS.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_Standard.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Classification_Standard.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Render Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1800_Classification/Render Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1800_Classification.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1800_Classification.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#3406 Fix material feature initialization value for transmission thickness mode
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScattering.hlsl
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3410 HDRP/SMAA test
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/4051_SMAA.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/4051_SMAA.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/4051_SMAA.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/4051_SMAA.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/4051_SMAA.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/4051_SMAA.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#3413 Updated the license year
  LICENSE.md
  com.unity.render-pipelines.core/LICENSE.md
  com.unity.render-pipelines.high-definition/LICENSE.md
  com.unity.render-pipelines.lightweight/LICENSE.md
  com.unity.shadergraph/LICENSE.md
  com.unity.testframework.graphics/LICENSE.md
  com.unity.visualeffectgraph/LICENSE.md
Labels: docs

#3415 Hdrp docs subscript
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Density-Volume.md
  com.unity.render-pipelines.high-definition/Documentation~/Glossary.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/MotionVectors1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/MotionVectors2.png
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Physical-Light-Units.md
  com.unity.render-pipelines.high-definition/Documentation~/ShaderGraph/Emission-Node.md
Labels: HDRP, docs, needs-backport-2019.1, needs-backport-2019.2

#3416 Fixed several issues when changing resolution
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/BufferedRTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3417 Improve the time that a selected list of test takes to run if they don't have to bake the GI
  com.unity.testframework.graphics/Editor/SetupGraphicsTestCases.cs
Labels: HDRP

#3214 Change the terrain keywords to local [2019.2 only - Wait before merging]
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_BasemapGen.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitAdd.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitBase.shader
Labels: HDRP, lwrp

#3426 Remove compute version of the color pyramid
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP, backported-2019.2

#3424 [VFX] Temporarily disable 19_Random
  TestProjects/VisualEffectGraph/ProjectSettings/EditorBuildSettings.asset
Labels: vfx

#3425 [VFX] Temporarily disable 19_Random (to 2019.2)
  TestProjects/VisualEffectGraph/ProjectSettings/EditorBuildSettings.asset
Labels: vfx

#3422 Added forward and deferred cameras for SSR test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_SSR.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/SSR_RenderTarget.renderTexture
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/SSR_RenderTarget.renderTexture.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2801_SSR.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2801_SSR.png.meta
Labels: HDRP

#3429 Fix scene color test shader graphs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/HDSceneColorMaterialLit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/HDSceneColorMaterialUnlit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/HDSceneColorShader.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/HDSceneColorShaderLit.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/HDSceneColorShaderLit_NEW.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/HDSceneColorShaderLit_NEW.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/HDSceneColorShader_NEW.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/HDSceneColorShader_NEW.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorMaterialLit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorMaterialUnlit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorShader.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorShaderLit.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorShaderLit_NEW.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorShaderLit_NEW.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorShader_NEW.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorShader_NEW.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8205_SceneDepthColorNodes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8205_SceneDepthColorNodes.png.meta
Labels: HDRP

#3430 Merge master into new_test_2019_2 branch
  TestProjects/VisualEffectGraph/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_BasemapGen.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitAdd.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitBase.shader
Labels: HDRP

#3129 Frame Pass API [2019.2]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVBuffers.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVBuffers.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequest.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequest.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestBuilder.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestBuilder.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestData.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestDataCollection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestDataCollection.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/RenderOutputProperties.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/RenderOutputProperties.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/FramePass/FramePassSettings.cs
Labels: HDRP

#3435 Add missing variants to the shader version of deferred tiled shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/DeferredTile.shader
Labels: HDRP, backported-2019.1, backported-2019.2

#3436 Fix single-pass stereo rendering in 2019.1
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, XR

#3449 Fix gradient sky hash not using the exposure hash
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.cs
Labels: HDRP, backported-2019.1, backported-2019.2

#3447 Fix per-object motion blur test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4011_MotionBlur_PerObject.unity
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#3443 Fixing anchor links
  com.unity.render-pipelines.high-definition/Documentation~/Environment-Lighting.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Planar-Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Renderer-And-Material-Priority.md
  com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
Labels: HDRP, docs, needs-backport-2019.1, needs-backport-2019.2

#3458 Don't push motion vector texture to AOV and debug if we don't support motion vector
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3457 Hdrp/fix hdr passet displayed framesettings header on reload
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
Labels: HDRP, backported-2019.1, backported-2019.2

#3448 Disable GraphicTest based on Sound
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/23_ParameterBinders.unity
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/23_ParameterBinders.png
  com.unity.testing.visualeffectgraph/Tests/Runtime/VFXGraphicsTests.cs
Labels: vfx

#3450 Disable GraphicTest based on Sound (2019.2)
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/23_ParameterBinders.unity
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/23_ParameterBinders.png
  com.unity.testing.visualeffectgraph/Tests/Runtime/VFXGraphicsTests.cs
Labels: vfx

#3438 Origin/stadia support
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.testframework.graphics/Runtime/Utils.cs
Labels: HDRP

#3467 Fixed a typo in the Particle Unlit Shader
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesUnlitForwardPass.hlsl
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3468 Backport #3467 to 2019.2
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesUnlitForwardPass.hlsl
Labels: lwrp

#3470 Lw/backport/#3467
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesUnlitForwardPass.hlsl
Labels: lwrp

#3386 Enable first stereo LWRP Graphics Tests using MockHMD
  TestProjects/LWGraphicsTest/Assets/CommonAssets/Scripts/LWGraphicsTests.cs
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/057_xr_Camera_Clip.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/057_xr_Camera_Clip.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/058_xr_LitShaderLightProbes.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/058_xr_LitShaderLightProbes.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/059_xr_LitShaderMaps.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/059_xr_LitShaderMaps.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/060_xr_UnlitSprites.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/060_xr_UnlitSprites.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/061_xr_PBS_EnvironmentBRDF_Spheres.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/061_xr_PBS_EnvironmentBRDF_Spheres.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/062_xr_Lighting_Scene_Directional.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/062_xr_Lighting_Scene_Directional.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/063_xr_Lighting_Scene_DirectionalBaked.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/063_xr_Lighting_Scene_DirectionalBaked.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/066_xr_Shader_PBRvalidation_Specular.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/066_xr_Shader_PBRvalidation_Specular.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/067_xr_Shader_PBRvalidation_Metallic.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/067_xr_Shader_PBRvalidation_Metallic.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/068_xr_CenterLine.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/068_xr_CenterLine.png.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/057_xr_Camera_Clip.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/057_xr_Camera_Clip.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/058_xr_LitShaderLightProbes.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/058_xr_LitShaderLightProbes.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/059_xr_LitShaderMaps.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/059_xr_LitShaderMaps.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/060_xr_UnlitSprites.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/060_xr_UnlitSprites.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/061_xr_PBS_EnvironmentBRDF_Spheres.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/061_xr_PBS_EnvironmentBRDF_Spheres.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/062_xr_Lighting_Scene_Directional.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/062_xr_Lighting_Scene_Directional.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/063_xr_Lighting_Scene_DirectionalBaked.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/063_xr_Lighting_Scene_DirectionalBaked.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/064_xr_Lighting_BasicPoint.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/064_xr_Lighting_BasicPoint.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/065_xr_Lighting_BasicSpot.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/065_xr_Lighting_BasicSpot.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/066_xr_Shader_PBRvalidation_Specular.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/066_xr_Shader_PBRvalidation_Specular.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/067_xr_Shader_PBRvalidation_Metallic.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/067_xr_Shader_PBRvalidation_Metallic.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/068_xr_CenterLine.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/068_xr_CenterLine.unity.meta
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  TestProjects/LWGraphicsTest/ProjectSettings/ProjectSettings.asset
  TestProjects/ShaderGraph/ProjectSettings/EditorSettings.asset
Labels: lwrp

#3469 Fix issues with rasterized vs ray traced area shadow lights
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, backported-2019.1, backported-2019.2

#3475 Hdrp/fix/cascase fixes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3474 Fixed issue with LightExplorer when volume have no profile
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3463 Disable SSR for negative, infinite and NaN history values
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
Labels: HDRP, backported-2019.1, backported-2019.2

#3233 Fx FB#1136706 - Baked GI Node Serialization Issue
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/BakedGINode.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3464 Improve SSR ray biasing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3462 HDRP doc corrections
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Projector.md
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Environment-Lighting.md
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Layers.md
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Contact-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-HDRI-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Micro-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Subsurface-Scattering.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Documentation~/Unlit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/VR-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumes.md
  com.unity.render-pipelines.high-definition/Documentation~/index.md
  com.unity.visualeffectgraph/Documentation~/Blocks.md
Labels: HDRP, docs, needs-backport-2019.1, needs-backport-2019.2

#3451 Add sphere portion handles that better match pyramid spot light volume
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Core/Lighting/CoreLightEditorUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs
Labels: HDRP, backported-2019.1, backported-2019.2

#3483 Hdrp/fix lightlayer ui in probes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3445 Removed UnityPerPassStereo CBUFFER
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP, XR

#3453 Remove XR single-pass double-wide support
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Deferred.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/DeferredTile.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurMotionVecPrep.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/RaytracingAreaShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuseAccumulation.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MSAA/ColorResolve.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MSAA/DepthValues.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MotionVectors/CameraMotionVectors.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/Blit.shader
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyUtils.hlsl
Labels: HDRP, XR

#3487 Fix diffusion profile causing nans when thickness and color was 0
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.cs
Labels: HDRP, backported-2019.1, backported-2019.2

#3484 Hdrp/fix light shadowmask multiedition
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP
