Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-06, with the labels that each got.

#3707 Lw/fix particles distortion
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesUnlit.shader
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3755 Fix for decals showing blurry low res mip when using texture mip map streaming
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
Labels: HDRP, needs-backport-2019.2

#3758 Fix package in isolation (to master)
  com.unity.visualeffectgraph/Editor/Models/VFXGraph.cs
  com.unity.visualeffectgraph/Editor/Templates/Empty Particle System.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Particle System.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Static Mesh.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Swarm Particle System.vfx
  com.unity.visualeffectgraph/Tests.meta
  com.unity.visualeffectgraph/Tests/Editor.meta
  com.unity.visualeffectgraph/Tests/Editor/Unity.VisualEffectGraph.Editor.Tests.asmdef
  com.unity.visualeffectgraph/Tests/Editor/Unity.VisualEffectGraph.Editor.Tests.asmdef.meta
  com.unity.visualeffectgraph/Tests/Editor/VisualEffectGraphEditorTests.cs
  com.unity.visualeffectgraph/Tests/Editor/VisualEffectGraphEditorTests.cs.meta
  com.unity.visualeffectgraph/Tests/Runtime.meta
  com.unity.visualeffectgraph/Tests/Runtime/Unity.VisualEffectGraph.Runtime.Tests.asmdef
  com.unity.visualeffectgraph/Tests/Runtime/Unity.VisualEffectGraph.Runtime.Tests.asmdef.meta
  com.unity.visualeffectgraph/Tests/Runtime/VisualEffectGraphRuntimeTests.cs
  com.unity.visualeffectgraph/Tests/Runtime/VisualEffectGraphRuntimeTests.cs.meta
Labels: vfx

#3746 Fix deferred shading for XR single-pass instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/DeferredTile.shader
Labels: HDRP, XR

#3721 Fix case 1152439 -
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/ScreenSpaceShadowResolvePass.cs
  com.unity.render-pipelines.lightweight/Runtime/RenderingUtils.cs
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3717 Fix shadowmap format warnings
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/ShadowUtils.cs
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3764 Fix for decal system mip streaming texture properties update
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
Labels: needs-backport-2019.2

#3765 Fix Unlit SG reference image and wraning in GridMesh script
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Scripts/GridMesh.cs
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1105_UnlitSG.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1105_UnlitSG.png.meta
Labels: HDRP

#3763 Fix cluster and material classification debug
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3767 Updated scene 1215
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfileOverride.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfileOverride.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfiles.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfiles/IndexOfRefraction1WorldScale0_1.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfiles/IndexOfRefraction1WorldScale0_1.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfiles/IndexOfRefraction1_25WorldScale1.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfiles/IndexOfRefraction1_25WorldScale1.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfiles/IndexOfRefraction1_5WorldScale10.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfiles/IndexOfRefraction1_5WorldScale10.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfiles/IndexOfRefraction2WorldScale100.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/DiffusionProfiles/IndexOfRefraction2WorldScale100.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/Materials.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/Materials/IndexOfRefraction1WorldScale0_1.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/Materials/IndexOfRefraction1WorldScale0_1.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/Materials/IndexOfRefraction1_25WorldScale1.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/Materials/IndexOfRefraction1_25WorldScale1.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/Materials/IndexOfRefraction1_5WorldScale10.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/Materials/IndexOfRefraction1_5WorldScale10.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/Materials/IndexOfRefraction2WorldScale100.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1215_Lit_SubSurfaceScattering/Materials/IndexOfRefraction2WorldScale100.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1215_Lit_SubSurfaceScattering.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1215_Lit_SubSurfaceScattering.png.meta
Labels: HDRP

#3729 Decal fade factor, fade start, draw distance automated test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1707-Decals-FadeFactorAndDistance.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1707-Decals-FadeFactorAndDistance.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1707-Decals-FadeFactorAndDistance.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1707-Decals-FadeFactorAndDistance/Decal_FactorAndStart.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1707-Decals-FadeFactorAndDistance/Decal_FactorAndStart.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1707-Decals-FadeFactorAndDistance/fadeFactorFadeStart.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1707-Decals-FadeFactorAndDistance/fadeFactorFadeStart.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1707-Decals-FadeFactorAndDistance.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1707-Decals-FadeFactorAndDistance.png.meta
Labels: HDRP

#3770 Color Modes, Precision Modes and Types
  com.unity.shadergraph/Documentation~/Color-Modes.md
  com.unity.shadergraph/Documentation~/Precision-Modes.md
  com.unity.shadergraph/Documentation~/Precision-Types.md
  com.unity.shadergraph/Documentation~/images/Color-Mode-User-Defined.png
Labels: Shader Graph, docs

#3771 [2019.2] Color Modes, Precision Modes and Types
  com.unity.shadergraph/Documentation~/Color-Modes.md
  com.unity.shadergraph/Documentation~/Precision-Modes.md
  com.unity.shadergraph/Documentation~/Precision-Types.md
  com.unity.shadergraph/Documentation~/images/Color-Mode-User-Defined.png
Labels: Shader Graph, docs

#3762 Various fixes based on @vlad feedback about subgraph in Visual Effect Graph
  com.unity.visualeffectgraph/Editor/GraphView/Elements/Controllers/VFXBlockController.cs
  com.unity.visualeffectgraph/Editor/GraphView/Elements/Controllers/VFXContextController.cs
  com.unity.visualeffectgraph/Editor/GraphView/Elements/Controllers/VFXDataAnchorController.cs
  com.unity.visualeffectgraph/Editor/GraphView/Elements/VFXDataAnchor.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXNodeProvider.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXPaste.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXView.cs
  com.unity.visualeffectgraph/Editor/Models/Blocks/VFXSubgraphBlock.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/VFXSubgraphContext.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/VFXSubgraphOperator.cs
  com.unity.visualeffectgraph/Editor/Models/Parameters/VFXParameter.cs
  com.unity.visualeffectgraph/Editor/Models/VFXGraph.cs
Labels: vfx

#3773 Refactored SSS in preparation for RenderGraph implementation
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#3761 Don't GC alloc in motion blur code
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/MotionBlur.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP

#3498 Rework Sub Graph importer
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/MinimalGraphData.cs
  com.unity.shadergraph/Editor/Data/Implementation/HasDependenciesAttribute.cs
  com.unity.shadergraph/Editor/Data/Implementation/IHasDependencies.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphAsset.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphAssetPostProcessor.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs.meta
Labels: Shader Graph, bug-fix, needs-backport-2019.2

#3788 Hdrp/fix probe ui
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDCubemapInspector.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Drawers.cs
Labels: HDRP, needs-backport-2019.2

#3786 Fix invalid direction for planar reflection probes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP, needs-backport-2019.2

#3779 Diffusion profile node precision
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/DiffusionProfileNode.cs
Labels: HDRP

#3749 [Backport 2019.2] Fix bug that didn't populate colors when precision changed
  com.unity.shadergraph/Editor/Drawing/Colors/PrecisionColors.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph, backported-2019.2

#3790 Fix exception with graph without resource.
  com.unity.visualeffectgraph/Editor/Models/Operators/VFXSubgraphContext.cs
Labels: vfx

#3795 Added a fp16 maximum epsilon definition
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/ImageBasedLighting.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Macros.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/NormalSurfaceGradient.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Packing.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/VolumeRendering.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP, needs-backport-2019.2

#3759 [VFX] Fix package in isolation (to 2019.2)
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Models/Blocks/Implementations/GPUEvent/GPUEventRate.cs.meta
  com.unity.visualeffectgraph/Editor/Models/VFXGraph.cs
  com.unity.visualeffectgraph/Editor/Templates/Empty Particle System.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Particle System.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Static Mesh.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Swarm Particle System.vfx
  com.unity.visualeffectgraph/Tests.meta
  com.unity.visualeffectgraph/Tests/Editor.meta
  com.unity.visualeffectgraph/Tests/Editor/Unity.VisualEffectGraph.Editor.Tests.asmdef
  com.unity.visualeffectgraph/Tests/Editor/Unity.VisualEffectGraph.Editor.Tests.asmdef.meta
  com.unity.visualeffectgraph/Tests/Editor/VisualEffectGraphEditorTests.cs
  com.unity.visualeffectgraph/Tests/Editor/VisualEffectGraphEditorTests.cs.meta
  com.unity.visualeffectgraph/Tests/Runtime.meta
  com.unity.visualeffectgraph/Tests/Runtime/Unity.VisualEffectGraph.Runtime.Tests.asmdef
  com.unity.visualeffectgraph/Tests/Runtime/Unity.VisualEffectGraph.Runtime.Tests.asmdef.meta
  com.unity.visualeffectgraph/Tests/Runtime/VisualEffectGraphRuntimeTests.cs
  com.unity.visualeffectgraph/Tests/Runtime/VisualEffectGraphRuntimeTests.cs.meta
Labels: vfx

#3780 Added an option in the frame settings to bind the depth buffer when TAA is enabled
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/SurfaceOptionUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableFrameSettingsArea.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#3800 Hdrp docs post processing and updated content
  com.unity.render-pipelines.high-definition/Documentation~/Forward-And-Deferred-Rendering.md
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/Glossary.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Camera.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/MatCap2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/MatCap3.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/MatCap4.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/PostProcessingMain1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/PostProcessingMain2.png
  com.unity.render-pipelines.high-definition/Documentation~/Layered-Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Layers.md
  com.unity.render-pipelines.high-definition/Documentation~/MatCap.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Contact-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exponential-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exposure.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Gradient-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-HDRI-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Indirect-Lighting-Controller.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Linear-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Procedural-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Screen-Space-Reflection.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Screen-Space-Refraction.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Visual-Environment.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog-Quality.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Bloom.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Channel-Mixer.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Chromatic-Aberration.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Color-Adjustments.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Color-Curves.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Depth-of-Field.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Film-Grain.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Lens-Distortion.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Lift-Gamma-Gain.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Main.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Motion-Blur.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Panini-Projection.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Shadows-Midtones-Highlights.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Split-Toning.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Tonemapping.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Vignette.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-White-Balance.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.1, needs-backport-2019.2

#3794 [TestProjects] Baking Emissive ShaderGraphs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/.gitignore
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Dark.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Dark.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissiveFabric.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissiveFabric.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissiveLit.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissiveLit.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissivePBR.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissivePBR.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissiveStackLit.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissiveStackLit.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissiveUnlit.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/EmissiveUnlit.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Layered.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Layered.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Lit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Lit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissiveFabric.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissiveFabric.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissiveLit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissiveLit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissivePBR.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissivePBR.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissiveStackLit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissiveStackLit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissiveUnlit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/Shader Graphs_EmissiveUnlit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/emissiveBox.fbx
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG/emissiveBox.fbx.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2106_GI_EmissionSG.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2106_GI_EmissionSG.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/2106_GI_EmissionSG.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/2106_GI_EmissionSG.png.meta
Labels: HDRP

#3797 Refactored forward pass in preparation for Render Graph
  com.unity.render-pipelines.high-definition/Runtime/Core/RendererList/RendererList.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3774 New Ambient Occlusion for HDRP
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2601_AO_HalfRes.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2601_AO_HalfRes/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2601_AO_HalfRes/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2601_SSAO_HalfRes.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2601_SSAO_HalfRes.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2601_SSAO_HalfRes.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2601_SSAO_HalfRes/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2601_SSAO_HalfRes/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2602_SSAO_FullRes.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2602_SSAO_FullRes.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2602_SSAO_FullRes.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2602_SSAO_FullRes/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2602_SSAO_FullRes/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2601_SSAO_HalfRes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2601_SSAO_HalfRes.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2602_SSAO_FullRes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2602_SSAO_FullRes.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusionDownsample1.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusionDownsample2.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusionRender.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusionUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOCommon.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAODenoise.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAODenoise.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOUpsample.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#3805 Update changelog for ssao
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#3803 fix ExecuteCaptureAction incorrect blit material source
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, bug-fix, needs-backport-2019.2

#3801 Vfx/2019.1 staging
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/03_EventAttribute.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/17_GPUEvent_Simple.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/21_DepthModules.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/HDRP.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/HDRPFog.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/SimpleLitShadow.vfx
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Models/Blocks/Implementations/Position/PositionCircle.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/HDRP/VFXAbstractParticleHDRPLitOutput.cs
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXLit.cginc
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXLitVaryings.template
Labels: vfx

#3775 Fix the double sided issue with shader graph when it is disabled in the master node
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode/DoubleSidedLitGraph.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode/DoubleSidedLitGraph.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode/DoubleSidedLitGraph_Flip.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode/DoubleSidedLitGraph_Flip.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode/DoubleSidedLitGraph_Mirror.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode/DoubleSidedLitGraph_Mirror.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode/DoubleSidedLitGraph_None.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode/DoubleSidedLitGraph_None.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1202_Lit_DoubleSideNormalMode.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1202_Lit_DoubleSideNormalMode.png.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/SharedCode.template.hlsl
Labels: HDRP

#3776 Directional Ray Traced Shadows
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/Sampling.hlsl
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDShadowInitParameters.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDSimpleDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDSimpleDenoiser.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingMIS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingMIS.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/SphericalQuad.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/SphericalQuad.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, dxr

#3810 Remove the "Range Attenuation" option for box spot lights
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP

#3811 Fix double sided normal mode mismatch in shadergraph master nodes
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
Labels: HDRP

#3812 Making the dxr project work again (vfx graph dependecy, recursive rendering)
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/103_RayTracingRecursiveRendering/103_RayTracingRecursiveRendering.unity
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/103_RayTracingRecursiveRendering/103_RayTracingRecursiveRendering/Scene Settings Profile.asset
  LocalTestProjects/HDRP_DXR_Tests/Packages/manifest.json
Labels: HDRP, dxr

#3791 Minor color mode fix for precision inheritance
  com.unity.shadergraph/Editor/Drawing/Colors/PrecisionColors.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph, bug-fix

#3816 Fix negative values for emission intensity and shadow map resolution
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/EmissionUIBlock.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#3806 Lw/docs/rendering in lwrp doc
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Documentation~/Images/Graphics/Rendering_Flowchart.png
  com.unity.render-pipelines.lightweight/Documentation~/TableOfContents.md
  com.unity.render-pipelines.lightweight/Documentation~/configuring-lwrp-for-use.md
  com.unity.render-pipelines.lightweight/Documentation~/creating-a-new-project-with-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/installing-lwrp-into-an-existing-project.md
  com.unity.render-pipelines.lightweight/Documentation~/rendering-in-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/upgrading-your-shaders.md
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3819 Fixing Screen space shadows in the lightloop
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
Labels: HDRP, dxr

#3820 Added documentation for mip debug rendering
  com.unity.render-pipelines.core/ShaderLibrary/Debug.hlsl
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Rendering.md
Labels: HDRP

#3821 Lookdev/second draft
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/LookDev/CameraController.cs
  com.unity.render-pipelines.core/Editor/LookDev/CameraController.cs.meta
  com.unity.render-pipelines.core/Editor/LookDev/CameraState.cs
  com.unity.render-pipelines.core/Editor/LookDev/ComparisonGizmo.cs
  com.unity.render-pipelines.core/Editor/LookDev/ComparisonGizmoController.cs
  com.unity.render-pipelines.core/Editor/LookDev/ComparisonGizmoController.cs.meta
  com.unity.render-pipelines.core/Editor/LookDev/ComparisonGizmoState.cs
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.cs
  com.unity.render-pipelines.core/Editor/LookDev/Context.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.uss
  com.unity.render-pipelines.core/Editor/LookDev/DropArea.cs
  com.unity.render-pipelines.core/Editor/LookDev/Environment.cs
  com.unity.render-pipelines.core/Editor/LookDev/EnvironmentLibrary.cs
  com.unity.render-pipelines.core/Editor/LookDev/EnvironmentLibrary.cs.meta
  com.unity.render-pipelines.core/Editor/LookDev/Icons/d_renderdoc.png
  com.unity.render-pipelines.core/Editor/LookDev/Icons/d_renderdoc.png.meta
  com.unity.render-pipelines.core/Editor/LookDev/Icons/renderdoc.png
  com.unity.render-pipelines.core/Editor/LookDev/Icons/renderdoc.png.meta
  com.unity.render-pipelines.core/Editor/LookDev/Inspectors.uss
  com.unity.render-pipelines.core/Editor/LookDev/Inspectors.uss.meta
  com.unity.render-pipelines.core/Editor/LookDev/LookDev.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDevRenderer.cs
  com.unity.render-pipelines.core/Editor/LookDev/Stage.cs
  com.unity.render-pipelines.core/Editor/LookDev/ToolbarRadio.cs
  com.unity.render-pipelines.core/Runtime/LookDev/IDataProvider.cs
  com.unity.render-pipelines.core/Runtime/Volume/VolumeManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LookDev.cs
Labels: HDRP

#3826 Lw/docs ppv2 and 2d note
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Documentation~/2d-index.md
  com.unity.render-pipelines.lightweight/Documentation~/Setup.md
  com.unity.render-pipelines.lightweight/Documentation~/TableOfContents.md
  com.unity.render-pipelines.lightweight/Documentation~/faq.md
  com.unity.render-pipelines.lightweight/Documentation~/integration-with-post-processing.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-asset.md
Labels: needs-backport-2019.2

#3827 remove renderdoc integration
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.uss
Labels: LookDev

#3833 Update VFXBlock.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXBlock.uss
Labels: HDRP

#3832 Fix for some motion blur bugs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/MotionBlurEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/MotionBlur.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
Labels: HDRP

#3834 Fix instancing of decal
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalGUI.cs
Labels: HDRP, backported-2019.2

#3825 Refactored LightLoop global parameters in preparation for RenderGraph
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3836 Fixes on ray tracing
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
Labels: HDRP, dxr

#3838 Fix issue on non VR platform
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, backported-2019.2

#3840 fix compil issue with GLES2
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES2.hlsl
Labels: backported-2019.2, lwrp

#3839 Hdrp docs format fixes and post processing tooltips
  com.unity.render-pipelines.high-definition/Documentation~/Alpha-Clipping.md
  com.unity.render-pipelines.high-definition/Documentation~/Creating-a-Custom-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Displacement-Mode.md
  com.unity.render-pipelines.high-definition/Documentation~/Geometric-Specular-Anti-Aliasing.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Camera.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingExecutionOrder1.png
  com.unity.render-pipelines.high-definition/Documentation~/Layered-Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Material-Type.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exponential-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exposure.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-HDRI-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Linear-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Planar-Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Bloom.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Color-Adjustments.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Depth-of-Field.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Execution-Order.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Lens-Distortion.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Motion-Blur.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Panini-Projection.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Tonemapping.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Vignette.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Wizard.md
  com.unity.render-pipelines.high-definition/Documentation~/Surface-Type.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumes.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Bloom.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ChannelMixer.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ChromaticAberration.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ColorAdjustments.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ColorLookup.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/DepthOfField.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Exposure.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/FilmGrain.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/LensDistortion.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/LiftGammaGain.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/MotionBlur.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/PaniniProjection.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ShadowsMidtonesHighlights.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/SplitToning.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Tonemapping.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Vignette.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/WhiteBalance.cs
Labels: HDRP, docs, needs-backport-2019.1, needs-backport-2019.2

#3842 Move Precision graph tests to test project
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor.meta
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/PrecisionTests.cs
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/PrecisionTests.cs.meta
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/ShaderGraphGraphicsTestsEditor.asmdef
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/ShaderGraphGraphicsTestsEditor.asmdef.meta
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs.meta
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/Precision.shadergraph
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/Precision.shadergraph.meta
  TestProjects/ShaderGraph/Assets/CommonAssets/Scripts/ShaderGraphGraphicsTests.asmdef
  TestProjects/ShaderGraph/Assets/CommonAssets/Scripts/Unity.ShaderGraph.GraphicsTests.asmdef
  TestProjects/ShaderGraph/Assets/CommonAssets/Scripts/Unity.ShaderGraph.GraphicsTests.asmdef.meta
  com.unity.shadergraph/Editor/AssemblyInfo.cs
Labels: Shader Graph

#3857 Fix crash in build when contact shadows are not enabled
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3858 Fix compilation error with metal inn SimpleDenoise.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
Labels: HDRP

#3859 Update CHANGELOG.md
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#3856 Merge Hdrp/staging
  com.unity.render-pipelines.core/ShaderLibrary/API/D3D11.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Switch.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Vulkan.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalGUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/HDShadow.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurMotionVecPrep.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/AmbientProbeConvolution.compute
Labels: HDRP, needs-backport-2019.2

#3787 Backport #3498 (Rework Sub Graph importer)
  .yamato/upm-ci-katana.yml
  com.unity.shadergraph/Editor/Data/Graphs/MinimalGraphData.cs
  com.unity.shadergraph/Editor/Data/Implementation/HasDependenciesAttribute.cs
  com.unity.shadergraph/Editor/Data/Implementation/IHasDependencies.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphAsset.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphAssetPostProcessor.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs.meta
Labels: Shader Graph

#3849 Backport #3498 (Rework Sub Graph importer)
  .yamato/upm-ci-katana.yml
  com.unity.shadergraph/Editor/Data/Graphs/MinimalGraphData.cs
  com.unity.shadergraph/Editor/Data/Implementation/HasDependenciesAttribute.cs
  com.unity.shadergraph/Editor/Data/Implementation/IHasDependencies.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphAsset.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphAssetPostProcessor.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs.meta
Labels: Shader Graph

#3852 [6.8.x backport] Rework slot validation to fix crash and provide better errors
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/EdgeTypeConversionTests.cs
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/EdgeTypeConversionTests.cs.meta
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/SlotConv.shadergraph
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/SlotConv.shadergraph.meta
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/DynamicVectorMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/Texture3DAssetNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/SlotValue.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
Labels: Shader Graph, backported-2019.2

#3804 [ShaderGraph] n* Styling Fixes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Controls/ChannelEnumMaskControl.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelEnumControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelMixerControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/EnumControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/EnumConversionControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/SliderControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ToggleControlView.uss
Labels: Shader Graph, bug-fix

#3865 Camera rendering callbacks order
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.2

#3863 Fix issue with wrong opaque blending for after postprocess
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitGUI.cs
Labels: HDRP, needs-backport-2019.2

#3869 Do copy of AO History manually and not via blit
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAODenoise.compute
Labels: HDRP, needs-backport-2019.2

#3868 Hdrp/fix/blit output type r32uint metal
  .gitattributes
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/ClearUIntTextureArray.compute
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/ClearUIntTextureArray.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP, needs-backport-2019.2

#3872 Fix meta from shader graph + end of line of decalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.shadergraph/Editor/Data/Graphs/MinimalGraphData.cs.meta
  com.unity.shadergraph/Editor/Data/Implementation/HasDependenciesAttribute.cs.meta
  com.unity.shadergraph/Editor/Data/Implementation/IHasDependencies.cs.meta
Labels: HDRP

#3874 Fix "XRSystem.ReleaseFrame() & ClearUIntTextureArray missing"
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#3841 Added HDRP Quality Settings in Project Preference Window
  com.unity.render-pipelines.high-definition/Editor/HDRPEditor.uss
  com.unity.render-pipelines.high-definition/Editor/HDRPEditor.uss.meta
  com.unity.render-pipelines.high-definition/Editor/HDRPEditorDark.uss
  com.unity.render-pipelines.high-definition/Editor/HDRPEditorDark.uss.meta
  com.unity.render-pipelines.high-definition/Editor/HDRPEditorLight.uss
  com.unity.render-pipelines.high-definition/Editor/HDRPEditorLight.uss.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/QualitySettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/QualitySettingsPanel.cs.meta
Labels: HDRP

#3751 Experimental Version of the PBR Sky System
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2307_Shadow_VeryHigh.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2307_Shadow_VeryHigh.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png.meta
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/HDRPFog.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/HDRPFog.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/Sampling.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/VolumeRendering.hlsl
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/VisualEnvironmentEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Material.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LookDev.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/GroundIrradiancePrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/GroundIrradiancePrecomputation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/InScatteredRadiancePrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/InScatteredRadiancePrecomputation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/OpticalDepthPrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/OpticalDepthPrecomputation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSky.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSkyCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSkyCommon.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSkyRenderer.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSkyRenderer.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSkyRenderer.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSkySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PbrSky/PbrSkySettings.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/ProceduralSky/ProceduralSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/VisualEnvironment.cs
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXCommon.cginc
Labels: HDRP

#3829 Hdrp/update shadow maps at custom rates
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs.hlsl
Labels: HDRP

#3799 Ray traced reflections DXR
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDSimpleDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Common.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Common/RayBinning.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Common/RayBinning.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingIntersectonGBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingIntersectonGBuffer.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuseAccumulation.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingFragInputs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingGBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingGBuffer.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingLightProbe.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingVisibility.hlsl
Labels: HDRP, dxr

#3873 Hdrp/small ui fixes
  com.unity.render-pipelines.high-definition/Editor/Core/Debugging/DebugUIDrawer.Builtins.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
Labels: HDRP, needs-backport-2019.2

#3882 [Shader Graph] Remove deprecated UIElements components
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GradientEdge.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph, bug-fix

#3883 Fix for Low res transparency depth buffer not rendering on PS4
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/DownsampleDepth.shader
Labels: HDRP, backported-2019.2

#3888 [Shader Graph] Removing failure from UIElements
  com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
Labels: Shader Graph, bug-fix

#3889 Fix warning from shadow caching
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
Labels: HDRP

#3887 Fix for OSX incorrect blit material texture dimension in ExecuteCaptureAction
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, bug-fix, needs-backport-2019.2

#3893 Fix Unexpected log
  com.unity.visualeffectgraph/Editor/Core/VFXLibrary.cs
Labels: HDRP

#3723 VisualEffectGraph - Shader macros for XR single-pass instancing
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/Shaders/rim.shader
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Shaders/DefaultStaticMeshOutput.shader
  com.unity.visualeffectgraph/Shaders/ParticleDecals/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassBasicForward.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleLines/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticleLines/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleLines/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleLines/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleLinesSW/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticleLinesSW/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleLinesSW/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleLinesSW/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticlePlanarPrimitives/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticlePlanarPrimitives/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticlePlanarPrimitives/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticlePlanarPrimitives/PassVS.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassMotionVectors.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleSpheres/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticleSpheres/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticleSpheres/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Hexahedron/PassGBuffer.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Hexahedron/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassDepth.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassDistortion.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassForward.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassGBuffer.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/PlanarPrimitive/PassDepth.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/PlanarPrimitive/PassForward.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/PlanarPrimitive/PassGBuffer.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/PlanarPrimitive/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Quad/PassDistortion.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Sphere/PassDepth.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Sphere/PassGBuffer.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXDefines.hlsl
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/VFXDefines.hlsl
  com.unity.visualeffectgraph/Shaders/VFXParticleHeader.template
Labels: HDRP, XR, lwrp, vfx

#3724 VisualEffectGraph - XR single-pass instancing support for indirect draws
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Shaders/VFXFillIndirectArgs.compute
Labels: HDRP, XR, lwrp, vfx

#3890 Allow custom spot angle for shadow map rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
Labels: HDRP

#3891 Rename PBR sky to physically based sky
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/GroundIrradiancePrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/GroundIrradiancePrecomputation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/InScatteredRadiancePrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/InScatteredRadiancePrecomputation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/OpticalDepthPrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/OpticalDepthPrecomputation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyCommon.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkySettings.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/VisualEnvironment.cs
Labels: HDRP

#3828 Supporting Reflection probes as a fallback in ray tracing effects
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl
Labels: HDRP, dxr

#2710 Lightweight Terrain shader feature upgrades
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderGUI/TerrainLitShaderGUI.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGUI/TerrainLitShaderGUI.cs.meta
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitAdd.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitBasemapGen.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitBasemapGen.shader.meta
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: lwrp

#3909 Fix memory leak in default settings
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/DefaultSettings.cs
Labels: HDRP

#3785 Time input & motion vectors
  com.unity.render-pipelines.core/ShaderLibrary/Wind.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Wind.hlsl.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/SharedCode.template.hlsl
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/VertexAnimation.template.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitDataMeshModification.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/ShaderPass/LitDepthPass.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/ShaderPass/LitDistortionPass.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/ShaderPass/LitMotionVectorPass.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/MotionVectorVertexShaderCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/VertMesh.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightPBRSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightSpriteLitSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightSpriteUnlitSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightUnlitSubShader.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.lightweight/ShaderLibrary/UnityInput.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/ShaderGraphRequirements.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/TimeNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGeneratorNames.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/ShaderGraphLibrary/ShaderVariables.hlsl
Labels: HDRP, Shader Graph, lwrp, needs-backport-2019.2

#3901 Hdrp/rename decal projector
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.Skin.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.Migration.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs.meta
Labels: HDRP

#3837 Disable recursive rendering for tier1
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RecursiveRenderingEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
Labels: HDRP, dxr

#3906 Merge Hdrp/staging
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG.unity
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RecursiveRenderingEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/GroundIrradiancePrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/GroundIrradiancePrecomputation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/InScatteredRadiancePrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/InScatteredRadiancePrecomputation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/OpticalDepthPrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/OpticalDepthPrecomputation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyCommon.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkySettings.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/VisualEnvironment.cs
Labels: HDRP

#3910 Fix POM node and change the Vector2 UV slot to an UV slot
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ParallaxOcclusionMappingNode.cs
Labels: HDRP, needs-backport-2019.2

#3898 Fix lighting with XR single-pass instancing by disabling deferred tile
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, XR, needs-backport-2019.2

#3885 Removed shader variant from resources at runtime if not used
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#3899 Fix warnings & add tests for the PBR sky
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Textures/earth_albedo.jpg.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Textures/earth_lights.jpg
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Textures/earth_lights.jpg.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Textures/stars_emissive.png
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Textures/stars_emissive.png.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5005_Pbr_Sky_Med_Altitude.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5005_Pbr_Sky_Med_Altitude.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5006_Pbr_Sky_Low_Altitude.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5006_Pbr_Sky_Low_Altitude.unity.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/InScatteredRadiancePrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/OpticalDepthPrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkySettings.cs
Labels: HDRP

#3900 Remove IMS setting from shadows
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/BaseShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
Labels: HDRP

#3877 Various fixes for HDRP and the volume system
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/Volume/VolumeEditor.cs
  com.unity.render-pipelines.core/Runtime/Volume/Volume.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLightingController.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/FilmGrain.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/LiftGammaGain.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ShadowsMidtonesHighlights.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomPrefilter.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/BlueNoise.cs
Labels: HDRP

#3912 Fix issue with TimeParameters not compiling when use as input for subgraph
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
Labels: HDRP, backported-2019.2

#3879 Refactored Decal Rendering in preparation for RenderGraph
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3911 Refactored color pyramid and sky in preparation for Render Graph Implementation
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ShaderVariablesScreenSpaceLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ShaderVariablesScreenSpaceLighting.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#3913 Change deprecated UIElement to use new accessor.
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph, bug-fix

#3914 [VFX] Fix warning
  com.unity.visualeffectgraph/Editor/GraphView/Elements/VFXNodeUI.cs
Labels: vfx
