Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-02, with the labels that each got.

#2873 Update render loop to support properly decal culling
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2878 Change TAA group size on Xbox
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.compute
Labels: HDRP

#2876 Added a pass for rendering objects after Post-Process
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/PostProcessVolume Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/PostProcessVolume Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_Add.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_Add.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_Add_AfterPost.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_Add_AfterPost.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_AfterPost.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_AfterPost.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_Alpha.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_Alpha.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_Alpha_AfterPost.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_AfterPostProcess/TestAfterPostProcess_Unlit_Alpha_AfterPost.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9701_AfterPostProcess.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9701_AfterPostProcess.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/BufferedRTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugColorPicker.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplayLatlong.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/DebugDisplayHDShadowMap.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Material.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FXAA.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderQueue.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
Labels: HDRP

#2877 Textured Area Light
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/DualColor.png
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/DualColor.png.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_0.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_1.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_1.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_2.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_2.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_3.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_3.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_4.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/M_Smoothness_4.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2701_TexturedAreaLights.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2701_TexturedAreaLights.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.core/ShaderLibrary/AreaLighting.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/FilterAreaLightCookies.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/FilterAreaLightCookies.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/LTCAreaLightCookieManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/LTCAreaLightCookieManager.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Mesh/Quad.FBX
Labels: HDRP

#2875 Fix cascade shadow count in shader
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP, backport-2018.3, backported-2019.1

#2879 Fix SimpleLit Debug (master)
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.visualeffectgraph/CHANGELOG.md
Labels: vfx

#2880 Fix SimpleLit Debug (2019.1)
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.visualeffectgraph/CHANGELOG.md
Labels: vfx

#2884 Hdrp/fix debugmenu framesettings safetyguard
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
Labels: HDRP

#2882 Fix VR double-wide
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, XR

#2860 Removed CoreUtils.clearColorAllBlack
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#2856 Change default value for depthSlice on SetRenderTarget functions
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP, XR

#2855 Add stereo instancing macros to MSAA shaders
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MSAA/ColorResolve.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MSAA/DepthValues.shader
Labels: HDRP, XR

#2826 Rename SampleCameraDepth to LoadCameraDepth and SampleCameraDepth
  TestProjects/HDRP_Tests/OSXBatchMode.sh
  TestProjects/HDRP_Tests/RunAllTests_OSX.sh
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewMaterialGBuffer.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/OpaqueAtmosphericScattering.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Deferred.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/DeferredTile.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoC.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurVelocityPrep.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MSAA/ColorResolve.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MotionVectors/CameraMotionVectors.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneColorNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneDepthNode.cs
Labels: HDRP, XR

#2861 Improved Motion Blur
  TestProjects/HDRP_Tests/OSXBatchMode.sh
  TestProjects/HDRP_Tests/RunAllTests_OSX.sh
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/MotionBlurEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/MotionBlur.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurVelocityPrep.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneColorNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneDepthNode.cs
Labels: HDRP

#2883 Missing documentation images
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/BakedLit.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/Lit.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/ParticlesExtra.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/ParticlesLit.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/ParticlesSimpleLit.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/ParticlesUnlit.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/SimpleLit.png
  com.unity.render-pipelines.lightweight/Documentation~/Images/Inspectors/Shaders/Unlit.png
Labels: docs, lwrp, needs-backport-2019.1

#2858 Improving the raytraced reflection quality modes
  com.unity.render-pipelines.core/ShaderLibrary/CommonMaterial.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/JointBilateralFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/JointBilateralFilter.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/OnlineVariance.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/OnlineVariance.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingConsts.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingConsts.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingReflection.hlsl
Labels: HDRP, dxr

#2865 Hdrp decals projector fade
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
Labels: HDRP

#2899 fix unlit and depth/motion with unlit MSAA
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1101_Unlit.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1102_Unlit_Distortion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1103_Unlit_Distortion_DepthTest.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1402_StackLitSG_Testers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2701_TexturedAreaLights.png
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDepthOnly.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForwardUnlit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassVelocity.hlsl
Labels: HDRP, backported-2019.1

#2892 Update stereo frame settings values
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/DepthOfField.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, XR

#2891 Add more macros for single-pass stereo instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalNormalBuffer.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/ColorPyramidPS.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MSAA/AmbientOcclusionResolve.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MotionVectors/CameraMotionVectors.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDepthOnly.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDistortion.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForwardUnlit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassGBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/VaryingMesh.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/VertMesh.hlsl
Labels: HDRP, XR

#2890 Rearrange FetchDepth functions
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderBase.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-clustered.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild.compute
Labels: HDRP, XR

#2889 Remove unused compute eye index
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP, XR

#2739 Hdrp tier 2 package documentation
  TestProjects/HDRP_Tests/OSXBatchMode.sh
  TestProjects/HDRP_Tests/RunAllTests_OSX.sh
  com.unity.render-pipelines.high-definition/Documentation~/Alpha-Clipping.md
  com.unity.render-pipelines.high-definition/Documentation~/Contact-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/ContactShadows1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/RendererPriority1.png
  com.unity.render-pipelines.high-definition/Documentation~/Material-Rendering-Priority.md
  com.unity.render-pipelines.high-definition/Documentation~/Material-Type.md
  com.unity.render-pipelines.high-definition/Documentation~/Procedural-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Surface-Type.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/IndirectLightingControllerEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/ContactShadowsEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeTextureTool.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Material/AxF/AxFUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/DiffusionProfile/DiffusionProfileSettingsEditor.Styles.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/BaseLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/TerrainLit/TerrainLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDecalSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/VisualEnvironmentEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/ExponentialFog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/LinearFog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLightingController.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/ProceduralSky/ProceduralSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkySettings.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneColorNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneDepthNode.cs
Labels: HDRP, docs

#2816 [ToTest] Implement fast portable versions of IsNaN() and IsInf()
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
Labels: HDRP

#2905 Fixed stencil copy
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2018.3, needs-backport-2019.1

#2907 update wizard tooltips
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
Labels: HDRP

#2910 Raytracing-GI related Changes
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingBuiltinData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingMacros.hlsl
Labels: HDRP, dxr

#2903 Added debug display for rays/frame
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/CountTracedRays.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/CountTracedRays.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugViewRayCount.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugViewRayCount.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingReflection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/DebugFont.tga
Labels: HDRP, dxr

#2914 Fix for deleting nodes with input edges
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph

#2915 Disable some motion blur improvements until HLSLcc bug is fixed
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
Labels: HDRP

#2898 Hdrp/refactor hdr passet inspector
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9102_Density-volumes-shadows/ChangeVolumetricQuality.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9102_Density-volumes-shadows/ChangeVolumetricQuality.cs.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/CubeLutImporter.cs
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Material/AxF/AxFShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/GlobalPostProcessSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/GlobalPostProcessSettingsUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDecalSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDynamicResolutionSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDynamicResolutionSettingsUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.Skin.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalLightLoopSettingsUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDShadowInitParametersUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableFrameSettingsArea.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/GlobalLightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/GlobalDecalSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/LTCAreaLightCookieManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ColorLookup.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/GlobalPostProcessSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalDynamicResolutionSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#2921 Disable Motion Blur velocity scattering on Metal
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
Labels: HDRP, needs-backport-2019.1

#2918 Fix issues with motion blur with game paused or not running (game view)
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP

#2909 Group camera tabs in debug menu
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/DebugManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/DebugUI.Panel.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
Labels: HDRP

#2924 Update 2307_ShadowVeryHigh.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_ShadowVeryHigh.unity
Labels: HDRP, backported-2019.1

#2925 HDRP - Solve SRP batcher issue with Debug Display shader
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
Labels: HDRP, needs-backport-2019.1

#2926 Fix alpha testing issue when using debug view mode
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
Labels: HDRP, backport-2018.3, backported-2019.1

#2911 Update TableOfContents.md
  com.unity.shadergraph/Documentation~/TableOfContents.md
Labels: Shader Graph, docs, needs-backport-2019.1

#2896 Update shading-model.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-asset.md
  com.unity.render-pipelines.lightweight/Documentation~/shaders-in-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/shading-model.md
Labels: docs, lwrp, needs-backport-2019.1

#2929 Add missing PLATFORM_NEEDS_UNORM_UAV_SPECIFIER to Vulkan.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Vulkan.hlsl
Labels: SRP

#2920 Hdrp/hide camera clear depth
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
Labels: HDRP

#2934 Hdrp/fix preview exposure
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#2930 Correcting UI and added tooltips
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
Labels: HDRP, docs

#2923 Improving sampling method for raytraced effects
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/LTCAreaLightCookieManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/BlueNoise.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/OwenScrambledNoise.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/OwenScrambledNoise.png.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/ScrambleNoise.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/ScrambleNoise.png.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_1_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_2_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_2_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_3_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_3_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_4_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_4_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_5_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_5_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_6_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_7_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_7_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_8_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_8_xy.bmp.meta
Labels: HDRP, dxr

#2942 Clamp dynamic resolution settings
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
Labels: HDRP

#2931 Fix planar anchor and standard capture rotation
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2207_ReflectionProbeVFace.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2210_ReflectionProbes_CaptureAtVolumeAnchor.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2207_ReflectionProbeVFace.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeCapturePositionSettings.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/HDAdditionalReflectionData.MigrationTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/PlanarReflectionProbe.MigrationTests.cs
Labels: HDRP

#2943 Fix build VisualEffectGraph
  com.unity.visualeffectgraph/Editor/PackageInfo.cs
Labels: bug-fix, vfx

#2947 Added tooltips
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
Labels: HDRP, docs, needs-backport-2019.1

#2938 Hdrp decals emissive (no shader graph)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProperties.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderPass/DecalSharePass.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl.meta
Labels: HDRP

#2948 Update uss files to valid properties and values
  com.unity.shadergraph/Editor/Resources/Styles/Blackboard.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/BooleanSlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelEnumControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelEnumMaskControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelMixerControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ColorControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ColorRGBASlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ColorRGBSlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/CubemapSlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/DielectricSpecularControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/EnumControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/EnumConversionControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/GradientControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/GradientSlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/IntegerControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/MultiFloatControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/MultiFloatSlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/PopupControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ScreenPositionSlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/SliderControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/Texture3DSlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/TextureArraySlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/TextureSlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/ToggleControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/Controls/UVSlotControlView.uss
  com.unity.shadergraph/Editor/Resources/Styles/GraphEditorView.uss
  com.unity.shadergraph/Editor/Resources/Styles/MasterPreviewView.uss
  com.unity.shadergraph/Editor/Resources/Styles/MaterialNodeView.uss
  com.unity.shadergraph/Editor/Resources/Styles/NodeSettings.uss
  com.unity.shadergraph/Editor/Resources/Styles/PixelCacheProfiler.uss
  com.unity.shadergraph/Editor/Resources/Styles/PortInputView.uss
  com.unity.shadergraph/Editor/Resources/Styles/PropertyNameReferenceField.uss
  com.unity.shadergraph/Editor/Resources/Styles/PropertyNodeView.uss
  com.unity.shadergraph/Editor/Resources/Styles/PropertyRow.uss
  com.unity.shadergraph/Editor/Resources/Styles/PropertySheet.uss
  com.unity.shadergraph/Editor/Resources/Styles/ShaderGraphBlackboard.uss
  com.unity.shadergraph/Editor/Resources/Styles/ShaderPort.uss
  com.unity.shadergraph/Editor/Resources/Styles/ShaderPropertyView.uss
Labels: Shader Graph

#2850 cull object with specific static flags when rendering a probe
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderUtilities.cs
Labels: HDRP

#2944 Fixed reflection stencil tests
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilShow.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilShow.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilShowDoubleSided.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilShowDoubleSided.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilShowShader.shader
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilShowShader.shader.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilWrite.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilWrite.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilWriteDoubleSided.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilWriteDoubleSided.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilWriteShader.shader
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilWriteShader.shader.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_PlanarReflectionCullingStencil.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2209_ReflectionProbeCullingStencil.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2208_PlanarReflectionCullingStencil.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2208_PlanarReflectionCullingStencil.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2209_ReflectionProbeCullingStencil.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2209_ReflectionProbeCullingStencil.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#2959 Post-processing fixes & scene view related improvements
  com.unity.render-pipelines.core/Runtime/Utilities/ColorUtils.cs
  com.unity.render-pipelines.core/Runtime/Utilities/CoreRenderPipelinePreferences.cs
  com.unity.render-pipelines.core/Runtime/Utilities/CoreRenderPipelinePreferences.cs.meta
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.core/Runtime/Volume/Volume.cs
  com.unity.render-pipelines.core/Runtime/Volume/VolumeManager.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/ColorCurvesEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/InspectorCurveEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Bloom.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/DepthOfField.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Exposure.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/FilmGrain.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Tonemapping.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Vignette.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/GlobalPostProcessSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderPipelinePreferences.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderPipelinePreferences.cs.meta
Labels: HDRP

#2966 Fix invalid state when creating a planar reflection for the first time
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedPlanarReflectionProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbe.cs
Labels: HDRP, needs-backport-2019.1

#2980 Fixed serialization bug in HDAsset
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/SerializedGlobalPostProcessSettings.cs
Labels: HDRP

#2977 Info-box in local volumes without colliders
  com.unity.render-pipelines.core/Editor/Volume/VolumeEditor.cs
Labels: HDRP, needs-backport-2019.1

#2978 fixed post processing with stereo double-wide
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP, XR, needs-backport-2019.1

#2919 Use sign bit to find the cache type instead of lowest bit.
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
Labels: HDRP

#2975 Fix blackboard disappearing
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Inspector/WindowDockingLayout.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph, needs-backport-2019.1

#2961 Supporting properly textured area lights for raytracing and some fixes
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8204_CustomSpecOcclusion.png
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/CommonMaterial.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/FilterAreaLightCookies.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/LTCAreaLightCookieManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderConfig.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderConfig.cs.hlsl
Labels: HDRP, dxr

#2962 Hdrp/add border in shadow cascade
  com.unity.render-pipelines.core/Editor/Resources/Advanced_Pressed_mini.png
  com.unity.render-pipelines.core/Editor/Resources/Advanced_Pressed_mini.png.meta
  com.unity.render-pipelines.core/Editor/Resources/Advanced_UnPressed_mini.png
  com.unity.render-pipelines.core/Editor/Resources/Advanced_UnPressed_mini.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/HDShadowSettingsEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/ShadowCascadeGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/ShadowCascadeGUI.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSettings.cs
Labels: HDRP

#2928 Allow for transparent objects to write to velocity [Wait C++ PR]
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassVelocity.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/VelocityVertexShaderCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/VelocityVertexShaderCommon.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#2982 Hdrp/add activefeaturetooltip in hdr passet
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableFrameSettingsArea.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
Labels: HDRP, needs-backport-2019.1

#2983 Raytracing Forward for Shader Graph
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingMacros.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
Labels: HDRP, dxr

#2970 Hdrp decals emissive sg, fix mesh decal emissive pass selection, fix decal shader graph crop by gizmo
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, needs-backport-2019.1

#2990 Fix mismatch when using custom render
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#2952 Use saturate to avoid nan when negative values
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Normal-Reconstruct-Z-Node.md
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Normal/NormalReconstructZNode.cs
Labels: Shader Graph

#2958 Update SRP API
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: SRP, needs-backport-2019.1

#2997 Update BeginFrameRendering in lightweight
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: SRP, lwrp, needs-backport-2019.1

#2998 Fixed decals in forward
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backported-2019.1

#2999 Prevent area light to request shadows as it's not yet supported
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#3002 Added a Stop NaNs option on cameras and scene views
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/SerializedHDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/NaNKiller.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/NaNKiller.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderPipelinePreferences.cs
Labels: HDRP

#2972 Swap TEXTURE2D_ARGS and TEXTURE2D_PARAM
  com.unity.render-pipelines.core/ShaderLibrary/API/D3D11.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES2.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Switch.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Vulkan.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/EntityLighting.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Filtering.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/ImageBasedLighting.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Macros.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/SampleUVMapping.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/SampleUVMappingInternal.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/SampleUVMappingNormalInternal.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/CharlieConvolve.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/GGXConvolution/GGXConvolve.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitSplatCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCombine.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FXAA.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/RTUpscale.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/IntegrateHDRISky.shader
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/Particles.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/Shadows.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/SurfaceInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/BakedLit.shader
  com.unity.render-pipelines.lightweight/Shaders/DepthOnlyPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/LitInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesLitInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesSimpleLitForwardPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesSimpleLitInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesUnlitForwardPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Particles/ParticlesUnlitInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/ShadowCasterPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/SimpleLitForwardPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/SimpleLitInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/SimpleLitMetaPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Terrain/WavingGrassPasses.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Utils/Sampling.shader
  com.unity.render-pipelines.lightweight/Shaders/Utils/ScreenSpaceShadows.shader
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/CubemapShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture3DShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/TextureShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.visualeffectgraph/CHANGELOG.md
Labels: SRP, needs-backport-2019.1

#3005 Fixed wrong scissor value leaking from editor code.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#3007 Add full metric support and clamping for shadow cascade
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/HDShadowSettingsEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSettings.cs
Labels: HDRP, needs-backport-2019.1

#2965 Enabled support for CBUFFER on OpenGL Core and OpenGL ES 3
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
Labels: lwrp

#2937 Rendering layer support for raytracing
  com.unity.render-pipelines.core/ShaderLibrary/CommonLighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
Labels: HDRP, dxr

#3000 Reflection and clear coat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/HDRP_Test_SSR.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/HDRP_Test_SSR.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Mirror.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Mirror.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0CC.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough0CC.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1CC.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough1CC.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough2.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough2.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough2CC.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/M_Rough2CC.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2801_SSR/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2801_SSR.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2801_SSR.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.core/ShaderLibrary/CommonMaterial.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceLighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
Labels: HDRP, dxr, needs-backport-2019.1

#2994 Fix Transform Node - Tangent Space > Any Space
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Math/Vector/TransformNode.cs
Labels: Shader Graph, backported-2019.1

#3017 Correcting an issue due to diffusion profile upgrade
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
Labels: HDRP, dxr

#3001 Fixes invalid probe culling when adding a new probe
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2204_ReflectionProbes_Lights.unity
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
Labels: HDRP, needs-backport-2019.1

#3022 Doc corrections
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Planar-Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
Labels: HDRP, docs, needs-backport-2019.1

#2893 Core logic and few examples for Texture2DX
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Filtering.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/GPUCopy.compute
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/GPUCopy.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/DeferredTile.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/GBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCombine.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/RTUpscale.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/ColorPyramid.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/ColorPyramidPS.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/Texture2DAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/Blit.shader
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl.meta
Labels: HDRP, XR

#3015 Fixed volume explorer using the wrong profile reference
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
Labels: HDRP

#3011 Hdrp/fix metric init for shadow cascade
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/HDShadowSettingsEditor.cs
Labels: HDRP, needs-backport-2019.1

#3026 Fixed curves infinite tangent behavior
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/InspectorCurveEditor.cs
Labels: HDRP, needs-backport-2019.1

#3027 Fix display of AfterPostProcess frame settings
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/SerializedHDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, needs-backport-2019.1

#3028 Adding the support for per-effect subscene
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Camera.meta
  com.unity.render-pipelines.high-definition/Runtime/Camera/HDRayTracingFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/Camera/HDRayTracingFilter.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
Labels: HDRP, dxr, needs-backport-2019.1

#3023 Added an unit selection dropdown to shutter speed
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
Labels: HDRP, needs-backport-2019.1

#3031 Don't use Min3/Max3 intrinsics on xbox for hull shaders.
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
Labels: HDRP, needs-backport-2019.1

#3025 Fixed culling and shadows for Pyramid, Box, Rectangle and Tube lights
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
Labels: HDRP, needs-backport-2019.1

#3035 fix the unit test in 5.5.0-preview templated packages [Not Fully Tested]
  com.unity.render-pipelines.high-definition/Tests/Editor/CameraSettingsUtilitiesTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
Labels: HDRP

#3032 Fix SSR mip count issue
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#3019 Add error helpboxes when not supported
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/VolumetricLightingControllerEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/VolumetricLightingControllerEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
Labels: HDRP, needs-backport-2019.1

#3021 Update diffusion profile doc
  com.unity.render-pipelines.high-definition/Documentation~/Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Subsurface-Scattering.md
Labels: HDRP, needs-backport-2019.1

#3037 Hdrp/update ui for 16bit shadow
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP, needs-backport-2019.1

#3038 [Port] Fix the unit test in templated packages
  com.unity.render-pipelines.high-definition/Tests/Editor/CameraSettingsUtilitiesTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
Labels: HDRP, backported-2019.1

#3043 add support for dots instancing in Lit master node
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
Labels: HDRP, needs-backport-2019.1

#3042 Fix diffusion profile asset references in shader graph
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/DiffusionProfileNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Slots/DiffusionProfileInputMaterialSlot.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
Labels: HDRP, needs-backport-2019.1

#3041 Disabled object motion vectors in the scene view
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3049 Fixing a missing include in the raytracing lit graph template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
Labels: HDRP, dxr

#2992 Refactor TerrainLit shader family
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitDataMeshModification.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData_Basemap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitSharePass.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitTemplate.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitTemplate.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.ShaderVariables.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap_Gen.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap.ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap.ShaderVariables.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap.hlsl.meta
Labels: HDRP

#3054 Hdrp/doc corrections
  com.unity.render-pipelines.high-definition/Documentation~/Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Atmospheric-Scattering.md
  com.unity.render-pipelines.high-definition/Documentation~/Contact-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Environment-Lighting.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumes.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumetric-Fog.md
Labels: HDRP, docs, needs-backport-2019.1

#3014 add double bit index check
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
Labels: HDRP

#3048 Clean diffusion profile content
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Skin Diffusion Profile.asset
Labels: HDRP

#3053 Decal prefabs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.cs
Labels: HDRP, needs-backport-2019.1

#2949 Display estimated rays/sec in display stats
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/CountTracedRays.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugViewRayCount.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugViewRayCount.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP, dxr

#3057 Move Color Pyramid History Mipcount to camera
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#3061 Hdrp/update frame settings image
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/FrameSettings2.png
Labels: HDRP, docs, needs-backport-2019.1

#3063 Fix Warning and update changelog
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
Labels: HDRP, needs-backport-2019.1

#3024 Disable specular lighting when rendering probes
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2210_ReflectionProbes_CaptureAtVolumeAnchor.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Light_on_Tesselation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Light_on_Tesselation.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP, needs-backport-2019.1

#3064 Adding the code required for realtime light probe support
  com.unity.render-pipelines.core/ShaderLibrary/EntityLighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightProbeBakeManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightProbeBakeManager.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingLightProbe.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingLightProbe.hlsl.meta
Labels: HDRP, dxr, needs-backport-2019.1

#3065 AreaCookie Cache Binding Fix (Raytracing)
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
Labels: HDRP, dxr

#3067 Fix LWRP tests 24 & 25
  com.unity.testing.srp.lightweight/Tests/CommonAssets/Meshes/Adam/Adam_basic_metallic.prefab
  com.unity.testing.srp.lightweight/Tests/CommonAssets/Meshes/Adam/Adam_basic_specular.prefab
  com.unity.testing.srp.lightweight/Tests/CommonAssets/Meshes/Adam/Crowd_LOD0.FBX.meta
Labels: high-priority, lwrp

#3068 GI Light Cluster Request
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
Labels: HDRP, dxr

#2976 Update FAQ and Comparison page
  TestProjects/HDRP_Tests/ProjectSettings/VFXManager.asset
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Documentation~/TableOfContents.md
  com.unity.render-pipelines.lightweight/Documentation~/faq.md
  com.unity.render-pipelines.lightweight/Documentation~/lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-simple-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/particles-unlit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/upgrading-your-shaders.md
Labels: lwrp, needs-backport-2019.1

#2842 Terrain details pipeline resources 19.1 backport
  TestProjects/HDRP_Tests/OSXBatchMode.sh
  TestProjects/HDRP_Tests/RunAllTests_OSX.sh
  TestProjects/ShaderGraph/ProjectSettings/EditorSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineEditorResources.asset
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineEditorResources.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineResources.asset
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainDetailLit.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/WavingGrass.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/WavingGrassBillboard.shader
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneColorNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneDepthNode.cs
Labels: HDRP, backported-2019.1, high-priority, lwrp

#3075 Fixed mutiselection issue with HDLight Inspector
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP

#3085 Fix planar reflection when looking at mirror normal
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2203_PlanarProbes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2203_PlanarProbes.png.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, needs-backport-2019.1

#3088 Update 1501_Fabric.png reference screenshots after PR on texture compression
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1501_Fabric.png
Labels: HDRP

#3050 Add parentheses to the soft voxelization code
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9101_Density-volumes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9101_Density-volumes.png.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
Labels: HDRP, needs-backport-2019.1

#3083 Fix subgraph hashcode
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
Labels: Shader Graph

#3058 Fix issue with setting a not available RT when disabling motion vectors.
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#2968 Fetch exposure from postprocess and forward to Gizmos.
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3081 fix missing migration code call on HDAdditionalCameraData
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
Labels: HDRP

#3056 Real time area light shadows (Blurred EVSM)
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2308_Shadow_AreaLight.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2308_Shadow_AreaLight.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2308_Shadow_AreaLight.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2308_Shadow_AreaLight/AreaLightShadowHDRPAsset.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2308_Shadow_AreaLight/AreaLightShadowHDRPAsset.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2701_TexturedAreaLights.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2308_Shadow_AreaLight.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2308_Shadow_AreaLight.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/HDShadow.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/EVSMBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/EVSMBlur.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowContext.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ShadowBlurMoments.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ShadowMoments.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#3082 Terminology sync
  com.unity.render-pipelines.core/Documentation~/ScriptableRenderPipeline.md
Labels: SRP, docs, needs-backport-2019.1

#3069 Update HDRP VFXSampleDepth() to use LoadCameraDepth()
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXCommon.cginc
Labels: HDRP, XR

#3079 Bumped shader defines. Moved them to a Version.hlsl file.
  com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/Version.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/Version.hlsl.meta
Labels: lwrp, needs-backport-2019.1

#3092 Hdrp/fix light explorer
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
Labels: HDRP

#3093 Area Shadows and Double Light contribution
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitProperties.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
Labels: HDRP, dxr

#3072 Add depth-of-field support with stereo instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/DepthOfField.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoC.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoCDilate.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoCReproject.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCombine.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldGather.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldMip.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldMipSafe.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldPrefilter.compute
Labels: HDRP, XR

#3070 update _SsrClearCoatMaskTexture with TEXTURE2D_X
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
Labels: HDRP, XR

#3098 Cleanup and graphic test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular/MetalBlue.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular/MetalBlue.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular/MetalGreen.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular/MetalGreen.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular/MetalRed.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular/MetalRed.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#3100 Fix EVSM Blur shader warning
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/EVSMBlur.compute
Labels: HDRP

#3104 Hdrp/docs/volume ui updates
  com.unity.render-pipelines.high-definition/Documentation~/Contact-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Fog-Overview.md
  com.unity.render-pipelines.high-definition/Documentation~/HD-Shadow-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Indirect-Lighting-Controller.md
  com.unity.render-pipelines.high-definition/Documentation~/Visual-Environment.md
  com.unity.render-pipelines.high-definition/Documentation~/Volume-Components.md
  com.unity.render-pipelines.high-definition/Documentation~/Volume-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumetric-Fog.md
Labels: HDRP, docs, needs-backport-2019.1

#3103 Fix issue with setting a not available RT when disabling motion vectors
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3101 Fix cascade border
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
Labels: HDRP

#2797 Remove HDRP from SG test project manifest for faster load times.
  TestProjects/ShaderGraph/Packages/manifest.json
Labels: Shader Graph
