Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-03, with the labels that each got.

#3113 Updated post-processing to 2.1.4
  TestProjects/PostProcessing/Packages/manifest.json
  com.unity.render-pipelines.lightweight/package.json
Labels: lwrp

#3120 Updated reference image for test 29
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/029_Particles.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/029_Particles.png.meta
Labels: lwrp

#3077 bug fixes
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporterEditor.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporterEditor.cs
Labels: Shader Graph

#3128 Refactor SSS
  com.unity.render-pipelines.high-definition/Documentation~/Subsurface-Scattering.md
Labels: HDRP, docs, needs-backport-2019.1

#3125 Fix area shadows blur over edge bug
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2308_Shadow_AreaLight.png
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/EVSMBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
Labels: HDRP, needs-backport-2019.1

#3122 Improving Area Shadows Quality
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAreaShadows.raytrace
Labels: HDRP, dxr

#3118 Indirect diffuse reference mode & InitBuiltinData
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxFData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitBuiltinData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIndirectDiffuse.raytrace.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl.meta
Labels: HDRP, dxr

#3114 Hdrp/depth offset shader graph
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ParallaxOcclusionMappingNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ParallaxOcclusionMappingNode.cs.meta
Labels: HDRP

#3116 Updated image and synced style
  com.unity.render-pipelines.high-definition/Documentation~/Atmospheric-Scattering.md
  com.unity.render-pipelines.high-definition/Documentation~/Contact-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Projector.md
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/Double-Sided.md
  com.unity.render-pipelines.high-definition/Documentation~/Fog-Overview.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/ForwardAndDeferred1.png
Labels: HDRP, docs, needs-backport-2019.1

#3111 Recorder implementation for HDRP
  com.unity.render-pipelines.core/Runtime/Utilities/CameraCaptureBridge.cs
  com.unity.render-pipelines.core/Runtime/Utilities/CameraCaptureBridge.cs.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#3132 Fixing the indirect diffuse for deferred mode
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuseAccumulation.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuseAccumulation.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP, dxr

#3139 Getting the area shadow code out of the async contact shadow context
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, dxr

#2744 Reselect graph after created
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/CreateDecalShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/CreateFabricShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/CreateHairShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/CreateHDLitShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/CreateStackLitShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/CreateHDUnlitShaderGraph.cs
  com.unity.shadergraph/Editor/AssetCallbacks/CreatePBRShaderGraph.cs
  com.unity.shadergraph/Editor/AssetCallbacks/CreatePBRShaderGraph.cs.meta
  com.unity.shadergraph/Editor/AssetCallbacks/CreateShaderGraph.cs
  com.unity.shadergraph/Editor/AssetCallbacks/CreateShaderGraph.cs.meta
  com.unity.shadergraph/Editor/AssetCallbacks/CreateUnlitShaderGraph.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
Labels: Shader Graph

#3124 Hdrp/fix densityvolume handles
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Drawer.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/SerializedDensityVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.Migration.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.cs
Labels: HDRP, needs-backport-2019.1

#2981 Update VFX USS files to valid properties and values
  com.unity.visualeffectgraph/Editor/Resources/PropertyRM.uss
  com.unity.visualeffectgraph/Editor/Resources/Resizable.uss
  com.unity.visualeffectgraph/Editor/Resources/Selectable.uss
  com.unity.visualeffectgraph/Editor/Resources/StickyNote.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXBlackboard.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXBlock.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXComponentBoard.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXContext.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXControls.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXDataAnchor.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXFlow.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXNode.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXNodeUI.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXOperator.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXParameter.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXReorderableList.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXSystemBorder.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXView.uss
Labels: vfx

#3131 Fix error thrown by SG test project due to removal of HD from project.
  TestProjects/ShaderGraph/Assets/Scenes/TestGraph.ShaderGraph
  TestProjects/ShaderGraph/Assets/TestbedAssets/Beachball.ShaderGraph
  TestProjects/ShaderGraph/Assets/TestbedAssets/Oilish.ShaderGraph
  TestProjects/ShaderGraph/Assets/TestbedAssets/PartyPreview.ShaderGraph
  TestProjects/ShaderGraph/Assets/TestbedAssets/Vector1PropGraph.ShaderGraph
  TestProjects/ShaderGraph/ProjectSettings/ProjectSettings.asset
Labels: Shader Graph

#3142 Hdrp/fix lightgizmo multi edition
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#3140 Use depth prepass in the shader graph preview
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.shadergraph/CHANGELOG.md
Labels: HDRP, needs-backport-2019.1

#3159 Fix SSR after R11G11B10 change
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3163 [Hdrp] fix normal handle densityvolume [Backport with 3124 & 3152]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/SerializedDensityVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.Migration.cs
Labels: HDRP

#3141 Fix mobile lighting attenuation
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
Labels: lwrp

#3153 Hdrp/add emission color normalization
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/EmissionNode.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderPipelinePreferences.cs
Labels: HDRP

#3162 Distortion Apply pass uses stencil
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/BaseLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistorsion.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistorsion.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistortion.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistortion.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#3177 Correct a problem relative to the maximal recursion of the primary visibility
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
Labels: HDRP, dxr

#3173 removed test folder that was readded by bad merge.
  com.unity.testing.srp.lightweight/Tests/Scenes/007_LitShaderMaps/LightingData.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/015_CameraMulti_FPSCam/GunRenderer.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/015_CameraMulti_FPSCam/GunRenderer.asset.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomRenderer.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomRenderer.asset.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/OutlineObject.mat
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/OutlineObject.mat.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/OverrideMaterial.mat
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/OverrideMaterial.mat.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/RenderOutline.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/RenderOutline.asset.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/052_LWCallbacks/CustomRenderer.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/052_LWCallbacks/CustomRenderer.asset.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/052_LWCallbacks/RenderPassFeature.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/052_LWCallbacks/RenderPassFeature.asset.meta
Labels: lwrp, needs-backport-2019.1

#3178 Update lwrp-builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-builtin-feature-comparison.md
Labels: lwrp, needs-backport-2019.1

#3184 Renable & Fix editor test to cover compilation failure behavior
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXComponentTest.cs
Labels: needs-backport-2019.1, vfx

#3176 Hide Shadow Quality settings from HDAsset UI
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#3174 LWRP Unlit (without graphicTest)
  TestProjects/VisualEffectGraph_Other_RenderPipe.7z
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Shaders/ParticleDecals/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassBasicForward.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleLines/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleLines/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleLinesSW/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleLinesSW/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleQuads/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleQuads/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleQuads/PassVS.template
  com.unity.visualeffectgraph/Shaders/ParticleSpheres/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXCommon.cginc
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleBasicCube.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleBasicCube.template.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleCube.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleCube.template.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleDecal.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleDecal.template.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleLinesHW.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleLinesHW.template.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleLinesSW.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleLinesSW.template.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleMeshes.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleMeshes.template.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticlePoints.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticlePoints.template.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleQuad.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/Templates/VFXParticleQuad.template.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/VFXCommon.cginc
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/VFXCommon.cginc.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/VFXDefines.hlsl
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/VFXDefines.hlsl.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/VFXPasses.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/LWRP/VFXPasses.template.meta
  com.unity.visualeffectgraph/Shaders/RenderPipeline/Legacy/VFXCommon.cginc
  com.unity.visualeffectgraph/Shaders/VFXCommonOutput.cginc
Labels: needs-backport-2019.1, vfx

#3160 Fix diffusion profile name upgrade and update the diffusion profile graphic test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2901_DiffusionProfiles/Fabric_BlueProfile.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2901_DiffusionProfiles/Lit_CheckboardProfile.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2901_DiffusionProfiles/ProjectFabric_BlueProfile.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2901_DiffusionProfiles/ProjectLit_CheckboardProfile.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2901_DiffusionProfiles/ProjectStackLit_GreenProfile_Node.ShaderGraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2901_DiffusionProfiles/StackLit_GreenProfile_Node.ShaderGraph
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/DiffusionProfileHashTable.cs
Labels: HDRP, needs-backport-2019.1

#3165 Fix HDRI sky intensity in lux mode
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Sky/HDRISky/HDRISkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
Labels: HDRP, needs-backport-2019.1

#3180 Fix tube light mesh size
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP, needs-backport-2019.1

#3171 SMAA Support in HDRP Postprocess stack
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/SerializedHDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Resources.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasingBridge.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasingBridge.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/SMAA.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/SMAA/AreaTex.tga
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/SMAA/AreaTex.tga.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/SMAA/SearchTex.tga
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/SMAA/SearchTex.tga.meta
Labels: HDRP

#3166 Don't allocate Motion blur velocity scattering textures if not supported
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP, needs-backport-2019.1

#3181 Backport of motion blur ps4 fix
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP

#3187 Implement temporal filtering for Area light shadows
  com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAreaShadows.raytrace
Labels: HDRP, dxr

#3188 Lw/fix template
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: lwrp, needs-backport-2019.1

#3185 Update lwrp-builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-builtin-feature-comparison.md
Labels: docs, lwrp, needs-backport-2019.1

#3089 Fix use of GetHashCode in SubGraphNode
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
Labels: Shader Graph, bug-fix

#3191 Implement a real filter for raytraced ambient occlusion
  com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/JointBilateralFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusionFilter.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP, dxr

#3145 Fix FB #1115432 and FB#1115112 - Various undo issues
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
  com.unity.shadergraph/Editor/Drawing/Views/Slots/BooleanSlotControlView.cs
  com.unity.shadergraph/Editor/Drawing/Views/Slots/GradientSlotControlView.cs
  com.unity.shadergraph/Editor/Drawing/Views/Slots/MultiFloatSlotControlView.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3138 Fix FB#1131211 - Voronoi Node Serialization Issue
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Procedural/Noise/VoronoiNode.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3137 Fix FB#1131755 - Drag-dropping normal map texture into a shader graph causes errors
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3135 Fix FB#1129900 - Invalid dependency paths when creating Unlit graphs
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightUnlitSubShader.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3134 Fix FB#1132342 - Multiply Bug. Zeroing components in code generation
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/DynamicValueMaterialSlot.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3107 Fix for Blend Node NaN Output
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Blend/BlendNode.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3156 [Backport] FB#1129900 - Invalid dependency paths when creating Unlit graphs
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightUnlitSubShader.cs
Labels: Shader Graph, bug-fix

#3194 Implement a spatio temporal filter for integrated reflections
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingSampling.hlsl
Labels: HDRP, dxr

#3071 HDRP dynamic resolution fix for XR
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ClearBlack.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ClearBlack.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP, XR

#3073 Preliminary changes for XR deferred shading
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.compute
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewMaterialGBuffer.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Deferred.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/builddispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-clustered.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/MomentShadows.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
Labels: HDRP, XR

#3196 Fix diffusion profile needlessly set to dirty when checking the hash
  com.unity.render-pipelines.high-definition/Runtime/Utilities/DiffusionProfileHashTable.cs
Labels: HDRP, needs-backport-2019.1

#3182 Fix for instance id semantic
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
Labels: HDRP, Shader Graph, bug-fix

#3183 [Backport] Fix for instance id semantic
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
Labels: HDRP, Shader Graph, backported-2019.1, bug-fix

#3133 Fix Case 1131646: IsFrontFace Breaks Subgraphs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3087 Add remaining ShaderProperty types to Blackboard
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/AbstractShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/BooleanShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/ColorShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/CubemapShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientInputMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix2MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix3MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix4MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/MatrixShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/PreviewProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture3DShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/TextureShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Gradient/GradientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix2Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix3Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix4Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SamplerStateNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/Util/PropertyCollector.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/Views/PropertyNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/ShaderGraphLibrary/Functions.hlsl
Labels: Shader Graph, needs-backport-2019.1, new-functionality

#3029 Custom Function Node and Subgraph Output Node refactor
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Implementation/NodeUtils.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs.meta
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/Views/HlslFunctionView.cs
  com.unity.shadergraph/Editor/Drawing/Views/HlslFunctionView.cs.meta
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs.meta
  com.unity.shadergraph/Editor/Resources/Styles/HlslFunctionView.uss
  com.unity.shadergraph/Editor/Resources/Styles/HlslFunctionView.uss.meta
  com.unity.shadergraph/Editor/Resources/Styles/ReorderableSlotListView.uss
  com.unity.shadergraph/Editor/Resources/Styles/ReorderableSlotListView.uss.meta
  com.unity.shadergraph/Tests/Editor/UnitTests/MaterialNodeTests.cs
Labels: Shader Graph, needs-backport-2019.1, new-functionality

#3106 Deleted Scripting API pages and links
  com.unity.shadergraph/Documentation~/CodeFunctionNode-Port-Types.md
  com.unity.shadergraph/Documentation~/CodeFunctionNode.Binding.md
  com.unity.shadergraph/Documentation~/CodeFunctionNode.GetFunctionToConvert.md
  com.unity.shadergraph/Documentation~/CodeFunctionNode.SlotAttribute.md
  com.unity.shadergraph/Documentation~/CodeFunctionNode.md
  com.unity.shadergraph/Documentation~/Scripting-API.md
  com.unity.shadergraph/Documentation~/TableOfContents.md
  com.unity.shadergraph/Documentation~/index.md
Labels: Shader Graph, docs, needs-backport-2019.1

#3155 [Backports] Shader Graph FogBugz Fixes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/DynamicValueMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Nodes/Procedural/Noise/VoronoiNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
Labels: Shader Graph, backported-2019.1, bug-fix

#3198 Updated default frame settings
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, needs-backport-2019.1

#3190 Post-processing scene view tweaks
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Resources.meta
Labels: HDRP

#3051 Fix nullrefs when removing port with connected edges
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3161 Update git attributes to avoid asset CRLF conversion on windows
  .gitattributes
Labels: HDRP, needs-backport-2019.1

#3199 [Backport] Add remaining ShaderProperty types to Blackboard
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/AbstractShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/BooleanShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/ColorShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/CubemapShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientInputMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix2MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix3MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix4MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/MatrixShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/PreviewProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture3DShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/TextureShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Gradient/GradientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix2Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix3Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix4Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SamplerStateNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/Util/PropertyCollector.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/ShaderGraphLibrary/Functions.hlsl
Labels: Shader Graph, backported-2019.1, new-functionality

#3189 Hdrp/fix culling null result in probes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#3136 Terrain shader refactor 3
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/TerrainLit/TerrainLitUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitSurfaceData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitSurfaceData.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_BasemapGen.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap.hlsl
Labels: HDRP

#3126 Add debug mode for area light atlas
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#3033 Enable texture array by default on DX11
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, XR

#3175 Delete optimal group size define
  com.unity.render-pipelines.core/ShaderLibrary/API/D3D11.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES2.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Switch.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Vulkan.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/builddispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/cleardispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-bigtile.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-clustered.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/materialflags.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/AmbientProbeConvolution.compute
Labels: HDRP

#3030 [Backport] Custom Function Node and Subgraph Output Node refactor
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Implementation/NodeUtils.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs.meta
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/Views/HlslFunctionView.cs
  com.unity.shadergraph/Editor/Drawing/Views/HlslFunctionView.cs.meta
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs.meta
  com.unity.shadergraph/Editor/Resources/Styles/HlslFunctionView.uss
  com.unity.shadergraph/Editor/Resources/Styles/HlslFunctionView.uss.meta
  com.unity.shadergraph/Editor/Resources/Styles/ReorderableSlotListView.uss
  com.unity.shadergraph/Editor/Resources/Styles/ReorderableSlotListView.uss.meta
  com.unity.shadergraph/Tests/Editor/UnitTests/MaterialNodeTests.cs
Labels: Shader Graph, backported-2019.1, new-functionality

#3195 Zero out stencil bit after they are not needed anymore
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalNormalBuffer.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistortion.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MotionVectors/CameraMotionVectors.shader
Labels: HDRP

#3172 Fix mobile lighting attenuation (#3141)
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
Labels: lwrp, needs-backport-2019.1

#3205 Disable SceneSelectionPass in shader graph preview
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
Labels: HDRP

#3164 group node fixes
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/PropertyNodeView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ShaderGroup.cs
Labels: Shader Graph

#3209 Disable light intensity normalization
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitUI.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderPipelinePreferences.cs
Labels: HDRP

#3210 small bug fixes
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXExpressionMathTests.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/New VFX.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/00_MultiOutput.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/01_Animator.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/02_Gradient.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/03_EventAttribute.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/04_Bounds.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/05_MotionVectors.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/06_LineOutput.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/07_UnityLogo.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/08_Shadows.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/09_AttributeMaps.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/09_PointCache.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/10_SortPriority.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/11_Space.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/11_SpaceBis.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/11_Space_Automatic.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/12_LocalTransformations.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/13_Decals.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/14_DecalsFlipBook.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/15_CubeAndMesh.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/16_CullingMode_Always.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/16_CullingMode_BoundUpdate.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/16_CullingMode_CullUpdate.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/16_MeshParticles.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/17_GPUEvent_Simple.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/17_SoftParticles.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/19_Random.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/20_SpawnerChaining.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/21_DepthModules.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/22_Prewarm_High.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/22_Prewarm_Medium.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/22_Prewarm_None.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/23_InvertTRSMatrix_Various_Path.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/23_InvertTRS_GPU_Event.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/AngularVelocity.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/CollisionInverted.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/CollisionPlane.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/CollisionSolid.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/ConformAndSDF.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/HDRP.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/HDRPFog.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/Noise.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/ParticleCountLimit.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/RenderStates.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/SimpleLitShadow.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/Timeline.vfx
  TestProjects/VisualEffectGraph/ProjectSettings/ProjectSettings.asset
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/GraphView/Elements/Controllers/VFXOperatorController.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/Controller/VFXViewControllerUndo.cs
  com.unity.visualeffectgraph/Editor/Templates/Empty Particle System.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Particle System.vfx
  com.unity.visualeffectgraph/Editor/Templates/Simple Swarm Particle System.vfx
Labels: vfx

#3115 Control punctual light and area light shadow atlas separately
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Def.asset
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDShadowInitParameters.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#3179 Per object occlusion probes
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/049_Lighting_Mixed_Subtractive.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/049_Lighting_Mixed_Subtractive.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/049_Lighting_Mixed_Subtractive.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/049_Lighting_Mixed_Subtractive.png.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/045_CustomLWPipe.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/045_CustomLWPipe.unity.meta
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ForwardLights.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/ShaderLibrary/Input.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/UnityInput.hlsl
Labels: lwrp, needs-backport-2019.1

#3212 Fix fogbugzz 1134980 + fix warning
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#3207 Fix SMAA for XR texture macros and temporarily disable stencil
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasingBridge.hlsl
Labels: HDRP

#3193 [Backport] Fix FB #1115432 and FB#1115112 - Various undo issues
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
  com.unity.shadergraph/Editor/Drawing/Views/Slots/BooleanSlotControlView.cs
  com.unity.shadergraph/Editor/Drawing/Views/Slots/GradientSlotControlView.cs
  com.unity.shadergraph/Editor/Drawing/Views/Slots/MultiFloatSlotControlView.cs
Labels: Shader Graph, bug-fix

#3202 Fix for motion blur on PS4 by declaring multiple variants for the scattering version
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#3203 Motion blur fix on PS4 by creating scattering variants (port from PR 3202)
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#3208 Updates to the changelog.
  com.unity.shadergraph/CHANGELOG.md
Labels: Shader Graph

#3222 Fix Xbox just rendering a grey screen
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, needs-backport-2019.1

#3223 Fix probe handles for multiselection
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.cs
Labels: HDRP, needs-backport-2019.1

#3217 Remove cubemap convolution for baked cubemaps at import
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
Labels: HDRP, needs-backport-2019.1

#3219 fix regression on checking null current rp asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
Labels: HDRP, needs-backport-2019.1

#3220 Fix a bunch of fullscreen debug modes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#3218 Hdrp/docs/toc reorg
  com.unity.render-pipelines.high-definition/Documentation~/Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.1

#3146 Optimized classes scanning done through CoreUtils.
  com.unity.render-pipelines.core/Editor/Volume/VolumeComponentEditor.cs
  com.unity.render-pipelines.core/Editor/Volume/VolumeComponentListEditor.cs
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.core/Runtime/Volume/VolumeManager.cs
  com.unity.render-pipelines.high-definition/Editor/Core/Debugging/DebugUIHandlerCanvasEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Core/Debugging/DebugWindow.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, SRP, needs-backport-2019.1

#3224 Move SMAA option after TAA
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
Labels: HDRP, needs-backport-2019.1

#3225 Fix warning in SMAA shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP, backported-2019.1

#3226 Patch 5.8.1 - Temp fix for missing resources to allow package migration
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP

#3200 XR volumetric rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, XR

#3230 Vfx/fix/2019.1/edge dynamic operator
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXVariableOperatorControllerTests.cs
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/GraphView/Elements/VFXDataAnchor.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/Controller/VFXViewController.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXView.cs
Labels: vfx

#3213 Vfx/fix/2019.1/floatfield focus
  com.unity.visualeffectgraph/Editor/VisualElementExtensions.cs
Labels: vfx

#3229 Add more variants for static only lighting and skip build light list when not needed.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
Labels: HDRP, needs-backport-2019.1

#3236 Hdrp/fix missing resources when upgrading cleanfix
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDAssetFactory.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/ResourceReloader.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/ResourceReloader.cs.meta
Labels: HDRP

#3239 Fix volumetric tests
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
Labels: HDRP, needs-backport-2019.1

#3238 Fix PBR master node preview
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
Labels: HDRP, needs-backport-2019.1

#3243 Fix missing invalidation in OnEnable of VFXGraph
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Models/VFXGraph.cs
Labels: vfx

#3074 Fix HDRP deferred shading with stereo instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/builddispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/materialflags.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, XR

#3241 Fix missing invalidation in OnEnable of VFXGraph
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Models/VFXGraph.cs
Labels: vfx

#3240 Fix missing invalidation in OnEnable of VFXGraph
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Models/VFXGraph.cs
Labels: vfx

#3227 Lw/lwrp examples
  TestProjects/LWGraphicsTest/Assets/Scenes/045_CustomLWPipe/CustomLWPipe.cs
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ForwardRendererDataEditor.cs
  com.unity.render-pipelines.lightweight/Editor/RenderStateDataEditor.cs
  com.unity.render-pipelines.lightweight/Editor/RenderStateDataEditor.cs.meta
  com.unity.render-pipelines.lightweight/Editor/ScriptableRendererDataEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/RenderStateData.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/RenderStateData.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/DepthOnlyPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/DrawObjectsPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/DrawObjectsPass.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderTransparentForwardPass.cs
Labels: lwrp

#3168 [HDRP] Update decal UI
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Core/Gizmo/HierarchicalBox.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.Skin.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentHandle.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/MigrationDescription.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.Migration.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderPipelinePreferences.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardLights.cs
Labels: HDRP

#3231 Vfx/fix/edge dynamic operator
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXVariableOperatorControllerTests.cs
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/GraphView/Elements/VFXDataAnchor.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/Controller/VFXViewController.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/Controller/VFXViewControllerUndo.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXView.cs
Labels: vfx

#3244 fix wrong time for calling MarkSceneAsDirty
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/MigrationDescription.cs
Labels: HDRP

#3245 Fixed an issue where shadow would not be rendered properly when light layer are not enabled
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2309_Shadow_DisableLightLayer.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2309_Shadow_DisableLightLayer.unity.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2309_Shadow_DisableLightLayer.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2309_Shadow_DisableLightLayer.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP, needs-backport-2019.1

#3247 Don't use light list if it has not been generated (Backport of 3246)
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
Labels: HDRP

#3246 Don't use light list if it has not been generated
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
Labels: HDRP, needs-backport-2019.1

#3112 Nested sub graphs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/ShaderGraphRequirements.cs
  com.unity.shadergraph/Editor/Data/Implementation/GraphObject.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/MaterialSubGraphAsset.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphAsset.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphAsset.cs.meta
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Data/Util/FunctionRegistry.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/IndexSetPool.cs
  com.unity.shadergraph/Editor/Data/Util/IndexSetPool.cs.meta
  com.unity.shadergraph/Editor/Data/Util/PropertyCollector.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs.meta
  com.unity.shadergraph/Editor/Importers/_.sgsubgraphdb
  com.unity.shadergraph/Editor/Importers/_.sgsubgraphdb.meta
  com.unity.shadergraph/Editor/Util/CopyPasteGraph.cs
  com.unity.shadergraph/Editor/Util/IndexSet.cs
Labels: Shader Graph, new-functionality

#3206 Backport PR #3112 (Nested sub graphs)
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/ShaderGraphRequirements.cs
  com.unity.shadergraph/Editor/Data/Implementation/GraphObject.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/MaterialSubGraphAsset.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphAsset.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphAsset.cs.meta
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Data/Util/FunctionRegistry.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/IndexSetPool.cs
  com.unity.shadergraph/Editor/Data/Util/IndexSetPool.cs.meta
  com.unity.shadergraph/Editor/Data/Util/PropertyCollector.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs
  com.unity.shadergraph/Editor/Importers/SubGraphData.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabase.cs.meta
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs.meta
  com.unity.shadergraph/Editor/Importers/_.sgsubgraphdb
  com.unity.shadergraph/Editor/Importers/_.sgsubgraphdb.meta
  com.unity.shadergraph/Editor/Util/CopyPasteGraph.cs
  com.unity.shadergraph/Editor/Util/IndexSet.cs
Labels: Shader Graph

#3259 Lw/render pass feature fixes
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/RendererFeatures.meta
  com.unity.render-pipelines.lightweight/Editor/RendererFeatures/RenderObjectsPassFeatureEditor.cs
  com.unity.render-pipelines.lightweight/Editor/RendererFeatures/RenderObjectsPassFeatureEditor.cs.meta
  com.unity.render-pipelines.lightweight/Editor/ScriptableRendererDataEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderObjectsPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderObjectsPass.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/RendererFeatures.meta
  com.unity.render-pipelines.lightweight/Runtime/RendererFeatures/RenderObjects.cs
  com.unity.render-pipelines.lightweight/Runtime/RendererFeatures/RenderObjects.cs.meta
Labels: lwrp

#3254 Fix issue causing controls to stick around
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Resources/Styles/MaterialNodeView.uss
Labels: Shader Graph, bug-fix

#3263 Fix issue causing controls to stick around (backport #3254)
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Resources/Styles/MaterialNodeView.uss
Labels: Shader Graph, bug-fix

#3257 Restructure code from HDCamera.Update()
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
Labels: HDRP, XR

#3265 Fix bad merge
  com.unity.render-pipelines.lightweight/Editor/ScriptableRendererDataEditor.cs
Labels: lwrp

#3256 Fixed Light intensity not played in the player when recorded with animation/timeline
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP, needs-backport-2019.1

#3255 Fix exposure weight for HDRP unlit shaders
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitData.hlsl
Labels: HDRP, needs-backport-2019.1

#3262 Fix emission node shader graph preview
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/EmissionNode.cs
Labels: HDRP, needs-backport-2019.1

#3149 Shader Graph asset icons
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Resources/Icons/sg_graph_icon@64.png
  com.unity.shadergraph/Editor/Resources/Icons/sg_graph_icon@64.png.meta
  com.unity.shadergraph/Editor/Resources/Icons/sg_subgraph_icon@64.png
  com.unity.shadergraph/Editor/Resources/Icons/sg_subgraph_icon@64.png.meta
Labels: Shader Graph

#3060 Async Compilation for Preview Shaders
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightPBRSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightUnlitSubShader.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/PreviewProperty.cs
  com.unity.shadergraph/Editor/Data/Interfaces/Graph/INode.cs
  com.unity.shadergraph/Editor/Data/MasterNodes/ISubShader.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/IMasterNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/MasterNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/PropertyCollector.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
  com.unity.shadergraph/Editor/DefaultShaderIncludes.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
  com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Util/MessageManager.cs
  com.unity.shadergraph/Tests/Editor/UnitTests/MessageManagerTests.cs
Labels: Shader Graph, needs-backport-2019.1

#3270 Lw/fix transparent sortflag
  TestProjects/LWGraphicsTest/Assets/Scenes/045_CustomLWPipe/CustomLWPipe.cs
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/DrawObjectsPass.cs
Labels: lwrp

#3278 Add _TERRAIN_BLEND_DENSITY macro
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap_Includes.hlsl
Labels: HDRP, needs-backport-2019.1

#3273 Checkout baked files when baking probes with HDRP's reflection system
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
Labels: HDRP, needs-backport-2019.1

#3268 Hdrp/docs/volume component docs and dynamic resolution
  com.unity.render-pipelines.high-definition/Documentation~/Atmospheric-Scattering.md
  com.unity.render-pipelines.high-definition/Documentation~/Dynamic-Resolution.md
  com.unity.render-pipelines.high-definition/Documentation~/Environment-Lighting.md
  com.unity.render-pipelines.high-definition/Documentation~/Fog-Overview.md
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/Getting-started-with-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/DynamicResolution1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-ContactShadows1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-DiffusionProfile1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-ExponentialFog1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-GradientSky1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-HDRISky1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-IndirectLightingController1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-LinearFog1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-ProceduralSky1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-Shadows1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-Shadows2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-Shadows3.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VisualEnvironment1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VisualEnvironment2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricFog1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricFog2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricFog3.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricLightingController1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/OverrideAmbientOcclusion1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/OverrideMicroShadows1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/OverrideMicroShadows2.png
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Contact-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exponential-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Gradient-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-HDRI-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Indirect-Lighting-Controller.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Linear-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Micro-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Procedural-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Visual-Environment.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Lighting-Controller.md
  com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Sky-Overview.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumetric-Lighting.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/DiffusionProfileOverrideEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
Labels: HDRP, docs, needs-backport-2019.1

#3264 Strip motion blur scattering code from Metal
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
Labels: HDRP, needs-backport-2019.1

#3276 Fix motion vector debug clamp due to UFloat debug texture format
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#3261 Add exposure test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/DecalEmission.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/DecalEmission.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/DecalEmissionGraph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/DecalEmissionGraph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/DecalEmissionGraph.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/DecalEmissionGraph.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/DecalReceiver.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/DecalReceiver.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/FabricEmissionGraph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/FabricEmissionGraph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/FabricEmissionGraph.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/FabricEmissionGraph.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LayeredLitEmission.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LayeredLitEmission.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LayeredLitEmissionWeight.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LayeredLitEmissionWeight.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LitEmission.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LitEmission.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LitEmissionGraph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LitEmissionGraph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LitEmissionGraph.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LitEmissionGraph.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LitEmissionWeight.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/LitEmissionWeight.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/PBREmissionGraph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/PBREmissionGraph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/PBREmissionGraph.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/PBREmissionGraph.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/StackLitEmissionGraph.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/StackLitEmissionGraph.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/StackLitEmissionGraph.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/StackLitEmissionGraph.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/UnLitEmission.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/UnLitEmission.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/UnLitEmissionWeight.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4000_Exposure/UnLitEmissionWeight.mat.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP, needs-backport-2019.1

#3266 Add exposure and HD scene color nodes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ExposureNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ExposureNode.cs.meta
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/HDSceneColorNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/HDSceneColorNode.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderGraphFunctions.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP, needs-backport-2019.1

#3117 [Backport] Fix for Blend Node NaN Output
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Blend/BlendNode.cs
Labels: Shader Graph, bug-fix

#3289 Revert line-ending changes to CHANGELOG.md.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
Labels: lwrp

#3258 LWRP XR Eye Texture Reallocation
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: lwrp

#3232 LWRP MSAA Optimization
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
Labels: lwrp

#3299 Revert "Add exposure and HD scene color nodes"
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ExposureNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ExposureNode.cs.meta
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/HDSceneColorNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/HDSceneColorNode.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderGraphFunctions.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#3292 Fixed issue with invalid gizmo position for rotated ReflectionProbe
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2207_ReflectionProbeVFace.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2210_ReflectionProbes_CaptureAtVolumeAnchor.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2207_ReflectionProbeVFace.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2207_ReflectionProbeVFace.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeCapturePositionSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP, needs-backport-2019.1

#3287 Hdrp/fix multiedition renderqueue
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
Labels: HDRP

#3285 [HDRP] Remove unused advanced button on light's shape
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP, needs-backport-2019.1

#3286 [HDRP] Remove pipeline reconstruction when selecting/modifying other pipeline asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
Labels: HDRP

#3282 Shadow debug mode fixes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP, needs-backport-2019.1

#3228 Re-enable SMAA stencil
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.shader
Labels: HDRP

#3216 Hdrp decals htile fix
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9005_Decals-stress-test.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
Labels: HDRP

#2912 Fix hair lighting
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1213_Lit_Anisotropy.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1213_Lit_Anisotropy.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1402_StackLitSG_Testers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1402_StackLitSG_Testers.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1501_Fabric.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1501_Fabric.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1701_HairGraph.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1701_HairGraph.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/ImageBasedLighting.hlsl
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
Labels: HDRP, needs-backport-2019.1

#3295 Re-fix HD PBR node preview in shader graph
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
Labels: HDRP

#3300 Update test shader StencilWriteShader.shader to motion vector nomenclature
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_And_2209_Reflection_Stencil/StencilWriteShader.shader
Labels: HDRP

#3298 Fix wobbling of AfterPostProcess objects when TAA is enabled
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.1

#3274 Remove use legacy unity matrix variables
  com.unity.render-pipelines.high-definition/Editor/Material/DiffusionProfile/DrawDiffusionProfile.shader
  com.unity.render-pipelines.high-definition/Editor/Material/DiffusionProfile/DrawTransmittanceGraph.shader
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitDataMeshModification.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitTemplate.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_BasemapGen.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/EditorShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/EditorShaderVariables.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesMatrixDefsLegacyUnity.hlsl
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/ShaderGraphLibrary/ShaderVariables.hlsl
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleLines/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleLinesSW/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleMeshes/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleQuads/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/ParticleSpheres/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Hexahedron/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Quad/PassShadowCaster.template
Labels: HDRP, needs-backport-2019.1

#3307 Disable ComputeLightEvaluation with XR instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, XR, needs-backport-2019.1

#3277 [Backport] Async Compilation for Preview Shaders
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightPBRSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightUnlitSubShader.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/PreviewProperty.cs
  com.unity.shadergraph/Editor/Data/Interfaces/Graph/INode.cs
  com.unity.shadergraph/Editor/Data/MasterNodes/ISubShader.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/IMasterNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/MasterNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/PropertyCollector.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
  com.unity.shadergraph/Editor/DefaultShaderIncludes.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
  com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Util/MessageManager.cs
  com.unity.shadergraph/Tests/Editor/UnitTests/MessageManagerTests.cs
Labels: Shader Graph
