Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-11, with the labels that each got.

#4947 Fix compile errors in XRGraphics.cs for platforms with no VR support
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
Labels: HDRP, SRP, Universal, XR, needs-backport-2019.3

#4946 Fix yet another issue with volumetrics and RTHandle scaling
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#4945 Disable deprecation warning
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineLightEditor.cs
  com.unity.testframework.graphics/Editor/SetupGraphicsTestCases.cs
Labels: HDRP, Universal

#4938 ShadowMatte Shader docs
  com.unity.render-pipelines.high-definition/Documentation~/Camera-Relative-Rendering.md
  com.unity.render-pipelines.high-definition/Documentation~/Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/Layered-Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Master-Node-Hair.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Getting-Started.md
  com.unity.render-pipelines.high-definition/Documentation~/ShadowMatte-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Documentation~/Unlit-Shader.md
Labels: HDRP, docs, needs-backport-2019.3

#4871 Removal of additional camera data fix
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/UniversalAdditionalCameraDataEditor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
Labels: Universal, needs-backport-2019.3

#4844 Fix renderer features list giving null reference
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/RendererFeatures/RenderObjectsPassFeatureEditor.cs
  com.unity.render-pipelines.universal/Editor/ScriptableRendererDataEditor.cs
Labels: Universal, needs-backport-2019.3

#4788 Fix URP post processing with XR single-pass methods
  TestProjects/UniversalGfxTestStereo/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl
  com.unity.render-pipelines.universal/Shaders/PostProcessing/Bloom.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/BokehDepthOfField.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/CameraMotionBlur.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/Common.hlsl
  com.unity.render-pipelines.universal/Shaders/PostProcessing/FinalPost.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/GaussianDepthOfField.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/StopNaN.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/SubpixelMorphologicalAntialiasingBridge.hlsl
  com.unity.render-pipelines.universal/Shaders/PostProcessing/UberPost.shader
  com.unity.render-pipelines.universal/Shaders/Utils/Sampling.shader
Labels: Universal, XR, needs-backport-2019.3

#4804 Remove special handling to set alpha of framebuffer to 1.0
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipelineCore.cs
  com.unity.render-pipelines.universal/Shaders/Utils/Blit.shader
Labels: Universal

#4941 2d/bug fixes chris
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/CinemachineUniversalPixelPerfectEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/CinemachineUniversalPixelPerfectEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.universal/Runtime/2D/CinemachineUniversalPixelPerfect.cs
  com.unity.render-pipelines.universal/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCamera.cs
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCameraInternal.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2DData.cs
  com.unity.render-pipelines.universal/Runtime/Unity.RenderPipelines.Universal.Runtime.asmdef
  com.unity.render-pipelines.universal/Shaders/2D/Include/CombinedShapeLightShared.hlsl
  com.unity.render-pipelines.universal/Shaders/2D/Include/LightingUtility.hlsl
Labels: Universal, needs-backport-2019.3

#4958 Fixed an issue where sky lighting might be updated uselessly
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, needs-backport-2019.3

#4956 Allow setting decal material to none
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs
Labels: HDRP

#4964 Backport #4941
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/CinemachineUniversalPixelPerfectEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/CinemachineUniversalPixelPerfectEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.universal/Runtime/2D/CinemachineUniversalPixelPerfect.cs
  com.unity.render-pipelines.universal/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCamera.cs
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCameraInternal.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2DData.cs
  com.unity.render-pipelines.universal/Runtime/Unity.RenderPipelines.Universal.Runtime.asmdef
  com.unity.render-pipelines.universal/Shaders/2D/Include/CombinedShapeLightShared.hlsl
  com.unity.render-pipelines.universal/Shaders/2D/Include/LightingUtility.hlsl
Labels: Universal

#4962 Backporting #4941
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/CinemachineUniversalPixelPerfectEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/CinemachineUniversalPixelPerfectEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.universal/Runtime/2D/CinemachineUniversalPixelPerfect.cs
  com.unity.render-pipelines.universal/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCamera.cs
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCameraInternal.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2DData.cs
  com.unity.render-pipelines.universal/Runtime/Unity.RenderPipelines.Universal.Runtime.asmdef
  com.unity.render-pipelines.universal/Shaders/2D/Include/CombinedShapeLightShared.hlsl
  com.unity.render-pipelines.universal/Shaders/2D/Include/LightingUtility.hlsl
Labels: Universal

#4965 Different bloom handling when low resolution
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP

#4953 Fix XR multi-pass decals rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, XR, needs-backport-2019.3

#4625 Group node fixes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ShaderGroup.cs
  com.unity.shadergraph/Editor/Drawing/Views/StickyNote.cs
Labels: Shader Graph

#4944 Hdrp/fixes on light inspector
  .github/PULL_REQUEST_TEMPLATE.md
  com.unity.render-pipelines.core/Editor/CoreEditorDrawers.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSettingValue.cs
Labels: HDRP, needs-backport-2019.3

#4969 Fix EOL for some files in HDRP
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/AutodeskInteractiveMaterialImport.cs
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/FBXMaterialDescriptionPostprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/ThreeDSMaterialDescriptionPostprocessor.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ClearPropertyMaskBuffer.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
Labels: HDRP

#4954 Add XR single-pass setting to HDRP asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedXRSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/GlobalXRSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
Labels: HDRP, XR, needs-backport-2019.3

#4970 Minor fix to changelog
  com.unity.render-pipelines.universal/CHANGELOG.md
Labels: Universal, needs-backport-2019.3

#4865 Universal/bugfixes
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/RendererFeatures/RenderObjectsPassFeatureEditor.cs
  com.unity.render-pipelines.universal/Editor/ScriptableRendererDataEditor.cs
  com.unity.render-pipelines.universal/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.universal/Runtime/RenderingUtils.cs
  com.unity.render-pipelines.universal/Shaders/Lit.shader
  com.unity.render-pipelines.universal/Shaders/SimpleLit.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitAdd.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBase.shader
  com.unity.render-pipelines.universal/Shaders/Unlit.shader
  com.unity.render-pipelines.universal/Shaders/Utils/FallbackError.shader
  com.unity.render-pipelines.universal/Shaders/Utils/FallbackError.shader.meta
Labels: Universal, needs-backport-2019.3

#4973 Fixed an issue with cached point shadows causing an exception.
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP, needs-backport-2019.3

#4975 Fixed an issue with cached point shadows causing an exception.
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4976 Universal/backports
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/Unity.Testing.SRP.Universal.Editor.asmdef
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/UniversalProjectEditorTests.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/UniversalProjectEditorTests.cs.meta
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/RendererFeatures/RenderObjectsPassFeatureEditor.cs
  com.unity.render-pipelines.universal/Editor/ScriptableRendererDataEditor.cs
  com.unity.render-pipelines.universal/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.universal/Editor/UniversalAdditionalCameraDataEditor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.universal/Runtime/Passes/ColorGradingLutPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Runtime/RenderingUtils.cs
  com.unity.render-pipelines.universal/Shaders/Lit.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/Common.hlsl
  com.unity.render-pipelines.universal/Shaders/SimpleLit.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitAdd.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBase.shader
  com.unity.render-pipelines.universal/Shaders/Unlit.shader
  com.unity.render-pipelines.universal/Shaders/Utils/FallbackError.shader
  com.unity.render-pipelines.universal/Shaders/Utils/FallbackError.shader.meta
Labels: Universal

#4986 Backport XR postfx fixes to Universal RP
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl
  com.unity.render-pipelines.universal/Shaders/PostProcessing/Bloom.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/BokehDepthOfField.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/CameraMotionBlur.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/Common.hlsl
  com.unity.render-pipelines.universal/Shaders/PostProcessing/FinalPost.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/GaussianDepthOfField.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/StopNaN.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/SubpixelMorphologicalAntialiasingBridge.hlsl
  com.unity.render-pipelines.universal/Shaders/PostProcessing/UberPost.shader
  com.unity.render-pipelines.universal/Shaders/Utils/Sampling.shader
Labels: Universal, XR

#4988 StackLit: Fix a graphics test failure introduced by an engine-side ch…
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1302_03_StackLit/Default-Checker-Gray-not_builtin.png
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1302_03_StackLit/Default-Checker-Gray-not_builtin.png.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1302_03_StackLit/SLSG_BaseM_2Mc.mat
Labels: HDRP

#4955 Fix HDRP scene view rendering with volumetrics and XR
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5002_Fog_DensityVolumes.unity
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
  com.unity.testing.hdrp/TestRunner/HDRP_GraphicTestRunner.cs
Labels: HDRP, XR, needs-backport-2019.3

#4974 remove unneeded protected that trigger exception on rider
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
Labels: HDRP

#4972 Make decals work with multiple cameras
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#4843 Backport bugfix for bug case 1183200
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, needs-backport-2019.2

#4952 Fix crash of prefab mode in 2019.2
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backported-2019.2

#4998 Added the new upgrading doc
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP10.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP11.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP1Main.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP3.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP4.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP5.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP6.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP7.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP8.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/UpgradingToHDRP9.png
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-To-HDRP.md
Labels: HDRP, docs, needs-backport-2019.3

#4989 Update docs and remove warning for AO
  com.unity.render-pipelines.high-definition/Documentation~/Images/OverrideAmbientOcclusion1.png
  com.unity.render-pipelines.high-definition/Documentation~/Override-Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
Labels: HDRP

#4981 Re-enable optional clears of GBuffers
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#4991 [Shader Graph] Remove Meta File
  com.unity.shadergraph/Editor/Data/Descriptors.meta
Labels: Shader Graph, bug-fix, needs-backport-2019.3

#4966 Hdrp/update lod test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9002_FrameSettings_LOD.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9002_FrameSettings_LOD.png
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#4921 Adding penumbra Tint and a test for shadow tint and penumbra tint
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2603_ShadowTint.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2603_ShadowTint.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2603_ShadowTint.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2603_ShadowTint/M_DiffuseMaterial.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2603_ShadowTint/M_DiffuseMaterial.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2603_ShadowTint.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2603_ShadowTint.png.meta
  TestProjects/HDRP_Tests/Assets/S_TintShadow.unity
  TestProjects/HDRP_Tests/Assets/S_TintShadow.unity.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.core/ShaderLibrary/CommonLighting.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
Labels: HDRP

#4878 Backport: Terrain holes fixed
  com.unity.render-pipelines.universal/Documentation~/universalrp-asset.md
  com.unity.render-pipelines.universal/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitAdd.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBase.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: Universal, backported-2019.3

#4879 Backport: Terrain holes fixed
  com.unity.render-pipelines.universal/Documentation~/universalrp-asset.md
  com.unity.render-pipelines.universal/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitAdd.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBase.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: Universal

#5000 Add mention of config package and quality/default settings to upgrade doc
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2019.2-to-2019.3.md
Labels: HDRP

#4993 Fix render target clears for XR single-pass
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, XR, needs-backport-2019.3

#4949 PCSS reparameterization
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2307_Shadow_VeryHigh.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2307_Shadow_VeryHigh.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2019.2-to-2019.3.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
Labels: HDRP

#4997 Fix issue that caused test to fail on MacOS OpenGL
  com.unity.render-pipelines.universal/Runtime/RenderingUtils.cs
  com.unity.testframework.graphics/Runtime/ImageAssert.cs
Labels: Universal

#5004 Changing the moment where the depth and normal history are copied
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#4948 Fixed XR shader failure in URP ShaderGraph
  com.unity.render-pipelines.core/ShaderLibrary/UnityInstancing.hlsl
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/DepthOnlyPass.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/LightingMetaPass.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/ShadowCasterPass.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/Varyings.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalShaderGraphResources.cs
Labels: Shader Graph, Universal, XR, needs-backport-2019.3

#4994 Add depth copy support for XR SDK
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/CopyDepthBuffer.shader
Labels: HDRP, XR, needs-backport-2019.3

#5014 Radius scale for PCSS softness
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#5023 Improve stability
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
Labels: HDRP

#4984 Updated the zoom level
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph

#5019 Added HDRP config doc and linked to it from the Config package
  com.unity.render-pipelines.high-definition-config/Documentation~/Configuration.md
  com.unity.render-pipelines.high-definition-config/Documentation~/index.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Config-Package.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.3

#5020 Adding an optional bilateral pass to filter the volumetric lighting and a test scene for it
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering/Sky and Fog Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering/Sky and Fog Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5008_FogFiltering.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5008_FogFiltering.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/FogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/Fog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
Labels: HDRP

#5033 Merge Hdrp/staging
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering/Sky and Fog Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering/Sky and Fog Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5008_FogFiltering.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5008_FogFiltering.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/FogEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/Fog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/CopyDepthBuffer.shader
Labels: HDRP, needs-backport-2019.3

#5021 Fixed a number of issues with Material Quality setting
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality/CaptureRenderTarget.renderTexture
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality/CaptureRenderTarget.renderTexture.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality/MaterialQualityTestShader.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality/MaterialQualityTestShader.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality/Shader Graphs_MaterialQualityTestShader.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality/Shader Graphs_MaterialQualityTestShader.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality/ShowCapture.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1801_MaterialQuality/ShowCapture.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1801_MaterialQuality.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1801_MaterialQuality.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.core/Runtime/Utilities/MaterialQuality.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/BaseShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.shadergraph/Editor/Data/Util/KeywordUtil.cs
  com.unity.testing.hdrp/RP_Assets/HDRP_Test_CustomQualityLevels.asset
  com.unity.testing.hdrp/RP_Assets/HDRP_Test_CustomQualityLevels.asset.meta
Labels: HDRP, needs-backport-2019.3

#5028 Fixed a warning regarding namespaces in LibTessDotNet.
  com.unity.render-pipelines.universal/Runtime/External/LibTessDotNet/Dict.cs
  com.unity.render-pipelines.universal/Runtime/External/LibTessDotNet/Geom.cs
  com.unity.render-pipelines.universal/Runtime/External/LibTessDotNet/Mesh.cs
  com.unity.render-pipelines.universal/Runtime/External/LibTessDotNet/MeshUtils.cs
  com.unity.render-pipelines.universal/Runtime/External/LibTessDotNet/PriorityHeap.cs
  com.unity.render-pipelines.universal/Runtime/External/LibTessDotNet/PriorityQueue.cs
  com.unity.render-pipelines.universal/Runtime/External/LibTessDotNet/Sweep.cs
  com.unity.render-pipelines.universal/Runtime/External/LibTessDotNet/Tess.cs
Labels: Universal

#5034 Corerp/add contextmenu dispatcher
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/ContextualMenuDispatcher.cs
  com.unity.render-pipelines.core/Editor/ContextualMenuDispatcher.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraEditor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
Labels: HDRP, Universal, needs-backport-2019.3

#5041 Rename the Material update progress bar triggered when saving a ShaderGraph
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/ShaderGraphMaterialsUpdater.cs
Labels: HDRP

#5040 Added a multiplier for transmission for directional lights
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-Shadows1.png
  com.unity.render-pipelines.high-definition/Documentation~/Override-Shadows.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/HDShadowSettingsEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, needs-backport-2019.3

#5038 Hdrp/fix whitelisted stylesheet error
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/QualitySettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Resources/DiffusionProfileSlotControlView.uss
  com.unity.render-pipelines.high-definition/Editor/USS/Formating.uss
  com.unity.render-pipelines.high-definition/Editor/USS/QualitySettings.uss
  com.unity.render-pipelines.high-definition/Editor/USS/WizardDark.uss
  com.unity.render-pipelines.high-definition/Editor/USS/WizardLight.uss
Labels: HDRP, needs-backport-2019.3

#5037 Fix nullrefs in the material editor when entering play mode
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/TerrainLit/TerrainLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/HDShaderGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitGUI.cs
Labels: HDRP

#5036 Rework XR automated tests for HDRP with XRLayout API
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2008_Light_Volumetrics.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2551_SSR.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5001_Fog_FogFallback.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5002_Fog_DensityVolumes.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5003_Fog_DensityVolumesShadows.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5008_FogFiltering.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8103_PrePostPass.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9002_FrameSettings_LOD.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9003_CameraRelativeRendering.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9004_MultiViewport.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9601_SkinnedMeshBatching-Off.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9602_SkinnedMeshBatching-On.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9603_MeshRendererBatching-Off.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9604_MeshRendererBatching-On.unity
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRLayout.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRLayout.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/XRSystemTests.cs
  com.unity.testing.hdrp/TestRunner/HDRP_GraphicTestRunner.cs
  com.unity.testing.hdrp/TestRunner/HDRP_TestSettings.cs
Labels: HDRP, XR, needs-backport-2019.3

#5026 Hdrp/fix/unlit double sided settings view
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSettingsView.cs
Labels: HDRP

#5025 Invalidating the history for directional, point and spot lights for ray traced screen space shadows when the light has moved
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
Labels: HDRP, dxr

#5029 Fix issue with contact shadow when max distance is close to far clip plane
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
Labels: HDRP

#5054 SSS shadergraph preview
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
Labels: HDRP

#5024 Custom pass fixes 3
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/GreenPP.cs
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/Volume/VolumeMenuItems.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassFullScreenShader.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/DrawRenderersCustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/FullScreenCustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/CustomPass.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/CustomPass/DefaultRenderer.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/CustomPass/DefaultRenderer.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing/CustomPostProcessInjectionPoint.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassInjectionPoint.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassInjectionPoint.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/DrawRenderersCustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/FullScreenCustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#5005 Changing the behavior for ray tracing in case a submesh has both opaque and transparent sub meshes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingGBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl
Labels: HDRP, dxr

#4987 Hdrp/fix camera with prefab override workflow
  .github/PULL_REQUEST_TEMPLATE.md
  com.unity.render-pipelines.core/Editor/CoreEditorStyles.cs
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/Utilities/SerializedBitArray.cs
  com.unity.render-pipelines.core/Runtime/Utilities/BitArray.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableFrameSettingsArea.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
Labels: HDRP, needs-backport-2019.3

#4996 Improve history buffer management
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, needs-backport-2019.3

#5016 Add Bellevue QA to SG code owners
  .github/CODEOWNERS
Labels: Shader Graph

#5055 Sync shadergraph settings name
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSettingsView.cs
Labels: HDRP

#4931 Universal/docs/post processing docs
  com.unity.render-pipelines.universal/Documentation~/2d-index.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Lift-Gamma-Gain.md
  com.unity.render-pipelines.universal/Documentation~/TableOfContents.md
  com.unity.render-pipelines.universal/Documentation~/index.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-bloom.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-chromatic-aberration.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-depth-of-field.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-tonemapping.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-vignette.md
Labels: Universal, docs, needs-backport-2019.3

#5065 Unlit Master Node
  com.unity.render-pipelines.high-definition/Documentation~/Images/MasterNodeUnlit1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/MasterNodeUnlit2.png
  com.unity.render-pipelines.high-definition/Documentation~/Master-Node-Hair.md
  com.unity.render-pipelines.high-definition/Documentation~/Master-Node-Unlit.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.3

#5064 Working around a Metal Shader Compiler Crash
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute
Labels: HDRP, needs-backport-2019.3

#5067 Spot lights missing from ray tracing indirect effects
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
Labels: HDRP, dxr

#5066 Backport of fix for bug 1193198 to 2019.2
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, backported-2019.2

#5073 Fixed CoreRP description
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/package.json
Labels: needs-backport-2019.3

#4960 Adding a new refraction mode and changing refraction UI
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/LitSurfaceInputsUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/RefractionUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/TransparencyUIBlock.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceRefraction.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitDataIndividualLayer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitProperties.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
Labels: HDRP

#5011 CoreRP/Catch srp loading error while assetdatabase not available [Need C++ PR]
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Runtime/Utilities/ResourceReloader.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2DData.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRendererData.cs
Labels: HDRP, Universal, needs-backport-2019.3

#5069 Hdrp/fix/diffusion profile wizzard
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.UIElement.cs
Labels: HDRP

#5068 Hdrp/fix/diffusion profile hash on creation
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/DiffusionProfileHashTable.cs
Labels: HDRP, needs-backport-2019.3

#5059 Replace deprecated XR code
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
Labels: HDRP, Universal, XR, needs-backport-2019.3

#5058 Initial implementation of Area Light Barn Doors
  com.unity.render-pipelines.high-definition-config/Runtime/ShaderConfig.cs
  com.unity.render-pipelines.high-definition-config/Runtime/ShaderConfig.cs.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
Labels: HDRP, dxr

#5083 Added instructions on how to enable high quality filtering in deferred mode
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Config-Package.md
  com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
Labels: HDRP, docs, needs-backport-2019.3

#5079 remove duplicate framesettings RealtimePlanarReflection
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
Labels: HDRP

#5081 Fix most of the garbage collection in HDRP
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/ShaderGraphMaterialsUpdater.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/GGXConvolution/IBLFilterGGX.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraCache.cs
Labels: HDRP

#4670 Fix leak in box spotlight shadows
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP

#5086 Cookie warning
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP

#5087 Fixing Refraction
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/Lit_Refraction_Plane.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/Lit_Refraction_Plane_NM.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/Lit_Refraction_Plane_NM_Thickness.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/Lit_Refraction_Plane_Thickness.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/Lit_Refraction_Sphere.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/Lit_Refraction_Sphere_NM.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/Lit_Refraction_Sphere_NM_Thickness.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/Lit_Refraction_Sphere_Thickness.mat
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png
Labels: HDRP

#5089 Fix nullref when using particle lights
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP

#4823 Make LOD fade mask scale with the FoV
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9001_LODTransition.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9001_LODTransition.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9601_SkinnedMeshBatching-Off.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9601_SkinnedMeshBatching-Off.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9602_SkinnedMeshBatching-On.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9602_SkinnedMeshBatching-On.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/CommonDeprecated.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/CommonDeprecated.hlsl.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyePass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Material.hlsl
  com.unity.render-pipelines.universal/Shaders/Nature/SpeedTree7CommonPasses.hlsl
  com.unity.render-pipelines.universal/Shaders/Nature/SpeedTree8Passes.hlsl
Labels: HDRP, needs-backport-2019.3

#5088 Remove debug log
  com.unity.render-pipelines.high-definition/Runtime/Utilities/DiffusionProfileHashTable.cs
Labels: HDRP

#5071 Hdrp/increase flexibility of wizard and small fixes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.UIElement.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
  com.unity.render-pipelines.high-definition/Editor/USS/Wizard.uss
Labels: HDRP, needs-backport-2019.3

#5053 Hdrp/planar reflection fov
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2206_PlanarReflectionVFace.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2208_PlanarReflectionCullingStencil.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2211_Probes_Specular.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2206_PlanarReflectionVFace.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2206_PlanarReflectionVFace.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2208_PlanarReflectionCullingStencil.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2208_PlanarReflectionCullingStencil.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2211_Probes_Specular.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2211_Probes_Specular.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP, needs-backport-2019.3

#5093 Fix contact shadow issue when MSAA is on (RTHandle scale not taken into account)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
Labels: HDRP, needs-backport-2019.3

#5072 Add "Save context" to Shader Graph to update dependent materials only when needed
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/ShaderGraphMaterialsUpdater.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Nodes/MasterNode.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
Labels: HDRP, Shader Graph

#5032 Changed the way Sky Intensity is handled
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5002_Fog_DensityVolumes/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/Resources/ProceduralSky.shader
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSkyRenderer.cs
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky.shader
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2019.2-to-2019.3.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/GradientSky/GradientSkyEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/HDRISky/HDRISkyEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky/PhysicallyBasedSkyEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/SkySettingsEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkySettings.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/Resources/ProceduralSky.shader
  com.unity.testing.hdrp/SkySettings/HDRP_Default_Sky_2.asset
  com.unity.testing.hdrp/SkySettings/HDRP_Default_Sky_3.asset
  com.unity.testing.hdrp/SkySettings/HDRP_Default_Sky_4.asset
  com.unity.testing.hdrp/SkySettings/HDRP_NormalLight.asset
Labels: HDRP, needs-backport-2019.3

#5098 Fix issues caused by box light leak fix PR
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2313_Shadow_Mask_Spotlight_Shapes.png
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP

#5102 Added custom post-process doc
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Post-Process.md
  com.unity.render-pipelines.high-definition/Documentation~/Getting-started-with-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/CustomPostProcess1.png
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Documentation~/index.md
Labels: HDRP, docs, needs-backport-2019.3

#5100 Update Custom-Pass.md
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
Labels: HDRP

#5104 Fixed an issue In URP where sometime the camera is not passed to the volume system and causes a null ref exception
  com.unity.render-pipelines.core/Runtime/Volume/VolumeManager.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP, needs-backport-2019.3

#5095 Fix scene id map warnings
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Sky/StaticLightingSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/SceneObjectIDMap.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/SceneObjectIDMapSceneAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/SceneObjectIDMapSceneAsset.cs.meta
Labels: HDRP

#5105 Fixing the refraction test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/ReflectionProbe-0.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1205_Lit_Transparent_Refraction/ReflectionProbe-0.exr.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1205_Lit_Transparent_Refraction.png
Labels: HDRP

#5106 HDRP fix custom pass release
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#5090 Read stencil directly via SRV on depth buffer
  com.unity.render-pipelines.core/Runtime/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/materialflags.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/SharedRTManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ResolveStencilBuffer.compute
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ResolveStencilBuffer.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, needs-backport-2019.3

#5112 Fix nullref when path tracing is enabled
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, dxr

#5111 Fix diffusion profile import
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.cs
Labels: HDRP

#5115 Fix builtin resource reloader
  com.unity.render-pipelines.core/Runtime/Utilities/ResourceReloader.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#5117 Fix light unit reset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP

#5122 Vfx/docs/index fix
  com.unity.visualeffectgraph/Documentation~/index.md
Labels: docs, needs-backport-2019.3, vfx

#5085 Tooltips for attributes
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Expressions/VFXAttributeExpression.cs
Labels: needs-backport-2019.3, vfx

#4995 [Shader Graph] Fix Cases 1188710 and 1158413
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Resources/Styles/Controls/UVSlotControlView.uss
Labels: Shader Graph, bug-fix, needs-backport-2019.3

#5120 Hdrp/update deocumentation links
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Wind/ShaderWindSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Wind/ShaderWindSettings.cs.meta
Labels: HDRP

#5119 Fix build with HDRP in the project when it is not assigned in the graphic settings
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
Labels: HDRP

#5116 Hdrp/backplate: Bugfixes
  com.unity.render-pipelines.core/ShaderLibrary/SDF2D.hlsl
  com.unity.render-pipelines.high-definition/Editor/Sky/HDRISky/HDRISkyEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/SkySettingsEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/HDShadowLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, needs-backport-2019.3

#5113 Fixed an issue where ambient probe would be black for the first face of a baked reflection probe
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, needs-backport-2019.3

#5108 Implemented an API to access HDRP Color, Depth and Normal buffers
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Unity.RenderPipelines.HighDefinition.Runtime.asmdef
  com.unity.render-pipelines.high-definition/Runtime/VFXGraph/Utility.meta
  com.unity.render-pipelines.high-definition/Runtime/VFXGraph/Utility/PropertyBinders.meta
  com.unity.render-pipelines.high-definition/Runtime/VFXGraph/Utility/PropertyBinders/HDRPCameraBinder.cs
  com.unity.render-pipelines.high-definition/Runtime/VFXGraph/Utility/PropertyBinders/HDRPCameraBinder.cs.meta
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Unity.VisualEffectGraph.Runtime.asmdef
Labels: HDRP, needs-backport-2019.3

#5118 Fixed an issue where rendering done by users in EndCameraRendering would be executed before the main render loop.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5103 Hdrp/fix volume with prefab overrides
  com.unity.render-pipelines.core/Editor/Volume/VolumeEditor.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP, needs-backport-2019.3

#5092 Hdrp/fix probes with prefab override workflow
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/CameraSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettings.cs
Labels: HDRP

#5109 Add information about version used in wizard
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.UIElement.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
Labels: HDRP

#5099 Hdrp/fix density volume with prefab overrides
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Drawer.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Skin.cs
Labels: HDRP, needs-backport-2019.3

#5110 Fix compilation error related to CreateLayoutFromXrSdk()
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9601_SkinnedMeshBatching-Off.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9602_SkinnedMeshBatching-On.unity
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
Labels: HDRP, XR, needs-backport-2019.3

#5052 Fix default value getter for structs
  com.unity.render-pipelines.core/Runtime/Common/GlobalDynamicResolutionSettings.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/GlobalLightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/GlobalDecalSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/GlobalPostProcessSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalLowResolutionTransparencySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalPostProcessingQualitySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/GlobalXRSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraPositionSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeCapturePositionSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettings.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/ProbeSettingsUtilitiesTests.cs
Labels: HDRP

#4801 Do not process lights beyond the specified limit
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#5060 Fixed XR Multiview with URP Shader Graph
  com.unity.render-pipelines.core/ShaderLibrary/UnityInstancing.hlsl
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalShaderGraphResources.cs
Labels: Shader Graph, Universal, XR, backported-2019.3

#4411 Lighting quality volume settings
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate/PostProcesses.asset
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate/VolumeSettings.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2601_AO_HalfRes/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2602_SSAO_FullRes/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4020_ChromaticAberration/Post Processing Profile.asset
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2601_SSAO_HalfRes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2602_SSAO_FullRes.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/ContactShadowsEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/ScalableSettingLevelParameterEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedLightingQualitySettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedLightingQualitySettings.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceRefraction.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalLightingQualitySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalLightingQualitySettings.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequest.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/VolumeComponentWithQuality.cs
Labels: HDRP

#5128 Fixed Pixel Depth Subgraph
  com.unity.visualeffectgraph/Samples~/VFXGraphAdditions/Shaders/Subgraphs/Pixel Depth.shadersubgraph
Labels: needs-backport-2019.3, vfx

#5130 Adding support for HDLit and HDUnlit for path tracing and adding a test scene for path tracing
  TestProjects/HDRP_DXR_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D12/5001_PathTracing.png
  TestProjects/HDRP_DXR_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D12/5001_PathTracing.png.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing.unity
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing.unity.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/Global Volume Profile.asset
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/Global Volume Profile.asset.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/M_GreyDiffuse.mat
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/M_GreyDiffuse.mat.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/M_RedDiffuse.mat
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/M_RedDiffuse.mat.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/M_UnlitSG.mat
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/M_UnlitSG.mat.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/SG_LitDiffuse.shadergraph
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/SG_LitDiffuse.shadergraph.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/SG_Unlit.shadergraph
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/5001_PathTracing/SG_Unlit.shadergraph.meta
  TestProjects/HDRP_DXR_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
Labels: HDRP, dxr

#5123 Add support for transparent material for path tracing
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitPathTracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitPathTracing.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingBSDF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingBSDF.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingLight.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingMaterial.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassPathTracing.hlsl
Labels: HDRP, dxr

#5131 Unlocked SSS, SSR, Motion Vectors and Distortion frame settings for reflections probes.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, needs-backport-2019.3

#5121 Hdrp/fix lookdev volume
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/LookDev/Stage.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/EditorDefaultSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/DefaultLookDevProfile.asset
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/DefaultLookDevProfile.asset.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/HDRenderPipelineEditorResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LookDev.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
Labels: HDRP, needs-backport-2019.3

#4616 Change how method for specular occlusions is decided
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2308_Microshadows/MicroShadowMaterial.mat
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1601_TerrainLit.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/MaterialPostProcessor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/TerrainLit/TerrainLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/AdvancedOptionsUIBlock.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitProperties.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
Labels: HDRP

#5133 Hdrp/lookdev smallfixes
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/Stage.cs
Labels: HDRP, needs-backport-2019.3

#5129 Universal/2019.3/backports
  com.unity.render-pipelines.universal/Documentation~/2d-index.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Lift-Gamma-Gain.md
  com.unity.render-pipelines.universal/Documentation~/TableOfContents.md
  com.unity.render-pipelines.universal/Documentation~/index.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-bloom.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-chromatic-aberration.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-depth-of-field.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-tonemapping.md
  com.unity.render-pipelines.universal/Documentation~/post-processing-vignette.md
  com.unity.testframework.graphics/Runtime/ImageAssert.cs
Labels: Universal

#5135 Fixed a typo in GLES3.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
Labels: needs-backport-2019.3

#5114 Implement a new PBR sky UI (WIP)
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4076_PhysicalCamera-lensShift.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_AltitudeSettings.lighting
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_AltitudeSettings.lighting.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5005_Pbr_Sky_Med_AltitudeSettings.lighting
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5005_Pbr_Sky_Med_AltitudeSettings.lighting.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5006_Pbr_Sky_Low_Altitude.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5006_Pbr_Sky_Low_AltitudeSettings.lighting
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5006_Pbr_Sky_Low_AltitudeSettings.lighting.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky/PhysicallyBasedSkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/InScatteredRadiancePrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
Labels: HDRP

#5136 Fixed NaNs with GGX BTDF and IOR set to 1.
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingBSDF.hlsl
Labels: HDRP, dxr

#5140 Add missing include in VFXcommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/VFXGraph/Shaders/VFXCommon.hlsl
Labels: backported-2019.3, vfx

#5139 Updated documentation on writing a custom sky
  com.unity.render-pipelines.high-definition/Documentation~/Creating-a-Custom-Sky.md
Labels: HDRP, needs-backport-2019.3

#5141 Improving RayTracing Reflection Denoising
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDReflectionDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDReflectionDenoiser.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/BilateralFilter.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/ReflectionDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/ReflectionDenoiser.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineRayTracingResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/ReflectionKernelMapping.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/ReflectionKernelMapping.png.meta
Labels: HDRP, dxr

#5142 Removing an extra blit in indirect diffuse denoising
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
Labels: HDRP, dxr

#5143 Rename before transparent in after opaque and sky in project settings
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
Labels: HDRP

#5144 Restored PBR sky ground color default value
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude/Scene Settings Profile.asset
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.cs
Labels: HDRP, needs-backport-2019.3

#5043 Fixed missing normalize operation on vertex normals.
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/Nature/SpeedTree7CommonPasses.hlsl
  com.unity.render-pipelines.universal/Shaders/Nature/SpeedTree8Passes.hlsl
Labels: Universal, bug-fix, needs-backport-2019.3

#5042 Shadergraph/fix/stencil
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Templates/PassMesh.template
Labels: Shader Graph, Universal, bug-fix, needs-backport-2019.3

#5157 Adding Reflection to the DXR wizard setup
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
Labels: HDRP, dxr

#5151 Fix for corrupt node to sub graph conversion
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.3

#5160 Use DelayedIntField instead of IntField for scalable settings
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSetting.cs
Labels: HDRP, needs-backport-2019.3

#5159 Minor doc fix for debug window
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Window.md
Labels: HDRP, needs-backport-2019.3

#5156 Fix initialisation of Debug in FrameSettingsHistory
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
Labels: HDRP, needs-backport-2019.3
