Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-01, with the labels that each got.

#2600 Adding support to LWRP for dynamic resolution scaling.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: lwrp

#2611 Various Fixes for Visual Effect Graph UI for 2019.1
  TestProjects/VisualEffectGraph/Packages/manifest.json
  com.unity.visualeffectgraph/Editor/GraphView/Blackboard/VFXBlackboard.cs
  com.unity.visualeffectgraph/Editor/GraphView/Elements/Controllers/VFXDataAnchorController.cs
  com.unity.visualeffectgraph/Editor/GraphView/Elements/VFXContextUI.cs
  com.unity.visualeffectgraph/Editor/GraphView/Elements/VFXEditableDataAnchor.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/Controller/VFXViewController.cs
  com.unity.visualeffectgraph/Editor/Resources/VFXContext.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXParameter.uss
  com.unity.visualeffectgraph/Editor/Utils/VFXSystemBorder.cs
Labels: vfx

#2612 Various Fixes for Visual Effect Graph UI for 2018.3
  com.unity.visualeffectgraph/Editor/GraphView/Elements/Controllers/VFXDataAnchorController.cs
  com.unity.visualeffectgraph/Editor/GraphView/Elements/VFXEditableDataAnchor.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/Controller/VFXViewController.cs
  com.unity.visualeffectgraph/Editor/Resources/VFXContext.uss
  com.unity.visualeffectgraph/Editor/Resources/VFXParameter.uss
  com.unity.visualeffectgraph/Editor/Utils/VFXSystemBorder.cs
Labels: backport-2018.3, vfx

#2697 Deprecate Linux Universal support in 2019.2+
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.testframework.graphics/Runtime/Utils.cs
Labels: HDRP

#2696 Fixed darker rendering when in gamma colorspace.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: lwrp, needs-backport-2018.3

#2644 Fix Shader Graph window not repainting in the background
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
Labels: Shader Graph, bug-fix

#2626 Fix for Fogbugz case 1107087. Reimporting shadergraphs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightPBRSubShader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/LightWeightUnlitSubShader.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
Labels: Shader Graph

#2700 Added Support for multi viewport
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9501_MultiViewport.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9501_MultiViewport.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9501_MultiViewport.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9501_MultiViewport/MultiViewport_Material.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9501_MultiViewport/MultiViewport_Material.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9501_MultiViewport/MultiViewport_Target.renderTexture
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9501_MultiViewport/MultiViewport_Target.renderTexture.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9501_MultiViewport/PostProcess Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9501_MultiViewport/PostProcess Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9501_MultiViewport.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9501_MultiViewport.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/CopyDepthBuffer.shader
Labels: HDRP

#2703 shader graph decal fixups
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDBuffer.hlsl
Labels: HDRP

#2642 Backport: LWRP enable postprocessing for XR (case 1110904)
  com.unity.render-pipelines.lightweight/Runtime/DefaultRendererSetup.cs
Labels: backport-2018.3, lwrp

#2711 Update shader stripping for decal
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2713 Various corrections asked during the initial review of the Raytracing PR
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingFragInputs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/SphericalRectangle.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingReflection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingVisibility.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/BlueNoise.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_1_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_1_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_2_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_2_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_3_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_3_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_4_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_4_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_5_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_5_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_6_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_6_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_7_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_7_xy.bmp.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_8_xy.bmp
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise128/sample_8_xy.bmp.meta
Labels: HDRP

#2717 Fixed pre-exposure being applied to realtime probes
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2204_ReflectionProbes_Lights.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2204_ReflectionProbes_Lights.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2207_ReflectionProbeVFace.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2207_ReflectionProbeVFace.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Light_on_Tesselation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Light_on_Tesselation.png.meta
  com.unity.render-pipelines.core/Runtime/Utilities/ColorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#2720 HDRP - Fix m_Time reset for NewFrame processing
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#2668 Make the light delegate function in LightweightRenderPipeline private
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: lwrp

#2693 Backport of #2636, #2647 and #2696
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightPBRExtraPasses.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightUnlitExtraPasses.template
  com.unity.render-pipelines.lightweight/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.lightweight/Shaders/ShadowCasterPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: backport-2018.3, lwrp

#2708 Added version define for LWRP.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/Unity.RenderPipelines.Lightweight.Editor.asmdef
  com.unity.render-pipelines.lightweight/Runtime/Unity.RenderPipelines.Lightweight.Runtime.asmdef
  com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl
Labels: lwrp

#2723 Lw/bugfix/backport ibeforerender
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/DefaultRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/IBeforeRender.cs
  com.unity.render-pipelines.lightweight/Runtime/IBeforeRender.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/Passes/CreateLightweightRenderTexturesPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderOpaqueForwardPass.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: backport-2018.3, lwrp

#2699 Lw/dynamic resolution [DONT MERGE IT YET]
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: lwrp

#2712 Small tweaks.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/RenderOpaqueForwardPass.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: lwrp

#2733 Hdrp fix open gl error message
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#2727 Motion blur for PP v3
  TestProjects/HDRP_Tests/OSXBatchMode.sh
  TestProjects/HDRP_Tests/RunAllTests_OSX.sh
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/MotionBlurEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Builtin/BuiltinData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/MotionBlur.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurVelocityPrep.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassVelocity.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneColorNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneDepthNode.cs
Labels: HDRP

#2736 Fix Metal API not allowed by HDRP
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessBuild.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#2735 Disable stereo post-process until SPI is ready
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, XR

#2731 udpated changelog dates
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.shadergraph/CHANGELOG.md
  com.unity.testframework.graphics/CHANGELOG.md
  com.unity.visualeffectgraph/CHANGELOG.md
Labels: SRP

#2743 Change cascade shadow map error message
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#2746 Fix compile for TerrainLit depth only pass
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitSplatCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap_Gen.shader
Labels: HDRP

#2704 LWRP + XR will now use HDR if it is enabled.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: lwrp

#2667 Lw/bugfix/case 1109009
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipelineCore.cs
Labels: lwrp

#2749 Quick optimization pass on post-processing
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
Labels: HDRP

#2759 Added color grading curves (YRGB + secondaries)
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/ColorCurvesEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/ColorCurvesEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/InspectorCurveEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/InspectorCurveEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/Shaders/CurveBackground.shader
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/Shaders/CurveBackground.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ColorCurves.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Exposure.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/LutBuilder3D.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/TextureCurve.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/TextureCurve.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#2750 HDRP shader graph HD render queues
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDMaterialTags.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDMaterialTags.cs.meta
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
Labels: HDRP

#2741 Modify GetPropertiesDeclaration to fix SRP batcher
  com.unity.shadergraph/Editor/Data/Util/PropertyCollector.cs
Labels: Shader Graph

#2738 Material validator hdrp
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/MaterialDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/PBRValidator.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/PBRValidator.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForward.hlsl
Labels: HDRP

#2724 Update for 32 threads in wavefronts on Switch.
  com.unity.render-pipelines.core/ShaderLibrary/API/D3D11.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES2.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Switch.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Vulkan.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/GPUCopy.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-bigtile.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-clustered.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/materialflags.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/MomentShadows.compute
Labels: HDRP

#2767 Use graphics format instead of format in the pool recycler
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP

#2768 Fix RenderQueue update when changing surface type on unlit HD master node
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSettingsView.cs
Labels: HDRP

#2760 Updated default LWRP asset settings to favor optimization by default
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.testing.srp.lightweight/Tests/CommonAssets/LightweightRenderPipelineAsset.asset
Labels: lwrp

#2771 Update depth and color node tests for HDRP
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorMaterialLit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorMaterialLit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorMaterialUnlit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorMaterialUnlit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorShader.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorShaderLit.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneColorShaderLit.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneDepthMaterialLit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneDepthMaterialLit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneDepthMaterialUnlit.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneDepthMaterialUnlit.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneDepthShader.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneDepthShaderLit.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8205_SceneDepthColorNodes/SceneDepthShaderLit.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8205_SceneDepthColorNodes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8205_SceneDepthColorNodes.png.meta
Labels: HDRP

#2740 Added Depth sampling modes to the scene depth node
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderGraphFunctions.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/ShaderGraphFunctions.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Scene-Depth-Node.md
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/SceneDepthNode.cs
Labels: HDRP, Shader Graph, lwrp

#2772 Add SH to TerrainLit shader
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: lwrp

#2776 Hdrp/fix shadergraph hdrenderqueue migration
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDMaterialTags.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderQueue.cs
Labels: HDRP

#2751 Sg/minor fixes 3
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Is-Infinite-Node.md
  com.unity.shadergraph/Documentation~/Is-NaN-Node.md
  com.unity.shadergraph/Documentation~/Normal-Unpack-Node.md
  com.unity.shadergraph/Documentation~/Property-Types.md
  com.unity.shadergraph/Documentation~/Rotate-About-Axis-Node.md
  com.unity.shadergraph/Editor/Data/Graphs/AbstractMaterialGraph.cs
  com.unity.shadergraph/Editor/Data/Graphs/BooleanShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Mask/ChannelMaskNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Normal/NormalUnpackNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Channel/FlipNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Channel/SplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Vector/RotateAboutAxisNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/Logic/IsInfiniteNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/Logic/IsNanNode.cs
  com.unity.shadergraph/Editor/Drawing/Controls/ToggleControl.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/ShaderGraphLibrary/ShaderVariablesMatrixDefsLegacyUnity.hlsl
Labels: Shader Graph, bug-fix

#2770 Primary Visibility and Area Shadow (plus some additional raytracing features)
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/Camera/HDRayTracingFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracing.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderQueue.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingFlagMask.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingFlagMask.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/SphericalRectangle.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingReflection.hlsl
Labels: HDRP, dxr

#2769 Lw/bugfixes
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
  com.unity.render-pipelines.lightweight/Shaders/LitForwardPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/SimpleLitForwardPass.hlsl
Labels: lwrp

#2542 blackboard in SG remember expanded states
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
Labels: Shader Graph

#2781 Hdrp/fix framesettings formerly nullable tests
  com.unity.render-pipelines.high-definition/Tests/Editor/CameraSettingsUtilitiesTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/HDRenderUtilitiesTests.cs
Labels: HDRP

#2786 Hdrp/fix framesettings msaa and exposurecontrol
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableFrameSettingsArea.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/FrameSettingsFieldAttribute.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#2782 Check resolution before each bake in 2018.3
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/EditorReflectionSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.cs
Labels: HDRP

#2630 Hdrp/new ambient mode
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/ScenePrefabs/HDRP_Default_Sky.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/ScenePrefabs/HDRP_Default_Sky_2.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/ScenePrefabs/HDRP_Default_Sky_3.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/ScenePrefabs/HDRP_Default_Sky_4.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/ScenePrefabs/HDRP_Linear_Fog.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/ScenePrefabs/HDRP_NormalLight.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/SkySettings/HDRP_Default_Sky.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1101_Unlit.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1201_Lit_Features.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1202_Lit_DoubleSideNormalMode.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1602_TerrainLit_Normal.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2101_GI_Metapass.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2102_GI_Emission.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8101_Opaque.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8104_Unlit.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8201_VertexAnimation.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8204_CustomSpecOcclusion.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardBoth.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1201_Lit_Features.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1202_Lit_DoubleSideNormalMode.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2001_Dynamic_Directional.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2002_Dynamic_Mix.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2101_GI_Metapass.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2101_GI_Metapass.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2102_GI_Emission.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2102_GI_Emission.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2206_LightLoopCullWOblique.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2206_LightLoopCullWOblique.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2307_ShadowVeryHigh.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8102_Transparent.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8104_Unlit.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8201_VertexAnimation.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/StaticLightingSkyEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/StaticLightingSkyEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Sky/VisualEnvironmentEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/Sky/AmbientProbeConvolution.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/AmbientProbeConvolution.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/StaticLightingSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/StaticLightingSky.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/VisualEnvironment.cs
Labels: HDRP

#2789 Updated materials that did not upgrade properly
  com.unity.testing.srp.lightweight/Tests/Scenes/004_Camera_TargetTexture/004_CameraTargetTextureSphere.mat
  com.unity.testing.srp.lightweight/Tests/Scenes/004_Camera_TargetTexture/004_Camera_TargetTexture_Sphere.mat
  com.unity.testing.srp.lightweight/Tests/Scenes/014_CameraMulti_MiniMap/red.mat
Labels: lwrp, needs-backport-2019.1

#2793 Fix shader compilation issue
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/AmbientProbeConvolution.compute
Labels: HDRP

#2790 Fix shader compiler warnings
  com.unity.render-pipelines.lightweight/ShaderLibrary/MetaInput.hlsl
Labels: lwrp, needs-backport-2019.1

#2794 Hdrp/fix framesettings probe overrides and tests
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettingsUtilities.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/CameraSettingsUtilitiesTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs.meta
  com.unity.render-pipelines.high-definition/Tests/Editor/TestFramework/RandomUtilities.cs
Labels: HDRP

#2801 FrameSettings SSR & Raytracing Fixes
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, bug-fix

#2804 Fix issues with MaterialUpgrader
  com.unity.render-pipelines.lightweight/Editor/MaterialPostprocessor.cs
  com.unity.render-pipelines.lightweight/Runtime/Materials/ParticlesLit.mat
  com.unity.render-pipelines.lightweight/Runtime/Materials/SimpleLit.mat
  com.unity.render-pipelines.lightweight/Runtime/Materials/TerrainLit.mat
Labels: lwrp, needs-backport-2019.1

#2783 Updated changelog
  com.unity.render-pipelines.lightweight/CHANGELOG.md
Labels: lwrp, needs-backport-2019.1

#2810 Update FrameSettingsTest to not gather hdrpAsset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
Labels: HDRP

#2824 Fix LOAD_TEXTURE2D_ARRAY_MSAA macro
  com.unity.render-pipelines.core/ShaderLibrary/API/D3D11.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLCore.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Vulkan.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP, XR

#2823 HDRP - Fix instancing macro usage for decals
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, XR, backport-2018.3, backported-2019.1

#2819 Hdrp/fix vertex displacement clamp and layeredlit foldouts 2
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/ExpandableAreaMaterial.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitUI.cs
Labels: HDRP, needs-backport-2019.1

#2833 Update shadow alpha clip on lit shader
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitDataIndividualLayer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitProperties.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
Labels: HDRP, backport-2018.3, backported-2019.1

#2837 Post-processing fixes & perf improvement
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoC.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
Labels: HDRP, backported-2019.1

#2838 Hdrp/fix framesettings typos
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
Labels: HDRP

#2815 Various bugfixes
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2007_FogFallback.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2007_FogFallback.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Sky/StaticLightingSkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkySettings.cs
Labels: HDRP

#2836 HDRP baked gi master node inputs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/DefaultMaterialSlot.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/DefaultMaterialSlot.cs.meta
Labels: HDRP, backported-2019.1

#2827 backport: Hdrp fix double sided (#2798)
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1202_Lit_DoubleSideNormalMode.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1501_Fabric.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxFData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/FabricData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData_Basemap.hlsl
Labels: HDRP

#2550 Pipeline hooks for terrain details shaders in lightweight.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/HDRenderPipelineEditorResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineEditorResources.asset
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineEditorResources.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineResources.asset
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainDetailLit.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/WavingGrass.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/WavingGrassBillboard.shader
Labels: HDRP, lwrp

#2830 Hdrp xr instancing flag
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandles.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/GBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SharedRTManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/Texture2DAtlas.cs
Labels: HDRP, XR

#2841 Improve HDRP shader graph default values
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.shadergraph/Editor/Data/MasterNodes/PBRMasterNode.cs
Labels: HDRP, needs-backport-2018.3, needs-backport-2019.1

#2840 Hdrp decals cullmask
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorComponentEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjectorComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
Labels: HDRP, needs-backport-2018.3, needs-backport-2019.1

#2694 Lw/expose renderersetup in camera
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/AssemblyInfo.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/ForwardRendererData.asset
  com.unity.render-pipelines.lightweight/Runtime/Data/ForwardRendererData.asset.meta
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineResources.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/IRendererData.cs
  com.unity.render-pipelines.lightweight/Runtime/IRendererData.cs.meta
  com.unity.render-pipelines.lightweight/Runtime/IRendererSetup.cs
  com.unity.render-pipelines.lightweight/Runtime/LWRPAdditionalCameraData.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CopyColorPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CopyDepthPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/SceneViewDepthCopy.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/ScreenSpaceShadowResolvePass.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.lightweight/Shaders/Utils/Blit.shader.meta
  com.unity.render-pipelines.lightweight/Tests/Editor/EditorTests.cs
  com.unity.testing.srp.lightweight/Tests/CommonAssets/LightweightRenderPipelineAsset.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe.unity
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomLWPipe.cs
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomRenderGraph.asset
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomRenderGraph.asset.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomRenderGraphData.cs
  com.unity.testing.srp.lightweight/Tests/Scenes/045_CustomLWPipe/CustomRenderGraphData.cs.meta
  com.unity.testing.srp.lightweight/Tests/Scenes/052_LWCallbacks/CameraCallbackTests.cs
Labels: lwrp, needs-backport-2019.1

#2831 Switch support
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Deferred.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/DeferredTile.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/DeferredTile.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/builddispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/cleardispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#2847 Fix mismatching between lightmode and passname (Fix shader stripping)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, backport-2018.3, backported-2019.1

#2849 fix shader stripping for unlit master node
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
Labels: HDRP, backport-2018.3, backported-2019.1

#2805 Dynamic resolution v1
  com.unity.render-pipelines.core/ShaderLibrary/Filtering.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDynamicResolutionSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/GlobalDynamicResolutionSettingsUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/RenderPipelineSettingsUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedDynamicResolutionSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedDynamicResolutionSettings.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.RTHandle.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandles.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/GBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SharedRTManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomPrefilter.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoCReproject.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCombine.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldGather.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldMipSafe.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldPrefilter.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/Exposure.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FXAA.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FXAA.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FXAA.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FXAA.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/PaniniProjection.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/RTUpscale.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/RTUpscale.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalDynamicResolutionSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalDynamicResolutionSettings.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDDynamicResolutionHandler.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDDynamicResolutionHandler.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/Texture2DAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.lightweight/Editor/ShaderGUI/ShadingModels/BakedLitGUI.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGUI/ShadingModels/LitGUI.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGUI/ShadingModels/SimpleLitGUI.cs
Labels: HDRP

#2844 Fix per-object reflection probes.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: lwrp

#2853 Added minimum UnityRelease to packages
  com.unity.render-pipelines.core/package.json
  com.unity.render-pipelines.high-definition/package.json
  com.unity.render-pipelines.lightweight/package.json
  com.unity.shadergraph/package.json
  com.unity.testframework.graphics/package.json
  com.unity.testing.srp.lightweight/package.json
  com.unity.visualeffectgraph/package.json
Labels: SRP

#2869 Update README.md
  README.md
Labels: needs-backport-2019.1

#2870 Post-processing package update
  TestProjects/PostProcessing/Packages/manifest.json
  com.unity.render-pipelines.lightweight/package.json
Labels: needs-backport-2019.1

#2868 Fix Inspector VisualEffect (backport 2019.1)
  com.unity.visualeffectgraph/Editor/Inspector/VisualEffectEditor.cs
Labels: bug-fix, vfx
