Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-07, with the labels that each got.

#3895 Default Settings for HDRP
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDSceneManagement.cs
  com.unity.render-pipelines.high-definition/Editor/Material/GeneralNodes.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/EditorDefaultSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/EditorDefaultSettings.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Sky/HDRISky/HDRISkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbeCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/ReflectionProbeCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/LTCAreaLightCookieManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/PreIntegratedFGD/PreIntegratedFGD.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/RenderPipelineMaterial.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/DefaultSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/BlueNoise.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/ProceduralSky/ProceduralSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
Labels: HDRP

#3920 Add support for volumetric shadow tint
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
Labels: HDRP, backported-2019.2

#3918 Small refactoring of RTHandles in preparation for Render Graph
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTCategory.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTCategory.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.RTHandle.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandles.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
Labels: HDRP

#3929 Correcting the invalid characters
  com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/ImageBasedLighting.hlsl
Labels: HDRP, dxr

#2725 Graphics/terrain/gpu/terrain surface mask (C++ PR landed in trunk)
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1604_Terrain_Holes.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1604_Terrain_Holes.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1604_Terrain_Holes.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1604_Terrain_Holes/TerrainData_Holes.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1604_Terrain_Holes/TerrainData_Holes.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/1604_Terrain_Holes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/1604_Terrain_Holes.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1604_Terrain_Holes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1604_Terrain_Holes.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/1604_Terrain_Holes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/1604_Terrain_Holes.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  TestProjects/LWGraphicsTest/Assets/CommonAssets/Scripts/LWGraphicsTests.cs
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/071_Terrain_Holes.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/071_Terrain_Holes.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/071_Terrain_Holes.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/071_Terrain_Holes.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/071_Terrain_Holes.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/071_Terrain_Holes.png.meta
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/071_Terrain_Holes.png
  TestProjects/LWGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/071_Terrain_Holes.png.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/071_Terrain_Holes.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/071_Terrain_Holes.unity
  TestProjects/LWGraphicsTest/Assets/Scenes/071_Terrain_Holes.unity.meta
  TestProjects/LWGraphicsTest/Assets/Scenes/071_Terrain_Holes/Terrain.asset
  TestProjects/LWGraphicsTest/Assets/Scenes/071_Terrain_Holes/Terrain.asset.meta
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitTemplate.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitAdd.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitBase.shader
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: HDRP, lwrp

#3921 Update Minimal to 0a8
  com.unity.render-pipelines.core/package.json
  com.unity.render-pipelines.high-definition/package.json
  com.unity.render-pipelines.lightweight/package.json
  com.unity.shadergraph/package.json
  com.unity.testframework.graphics/package.json
  com.unity.testing.visualeffectgraph/package.json
  com.unity.visualeffectgraph/package.json
Labels: HDRP, lwrp, vfx

#3924 Dither transition between cascades
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/HDShadow.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
Labels: HDRP

#3926 Various small refactor for RenderGraph
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/MRTBufferManager.cs
Labels: HDRP

#3932 Fix editor performance issue related to black emission on LWRP
  com.unity.render-pipelines.lightweight/Editor/ShaderGUI/BaseShaderGUI.cs
Labels: lwrp

#3784 [Shader Graph] Fix Bitangent not generating requirements
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
Labels: Shader Graph, bug-fix

#3923 2d/preview window fix
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.lightweight/Shaders/2D/Include/CombinedShapeLightShared.hlsl
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Fallback.shader
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Fallback.shader.meta
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Lit-Default.shader
Labels: lwrp, needs-backport-2019.2

#3851 DXR + Unlit SG + GBuffer
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitRaytracingPass.template.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialGBufferMacros.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/RaytracingMaterialGBufferMacros.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/RaytracingMaterialGBufferMacros.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitRaytracing.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingIntersectonGBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingGBuffer.hlsl
Labels: HDRP, dxr

#3936 Lookdev/shadow composition
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.cs
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.shader
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow-PersonalSkin.uss
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow-PersonalSkin.uss.meta
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.uss
  com.unity.render-pipelines.core/Editor/LookDev/Environment.cs
  com.unity.render-pipelines.core/Editor/LookDev/EnvironmentLibrary.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDev.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDevRenderer.cs
  com.unity.render-pipelines.core/Editor/LookDev/Stage.cs
  com.unity.render-pipelines.core/Runtime/LookDev/IDataProvider.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LookDev.cs
Labels: HDRP, SRP

#3930 Correcting the invalid characters
  com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/ImageBasedLighting.hlsl
Labels: HDRP, dxr, needs-backport-2019.2

#3931 Clamp emissive value in EV100
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/EmissionUIBlock.cs
Labels: HDRP, needs-backport-2019.2

#3897 Single-pass instancing support with XR SDK
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/XRSystemTests.cs
Labels: HDRP, XR

#3949 Fix warning with shadow algorithm macro
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
Labels: HDRP

#3495 [backport 2019.2] Miscellaneous Shader Graph Fixes
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Gradient/GradientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs
Labels: Shader Graph, backported-2019.2, bug-fix

#3945 Pre-expose Planar Reflection Probe preview in the scene view
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/Materials.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/Materials/GUITextureBlit2SRGB.mat
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/Materials/GUITextureBlit2SRGB.mat.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/Shaders.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/Shaders/GUITextureBlit2SRGB.shader
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/Shaders/GUITextureBlit2SRGB.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/DefaultSettings.cs.meta
Labels: HDRP

#3948 Update Editor Ressource asset for pre-expose fix
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/HDRenderPipelineEditorResources.asset
Labels: HDRP

#3944 Enable inverse squared falloff on Enlighten and Deprecated Realtime Enlighten
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIlluminationUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3955 Backport
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.lightweight/Shaders/2D/Include/CombinedShapeLightShared.hlsl
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Fallback.shader
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Fallback.shader.meta
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Lit-Default.shader
Labels: backported-2019.2, lwrp

#3954 Backport
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.lightweight/Shaders/2D/Include/CombinedShapeLightShared.hlsl
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Fallback.shader
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Fallback.shader.meta
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Lit-Default.shader
Labels: backported-2019.2, lwrp

#3957 Fix control z shadow mask mode
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP

#3940 Add Light Scripting API and deprecate the AdditionalShadowData component
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/ScenePrefabs/HDRP_Test_Camera.prefab
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting/LightScriptCreator.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting/LightScriptCreator.cs.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting/trasnparnetShadowCasting.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting/trasnparnetShadowCasting.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9500_LightScripting.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9500_LightScripting.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Editor/Lighting/AdditionalShadowDataEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.ContextualMenu.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light/HDAdditionalLightDataEditorExtension.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light/HDAdditionalLightDataEditorExtension.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIlluminationUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalShadowData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Scripting.meta
  com.unity.render-pipelines.high-definition/Runtime/Scripting/GameObjectExtension.cs
  com.unity.render-pipelines.high-definition/Runtime/Scripting/GameObjectExtension.cs.meta
Labels: HDRP

#3935 Removed _DepthPyramidTexture shader parameter
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ShaderVariablesScreenSpaceLighting.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#3866 Adding a standard Lit model that is our go to for indirect lighting for tier1
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/FabricRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialGBufferMacros.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/RaytracingMaterialGBufferMacros.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StandardLit.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/StandardLit/StandardLit.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/StandardLit/StandardLit.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StandardLit/StandardLit.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/StandardLit/StandardLit.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/StandardLit/StandardLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StandardLit/StandardLit.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingGBuffer.hlsl
Labels: HDRP, dxr

#3959 Remove migration code for V1 HDLight
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light/HDAdditionalLightDataEditorExtension.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#3939 Refactored Volumetric Lighting in preparation for RenderGraph implementation
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandles.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LookDev.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#3961 Fixed a null ref exception in lookdev
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.cs
Labels: HDRP

#3876 Implement multibounce for reflections and indirect diffuse
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIllumination.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingLightProbe.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingLightProbe.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/OwenScrambledNoise256.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/OwenScrambledNoise256.png.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/OwenScrambledNoise4.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/OwenScrambledNoise4.png.meta
Labels: HDRP, dxr

#3967 Fix camera flickering when TAA is activated and selecting the camera
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraEditor.Handlers.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backported-2019.2

#3969 Fixing DXR shaders warnings
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Common/RayBinning.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
Labels: HDRP, dxr

#3966 Update shadow docs regarding atlas
  com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
Labels: HDRP, backported-2019.2

#3952 Fix issue with single shadow debug view and volumetrics
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
Labels: HDRP, backported-2019.2

#3962 Change how shadow resolution dynamic scaling works
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, backported-2019.2

#3973 Fix compilation issues on player in HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light/HDAdditionalLightDataEditorExtension.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#3907 Place nodes spaced out when convert to subgraph
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
Labels: Shader Graph, needs-backport-2019.2

#3850 Sg/ui ux sticky note
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/ParentGroupChange.cs
  com.unity.shadergraph/Editor/Data/Graphs/ParentGroupChange.cs.meta
  com.unity.shadergraph/Editor/Data/Graphs/StickyNoteData.cs
  com.unity.shadergraph/Editor/Data/Graphs/StickyNoteData.cs.meta
  com.unity.shadergraph/Editor/Data/Interfaces/IGroupItem.cs
  com.unity.shadergraph/Editor/Data/Interfaces/IGroupItem.cs.meta
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ShaderGroup.cs
  com.unity.shadergraph/Editor/Drawing/Views/StickyNote.cs
  com.unity.shadergraph/Editor/Drawing/Views/StickyNote.cs.meta
  com.unity.shadergraph/Editor/Resources/Resizable.uss
  com.unity.shadergraph/Editor/Resources/Resizable.uss.meta
  com.unity.shadergraph/Editor/Resources/Selectable.uss
  com.unity.shadergraph/Editor/Resources/Selectable.uss.meta
  com.unity.shadergraph/Editor/Resources/StickyNote.uss
  com.unity.shadergraph/Editor/Resources/StickyNote.uss.meta
  com.unity.shadergraph/Editor/Resources/UXML/Resizable.uxml
  com.unity.shadergraph/Editor/Resources/UXML/Resizable.uxml.meta
  com.unity.shadergraph/Editor/Resources/UXML/StickyNote.uxml
  com.unity.shadergraph/Editor/Resources/UXML/StickyNote.uxml.meta
  com.unity.shadergraph/Editor/Util/CopyPasteGraph.cs
  com.unity.shadergraph/Tests/Editor/UnitTests/SerializedGraphTests.cs
Labels: Shader Graph

#3976 Add batch to generate local packages
  Tools/CreateLocalPackages.cmd
  Tools/CreateOneLocalPackage.bat
Labels: SRP

#3977 Remove Enlighten deprecated message (useless as it is in the UI)
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backported-2019.2

#3980 Fix warning issue for template in 2019.2
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
Labels: Shader Graph, backported-2019.2

#3984 Make the OnEnable trigger again
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
Labels: HDRP

#3978 Fix error in spot light UI post light scripting API
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#3988 Introducing shadow resolution quality tiers
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/Material/BaseShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDShadowInitParameters.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
Labels: HDRP

#3985 Hdrp/update moreoptions icons
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/Volume/VolumeComponentEditor.cs
  com.unity.render-pipelines.core/Editor/Volume/VolumeComponentListEditor.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/ColorCurvesEditor.cs
Labels: HDRP

#3981 Hdrp/additional velocity changes support for alembic
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/AxF/AxFGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/AdvancedOptionsUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitGUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/MotionVectorVertexShaderCommon.hlsl
  com.unity.shadergraph/Editor/Data/MasterNodes/UnlitMasterNode.cs
Labels: HDRP

#3986 Update Reflection settings +Rename EnableSpecularLighting
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Def.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Def_MSAABoth.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Def_MSAAForward.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_FabricConvolutionOn.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Fwd_Shadow_VeryHigh.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Settings/EmptyVolumeProfile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Settings/EmptyVolumeProfile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2210_ReflectionProbes_CaptureAtVolumeAnchor.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1219_Lit_Light_on_Tesselation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1219_Lit_Light_on_Tesselation.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/desktop.ini.meta
  TestProjects/HDRP_Tests/Packages/manifest.json
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP

#3950 Support more than 2 views with XR single-pass instancing
  com.unity.render-pipelines.core/ShaderLibrary/UnityInstancing.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-bigtile.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild-clustered.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderConfig.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderConfig.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, XR

#3991 Fix indirect deferred compute with XR single-pass instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/builddispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, XR

#4003 Fix remaining ray tracing shader warnings
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightCluster.compute
Labels: HDRP

#3975 DXR Indirect Diffuse Deferred
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIllumination.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.raytrace.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuseAccumulation.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingGBuffer.hlsl
Labels: HDRP, dxr

#3998 Removed unused component
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/ColorLookupEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/ColorLookupEditor.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ColorLookup.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ColorLookup.cs.meta
Labels: HDRP

#3996 Hdrp/alembic motionvectors shadergraph patch
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/ShaderGraphUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
Labels: HDRP

#3963 Exclude objects that tag the stencil with a specific bit from TAA (bis)
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntiAliasing.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntiAliasing.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP

#3995 Implement precomputed atmospheric attenuation
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderConfig.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderConfig.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkySettings.cs
Labels: HDRP

#4010 Fixes for the TAA tag PR
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntiAliasing.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#2971 Add support for half types in shaders for Switch platform.
  com.unity.render-pipelines.core/Editor/ShaderGenerator/ShaderTypeGeneration.cs
  com.unity.render-pipelines.core/Runtime/ShaderGenerator/ShaderGeneratorAttributes.cs
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Packing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Builtin/BuiltinData.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Builtin/BuiltinData.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StandardLit/StandardLit.cs.hlsl
Labels: HDRP

#4011 Fix light animation with timeline
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4008 Move display emissive mesh API to editor only (due to mesh resources)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light/HDAdditionalLightDataEditorExtension.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#3516 Rework slot validation to fix crash and provide better errors
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/EdgeTypeConversionTests.cs
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/EdgeTypeConversionTests.cs.meta
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/SlotConv.shadergraph
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/SlotConv.shadergraph.meta
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/DynamicVectorMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/Texture3DAssetNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/SlotValue.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
Labels: Shader Graph, needs-backport-2019.2

#3994 [6.9.x backport] Rework slot validation to fix crash and provide better errors
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/EdgeTypeConversionTests.cs
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/EdgeTypeConversionTests.cs.meta
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/SlotConv.shadergraph
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/SlotConv.shadergraph.meta
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/DynamicVectorMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/Texture3DAssetNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/SlotValue.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
Labels: Shader Graph, bug-fix

#3993 [19.2 backport] Rework slot validation to fix crash and provide better errors
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/EdgeTypeConversionTests.cs
  TestProjects/ShaderGraph/Assets/CommonAssets/Editor/EdgeTypeConversionTests.cs.meta
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/SlotConv.shadergraph
  TestProjects/ShaderGraph/Assets/CommonAssets/Graphs/SlotConv.shadergraph.meta
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/DynamicVectorMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/Texture3DAssetNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/SlotValue.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
Labels: Shader Graph, bug-fix

#4019 Fixed DebugMenu ugui dependency and widgets
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Resources/DebugUI Canvas.prefab
  com.unity.render-pipelines.core/package.json
  com.unity.render-pipelines.high-definition/package.json
Labels: HDRP

#4004 Fix specular fp16 overflow on Switch
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl
Labels: Universal

#4021 Re-rendered cached when their position in atlas changes.
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4023 Small change to better handle cached point light shadows with new caching policy
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4022 Fix area light emissive mesh test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2401_Area_Light_Meshes.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Area_Light_Meshes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Area_Light_Meshes.png.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.testframework.graphics/Editor/SetupGraphicsTestCases.cs
Labels: HDRP

#4025 Fix the SetAreaLightSize when the display emissive mesh option is enabled
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4015 Mirror view support with XR SDK
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/Blit.shader
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/XRMirrorView.shader
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/XRMirrorView.shader.meta
Labels: HDRP, XR

#4027 Fix compilation error of XRDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRDebug.cs
Labels: HDRP

#4026 Fix the PBR master node forward pass blend modes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
Labels: HDRP

#4029 Creating a view on the stencil buffer
  com.unity.render-pipelines.core/Runtime/Textures/RTHandleSystem.cs
Labels: HDRP

#4030 Restored XRDebug code after incorrect merge
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRDebug.cs
Labels: HDRP, XR

#4031 Backport: Fix the PBR master node forward pass blend modes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
Labels: HDRP

#4032 Hdrp/wizard vr dxr 2
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Wizard.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
Labels: HDRP, dxr

#4035 Fix TAA with XR single-pass instancing (missing macros)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntiAliasing.shader
Labels: HDRP, XR

#4040 Implement a custom editor for the PBR sky
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky.meta
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky/PhysicallyBasedSkyEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky/PhysicallyBasedSkyEditor.cs.meta
Labels: HDRP

#3831 Condense LWRP Shader Graph Sub Shader code
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalPBRSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalSpriteLitSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalSpriteUnlitSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalSubShaderUtilities.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalSubShaderUtilities.cs.meta
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalUnlitSubShader.cs
Labels: Universal

#4037 Lookdev/out of experimental
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/LookDev/CameraController.cs
  com.unity.render-pipelines.core/Editor/LookDev/CameraState.cs
  com.unity.render-pipelines.core/Editor/LookDev/ComparisonGizmoController.cs
  com.unity.render-pipelines.core/Editor/LookDev/ComparisonGizmoState.cs
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.cs
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.shader
  com.unity.render-pipelines.core/Editor/LookDev/Context.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/DropArea.cs
  com.unity.render-pipelines.core/Editor/LookDev/Environment.cs
  com.unity.render-pipelines.core/Editor/LookDev/EnvironmentLibrary.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDev.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDevRenderer.cs
  com.unity.render-pipelines.core/Editor/LookDev/Stage.cs
  com.unity.render-pipelines.core/Editor/LookDev/ToolbarRadio.cs
  com.unity.render-pipelines.core/Runtime/LookDev/IDataProvider.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LookDev.cs
Labels: HDRP

#4020 Backport specular fp16 overflow fix on Switch
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
Labels: Universal, backported-2019.2

#4036 Deprecate procedural sky
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultPostprocessingSettings.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultRenderingSettings.asset
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/DefaultHDRISky.exr
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/DefaultHDRISky.exr.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Editor/ProceduralSky.meta
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Editor/ProceduralSky/ProceduralSkyEditor.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Editor/ProceduralSky/ProceduralSkyEditor.cs.meta
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky.meta
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSky.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSky.cs.meta
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSky.shader
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSky.shader.meta
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs.meta
  com.unity.render-pipelines.high-definition/package.json
Labels: HDRP

#4042 Fix Scene View selection wire HDRP Shader Graphs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
Labels: HDRP, Shader Graph, needs-backport-2019.2

#3979 Hdrp/update sky workflow [Need C++ 89546]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Sky/HDLightingWindowEnvironmentSection.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/HDLightingWindowEnvironmentSection.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Sky/StaticLightingSkyEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/VisualEnvironmentEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/StaticLightingSky.cs
Labels: HDRP

#4047 Fix UD2 access
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCamera.cs
Labels: Universal

#4046 Bugfix bundle
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#4045 Allocate m_CachedShadowRect regardless to avoid rare OOB issue
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4053 Volume menu items
  com.unity.render-pipelines.core/Editor/Volume/VolumeMenuItems.cs
  com.unity.render-pipelines.core/Editor/Volume/VolumeMenuItems.cs.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
Labels: HDRP, SRP, needs-backport-2019.3

#4054 Fix material alpha clip renderqueue
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/SurfaceOptionUIBlock.cs
Labels: HDRP

#4051 Added Version.hlsl file to Core ShaderLibrary
  com.unity.render-pipelines.core/ShaderLibrary/Version.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Version.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/Version.hlsl
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl
  com.unity.render-pipelines.universal/ShaderLibrary/Version.hlsl
Labels: HDRP, Universal

#4055 Bugfix bundle
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#4058 Hdrp/backport/fix alpha clip render queue
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/SurfaceOptionUIBlock.cs
Labels: HDRP

#4060 Fix static lighting procedural sky error message
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#4050 Fix issue with Matcap view + update ReplaceDiffuse
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png.meta
  TestProjects/HDRP_Tests/Assets/Samples.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Editor.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Editor/ProceduralSky.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Editor/ProceduralSky/ProceduralSkyEditor.cs
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Editor/ProceduralSky/ProceduralSkyEditor.cs.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSky.cs
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSky.cs.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSky.shader
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSky.shader.meta
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/HDRenderPipelineEditorResources.asset
  com.unity.render-pipelines.high-definition/Runtime/Debug/PBRValidator.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#3747 Toggle preview windows for selected nodes
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph

#3990 Backport ##3907 subgraph node placement
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
Labels: Shader Graph

#4065 Hdrp/move menu renderpipeline
  com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDev.cs
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Window.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Wizard.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
Labels: HDRP

#4066 Fixing DXR on staging
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
Labels: HDRP, dxr

#4061 Rename PhysicallyBasedSkySettings to PhysicallyBasedSky
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5001_Fog_FogFallback.png.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/VolumetricFogEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky/PhysicallyBasedSkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/VolumetricFog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
Labels: HDRP

#4052 Shadergraph properties sync
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/ShaderGraphUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/HDShaderGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitGUI.cs
Labels: HDRP, Shader Graph

#4067 Fixing HDRP
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
Labels: HDRP

#4063 Fix for case 1168215
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: Universal

#4062 [Shader Graph] Update Test Images
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/ArtisticNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/InputNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/TransformNode.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/UVNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/ArtisticNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/ArtisticNodes.png.meta
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/MathNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/MathNodes.png.meta
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/ProceduralNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/ProceduralNodes.png.meta
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/TransformNode.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/TransformNode.png.meta
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/UVNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/UVNodes.png.meta
Labels: Shader Graph

#4070 Removing an extra comma
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
Labels: HDRP, dxr

#4073 Hdrp/fix wizard dxr
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
Labels: HDRP, dxr

#4083 Restore PBR Sky update frequency setting
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky/PhysicallyBasedSkyEditor.cs
Labels: HDRP

#4086 Move procedural sky shader in samples to a Resources folder
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/Resources/ProceduralSky.shader
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/Resources/ProceduralSky.shader.meta
Labels: HDRP

#4078 Fixed the shadow map debug mode
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP

#4084 Fix area light emissive mesh stackoverflow on setting width
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4082 Update default scene
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultPostprocessingSettings.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultRenderingSettings.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultSceneRoot.prefab
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/Scene PostProcess Profile.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/Scene PostProcess Profile.asset.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/Sky and Fog Settings Profile.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/Sky and Fog Settings Profile.asset.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/DefaultSettingsVolumeProfile.asset
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/HDRenderPipelineEditorResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#4077 quickfix uielement issue with pixelperpoint
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/Environment.cs
Labels: HDRP

#4075 Fix the nullref when reseting the HDRP asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
Labels: HDRP

#4076 Bind magenta sky when matcap mode
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#4081 [VFX] Some fixes for StandAlone
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/08_Shadows.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/14_DecalsFlipBook.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/HDRPFog.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/Jumping Cubes.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/SimpleLit.expected.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/SubgraphEventTransmission.png
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources.meta
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky.meta
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky/ProceduralSky.cs
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky/ProceduralSky.cs.meta
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky/ProceduralSky.shader
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky/ProceduralSky.shader.meta
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky/ProceduralSkyRenderer.cs
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky/ProceduralSkyRenderer.cs.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/000_MultiOutput.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/005_PlanarPrimitives.png
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/Mesh/PassForward.template
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/Templates/PlanarPrimitive/PassForward.template
Labels: vfx

#3756 Property and Blackboard Refactor
  com.unity.shadergraph/Editor/Data/Enumerations/PropertyType.cs
  com.unity.shadergraph/Editor/Data/Enumerations/PropertyType.cs.meta
  com.unity.shadergraph/Editor/Data/Graphs/AbstractShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/BooleanShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/ColorShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/CubemapShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/DynamicValueMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/DynamicVectorMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientInputMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Graphs/MaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/MatrixShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/PreviewProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/ShaderInput.cs
  com.unity.shadergraph/Editor/Data/Graphs/ShaderInput.cs.meta
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture3DShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/TextureShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/VectorShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Gradient/GradientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/MasterNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/SlotValue.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/Util/GradientUtil.cs
  com.unity.shadergraph/Editor/Data/Util/GradientUtil.cs.meta
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/PropertyCollector.cs
  com.unity.shadergraph/Editor/Data/Util/PropertyUtil.cs
  com.unity.shadergraph/Editor/Data/Util/PropertyUtil.cs.meta
  com.unity.shadergraph/Editor/Data/Util/SlotValueTypeUtil.cs
  com.unity.shadergraph/Editor/Data/Util/SlotValueTypeUtil.cs.meta
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldView.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldView.cs.meta
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Resources/Styles/ShaderGraphBlackboard.uss
  com.unity.shadergraph/Editor/Util/CopyPasteGraph.cs
Labels: Shader Graph

#4091 Avoid TAA UAV writes as it creates lots of problem internally
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/CopyTAAHistory.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/CopyTAAHistory.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntiAliasing.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#4099 Change texture format for debug texture
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
Labels: HDRP

#4097 Fix shader compilation errors for Android XR projects.
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderGraph/universal2DPBRPass.template
  com.unity.render-pipelines.universal/Shaders/Utils/Universal2D.hlsl
Labels: Universal, needs-backport-2019.2

#4095 Universal/global shader tag
  .github/CODEOWNERS
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal

#4101 Backports for UniversalRP 7.0.0
  .github/CODEOWNERS
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderGraph/universal2DPBRPass.template
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
  com.unity.render-pipelines.universal/Shaders/Utils/Universal2D.hlsl
Labels: Universal

#4106 fix menu order
  com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDev.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
Labels: HDRP

#4103 Fix Undo/Redo when changing the light intensity
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
Labels: HDRP

#4102 Use m_CurrentDebugDisplaySettings instead of m_DebugDisplaySettings for Matcap view check
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3870 Hdrp/terrain layer blending and custom UI improvements
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1601_TerrainLit.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1601_TerrainLit.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1603_TerrainLit_BaseMap.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1603_TerrainLit_BaseMap.png.meta
  com.unity.render-pipelines.high-definition/Editor/Material/TerrainLit/TerrainLitGUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_BasemapGen.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap_Includes.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitPasses.hlsl
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBasemapGen.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitInput.hlsl
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
  com.unity.shadergraph/Editor/AssemblyInfo.cs
Labels: HDRP

#3479 Dock new Shader Graph windows
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporterEditor.cs
Labels: Shader Graph

#4110 Try to make writeable cubemaps when baking reflection probes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
Labels: HDRP

#4109 Hdrp/fix wizard dxr window only
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
Labels: HDRP

#4113 disabled postprocessing on reflection cameras
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal, needs-backport-2019.3

#4115 Backport of #4113
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal

#4116 StackLit: Fixes: per light min roughness when coat is disabled and recompute per light
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
Labels: HDRP, needs-backport-2019.3

#4117 Fix labels
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
Labels: HDRP

#4112 Removed shadow mask debug and fixed an issue where selecting various material debug modes would not reset the others.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/MaterialDebug.cs
Labels: HDRP

#4125 Backport #4097
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweight2DPBRPass.template
  com.unity.render-pipelines.lightweight/Shaders/Utils/Lightweight2D.hlsl
Labels: Universal

#4124 Fix the Basemap generation pass issue within case #1168215
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBasemapGen.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: Universal

#4126 Fix the Basemap generation pass issue within case #1168215 (#4124)
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBasemapGen.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: Universal

#4121 Add the procedural sky sample json
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/.sample.json
Labels: HDRP

#4129 Move use color temperature API to runtime
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light/HDAdditionalLightDataEditorExtension.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4130 Fix config package name length
  com.unity.render-pipelines.high-definition-config/package.json
Labels: HDRP

#4131 Fix HDRP config package test assembly
  com.unity.render-pipelines.high-definition-config/Tests/Editor/Unity.RenderPipelines.HighDefinitionConfig.Editor.Tests.asmdef
  com.unity.render-pipelines.high-definition-config/Tests/Editor/Unity.RenderPipelines.HighDefinitionConfig.Editor.Tests.asmdef.meta
  com.unity.render-pipelines.high-definition-config/Tests/com.unity.render-pipelines.high-definition-config.tests.asmdef
Labels: HDRP

#4128 Merge Hdrp/staging
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.high-definition-config/CHANGELOG.md
  com.unity.render-pipelines.high-definition-config/Tests/Editor/Unity.RenderPipelines.HighDefinitionConfig.Editor.Tests.asmdef
  com.unity.render-pipelines.high-definition-config/Tests/Editor/Unity.RenderPipelines.HighDefinitionConfig.Editor.Tests.asmdef.meta
  com.unity.render-pipelines.high-definition-config/Tests/com.unity.render-pipelines.high-definition-config.tests.asmdef
  com.unity.render-pipelines.high-definition-config/package.json
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light/HDAdditionalLightDataEditorExtension.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/MaterialDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/.sample.json
  com.unity.testing.visualeffectgraph/package.json
Labels: HDRP

#4114 Cube LUT support in HDRP
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Luts.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Luts/LutTest.cube
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/Luts/LutTest.cube.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4037_TonemappingExternal.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4037_TonemappingExternal.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4037_TonemappingExternal.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4037_TonemappingExternal/Post Processing Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4037_TonemappingExternal/Post Processing Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/4037_TonemappingExternal.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/4037_TonemappingExternal.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/4037_TonemappingExternal.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/4037_TonemappingExternal.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/4037_TonemappingExternal.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/4037_TonemappingExternal.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/TonemappingEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Tonemapping.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/LutBuilder3D.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Samples~/PostProcessingData/PostProcessingData.unitypackage
Labels: HDRP, needs-backport-2019.3

#4133 Fixed light component used after being destroyed when using undo.
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4132 Spot light shapes are now correctly taken into account when baking.
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2105_GI_BakedSpotShape.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2105_GI_BakedSpotShape.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIlluminationUtils.cs
Labels: HDRP

#4138 [VFX] Fix wrong VFX_HAS_UI
  com.unity.visualeffectgraph/Editor/Unity.VisualEffectGraph.Editor.asmdef
  com.unity.visualeffectgraph/Unity.VisualEffectGraph.Runtime.asmdef
Labels: vfx

#4137 Fix copy paste test instabilities
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXCopyPasteTests.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXView.cs
Labels: vfx

#4139 Update DefaultSceneRoot.prefab
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultSceneRoot.prefab
Labels: HDRP

#4140 Update area light emissive mesh reference image
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Area_Light_Meshes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Area_Light_Meshes.png.meta
Labels: HDRP

#4142 Lookdev/optimize allocation
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDevRenderer.cs
  com.unity.render-pipelines.core/Editor/LookDev/Stage.cs
Labels: HDRP

#4092 Don't apply atmospheric scattering to sky during the atmospheric scattering pass
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png.meta
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky/PhysicallyBasedSkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/InScatteredRadiancePrecomputation.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
Labels: HDRP

#4100 [VFX] Spawn & Delay
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_Chaining.expected.txt
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_Chaining.expected.txt.meta
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Constant-LoopCount_Random-DelayBeforeLoop_None-DelayAfterLoop_None.expected.txt
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Constant-LoopCount_Random-DelayBeforeLoop_None-DelayAfterLoop_None.expected.txt.meta
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Infinite-LoopCount_Infinite-DelayBeforeLoop_None-DelayAfterLoop_None.expected.txt
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Infinite-LoopCount_Infinite-DelayBeforeLoop_None-DelayAfterLoop_None.expected.txt.meta
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Random-LoopCount_Infinite-DelayBeforeLoop_None-DelayAfterLoop_None.expected.txt
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Random-LoopCount_Infinite-DelayBeforeLoop_None-DelayAfterLoop_None.expected.txt.meta
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Random-LoopCount_Infinite-DelayBeforeLoop_Random-DelayAfterLoop_None.expected.txt
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Random-LoopCount_Infinite-DelayBeforeLoop_Random-DelayAfterLoop_None.expected.txt.meta
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Random-LoopCount_Random-DelayBeforeLoop_Random-DelayAfterLoop_Random.expected.txt
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest_CreateSpawner_ChangeLoopMode_LoopDuration_Random-LoopCount_Random-DelayBeforeLoop_Random-DelayAfterLoop_Random.expected.txt.meta
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/20_SpawnerChaining.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/20_SpawnerChainingAndLoop.unity
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/20_SpawnerChainingAndLoop.unity.meta
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/20_SpawnerLoop.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/20_SpawnerLoop.vfx.meta
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/20_SpawnerChainingAndLoop.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/20_SpawnerChainingAndLoop.png.meta
  TestProjects/VisualEffectGraph/ProjectSettings/EditorBuildSettings.asset
  com.unity.testing.visualeffectgraph/Tests/Runtime/VFXGraphicsTests.cs
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Compiler/VFXGraphCompiledData.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXBasicSpawner.cs
  com.unity.visualeffectgraph/Editor/Models/VFXGraph.cs
Labels: vfx
