Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-05, with the labels that each got.

#3456 Fix freeze on save with sub graph node
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph, bug-fix

#3480 Force AA on Shader Graph windows
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
Labels: Shader Graph

#3466 Shader Graph bug fixes (backport #3281)
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/SerializableCubemap.cs
  com.unity.shadergraph/Editor/Data/Graphs/SerializableMesh.cs
  com.unity.shadergraph/Editor/Data/Graphs/SerializableTexture.cs
  com.unity.shadergraph/Editor/Data/Graphs/SerializableTextureArray.cs
  com.unity.shadergraph/Editor/Data/Implementation/GraphObject.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporterEditor.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
Labels: Shader Graph, bug-fix

#3334 Bug Fixes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/AssetCallbacks/CreateShaderSubGraph.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Implementation/NodeUtils.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporterEditor.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporterEditor.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Util/CopyPasteGraph.cs
  com.unity.shadergraph/Tests/Editor/UnitTests/SerializedGraphTests.cs
Labels: Shader Graph, needs-backport-2019.1

#3330 Fix FB#1141553 - Sampler State properties are treated as duplicate when parameters are different
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/AbstractShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/BooleanShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/ColorShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/CubemapShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture3DShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/TextureShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SamplerStateNode.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1

#3331 Backport: Fix FB#1141553 - Sampler State properties are treated as duplicate when parameters are different
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/AbstractShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/BooleanShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/ColorShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/CubemapShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture3DShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/TextureShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SamplerStateNode.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
Labels: Shader Graph, backported-2019.1, bug-fix

#3500 Fix motion blur and SMAA with VR single-pass instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasingBridge.hlsl
Labels: HDRP, XR, backported-2019.2

#3485 Fix NaNs generated by phase functions
  com.unity.render-pipelines.core/ShaderLibrary/VolumeRendering.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP, backported-2019.1, backported-2019.2

#3441 Enable support for hardware dynamic resolution
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/SerializedHDCamera.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalDynamicResolutionSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDDynamicResolutionHandler.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.2

#3459 Hdrp/make transparent write motion vecs fit in ui
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, needs-backport-2019.2

#3504 Hdrp/fix default ssr in framesettings
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, backported-2019.1, backported-2019.2

#3502 Enabled taa sharpening
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl
Labels: HDRP, backported-2019.1, backported-2019.2

#3508 Fix change log after bad merge
  com.unity.shadergraph/CHANGELOG.md
Labels: Shader Graph

#3499 Backport #3334 (martin fixes)
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/AssetCallbacks/CreateShaderSubGraph.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Implementation/NodeUtils.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporterEditor.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Util/CopyPasteGraph.cs
  com.unity.shadergraph/Tests/Editor/UnitTests/SerializedGraphTests.cs
Labels: Shader Graph

#3518 Fix for refraction causing NaNs when IOR is set to 1 and refraction mode is Box
  com.unity.render-pipelines.core/ShaderLibrary/Refraction.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP, backported-2019.1, backported-2019.2

#3509 Matcap view
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/Matcap.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/Matcap/DefaultMatcap.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/Matcap/DefaultMatcap.png.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/Matcap/MatcapMetal.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/Matcap/MatcapMetal.png.meta
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderPipelinePreferences.cs
Labels: HDRP, needs-backport-2019.2

#3510 Hdrp/expose lightlayer editor drawer for other packages
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
Labels: HDRP, backported-2019.1, backported-2019.2

#3486 Fixed resource issues in LW
  TestProjects/LWGraphicsTest/Assets/Scenes/052_LWCallbacks/CustomRenderer.asset
  com.unity.render-pipelines.core/Runtime/Utilities/ResourceReloader.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/ForwardRendererData.asset
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineEditorResources.asset
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
Labels: lwrp, needs-backport-2019.2

#3507 Lw/bugfixes
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ScriptableRendererDataEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.lightweight/ShaderLibrary/MetaInput.hlsl
  com.unity.render-pipelines.lightweight/Shaders/BakedLitMetaPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Lit.shader
  com.unity.render-pipelines.lightweight/Shaders/LitMetaPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/SimpleLitMetaPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/Terrain/TerrainLitMetaPass.hlsl
  com.unity.render-pipelines.lightweight/Shaders/UnlitMetaPass.hlsl
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3523 Fix player compilation error caused by matcap view
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backported-2019.2

#3524 Hdrp docs wiki deprecation sync
  com.unity.render-pipelines.high-definition/Documentation~/Camera-Relative-Rendering.md
  com.unity.render-pipelines.high-definition/Documentation~/Creating-a-Custom-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/MotionVectors2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-Exposure1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-Exposure2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-Exposure3.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/RenderPipelineWizard1.png
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Motion-Vectors.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exponential-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exposure.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Gradient-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-HDRI-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Linear-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Procedural-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Visual-Environment.md
  com.unity.render-pipelines.high-definition/Documentation~/Planar-Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-Proxy-Volume.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Wizard.md
  com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.1, needs-backport-2019.2

#3525 Fixed nan tracker not using the exposure
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
Labels: HDRP

#3527 Fixed sorting priority
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitUI.cs
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3440 Fix FB Case 1136856: Scene Color and Scene Depth nodes broken in Subgraphs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.1, needs-backport-2019.2

#3488 [backport.1] Fix 1136856: Scene Color and Scene Depth nodes broken in Subgraphs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
Labels: Shader Graph, backported-2019.1, bug-fix

#3452 Remove Remaining Outdated Docs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Custom-Nodes-With-CodeFunctionNode.md
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode01.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode02.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode03.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode04.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode05.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode06.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode07.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode08.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode09.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode10.png
Labels: Shader Graph, docs, needs-backport-2019.2

#3492 [backport] Remove Remaining Outdated Docs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Custom-Nodes-With-CodeFunctionNode.md
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode01.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode02.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode03.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode04.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode05.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode06.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode07.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode08.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode09.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode10.png
Labels: Shader Graph, backported-2019.2, docs

#3528 [backport 2019.1] Remove Remaining Outdated Docs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Custom-Nodes-With-CodeFunctionNode.md
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode01.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode02.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode03.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode04.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode05.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode06.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode07.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode08.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode09.png
  com.unity.shadergraph/Documentation~/images/Custom-Nodes-With-CodeFunctionNode10.png
Labels: Shader Graph, backported-2019.1, docs

#3370 Fix FB 1143542 - Slot names give better error messages
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Implementation/NodeUtils.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.2

#3533 Fix a NPE with AOVRequests
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
Labels: HDRP, needs-backport-2019.2

#3534 Fix hd probe dirty prefabs 1145195
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
Labels: needs-backport-2019.1, needs-backport-2019.2

#3442 Set the now exposed cascade blend factor to the previous hard-coded v…
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
Labels: HDRP, backported-2019.2

#3535 Fixed CopyDepthBuffer shader to be compatible with XR texture arrays
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/CopyDepthBuffer.shader
Labels: HDRP, needs-backport-2019.2

#3515 HDRP half support
  com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Macros.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/NormalSurfaceGradient.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Packing.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Shadow/ShadowSamplingTent.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP, needs-backport-2019.2

#3538 Hdrp/fix wizard default scene prefab extension
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3522 Lw/docs update asset and faq
  com.unity.render-pipelines.lightweight/Documentation~/baked-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/configuring-lwrp-for-use.md
  com.unity.render-pipelines.lightweight/Documentation~/creating-a-new-project-with-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/faq.md
  com.unity.render-pipelines.lightweight/Documentation~/getting-started-with-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/inside-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/installing-lwrp-into-an-existing-project.md
  com.unity.render-pipelines.lightweight/Documentation~/lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/shader-stripping-keywords.md
  com.unity.render-pipelines.lightweight/Documentation~/shader-stripping.md
  com.unity.render-pipelines.lightweight/Documentation~/shaders-in-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/shading-model.md
  com.unity.render-pipelines.lightweight/Documentation~/simple-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/unlit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/upgrading-your-shaders.md
Labels: lwrp

#3542 Update AOVRequest doc
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVBuffers.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequest.cs
Labels: HDRP, needs-backport-2019.2

#3529 Adding Custom Function Node documentation
  com.unity.shadergraph/Documentation~/Custom-Function-Node.md
  com.unity.shadergraph/Documentation~/Custom-Port-Menu.md
  com.unity.shadergraph/Documentation~/Sub-graph-Asset.md
  com.unity.shadergraph/Documentation~/Sub-graph-Node.md
  com.unity.shadergraph/Documentation~/Sub-graph.md
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-01.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-02.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-03.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-04.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-wFunction.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-String-Output.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-String-wFunction.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-String.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-Subgraph.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Add.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Empty.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Remove.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Rename.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Type.png
  com.unity.shadergraph/Documentation~/index.md
Labels: Shader Graph, docs

#3530 [Backport 2019.1] Adding Custom Function Node documentation
  com.unity.shadergraph/Documentation~/Custom-Function-Node.md
  com.unity.shadergraph/Documentation~/Custom-Port-Menu.md
  com.unity.shadergraph/Documentation~/Sub-graph-Asset.md
  com.unity.shadergraph/Documentation~/Sub-graph-Node.md
  com.unity.shadergraph/Documentation~/Sub-graph.md
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-01.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-02.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-03.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-04.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-wFunction.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-String-Output.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-String-wFunction.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-String.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-Subgraph.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Add.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Empty.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Remove.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Rename.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Type.png
  com.unity.shadergraph/Documentation~/index.md
Labels: Shader Graph, backported-2019.1, docs

#3531 [Backport 2019.2] Adding Custom Function Node documentation
  com.unity.shadergraph/Documentation~/Custom-Function-Node.md
  com.unity.shadergraph/Documentation~/Custom-Port-Menu.md
  com.unity.shadergraph/Documentation~/Sub-graph-Asset.md
  com.unity.shadergraph/Documentation~/Sub-graph-Node.md
  com.unity.shadergraph/Documentation~/Sub-graph.md
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-01.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-02.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-03.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-Function-04.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File-wFunction.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-File.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-String-Output.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-String-wFunction.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-String.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node-Subgraph.png
  com.unity.shadergraph/Documentation~/images/Custom-Function-Node.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Add.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Empty.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Remove.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Rename.png
  com.unity.shadergraph/Documentation~/images/Custom-Port-Menu-Type.png
  com.unity.shadergraph/Documentation~/index.md
Labels: Shader Graph, backported-2019.2, docs

#3283 Hidden Path Namespace for Subgraphs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs
Labels: Shader Graph

#3350 Fix FB Case 1118393 - Settings Pop Up Draws Behind Nodes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.2

#3517 2d/global light refactor
  com.unity.render-pipelines.lightweight/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Utility/RendererLighting.cs
Labels: lwrp

#3548 [VFX] Fix package build to master (ugui)
  com.unity.visualeffectgraph/Unity.VisualEffectGraph.Runtime.asmdef
Labels: vfx

#3536 [VFX] Fix package build to 2019.2 (ugui)
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXExpressionMathTests.cs
  com.unity.visualeffectgraph/Unity.VisualEffectGraph.Runtime.asmdef
Labels: vfx

#3532 HDRP - Fix decal issue in player
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3547 LWRP Added Unity.ugui to LWRP Test Project asmdef
  TestProjects/LWGraphicsTest/Assets/Scenes/013_CameraMulti_Splitscreen.unity
  TestProjects/LWGraphicsTest/Assets/Unity.Testing.SRP.Lightweight.Runtime.asmdef
  TestProjects/LWGraphicsTest/Assets/Unity.Testing.SRP.Lightweight.Runtime.asmdef.meta
Labels: lwrp, needs-backport-2019.2

#3549 Lw/fix serialization issue
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
Labels: lwrp, needs-backport-2019.2

#3554 Add support of decal shader graph preview
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3553 Add missing stereo rendering macros in some fragment shaders
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/Distortion/ApplyDistortion.shader
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/CopyDepthBuffer.shader
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/DownsampleDepth.shader
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/UpsampleTransparent.shader
Labels: HDRP, XR, needs-backport-2019.2

#3555 LWRP Backport #3547 - asmdef/ugui issue
  TestProjects/LWGraphicsTest/Assets/Scenes/013_CameraMulti_Splitscreen.unity
  TestProjects/LWGraphicsTest/Assets/Unity.Testing.SRP.Lightweight.Runtime.asmdef
  TestProjects/LWGraphicsTest/Assets/Unity.Testing.SRP.Lightweight.Runtime.asmdef.meta
Labels: lwrp

#3556 Fixed exposure for planar/reflection probe gizmos
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbesPreview.shader
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ReflectionProbesPreview.shader
Labels: HDRP, backported-2019.1, backported-2019.2

#3552 Fix single-pass instancing on PSVR
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, XR, needs-backport-2019.2

#3551 Fix Vulkan shader issue with Texture2DArray in ScreenSpaceShadow
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadow.compute
Labels: HDRP, XR, needs-backport-2019.2

#3501 Fix camera-relative issue with lights and XR single-pass instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
Labels: HDRP, XR, needs-backport-2019.2

#3558 Fix single-pass instancing on Vulkan
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, XR, needs-backport-2019.2

#3541 Correcting various bugs due linked to ray tracing
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingFragInputs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/OwenScrambledNoise.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Texture/CoherentNoise/OwenScrambledNoise.png.meta
Labels: HDRP, dxr, needs-backport-2019.2

#3374 [LW][XR] Fix FB#1142952 - Vulkan renders only to one eye with single-pass instancing mode
  com.unity.render-pipelines.core/ShaderLibrary/UnityInstancing.hlsl
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/ShaderLibrary/UnityInput.hlsl
Labels: lwrp, needs-backport-2019.2

#3561 [Backport 2019.1][ShaderGraph] Fix FB Case 1152247 - SubGraph Preview Generation Fails
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
Labels: Shader Graph, backported-2019.1, bug-fix

#3560 [ShaderGraph] Fix FB Case 1152247 - SubGraph Preview Generation Fails
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
Labels: Shader Graph, bug-fix

#3570 Lw/bugfixes
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/MaterialPostprocessor.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightPBRExtraPasses.template
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3571 Lw/backports
  TestProjects/LWGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.core/ShaderLibrary/UnityInstancing.hlsl
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Documentation~/baked-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/configuring-lwrp-for-use.md
  com.unity.render-pipelines.lightweight/Documentation~/creating-a-new-project-with-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/faq.md
  com.unity.render-pipelines.lightweight/Documentation~/getting-started-with-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/inside-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/installing-lwrp-into-an-existing-project.md
  com.unity.render-pipelines.lightweight/Documentation~/lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/shader-stripping-keywords.md
  com.unity.render-pipelines.lightweight/Documentation~/shader-stripping.md
  com.unity.render-pipelines.lightweight/Documentation~/shaders-in-lwrp.md
  com.unity.render-pipelines.lightweight/Documentation~/shading-model.md
  com.unity.render-pipelines.lightweight/Documentation~/simple-lit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/unlit-shader.md
  com.unity.render-pipelines.lightweight/Documentation~/upgrading-your-shaders.md
  com.unity.render-pipelines.lightweight/Editor/MaterialPostprocessor.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightPBRExtraPasses.template
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.lightweight/ShaderLibrary/UnityInput.hlsl
Labels: lwrp

#3574 Disable HD and VFX pipelines yamato
  .yamato/upm-ci-projects.yml
  .yamato/upm-ci-vfx_lwrp.yml
Labels: needs-backport-2019.1, needs-backport-2019.2

#3579 Fix gizmo in camera preview
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Core/CameraEditorUtils.cs
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3580 Hdrp/fix resources again
  .github/PULL_REQUEST_TEMPLATE.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP, needs-backport-2019.2

#3577 [VFX] Desactivate pre-exposure in unlit (2019.1)
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXContextTests.cs
  TestProjects/VisualEffectGraph/Assets/HDRP/HDRenderPipelineAsset.asset
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/00_MultiOutput.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/01_Animator.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/02_Gradient.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/03_EventAttribute.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/04_Bounds.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/06_LineOutput.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/07_UnityLogo.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/08_Shadows.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/09_AttributeMaps.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/10_SortPriority.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/11_Space.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/11_SpaceBis.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/12_LocalTransformations.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/14_DecalsFlipBook.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/15_CubeAndMesh.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/16_CullingMode.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/16_MeshParticles.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/17_GPUEvent_Simple.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/17_SoftParticles.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/19_Random.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/21_DepthModules.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/22_Prewarm.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/23_InvertTRSMatrix.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/AngularVelocity.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/Collision.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/HDRP.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/HDRPFog.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/Noise.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/ParticleCountLimit.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/SimpleLit.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/Timeline.png
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Inspector/VFXContextEditor.cs
  com.unity.visualeffectgraph/Editor/Inspector/VFXSlotContainerEditor.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/VFXContext.cs
  com.unity.visualeffectgraph/Shaders/RenderPipeline/HDRP/VFXCommon.cginc
Labels: vfx

#3581 Add exposure weight / pre-exposure for emissive decal and correct fade control
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/4001_Exposure.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/4001_Exposure.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProperties.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3572 Moved LOD Settings in Rendering section
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, needs-backport-2019.2

#3567 Updated exposure prepass to support single-pass instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/Exposure.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP, XR, needs-backport-2019.2

#3563 Force preIntegratedFGD_GGXDisneyDiffuse and volumetricLighting shaders to use float when they generate data.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/PreIntegratedFGD_CookTorrance.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/PreIntegratedFGD_Ward.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/PreIntegratedFGD/preIntegratedFGD_CharlieFabricLambert.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/PreIntegratedFGD/preIntegratedFGD_GGXDisneyDiffuse.shader
Labels: HDRP, needs-backport-2019.2

#3461 Screen Space directional shadows option (under define)
  TestProjects/LWGraphicsTest/Assets/CommonAssets/Scripts/LWGraphicsTests.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadows.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadows.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP, backported-2019.2

#3418 Hdrp decals htile fix
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3582 Fix NaNs arising during the hair lighting pass
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3493 [backport 2019.1] Miscellaneous Shader Graph Fixes
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Gradient/GradientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs
Labels: Shader Graph, backported-2019.1, bug-fix

#3586 Remove QualitySettings shadow related value tweaks, not needed anymore.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backported-2019.2

#3557 Added a new abstraction for RendererList that will help transition to Render Graph and future RendererList API
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/RendererList.meta
  com.unity.render-pipelines.high-definition/Runtime/Core/RendererList/RendererList.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/RendererList/RendererList.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP, needs-backport-2019.2

#3393 VR multipass and XR SDK integration
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRDebug.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
  com.unity.render-pipelines.high-definition/Tests/Editor/XRSystemTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/XRSystemTests.cs.meta
Labels: HDRP, XR

#3592 Fix shader warning
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl
Labels: HDRP, backported-2019.2

#3594 Use GetPositionInput instead of GetPositionInput_Stereo in Screen space shadows
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadows.shader
Labels: HDRP

#3591 Fix precision label for Shadow - Ponctual Lights Atlas
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
Labels: HDRP, backported-2019.2

#3597 Fix for contact shadows texture not being bound
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3598 Light explorer improvements
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
Labels: HDRP, needs-backport-2019.2

#3599 Fix build PS4
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/AreaBilateralShadow.compute
Labels: HDRP, dxr, needs-backport-2019.2

#3601 Fix LOD transition
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9001_LODTransition.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9001_LODTransition.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9001_LODTransition.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP, needs-backport-2019.2

#3604 Fix shader warnings related to raytracing and TEXTURE2D_X
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/AreaBilateralShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/RaytracingAreaShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuseAccumulation.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
Labels: HDRP, XR, dxr

#3607 Hdrp/tests/fix 2103
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/.gitignore
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/LightingData.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/LightingData.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-0_comp_dir.png
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-0_comp_dir.png.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-0_comp_light.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-0_comp_light.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-1_comp_dir.png
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-1_comp_dir.png.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-1_comp_light.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-1_comp_light.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-2_comp_dir.png
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-2_comp_dir.png.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-2_comp_light.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/Lightmap-2_comp_light.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-0.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-0.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-1.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-1.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-10.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-10.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-11.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-11.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-12.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-12.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-13.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-13.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-14.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-14.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-15.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-15.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-16.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-16.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-2.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-2.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-3.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-3.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-4.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-4.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-5.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-5.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-6.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-6.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-7.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-7.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-8.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-8.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-9.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2103_GI_BakeMixed/ReflectionProbe-9.exr.meta
Labels: HDRP, needs-backport-2019.2

#3612 Renamed file LookDev/Renderer.cs to avoid conflict with builtin Unity
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.cs
  com.unity.render-pipelines.core/Editor/LookDev/Environment.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDevRenderer.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDevRenderer.cs.meta
Labels: HDRP, needs-backport-2019.2

#3595 Fixed asset creation causing NullReference exception.
  TestProjects/LWGraphicsTest/Assets/Scenes/052_LWCallbacks/CameraCallbackTests.cs
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/CopyColorPass.cs
  com.unity.render-pipelines.lightweight/Tests/Editor/EditorTests.cs
  com.unity.render-pipelines.lightweight/Tests/Editor/Unity.RenderPipelines.Core.Editor.Tests.asmdef
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3578 Lw/docs upd comparison table
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Documentation~/lwrp-builtin-feature-comparison.md
  com.unity.render-pipelines.lightweight/Documentation~/shading-model.md
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3562 Remove ShaderGraph tests from HD and LW Test Projects.
  TestProjects/HDRP_Tests/Packages/manifest.json
  TestProjects/LWGraphicsTest/Packages/manifest.json
Labels: Shader Graph, needs-backport-2019.2

#3349 Miscellaneous Shader Graph Fixes
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Gradient/GradientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs
Labels: Shader Graph, bug-fix

#3616 [BACKPORT][XR][Graphics] 2019.1/xr/lwrp/auto resolve spi optimization
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
Labels: lwrp

#3618 Move sceneLightingWasDisabled to camera
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.2

#3621 Max dynamic res was labelled as min dynamic res #3613
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
Labels: HDRP, needs-backport-2019.2

#3596 Lw/set camera properties
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: lwrp

#3606 Add "Experimental" tag to various menus regarding the 2D renderer.
  com.unity.render-pipelines.lightweight/Editor/2D/Renderer2DMenus.cs
  com.unity.render-pipelines.lightweight/Editor/2D/Renderer2DUpgrader.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineMaterialUpgrader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/CreateSpriteLitShaderGraph.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/CreateSpriteUnlitShaderGraph.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/SpriteLitMasterNode.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/SpriteUnlitMasterNode.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/PixelPerfectCamera.cs
Labels: lwrp, needs-backport-2019.2

#3633 Add "Experimental" tag to various menus regarding the 2D renderer.
  com.unity.render-pipelines.lightweight/Editor/2D/Renderer2DMenus.cs
  com.unity.render-pipelines.lightweight/Editor/2D/Renderer2DUpgrader.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineMaterialUpgrader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/CreateSpriteLitShaderGraph.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/CreateSpriteUnlitShaderGraph.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/SpriteLitMasterNode.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/SpriteUnlitMasterNode.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/PixelPerfectCamera.cs
Labels: backported-2019.2, lwrp

#3634 Add "Experimental" tag to various menus regarding the 2D renderer
  com.unity.render-pipelines.lightweight/Editor/2D/Renderer2DMenus.cs
  com.unity.render-pipelines.lightweight/Editor/2D/Renderer2DUpgrader.cs
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineMaterialUpgrader.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/CreateSpriteLitShaderGraph.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/CreateSpriteUnlitShaderGraph.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/SpriteLitMasterNode.cs
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/MasterNodes/SpriteUnlitMasterNode.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/PixelPerfectCamera.cs
Labels: backported-2019.2, lwrp

#3630 Remove post process condition on skipping pyramid since bloom runs its own pyramid
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backported-2019.2

#3632 Move chagnelog for fix to case 1142495
  com.unity.render-pipelines.lightweight/CHANGELOG.md
Labels: lwrp

#3642 Update Samples folder to respect publishing validation
  com.unity.render-pipelines.high-definition/Samples.meta
  com.unity.render-pipelines.high-definition/Samples~/PostProcessingData.meta
  com.unity.render-pipelines.high-definition/Samples~/PostProcessingData/.sample.json
  com.unity.render-pipelines.high-definition/Samples~/PostProcessingData/PostProcessingData.unitypackage
  com.unity.render-pipelines.high-definition/Samples~/PostProcessingData/PostProcessingData.unitypackage.meta
  com.unity.render-pipelines.high-definition/Samples~/ShaderGraphSamples.meta
  com.unity.render-pipelines.high-definition/Samples~/ShaderGraphSamples/.sample.json
  com.unity.render-pipelines.high-definition/Samples~/ShaderGraphSamples/ShaderGraphSamples.unitypackage
  com.unity.render-pipelines.high-definition/Samples~/ShaderGraphSamples/ShaderGraphSamples.unitypackage.meta
  com.unity.render-pipelines.high-definition/package.json
Labels: HDRP, needs-backport-2019.2

#3644 Fixed a conflict between preview and main view sky rendering
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, needs-backport-2019.2

#3099 Improvement of planar probes
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2203_PlanarProbes.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2206_PlanarReflectionVFace.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2210_ReflectionProbes_CaptureAtVolumeAnchor.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2210_ReflectionProbes_CaptureAtVolumeAnchor/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2210_ReflectionProbes_CaptureAtVolumeAnchor/Volume Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2501_LightLayers.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2203_PlanarProbes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2203_PlanarProbes.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2206_PlanarReflectionVFace.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2208_PlanarReflectionCullingStencil.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2211_Probes_Specular.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2211_Probes_Specular.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2501_LightLayers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2501_LightLayers.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.Gizmos.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedHDProbe.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedProbeSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeCapturePositionSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP, needs-backport-2019.2

#3512 Backport 2019.2 #3330 (sg/bugfix-1141553)
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/AbstractShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/BooleanShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/ColorShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/CubemapShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Matrix4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Graphs/SamplerStateShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture2DArrayShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Texture3DShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/TextureShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector2ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector3ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/Vector4ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SamplerStateNode.cs
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
Labels: Shader Graph, bug-fix

#3513 Backport 2019.2 #3233 (sg/bugfix-1136706)
  com.unity.shadergraph/Editor/Data/Nodes/Input/Lighting/BakedGINode.cs
Labels: Shader Graph, bug-fix

#3514 Backport 2019.2 #3144 (sg/bugfix-1131638)
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
Labels: Shader Graph, bug-fix

#3643 Fix volumetric rendering with single-pass instancing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, XR, backported-2019.2

#3648 Fixing syntax in yamato yml files
  .yamato/upm-ci-hdrp.yml
  .yamato/upm-ci-lwrp.yml
  .yamato/upm-ci-postprocessing.yml
  .yamato/upm-ci-shadergraph.yml
  .yamato/upm-ci-vfx_lwrp.yml
  .yamato/upm-ci-vfxmain.yml
Labels: needs-backport-2019.1, needs-backport-2019.2

#3649 Fixed volumetric reprojection issue due to divide by 0
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
Labels: HDRP, backported-2019.2

#3609 Change ifdef guard to 2019.2 for backport
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
Labels: HDRP

#3588 LightLoop and Volumetric Lighting are not separate class anymore but are part of HDRenderPipline partial class.
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/HDShadowSettingsEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.2

#3658 Moving ray tracing parameters to Volume system, HDAddditionalLightData and fixing compilation errors
  com.unity.render-pipelines.core/Runtime/Volume/VolumeParameter.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDAssetFactory.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineRayTracingResourcesAsset.png
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineRayTracingResourcesAsset.png.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineRayTracingResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineRayTracingResources.asset.meta
Labels: HDRP, dxr

#3625 Custom Function Node fixes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/TextureSamplerState.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Drawing/Views/HlslFunctionView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs
Labels: Shader Graph, bug-fix

#3628 [Backport 2019.1] Fix Custom Function Node variable names
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
Labels: Shader Graph, backported-2019.1, bug-fix

#3626 [Backport 2019.2] Custom Function Node fixes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/TextureSamplerState.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Drawing/Views/HlslFunctionView.cs
  com.unity.shadergraph/Editor/Drawing/Views/ReorderableSlotListView.cs
Labels: Shader Graph, backported-2019.2, bug-fix

#3659 Hdrp/update wizard
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/WizardResources.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/WizardResources/Error.png
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/WizardResources/Error.png.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/WizardResources/OK.png
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/WizardResources/OK.png.meta
Labels: HDRP, backported-2019.2

#3638 Backport changes to fix 1142495
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: lwrp

#3655 Added a test for material and renderer sorting priority
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Blue_Priority_0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Blue_Priority_0.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Green_Priority_-20.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Green_Priority_-20.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Green_Priority_0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Green_Priority_0.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Red_Priority_0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Red_Priority_0.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Red_Priority_20.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Lit_Red_Priority_20.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Blue_Priority_0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Blue_Priority_0.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Green_Priority_-20.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Green_Priority_-20.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Green_Priority_0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Green_Priority_0.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Red_Priority_0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Red_Priority_0.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Red_Priority_20.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1220_Sorting/Unlit_Red_Priority_20.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1220_Sorting.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1220_Sorting.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP, needs-backport-2019.2

#3654 [master] Reduce the group size of the deferred lighting pass from 16x16 to 8x8
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/builddispatchindirect.compute
Labels: HDRP, needs-backport-2019.2

#3668 fixed null reference error when accessing scriptableRendererData
  com.unity.render-pipelines.lightweight/Runtime/Data/LightweightRenderPipelineAsset.cs
Labels: lwrp, needs-backport-2019.2

#3491 [backport] Fix FB Case 1118393 - Settings Pop Up Draws Behind Nodes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph, backported-2019.2, bug-fix

#3490 [backport] Fix FB 1143542 - Slot names give better error messages
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Implementation/NodeUtils.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
Labels: Shader Graph, backported-2019.2, bug-fix

#3489 [backport.2] Fix 1136856: Scene Color and Scene Depth nodes broken in Subgraphs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
Labels: Shader Graph, backported-2019.2, bug-fix

#3667 Disable sky when in matcap view
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.2

#3665 Hdrp/removed unused shadow data
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
Labels: HDRP, needs-backport-2019.2

#3672 Merge HDRP staging
  com.unity.render-pipelines.core/Runtime/Volume/VolumeParameter.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDAssetFactory.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineRayTracingResourcesAsset.png
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/RenderPipelineResources/Texture/HDRenderPipelineRayTracingResourcesAsset.png.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/RaytracingAreaShadows.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineRayTracingResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineRayTracingResources.asset.meta
Labels: HDRP

#3675 Remove async compil selection
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
Labels: HDRP

#3677 Better handling of fully metallic objects in matcaps
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
Labels: HDRP

#3569 Fixed crash on exception when saving, case 1136543
  com.unity.shadergraph/Editor/AssetCallbacks/CreateShaderSubGraph.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Util/FileUtilities.cs
  com.unity.shadergraph/Editor/Util/FileUtilities.cs.meta
Labels: Shader Graph, needs-backport-2019.2

#3539 Backport #3334 (martin fixes)
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/AssetCallbacks/CreateShaderSubGraph.cs
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Implementation/NodeUtils.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporterEditor.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporterEditor.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
  com.unity.shadergraph/Editor/Util/CopyPasteGraph.cs
  com.unity.shadergraph/Tests/Editor/UnitTests/SerializedGraphTests.cs
Labels: Shader Graph

#3676 Fix default contact shadow texture type mismatch
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, needs-backport-2019.2

#3664 Ray tracing effects to volume system
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RecursiveRenderingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RecursiveRenderingEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIllumination.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIllumination.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RayTracing.meta
  com.unity.render-pipelines.high-definition/Runtime/RayTracing/RayTracing.cs
  com.unity.render-pipelines.high-definition/Runtime/RayTracing/RayTracing.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
Labels: HDRP, dxr, needs-backport-2019.2

#3669 Fixed LWRP missing resources when upgrading template from older version.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ForwardRendererData.cs
Labels: lwrp, needs-backport-2019.2

#3636 Backport changes from fix to case 1142495
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
Labels: lwrp

#3684 Hdrp/fix generate shader includes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Core/ShaderGenerator/CSharpToHLSL.cs
Labels: HDRP, needs-backport-2019.2

#3685 Hdrp/fix cleaned texture in cascade inspector
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Shadow/ShadowCascadeGUI.cs
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3653 [Backport] Remove ShaderGraph tests from HD and LW Test Projects.
  TestProjects/HDRP_Tests/Packages/manifest.json
  TestProjects/LWGraphicsTest/Packages/manifest.json
Labels: SRP, backported-2019.2

#3691 Fix crash in FrameSettingsHistory when double disabling a camera
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
Labels: HDRP, needs-backport-2019.1, needs-backport-2019.2

#3683 [LWRP] Replace beginCameraRendering callbacks by non obsolete implementation
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.lightweight/Tests/Runtime/Light2DTests.cs
Labels: lwrp

#3662 Fix LWRP GC spikes
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipelineCore.cs
  com.unity.render-pipelines.lightweight/Runtime/Passes/ScreenSpaceShadowResolvePass.cs
  com.unity.render-pipelines.lightweight/Runtime/RenderingUtils.cs
  com.unity.render-pipelines.lightweight/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/ShadowUtils.cs
Labels: lwrp, needs-backport-2019.1, needs-backport-2019.2

#3602 Move IGeneratesBodyCode to ShaderStringBuilder
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/DiffusionProfileNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/EmissionNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ExposureNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/HDSceneColorNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ParallaxOcclusionMappingNode.cs
  com.unity.shadergraph/Editor/Data/Interfaces/IGeneratesBodyCode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Adjustment/ChannelMixerNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Adjustment/InvertColorsNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Mask/ChannelMaskNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Normal/NormalFromHeightNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Normal/NormalFromTextureNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Channel/FlipNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Channel/SplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Channel/SwizzleNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/CodeFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/BooleanNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/ColorNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/ConstantNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/IntegerNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/SliderNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector1Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector2Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector3Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector4Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Geometry/ScreenPositionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Geometry/UVNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Gradient/GradientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix2Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix3Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix4Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PBR/DielectricSpecularNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PBR/MetalReflectanceNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleCubemapNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture2DArrayNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture2DLODNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture2DNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture3DNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/TexelSizeNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixConstructionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Vector/TransformNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/UV/FlipbookNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/UV/TriplanarNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/Logic/IsFrontFaceNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
Labels: Shader Graph, needs-backport-2019.2

#3689 [Backport 2019.2] Move IGeneratesBodyCode to ShaderStringBuilder
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/DiffusionProfileNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/EmissionNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ExposureNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/HDSceneColorNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ParallaxOcclusionMappingNode.cs
  com.unity.shadergraph/Editor/Data/Interfaces/IGeneratesBodyCode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Adjustment/ChannelMixerNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Adjustment/InvertColorsNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Mask/ChannelMaskNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Normal/NormalFromHeightNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Normal/NormalFromTextureNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Channel/FlipNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Channel/SplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Channel/SwizzleNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/CodeFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/BooleanNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/ColorNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/ConstantNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/IntegerNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/SliderNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector1Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector2Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector3Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector4Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Geometry/ScreenPositionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Geometry/UVNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Gradient/GradientNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix2Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix3Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/Matrix4Node.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PBR/DielectricSpecularNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PBR/MetalReflectanceNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/PropertyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleCubemapNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture2DArrayNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture2DLODNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture2DNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture3DNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/TexelSizeNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixConstructionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Vector/TransformNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/UV/FlipbookNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/UV/TriplanarNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/Logic/IsFrontFaceNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Importers/SubGraphDatabaseImporter.cs
Labels: Shader Graph, backported-2019.2

#3605 Color Mode Feature - color nodes by category or custom user colors
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Color-Modes.md
  com.unity.shadergraph/Documentation~/Node.md
  com.unity.shadergraph/Documentation~/Shader-Graph-Window.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Drawing/Colors.meta
  com.unity.shadergraph/Editor/Drawing/Colors/CategoryColors.cs
  com.unity.shadergraph/Editor/Drawing/Colors/CategoryColors.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/ColorManager.cs
  com.unity.shadergraph/Editor/Drawing/Colors/ColorManager.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/CustomColorData.cs
  com.unity.shadergraph/Editor/Drawing/Colors/CustomColorData.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/IColorProvider.cs
  com.unity.shadergraph/Editor/Drawing/Colors/IColorProvider.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/NoColors.cs
  com.unity.shadergraph/Editor/Drawing/Colors/NoColors.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/UserColors.cs
  com.unity.shadergraph/Editor/Drawing/Colors/UserColors.cs.meta
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/IShaderNodeView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Drawing/Views/PropertyNodeView.cs
  com.unity.shadergraph/Editor/Resources/Styles/ColorMode.uss
  com.unity.shadergraph/Editor/Resources/Styles/ColorMode.uss.meta
  com.unity.shadergraph/Editor/Resources/Styles/MaterialNodeView.uss
Labels: Shader Graph, needs-backport-2019.2

#3701 [Backport] Color Mode for 2019.2
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/Color-Modes.md
  com.unity.shadergraph/Documentation~/Node.md
  com.unity.shadergraph/Documentation~/Shader-Graph-Window.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Drawing/Colors.meta
  com.unity.shadergraph/Editor/Drawing/Colors/CategoryColors.cs
  com.unity.shadergraph/Editor/Drawing/Colors/CategoryColors.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/ColorManager.cs
  com.unity.shadergraph/Editor/Drawing/Colors/ColorManager.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/CustomColorData.cs
  com.unity.shadergraph/Editor/Drawing/Colors/CustomColorData.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/IColorProvider.cs
  com.unity.shadergraph/Editor/Drawing/Colors/IColorProvider.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/NoColors.cs
  com.unity.shadergraph/Editor/Drawing/Colors/NoColors.cs.meta
  com.unity.shadergraph/Editor/Drawing/Colors/UserColors.cs
  com.unity.shadergraph/Editor/Drawing/Colors/UserColors.cs.meta
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/IShaderNodeView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
  com.unity.shadergraph/Editor/Drawing/Views/PropertyNodeView.cs
  com.unity.shadergraph/Editor/Resources/Styles/ColorMode.uss
  com.unity.shadergraph/Editor/Resources/Styles/ColorMode.uss.meta
  com.unity.shadergraph/Editor/Resources/Styles/MaterialNodeView.uss
Labels: Shader Graph, backported-2019.2

#3700 Hdrp docs post processing
  com.unity.render-pipelines.high-definition/Documentation~/Glossary.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-ScreenSpaceReflection1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-ScreenSpaceRefraction1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingBloom1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingChannelMixer1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingChromaticAberration1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingColorAdjustments1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingColorCurves1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingColorLookup1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingDepthOfField1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingFilmGrain1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingLensDistortion1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingLiftGammaGain1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingMotionBlur1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingPaniniProjection1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingShadowsMidtonesHighlights1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingSplitToning1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingTonemapping1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingVignette1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-processingWhiteBalance1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/RefractionInHDRP1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/RefractionInHDRP2.png
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exposure.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Screen-Space-Reflection.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Screen-Space-Refraction.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Refraction-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.1, needs-backport-2019.2

#3693 Change to more explicit names the motion blur fields
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/MotionBlurEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/MotionBlur.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP, needs-backport-2019.2

#3694 Add shadow layers to decouple from light layers
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2501_LightLayers.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2502_LightLayers Bitmask.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2502_LightLayers Bitmask.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2502_LightLayers Bitmask/CastShadowTransparent.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2502_LightLayers Bitmask/CastShadowTransparent.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2501_LightLayers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2501_LightLayers.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2502_LightLayers Bitmask.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2502_LightLayers Bitmask.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Layers.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#3687 Refactor Light List Build in prevision of RenderGraph
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#3660 Fix volumetric reprojection with XR
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/MotionVectorVertexShaderCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesMatrixDefsHDCamera.hlsl
Labels: HDRP, XR

#3695 Hdrp/raytracing lod
  com.unity.render-pipelines.core/ShaderLibrary/ImageBasedLighting.hlsl
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/AreaShadows/RaytracingMIS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuseAccumulation.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RayTracingCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RayTracingCommon.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingBuiltinData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingConsts.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingConsts.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingFragInputs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
Labels: HDRP, dxr
