Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-09, with the labels that each got.

#4414 Cache output node type in metadata object on import
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphMetadata.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphMetadata.cs.meta
Labels: Shader Graph

#4410 Inner cone angle is now working.
  com.unity.render-pipelines.core/Editor/Lighting/CoreLightEditorUtilities.cs
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineLightEditor.cs
  com.unity.render-pipelines.universal/Runtime/ForwardLights.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipelineCore.cs
Labels: Universal

#4178 [VFX] Better integration of VFXManager in UniversalRP
  com.unity.render-pipelines.universal/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Unity.RenderPipelines.Universal.Runtime.asmdef
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal, vfx

#4452 Universal/fix color copy pass
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/Passes/CopyColorPass.cs
Labels: Universal

#4438 2d/light-fixes
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditorUtility.cs
  com.unity.render-pipelines.universal/Editor/2D/Renderer2DMenus.cs
  com.unity.render-pipelines.universal/Editor/2D/ShadowCaster2DEditor.cs
  com.unity.render-pipelines.universal/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/ShadowCaster2D.cs
Labels: Universal

#4403 Vfx/2019.2 staging
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/SubgraphEventTransmission/animals/cat.png
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/SubgraphEventTransmission/animals/cat.png.meta
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/GraphView/Views/Properties/ObjectPropertyRM.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXConvertSubgraph.cs
  com.unity.visualeffectgraph/Editor/Models/Blocks/VFXSubgraphBlock.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/HDRP.meta
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXBasicCubeOutput.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXLineOutput.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXPointOutput.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/VFXSubgraphContext.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/VFXSubgraphOperator.cs
  com.unity.visualeffectgraph/Editor/Models/Parameters/VFXParameter.cs
  com.unity.visualeffectgraph/Shaders/ParticleDecals/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassBasicForward.template
  com.unity.visualeffectgraph/Shaders/VFXCommon.cginc
  com.unity.visualeffectgraph/Shaders/VFXCommonOutput.cginc
  com.unity.visualeffectgraph/Shaders/VFXParticleCommon.template
Labels: vfx

#4474 fix for uss warning
  com.unity.visualeffectgraph/Editor Default Resources/uss/VFXBlackboard.uss
Labels: vfx

#4317 HDRP Custom pass
  com.unity.render-pipelines.core/Runtime/RendererList/RendererList.cs
  com.unity.render-pipelines.core/Runtime/Volume/Volume.cs
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultSceneRoot.prefab
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassCSharpScript.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassCSharpScript.template.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawer.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawerAttribute.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawerAttribute.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassFullScreenShader.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassFullScreenShader.template.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassRenderersShader.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassRenderersShader.template.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassVolumeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassVolumeEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/DrawRenderersCustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/DrawRenderersCustomPassDrawer.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/FullScreenCustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/FullScreenCustomPassDrawer.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDShaderUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassCommon.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassInjectionPoint.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassInjectionPoint.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassInjectionPoint.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassInjectionPoint.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassRenderers.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassRenderers.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/DrawRenderersCustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/DrawRenderersCustomPass.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/FullScreenCustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/FullScreenCustomPass.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#4455 Hdrp/various small ui fixes
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/MaterialPostProcessor.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDProjectSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/DiffusionProfileNode.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#4448 Hair master node docs
  com.unity.render-pipelines.high-definition/Documentation~/Images/MasterNodeHair1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/MasterNodeHair2.png
  com.unity.render-pipelines.high-definition/Documentation~/Master-Node-Hair.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs

#4453 remove debugmenu in non devlopment build
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Runtime/Debugging/DebugManager.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugUpdater.cs
Labels: HDRP, SRP

#4465 Fixing Ray Tracing bugs (XR, Lights)
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/RecursiveRendering.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/RecursiveRendering.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
Labels: HDRP, dxr

#4462 Moved render passes to Internal namespace. Added some missing docs.
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CameraCallbackTests.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CustomRenderPipeline/CustomRenderer.cs
  com.unity.render-pipelines.universal/Editor/AssemblyInfo.cs
  com.unity.render-pipelines.universal/Editor/AssemblyInfo.cs.meta
  com.unity.render-pipelines.universal/Editor/EditorUtils.cs
  com.unity.render-pipelines.universal/Editor/RendererFeatures/NewRendererFeatureDropdownItem.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/ForwardLights.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/AdditionalLightsShadowCasterPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/ColorGradingLutPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/CopyColorPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/CopyDepthPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/DepthOnlyPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/DrawObjectsPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/DrawSkyboxPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/MainLightShadowCasterPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/ScreenSpaceShadowResolvePass.cs
  com.unity.render-pipelines.universal/Runtime/RenderingUtils.cs
  com.unity.render-pipelines.universal/Tests/Editor/EditorTests.cs
Labels: Universal

#4444 Fixed post-processing history reset handling rt-scale incorrectly
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP, needs-backport-2019.2

#4432 Use alternative stencil copy path for MacOS to work around driver bug
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP

#4450 Hdrp/framesettingshistory upgrade
  com.unity.render-pipelines.core/Runtime/Debugging/DebugManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
Labels: HDRP

#4477 Added space to menu entry
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
Labels: Universal

#4478 Update documentation for DebugMenu in Devlopment build only
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Window.md
Labels: HDRP

#4479 Fix half pixel shift in ao in half res
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOUpsample.compute
Labels: HDRP

#4433 Restore camera alpha compositing to HDRP
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition/AlphaCompositingMaterial_Alpha.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition/AlphaCompositingMaterial_Alpha.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition/CompositingRT.renderTexture
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition/CompositingRT.renderTexture.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition/GenerateComposite.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition/GenerateComposite.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition/UseComposite.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9007_CameraAlphaComposition/UseComposite.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9007_CameraAlphaComposition.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9007_CameraAlphaComposition.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/UpsampleTransparent.shader
  com.unity.testing.hdrp/RP_Assets/HDRP_Test_Def_FP16.asset
  com.unity.testing.hdrp/RP_Assets/HDRP_Test_Def_FP16.asset.meta
Labels: HDRP

#4483 Update CHANGELOG.md
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#4481 Restored HDCamera to the sky rendering builtin parameters
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
Labels: HDRP

#4482 Fix culling with XR multi-pass
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/XRSystemTests.cs
Labels: HDRP, XR

#4418 Support new API for XR mirror view
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/XRMirrorView.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/XRMirrorView.shader
Labels: HDRP, XR

#4421 Keywords docs
  com.unity.shadergraph/Documentation~/Blackboard.md
  com.unity.shadergraph/Documentation~/Keyword-Node.md
  com.unity.shadergraph/Documentation~/Keywords.md
  com.unity.shadergraph/Documentation~/Sub-graph.md
  com.unity.shadergraph/Documentation~/TableOfContents.md
  com.unity.shadergraph/Documentation~/images/blackboard_shadergraph_path.png
  com.unity.shadergraph/Documentation~/images/blackboard_subgraph_path.png
  com.unity.shadergraph/Documentation~/images/keywords_boolean.png
  com.unity.shadergraph/Documentation~/images/keywords_built-in.png
  com.unity.shadergraph/Documentation~/images/keywords_enum.png
Labels: Shader Graph, docs

#4467 Remove usage of StructuredBuffer for XR View Constants
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesMatrixDefsHDCamera.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyUtils.hlsl
Labels: HDRP, XR

#4485 Add refresh after a frame on history element of debugmenu to handle sanitization
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerEnumHistory.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerToggleHistory.cs
Labels: HDRP

#4442 [Shader Graph][HDRP] Enable Normal and Tangent Modification in Vertex
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/VertexAnimation.template.hlsl
Labels: HDRP, Shader Graph, high-priority

#4489 Binding correctly the sky texture for both forward and deferred ray tracing modes
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
Labels: HDRP, dxr

#4491 Fix ambient light in lookdev
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LookDev.cs
Labels: HDRP

#4503 Lookdev/rework debug panel workflow
  com.unity.render-pipelines.core/Editor/LookDev/Context.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow-PersonalSkin.uss
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.DebugSidePanel.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.EnvironmentLibrarySidePanel.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.uss
  com.unity.render-pipelines.core/Editor/LookDev/Stage.cs
  com.unity.render-pipelines.core/Editor/LookDev/ToolbarRadio.cs
Labels: HDRP

#4499 fix default scene broken GUID
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultSceneRoot.prefab
Labels: HDRP

#4493 Depth of Field CoC Fullscreen Debug Mode
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP

#4497 Update sg materials
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/ShaderGraphMaterialsUpdater.cs
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/ShaderGraphMaterialsUpdater.cs.meta
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
Labels: HDRP, Shader Graph, needs-backport-2019.2

#4509 Minor UI fix
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP

#4490 Add ambient occlusion override in debug windows
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/LightingDebug.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP

#4484 Custom Post Processes
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/BluePP.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/BluePP.cs.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/BluePP.shader
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/BluePP.shader.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/GreenPP.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/GreenPP.cs.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/GreenPP.shader
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/GreenPP.shader.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/Post Processing Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/Post Processing Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/RedPP.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/RedPP.cs.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/RedPP.shader
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/RedPP.shader.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/Transparent.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/4x_PostProcessing/4060_CustomPostProcess/Transparent.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/4060_CustomPostProcess.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/4060_CustomPostProcess.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/4060_CustomPostProcess.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/4060_CustomPostProcess.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/Templates.meta
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/Templates/CustomPostProcessingShader.template
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/Templates/CustomPostProcessingShader.template.meta
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/Templates/CustomPostProcessingVolume.template
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/Templates/CustomPostProcessingVolume.template.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing/CustomPostProcessInjectionPoint.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing/CustomPostProcessInjectionPoint.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing/CustomPostProcessVolumeComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing/CustomPostProcessVolumeComponent.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/IPostProcessComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.testing.hdrp/RP_Assets/HDRP_Test_Def.asset
Labels: HDRP

#4171 Minor Fixes
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/EmissionNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ExposureNode.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/universalUnlitPass.template
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/ColorNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
Labels: Shader Graph, bug-fix, needs-backport-7.1.x

#4511 Minor Fixes
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/EmissionNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/ExposureNode.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/universalUnlitPass.template
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/ColorNode.cs
  com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
Labels: Shader Graph

#4516 Fix issue with documentation link (need to point to a valid existing …
  com.unity.render-pipelines.core/Runtime/Documentation.cs
Labels: HDRP

#4244 Hdrp/staging pt
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/PathTracing.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/PathTracing/PathTracingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/PathTracing/PathTracingEditor.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/UnlitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/PathTracing.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/PathTracing.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingLight.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingLight.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingMain.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingMain.raytrace.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingMaterial.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingMaterial.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingSampling.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingFragInputs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPass.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassPathTracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassPathTracing.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineRayTracingResources.asset
Labels: HDRP, dxr

#4487 Adding 2D Pixel Perfect and Cinemachine extension pages
  com.unity.render-pipelines.universal/Documentation~/2DLightProperties.md
  com.unity.render-pipelines.universal/Documentation~/2d-index.md
  com.unity.render-pipelines.universal/Documentation~/2d-pixelperfect.md
  com.unity.render-pipelines.universal/Documentation~/HDREmulationScale.md
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_0.png
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_1.png
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_2.png
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_3.png
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_4.png
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_5.png
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_6.png
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_7.png
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_8.png
  com.unity.render-pipelines.universal/Documentation~/Images/2D_Pix_image_9.png
  com.unity.render-pipelines.universal/Documentation~/Images/cine_2Dpixelperfect_ex.png
  com.unity.render-pipelines.universal/Documentation~/LightBlendStyles.md
  com.unity.render-pipelines.universal/Documentation~/Lights-2D-intro.md
  com.unity.render-pipelines.universal/Documentation~/Setup.md
  com.unity.render-pipelines.universal/Documentation~/ShaderGraph.md
  com.unity.render-pipelines.universal/Documentation~/TableOfContents.md
  com.unity.render-pipelines.universal/Documentation~/pixel-cinemachine.md
Labels: Universal, docs, needs-backport-2019.3, needs-backport-7.1.x

#4521 fix custom postprocess bad init
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing/CustomPostProcessVolumeComponent.cs
Labels: HDRP

#4520 Using the right light type for defining if we need to compute directional ray traced shadows
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP, dxr

#4500 2d/bug fixes
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/Renderer2DMenus.cs
  com.unity.render-pipelines.universal/Editor/2D/ShadowCaster2DEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/SortingLayerDropDown.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Shaders/2D/Light2D-Point.shader
Labels: Universal

#4496 Fix ForwardRenderer stencil state being reset each frame
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/ForwardRendererData.cs
Labels: Universal, needs-backport-7.1.x

#4523 Remove blue book links tests
  com.unity.render-pipelines.core/Tests/Editor/DocumentationTests.cs
  com.unity.render-pipelines.core/Tests/Editor/DocumentationTests.cs.meta
  com.unity.render-pipelines.high-definition/Tests/Editor/DocumentationTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/DocumentationTests.cs.meta
Labels: HDRP

#4510 [DO NOT MERGE]Asset Upgrader fixes
  TestProjects/UniversalGfxTestStereo/Assets/CommonAssets/LightweightRenderPipelineAsset.asset
  TestProjects/UniversalGfxTestStereo/Assets/ForwardRenderer.asset
  TestProjects/UniversalGfxTestStereo/Assets/ForwardRenderer.asset.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ForwardRenderer.asset
  TestProjects/VisualEffectGraph_LWRP/Assets/ForwardRenderer.asset.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/LWRP.asset
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
Labels: Universal, high-priority, needs-backport-7.1.x

#4528 Fixing DXR bugs (Shader compil, lightmap fallback, volumetric scattering)
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
Labels: HDRP, dxr

#4468 Hdrp/scalable settings
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/QualitySettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDShadowInitParameters.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSetting.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSetting.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSettingValue.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSettingValue.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/ScalableSetting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/ScalableSetting.cs.meta
Labels: HDRP

#4440 Universal/bugfix/boat attack na ns
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/Packing.hlsl
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Artistic/Adjustment/HueNode.cs
Labels: Shader Graph

#4443 [Shader Graph] Enable Normal and Tangent Modification in Vertex (cross pipeline)
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/VertexAnimation.template.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/AssetCallbacks.meta
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes.meta
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/Varyings.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Interfaces.meta
  com.unity.render-pipelines.universal/Editor/ShaderGraph/MasterNodes/SpriteLitMasterNode.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/MasterNodes/SpriteUnlitMasterNode.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalPBRSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalSpriteLitSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalSpriteUnlitSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalUnlitSubShader.cs
  com.unity.shadergraph/Editor/Data/MasterNodes/PBRMasterNode.cs
  com.unity.shadergraph/Editor/Data/MasterNodes/UnlitMasterNode.cs
  com.unity.shadergraph/Editor/Templates/PassMesh.template.meta
Labels: HDRP, Shader Graph, Universal

#4527 Update fog documentation with new Fog volume component.
  com.unity.render-pipelines.high-definition/Documentation~/Atmospheric-Scattering.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VisualEnvironment1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricFog1.png
  com.unity.render-pipelines.high-definition/Documentation~/Override-Exponential-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Linear-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Visual-Environment.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog-Quality.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2019.2-to-2019.3.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumetric-Lighting.md
Labels: HDRP

#4533 Hdrp/staging
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting/LightScriptCreator.cs
  com.unity.render-pipelines.core/Tests/Editor/DocumentationTests.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/BloomEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/ChromaticAberrationEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/DepthOfFieldEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/MotionBlurEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDShaderUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/ScalableSettingLevelParameterEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/ScalableSettingLevelParameterEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/QualitySettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedFrameSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDShadowInitParameters.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSetting.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSetting.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSettingValue.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSettingValue.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedShadowResolutionSetting.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedShadowResolutionSetting.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedShadowResolutionSettingValue.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedShadowResolutionSettingValue.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/VolumeComponentWithQualityEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Bloom.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ChromaticAberration.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/DepthOfField.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/MotionBlur.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalPostProcessingQualitySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/ScalableSetting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/ScalableSetting.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Utilities/VolumeComponentWithQuality.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/DocumentationTests.cs
Labels: HDRP

#4435 Tests/sg/mirror once
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXEditor/Metal/ArtisticNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXEditor/Metal/InputNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXEditor/Metal/InputNodes.png.meta
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXEditor/Metal/MathNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXEditor/Metal/UVNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXEditor/Metal/UtilityNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/InputNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/InputNodes.png.meta
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/InputNodes.png
  TestProjects/ShaderGraph/Assets/Scenes/InputNodes.unity
  TestProjects/ShaderGraph/Assets/Testing/IntegrationTests/Graphs/Input/Texture/SamplerStateLinearMirrorOnceTexture2D.mat
  TestProjects/ShaderGraph/Assets/Testing/IntegrationTests/Graphs/Input/Texture/SamplerStateLinearMirrorOnceTexture2D.mat.meta
  TestProjects/ShaderGraph/Assets/Testing/IntegrationTests/Graphs/Input/Texture/SamplerStateLinearMirrorOnceTexture2D.shadergraph
  TestProjects/ShaderGraph/Assets/Testing/IntegrationTests/Graphs/Input/Texture/SamplerStateLinearMirrorOnceTexture2D.shadergraph.meta
Labels: Shader Graph

#4538 [Shader Graph] Fix 1182436
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/CodeGen/ShaderSpliceUtil.cs
  com.unity.shadergraph/Editor/Templates/PassMesh.template
Labels: Shader Graph, bug-fix

#4539 [Shader Graph] Fix 1182436
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/CodeGen/ShaderSpliceUtil.cs
  com.unity.shadergraph/Editor/Templates/PassMesh.template
Labels: Shader Graph, bug-fix

#4504 Expose Camera Capture
  com.unity.render-pipelines.core/Runtime/Utilities/CameraCaptureBridge.cs
Labels: HDRP

#4540 Fix failing runtime tests
  com.unity.render-pipelines.universal/Tests/Runtime/RuntimeTests.cs
Labels: Universal

#4543 Backport of (#4540) to 7.1.x
  com.unity.render-pipelines.universal/Tests/Runtime/RuntimeTests.cs
Labels: Universal

#4547 Fix case 1181335
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/EmissionUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitGUI.cs
Labels: HDRP

#4548 backporting 4544 redundant outer angle UI
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineLightEditor.cs
Labels: Universal

#4550 Urp/docs/toc reshuffle
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Documentation~/CreateNewProjectFromTemplate.md
  com.unity.render-pipelines.universal/Documentation~/EffectList.md
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/Bloom.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/BokehDepthOfField.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/ChannelMixer.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/ChromaticAberration.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/ColorAdjustments.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/ColorCurves.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/ColorLookup.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/FilmGrain.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/GaussianDepthOfField.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/LensDistortion.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/LiftGammaGain.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/MotionBlur.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/PaniniProjection.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/ShadowsMidtonesHighlights.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/SplitToning.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/Tonemapping.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/Vignette.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/Volume1.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/VolumeProfile.png
  com.unity.render-pipelines.universal/Documentation~/Images/Inspectors/WhiteBalance.png
  com.unity.render-pipelines.universal/Documentation~/InstallURPIntoAProject.md
  com.unity.render-pipelines.universal/Documentation~/InstallingAndConfiguringURP.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Channel-Mixer.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Color-Adjustments.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Color-Curves.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Film-Grain.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Lens-Distortion.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Lift-Gamma-Gain.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Motion-Blur.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Panini-Projection.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Shadows-Midtones-Highlights.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Split-Toning.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-White-Balance.md
  com.unity.render-pipelines.universal/Documentation~/TableOfContents.md
  com.unity.render-pipelines.universal/Documentation~/VolumeOverrides.md
  com.unity.render-pipelines.universal/Documentation~/VolumeProfile.md
  com.unity.render-pipelines.universal/Documentation~/Volumes.md
  com.unity.render-pipelines.universal/Documentation~/getting-started-with-universalrp.md
  com.unity.render-pipelines.universal/Documentation~/index.md
  com.unity.render-pipelines.universal/Documentation~/installing-universalrp-into-an-existing-project.md
  com.unity.render-pipelines.universal/Documentation~/integration-with-post-processing.md
  com.unity.render-pipelines.universal/Documentation~/rendering-in-universalrp.md
  com.unity.render-pipelines.universal/Documentation~/shader-stripping.md
  com.unity.render-pipelines.universal/Documentation~/shaders-in-universalrp.md
  com.unity.render-pipelines.universal/Documentation~/shading-model.md
  com.unity.render-pipelines.universal/Documentation~/simple-lit-shader.md
  com.unity.render-pipelines.universal/Documentation~/speedtree.md
  com.unity.render-pipelines.universal/Documentation~/universalrp-asset.md
  com.unity.render-pipelines.universal/Documentation~/universalrp-builtin-feature-comparison.md
  com.unity.render-pipelines.universal/Documentation~/unlit-shader.md
  com.unity.render-pipelines.universal/Documentation~/upgrading-your-shaders.md
Labels: Universal, docs, needs-backport-7.1.x

#4534 [Shader Graph] Delete Sticky Notes through Right Click menu
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Drawing/Views/StickyNote.cs
Labels: Shader Graph

#4515 [Shader Graph] Procedural Pattern Samples
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Documentation~/ShaderGraph-Samples.md
  com.unity.shadergraph/Documentation~/TableOfContents.md
  com.unity.shadergraph/Documentation~/images/PatternSamples_01.png
  com.unity.shadergraph/Documentation~/images/PatternSamples_02.png
  com.unity.shadergraph/Documentation~/images/Patterns_Page.PNG
  com.unity.shadergraph/Samples~/ProceduralPatterns/.sample.json
  com.unity.shadergraph/Samples~/ProceduralPatterns/Bacteria.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Bacteria.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/BacteriaSmoothstep.shadersubgraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/BacteriaSmoothstep.shadersubgraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Brick.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Brick.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Dots.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Dots.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Grid.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Grid.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Herringbone.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Herringbone.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Hex Lattice.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Hex Lattice.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Houndstooth.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Houndstooth.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Smooth Wave.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Smooth Wave.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Spiral.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Spiral.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Stripes.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Stripes.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Truchet.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Truchet.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Whirl.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Whirl.ShaderSubGraph.meta
  com.unity.shadergraph/Samples~/ProceduralPatterns/Zig Zag.ShaderSubGraph
  com.unity.shadergraph/Samples~/ProceduralPatterns/Zig Zag.ShaderSubGraph.meta
  com.unity.shadergraph/package.json
Labels: Shader Graph

#4552 Fix for flickering gizmos in matcap mode
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#4546 Incorrect type caching hd light
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4549 Area light emissive quad
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light/HDAdditionalLightDataEditorExtension.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#4563 Fixed an issue where updating an HDRP asset in the Quality setting panel would not recreate the pipeline.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
Labels: HDRP

#4553 [DXR] New Light Cluster Debug View + Fixes
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.shader.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RayTracingLightCluster.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RayTracingLightCluster.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineRayTracingResources.asset
Labels: HDRP, dxr

#4565 Hdrp/fix runtime test
  TestProjects/HDRP_RuntimeTests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/001-HDTemplate.png
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate.unity
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate/LightingData.asset
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate/Lightmap-0_comp_dir.png
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate/Lightmap-0_comp_light.exr
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate/ReflectionProbe-0.exr
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate/ReflectionProbe-1.exr
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate/ReflectionProbe-2.exr
  TestProjects/HDRP_RuntimeTests/ProjectSettings/QualitySettings.asset
Labels: HDRP

#4557 [Shader Graph] Fix cases #1183032 & #1183088
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/PBRForwardPass.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/Varyings.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalPBRSubShader.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Templates/PassMesh.template
Labels: Shader Graph, Universal, bug-fix, needs-backport-7.1.x

#4575 [Shader Graph] Fix cases #1183032 & #1183088
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/PBRForwardPass.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/Varyings.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalPBRSubShader.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Templates/PassMesh.template
Labels: Shader Graph, Universal, bug-fix

#4578 Fix for area lights counted as point lights for max count
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP

#4576 Don't process lights that are smaller than 1 px on screen
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP

#4581 Clamp factor that could lead to NaNs in Iridescence
  com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#4572 Avoid that inner spot percentage goes to NaN
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs
Labels: HDRP

#4570 Debug menu exposure fixes
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
Labels: HDRP, dxr

#4569 Fix for decal not fully patching the normal buffer
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalNormalBuffer.shader
Labels: HDRP

#4564 DXR UI and Fixes
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
Labels: HDRP, dxr

#4551 Fix lit transparent refraction with XR single-pass rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
Labels: HDRP, XR

#4554 Using the "Cast Shadow" member when building the ray tracing acceleration structure
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
Labels: HDRP, dxr

#4555 Do not add extra jitter in VR for TemporalAA
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, XR

#4463 Fix Fog with URP & VFX
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.unity
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.unity.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.vfx
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.vfx.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/100_Fog.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/100_Fog.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/100_Fog.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/100_Fog.png.meta
  TestProjects/VisualEffectGraph_LWRP/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Shaders/RenderPipeline/Universal/VFXCommon.hlsl
Labels: Universal, vfx

#4583 Added Save As functionality
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
  com.unity.shadergraph/Editor/Data/Implementation/Edge.cs
  com.unity.shadergraph/Editor/Data/Interfaces/Graph/SlotReference.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Importers/ShaderGraphAssetPostProcessor.cs
  com.unity.shadergraph/Editor/Util/FileUtilities.cs
Labels: Shader Graph

#4606 Restore usage of ENABLE_VR to fix compilation errors on some platforms
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
Labels: HDRP, XR

#4608 Moving some controls over to the custom GUI and adding LOD toggles to the node...
  com.unity.render-pipelines.high-definition/Editor/Material/SpeedTreeLit/ShaderGraph/SpeedTreeLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/SpeedTreeLit/ShaderGraph/SpeedTreeLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/SpeedTreeLit/ShaderGraph/SpeedTreeLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/SpeedTreeLit/ShaderGraph/SpeedTreeLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/SpeedTreeLitOptionsUIBlock.cs
Labels: HDRP, Shader Graph

#4623 [Shader Graph] Fix 1184621
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
Labels: Shader Graph, bug-fix

#4532 [Shader Graph] Add Rounded Polygon Node
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXEditor/Metal/ProceduralNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/OSXEditor/Metal/ProceduralNodes.png.meta
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/ProceduralNodes.png
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/ProceduralNodes.png.meta
  TestProjects/ShaderGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/ProceduralNodes.png
  TestProjects/ShaderGraph/Assets/Scenes/ProceduralNodes.unity
  TestProjects/ShaderGraph/Assets/Testing/IntegrationTests/Graphs/Procedural/Shape/Rounded Polygon.mat
  TestProjects/ShaderGraph/Assets/Testing/IntegrationTests/Graphs/Procedural/Shape/Rounded Polygon.mat.meta
  TestProjects/ShaderGraph/Assets/Testing/IntegrationTests/Graphs/Procedural/Shape/Rounded Polygon.shadergraph
  TestProjects/ShaderGraph/Assets/Testing/IntegrationTests/Graphs/Procedural/Shape/Rounded Polygon.shadergraph.meta
  com.unity.shadergraph/Documentation~/Procedural-Nodes.md
  com.unity.shadergraph/Documentation~/Rounded-Polygon-Node.md
  com.unity.shadergraph/Documentation~/TableOfContents.md
  com.unity.shadergraph/Documentation~/images/RoundedPolygonNodeThumb.png
  com.unity.shadergraph/Editor/Data/Nodes/Procedural/Shape/RoundedPolygonNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Procedural/Shape/RoundedPolygonNode.cs.meta
Labels: Shader Graph

#4536 [Shader Graph] Toggle Precision on all selected nodes
  TestProjects/ShaderGraph/Assets/Testing/IntegrationTests/Graphs/Procedural/Shape/RoundedRectangle.shadergraph
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
Labels: Shader Graph

#4595 [Shader Graph] Fix 5 HUP Bugs for Sub Graphs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/Util/KeywordUtil.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.3

#4624 [19.3 Backport][Shader graph] Fix 5 HUP Bugs for sub graphs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Utility/SubGraphNode.cs
  com.unity.shadergraph/Editor/Data/Util/KeywordUtil.cs
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
Labels: Shader Graph, backported-2019.3, bug-fix

#4387 [2019.2/lw][XR] enable Android postprocessing using single-pass double-wide stereo mode
  com.unity.render-pipelines.core/package.json
  com.unity.render-pipelines.high-definition/package.json
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/package.json
  com.unity.shadergraph/package.json
  com.unity.testframework.graphics/package.json
  com.unity.visualeffectgraph/package.json
Labels: Universal

#4594 Fix ShaderGraph SceneDepth node with XR single-pass (double-wide)
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/ShaderLibrary/ShaderGraphFunctions.hlsl
Labels: Universal, XR, needs-backport-2019.1, needs-backport-2019.2, needs-backport-2019.3

#4512 Restored missing terrain holes fragments for universal shaders
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Documentation~/universalrp-asset.md
  com.unity.render-pipelines.universal/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitAdd.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBase.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: Universal

#4589 UI UX Camera for Universal
  TestProjects/UniversalGraphicsTest/Assets/Scenes/015_CameraMulti_FPSCam.unity
  com.unity.render-pipelines.universal/Editor/ForwardRendererDataEditor.cs
  com.unity.render-pipelines.universal/Editor/Gizmos.meta
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_Base.png
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_Base.png.meta
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_Offscreen.png
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_Offscreen.png.meta
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_Overlay.png
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_Overlay.png.meta
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_PostProcessing.png
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_PostProcessing.png.meta
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_UI.png
  com.unity.render-pipelines.universal/Editor/Gizmos/Camera_UI.png.meta
  com.unity.render-pipelines.universal/Editor/ShaderGUI/BaseShaderGUI.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineLightEditor.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/ScriptableRenderPass.cs
  com.unity.render-pipelines.universal/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.universal/Runtime/ShadowUtils.cs
  com.unity.render-pipelines.universal/Runtime/UniversalAdditionalCameraData.cs
Labels: Universal, backported-2019.3

#4451 Universal/multiple directional lights
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Documentation~/universalrp-builtin-feature-comparison.md
  com.unity.render-pipelines.universal/Runtime/ForwardLights.cs
  com.unity.render-pipelines.universal/Runtime/Passes/AdditionalLightsShadowCasterPass.cs
  com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl
Labels: Universal, needs-backport-2019.3

#4531 Hdrp/add dxr template scene
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/DefaultSceneRoot.prefab
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/DefaultSceneRoot.prefab.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/Scene PostProcess Profile.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/Scene PostProcess Profile.asset.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/Sky and Fog Settings Profile.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/Sky and Fog Settings Profile.asset.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDProjectSettings.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDSceneManagement.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.UIElement.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
  com.unity.render-pipelines.high-definition/Editor/USS/Wizard.uss
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
Labels: HDRP, dxr

#4637 Adding a warning message when ray tracing is enabled on the asset and the platform does not support it
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
Labels: HDRP, dxr

#4634 Hdrp/fix/alpha cutoff ui
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/HDShaderGUI.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/Upgraders/UpgradeMenuItem.cs
  com.unity.testing.hdrp/Scripts/Editor/ResetShaderGraphMaterialProperties.cs
Labels: HDRP

#4633 Fixed an issue where building a player in non-dev mode would generate render target error logs every frame
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP

#4628 Restored proper test for IsRegularPreview
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#4629 Expose light utils and doc
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightUtils.cs
Labels: HDRP

#4619 Added default settings window docs
  com.unity.render-pipelines.high-definition/Documentation~/Default-Settings-Window.md
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/FrameSettings1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/RayTracedAmbientOcclusion3.png
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Bloom.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Ambient-Occlusion.md
Labels: HDRP, docs, needs-backport-2019.3

#4618 Refresh cached shadow on editor changes
  com.unity.render-pipelines.high-definition-config/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4607 Fix custom pass API
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassRenderersShader.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/FullScreenCustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/CustomPass/DefaultRenderer.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP

#4600 Fix issue introduced with decal roughness blend
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalNormalBuffer.shader
Labels: HDRP

#4604 Fix typo in HDRP Asset missing message
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessBuild.cs
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
Labels: HDRP

#4652 Fixed shader compilations errors caused by ShaderGraph refactor.
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/BakedLitMetaPass.hlsl
  com.unity.render-pipelines.universal/Shaders/UnlitMetaPass.hlsl
Labels: Universal

#4649 light.light can be null for shuriken particles with light module
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, bug-fix

#4653 Fixed format issue
  com.unity.render-pipelines.high-definition/Documentation~/Layered-Lit-Shader.md
Labels: HDRP, docs, needs-backport-2019.3

#4660 [Shader Graph] Fix 1184637 NUnit reference
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/CodeGen/GraphCompilationResult.cs
Labels: Shader Graph, bug-fix, needs-backport-2019.3

#4655 Incorrect type caching hd light
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4658 fix SRP Batcher shader compatibility issue in dots shooter
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/CodeGen/PropertyCollector.cs
Labels: Shader Graph

#4654 Fixed an issue where SSAO (that needs temporal reprojection) was still being rendered when Motion Vectors were not available
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
Labels: HDRP

#4659 FIx the layered option height map options in the material UI
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/LayersUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/LitSurfaceInputsUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/MaterialUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/MaterialUIBlockList.cs
Labels: HDRP, needs-backport-2019.2

#4651 Hdrp/fix decal pivot
  com.unity.render-pipelines.core/Editor/Gizmo/HierarchicalBox.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs
Labels: HDRP, needs-backport-2019.3

#4627 Fixed an issue where using the LightingOverrideMask would break sky reflection for regular cameras
  com.unity.render-pipelines.core/Runtime/Volume/VolumeManager.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#4630 Forcing the ray traced shadow to be black when the area light is in the bottom hemisphere created by the normal
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingMIS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
Labels: HDRP, dxr

#4622 Universal/postprocessing load actions
  com.unity.render-pipelines.universal/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Shaders/PostProcessing/GaussianDepthOfField.shader
Labels: Universal

#4611 Fix Fog with URP & VFX (backport to 2019.3)
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.unity
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.unity.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.vfx
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.vfx.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/100_Fog.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/100_Fog.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/100_Fog.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/100_Fog.png.meta
  TestProjects/VisualEffectGraph_LWRP/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Shaders/RenderPipeline/Universal/VFXCommon.hlsl
Labels: Universal, vfx

#4612 Fix Fog with URP & VFX (backport to 7.1.x)
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.unity
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.unity.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.vfx
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.vfx.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/100_Fog.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/100_Fog.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/100_Fog.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/100_Fog.png.meta
  TestProjects/VisualEffectGraph_LWRP/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Shaders/RenderPipeline/Universal/VFXCommon.hlsl
Labels: Universal, vfx

#4663 Vfx/2019.3 staging
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/ParticleRibbonLit.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/ParticleStripUnlit.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/ParticleRibbonLit.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/ParticleStripUnlit.png
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXAbstractParticleOutput.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXAbstractRenderedOutput.cs
  com.unity.visualeffectgraph/Editor/ShaderGraph/VFXShaderGraphParticleOutput.cs
  com.unity.visualeffectgraph/Shaders/ParticlePlanarPrimitives/PassVS.template
  com.unity.visualeffectgraph/Shaders/VFXUpdate.template
Labels: vfx

#4671 Fixed a compilation issue on PS4 with the Bokeh Depth of Field shader
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/PostProcessing/BokehDepthOfField.shader
Labels: Universal, backported-2019.3

#4632 Fix an issue where hdrp decal shaders were incorrectly skipped at runtime
  TestProjects/HDRP_RuntimeTests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/001-HDTemplate.png
  TestProjects/HDRP_RuntimeTests/Assets/Scenes/001-HDTemplate.unity
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
Labels: HDRP

#4639 Edit HDRP documentation for VR
  com.unity.render-pipelines.high-definition/Documentation~/VR-in-HDRP.md
Labels: HDRP, XR, docs

#4674 Ray tracing format fixes
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Environment.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Getting-Started.md
Labels: HDRP, docs

#4638 Add an animation section to the light component doc
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
Labels: HDRP, docs

#4573 Ray tracing support for VR single-pass
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ShaderVariablesLightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAODenoise.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadows.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDDiffuseDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDSimpleDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/CountTracedRays.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/DiffuseDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, XR, dxr

#4678 [LookDev] Fix assignation of New Library after creation with "new" button
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.EnvironmentLibrarySidePanel.cs
  com.unity.render-pipelines.core/Editor/LookDev/EnvironmentLibrary.cs
Labels: HDRP, needs-backport-2019.3

#4669 Hdrp/various UI fixes
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedHDProbe.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/Volume/InfluenceVolumeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Drawer.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/VolumetricLighting/DensityVolumeUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Builtin/BuiltinData.cs
Labels: HDRP, needs-backport-2019.3

#4672 Improved color buffer history allocations
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP

#4605 Fix for not all UI fields in the async compute tab fitting correctly
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
Labels: HDRP

#4686 Fix light layers scripting api
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9500_LightScripting/LightScriptCreator.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4683 Hdrp/fix planar probe preview initialisation
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
Labels: HDRP, needs-backport-2019.2, needs-backport-2019.3

#4666 Expose TAA sharpen strength
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/SerializedHDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntiAliasing.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP, XR, needs-backport-2019.3

#4696 Fixed an issue where SSR would use an incorrect roughness value on Fo…
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.2, needs-backport-2019.3

#4687 Fix crash on invalid JSON
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
  com.unity.shadergraph/Editor/Importers/ShaderSubGraphImporter.cs
Labels: Shader Graph, bug-fix

#4719 Forcing the ray tracing resources to null when ray tracing is disabled (to exclude the resources)
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RayTracingShaderPreprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RayTracingShaderPreprocessor.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, dxr

#4599 Using Opaque Meshes for Ambient Occlusion and moving the instance flags to an enum
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingMain.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassPathTracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl
Labels: HDRP, dxr

#4689 Fixing shader warnings
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/DiffuseDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingMIS.hlsl
Labels: HDRP, dxr

#4598 Clearing the directional screen space shadow (fixes a bug with ray traced shadows)
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, dxr

#4690 New frame not called on the area light cookie manager
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/LTCAreaLightCookieManager.cs
Labels: HDRP, dxr

#4697 Fixing a bug in the ray binning code and Implementing half resolution RTGI
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIllumination.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.compute
Labels: HDRP, dxr

#4602 Implementing Ray Traced Shadows for Spot Cone Lights
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/SphericalCone.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/SphericalCone.hlsl.meta
Labels: HDRP, dxr

#4681 HDRP Light explorer fixes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
Labels: HDRP

#4698 Hdrp/fix layerlist
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/MaterialHeaderScope.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/LayerListUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/LayerListUIBlock.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/LayeringOptionsUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/LayersUIBlock.cs
Labels: HDRP, needs-backport-2019.3

#4700 Don't render gizmos in render textures
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#4704 Fix disable light emissive mesh
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Light/HDAdditionalLightDataEditorExtension.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP, needs-backport-2019.3

#4706 Fix Light layers light scripting
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP
