Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-08, with the labels that each got.

#4261 Fix MetaInput.hlsl typo generating shader error
  com.unity.render-pipelines.lightweight/ShaderLibrary/MetaInput.hlsl
Labels: Universal

#4251 Access vertex tangents in 2D shaders
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/056_2D_Lights.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/056_2D_Lights_Shader_Graph.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/056_2D_Lights.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/056_2D_Lights_Shader_Graph.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/056_2D_Lights.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/056_2D_Lights_Shader_Graph.png
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalSpriteLitSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/universalSpriteNormalPass.template
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Lit-Default.shader
Labels: Universal

#4272 Universal Improve tests
  TestProjects/LWGraphicsTest/Assets/Lights.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/001_SimpleCube.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/045_CustomLWPipe/CustomLWPipe.cs
  TestProjects/UniversalGraphicsTest/Assets/Scenes/045_CustomLWPipe/CustomRenderGraphData.cs
  TestProjects/UniversalGraphicsTest/Assets/Scripts.meta
  TestProjects/UniversalGraphicsTest/Assets/Scripts/Editor.meta
  TestProjects/UniversalGraphicsTest/Assets/Scripts/Editor/CustomBuild.cs
  TestProjects/UniversalGraphicsTest/Assets/Scripts/Editor/CustomBuild.cs.meta
  TestProjects/UniversalGraphicsTest/Assets/Scripts/Runtime.meta
  TestProjects/UniversalGraphicsTest/Assets/Scripts/Runtime/GotoNextScene.cs
  TestProjects/UniversalGraphicsTest/Assets/Scripts/Runtime/GotoNextScene.cs.meta
  TestProjects/UniversalGraphicsTest/Assets/Test.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/SetupGraphicsTestCases.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/SetupGraphicsTestCases.cs.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/SetupProject.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/SetupProject.cs.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/Unity.Testing.SRP.Universal.Editor.asmdef
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/Unity.Testing.SRP.Universal.Editor.asmdef.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/ArrayDrawer.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/ArrayDrawer.cs.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CameraCallbackTests.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CameraCallbackTests.cs.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CustomRenderPipeline.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CustomRenderPipeline/CustomRenderGraph.asset
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CustomRenderPipeline/CustomRenderGraph.asset.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CustomRenderPipeline/CustomRenderGraphData.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CustomRenderPipeline/CustomRenderGraphData.cs.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CustomRenderPipeline/CustomRenderer.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CustomRenderPipeline/CustomRenderer.cs.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/Unity.Testing.SRP.Universal.Runtime.asmdef
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/Unity.Testing.SRP.Universal.Runtime.asmdef.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/UniversalGraphicsTestSettings.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/UniversalGraphicsTestSettings.cs.meta
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/UniversalGraphicsTests.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/UniversalGraphicsTests.cs.meta
  TestProjects/UniversalGraphicsTest/ProjectSettings/GraphicsSettings.asset
  TestProjects/UniversalGraphicsTest/ProjectSettings/InputManager.asset
  TestProjects/UniversalGraphicsTest/ProjectSettings/ProjectSettings.asset
  com.unity.render-pipelines.universal/Runtime/RenderingUtils.cs
Labels: Universal

#4254 Add pass for invoking OnRenderObjectCallback in forward renderer
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/InvokeOnRenderObjectCallbackPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/InvokeOnRenderObjectCallbackPass.cs.meta
Labels: Universal, bug-fix

#4279 Fix compilation of rendergraphUtils
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraphUtils.cs
Labels: HDRP

#4263 Hdrp docs additions
  com.unity.render-pipelines.high-definition/Documentation~/Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Creating-and-Editing-HDRP-Shader-Graphs.md
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Projector.md
  com.unity.render-pipelines.high-definition/Documentation~/Environment-Lighting.md
  com.unity.render-pipelines.high-definition/Documentation~/Glossary.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Camera.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/CreatingAndEditingHDRPShaderGraphs1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/DecalProjector3.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/DecalProjector4.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/DecalProjector5.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/GettingStarted1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDev1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDev2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDev3.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDev4.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDev5.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDev6.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDev7.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDev8.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDev9.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDevEnvironmentLibrary1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDevEnvironmentLibrary2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDevEnvironmentLibrary3.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDevEnvironmentLibrary4.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LookDevEnvironmentLibrary5.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/OverrideAmbientOcclusion1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Post-ProcessingDepthOfField2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/VolumeComponents1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Volumes1.png
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Look-Dev-Environment-Library.md
  com.unity.render-pipelines.high-definition/Documentation~/Look-Dev.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Gradient-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-HDRI-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Procedural-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Depth-of-Field.md
  com.unity.render-pipelines.high-definition/Documentation~/Surface-Type.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-HDRP-Between-Major-Versions.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2019.1-to-2019.2.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2019.2-to-2019.3.md
  com.unity.render-pipelines.high-definition/Documentation~/VR-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Volume-Components.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumes.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.Skin.cs
Labels: HDRP, docs

#4252 Precomputed velocity
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/AxF/AxFGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/AdvancedOptionsUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/ShaderGraphUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitGUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/MotionVectorVertexShaderCommon.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/MasterNodes/UnlitMasterNode.cs
Labels: HDRP

#4243 Hdrp/wizard fix code loop 2
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/RenderPipelineWizard1.png
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Wizard.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDProjectSettings.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDRPWizard.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDSceneManagement.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.UIElement.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.UIElement.cs.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/QualitySettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/USS.meta
  com.unity.render-pipelines.high-definition/Editor/USS/Formating.uss
  com.unity.render-pipelines.high-definition/Editor/USS/Formating.uss.meta
  com.unity.render-pipelines.high-definition/Editor/USS/QualitySettings.uss
  com.unity.render-pipelines.high-definition/Editor/USS/QualitySettings.uss.meta
  com.unity.render-pipelines.high-definition/Editor/USS/QualitySettingsDark.uss
  com.unity.render-pipelines.high-definition/Editor/USS/QualitySettingsDark.uss.meta
  com.unity.render-pipelines.high-definition/Editor/USS/QualitySettingsLight.uss
  com.unity.render-pipelines.high-definition/Editor/USS/QualitySettingsLight.uss.meta
  com.unity.render-pipelines.high-definition/Editor/USS/Wizard.uss
  com.unity.render-pipelines.high-definition/Editor/USS/Wizard.uss.meta
  com.unity.render-pipelines.high-definition/Editor/USS/WizardDark.uss
  com.unity.render-pipelines.high-definition/Editor/USS/WizardDark.uss.meta
  com.unity.render-pipelines.high-definition/Editor/USS/WizardLight.uss
  com.unity.render-pipelines.high-definition/Editor/USS/WizardLight.uss.meta
  com.unity.render-pipelines.high-definition/Editor/Upgraders/UpgradeStandardShaderMaterials.cs
Labels: HDRP

#4194 Hdrp/reduce garbage collection
  com.unity.render-pipelines.core/Editor/Volume/VolumeEditor.cs
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.core/Runtime/Volume/VolumeParameter.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolumeManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDCustomSamplerId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDGPUAsyncTask.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
Labels: HDRP

#4284 Backport of AO History fix
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/BufferedRTHandleSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
Labels: HDRP

#4281 Reduce the size of the thread group of ComputeGgxIblSampleData
  com.unity.render-pipelines.high-definition/Runtime/Material/GGXConvolution/ComputeGgxIblSampleData.compute
Labels: HDRP, needs-backport-2019.2

#4287 Fix two issue regarding shader stripper and contact shadow on mac.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
Labels: HDRP, needs-backport-2019.2

#4280 Rename AdditionalVeclocityChange to AddPrecomputeVelocity
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/AxF/AxFGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/AdvancedOptionsUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/ShaderGraphUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitGUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/MotionVectorVertexShaderCommon.hlsl
  com.unity.shadergraph/Editor/Data/MasterNodes/UnlitMasterNode.cs
Labels: HDRP

#4291 More garbage collection fixes
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.testframework.graphics/Runtime/ImageAssert.cs
Labels: HDRP

#4290 Camera callback for custom render
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.2

#4242 Add ParticleSystem Shader Samples
  com.unity.render-pipelines.high-definition/Samples~/ParticleSystemShaderSamples/.sample.json
  com.unity.render-pipelines.high-definition/Samples~/ParticleSystemShaderSamples/ParticleSystemShaderSamples.unitypackage
  com.unity.render-pipelines.high-definition/Samples~/ParticleSystemShaderSamples/ParticleSystemShaderSamples.unitypackage.meta
  com.unity.render-pipelines.high-definition/package.json
Labels: HDRP

#4266 Sg/19.2 update documentation
  com.unity.shadergraph/Documentation~/Blackboard.md
  com.unity.shadergraph/Documentation~/Color-Modes.md
  com.unity.shadergraph/Documentation~/Create-Node-Menu.md
  com.unity.shadergraph/Documentation~/Create-Shader-Graph.md
  com.unity.shadergraph/Documentation~/Data.md
  com.unity.shadergraph/Documentation~/First-Shader-Graph.md
  com.unity.shadergraph/Documentation~/Getting-Started.md
  com.unity.shadergraph/Documentation~/Shader-Graph-Window.md
  com.unity.shadergraph/Documentation~/Shader-Graph.md
  com.unity.shadergraph/Documentation~/TableOfContents.md
  com.unity.shadergraph/Documentation~/images/Blackboard.png
  com.unity.shadergraph/Documentation~/images/MainPreview.png
  com.unity.shadergraph/Documentation~/images/MasterNode.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_01.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_02.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_03.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_04.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_05.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_06.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_07.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_08.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_09.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_10.png
  com.unity.shadergraph/Documentation~/images/MyFirstShaderGraph_11.png
  com.unity.shadergraph/Documentation~/images/ShaderGraphWindow.png
  com.unity.shadergraph/Documentation~/index.md
Labels: Shader Graph, docs

#4268 Fix grouping for selected nodes
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph

#4292 Update screenshots after C++ change
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1217_Lit_SSS_Pre-Post.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1217_Lit_SSS_Pre-Post.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1301_StackLitSG.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1301_StackLitSG.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardBoth.png.meta
  TestProjects/HDRP_Tests/Packages/manifest.json
  TestProjects/HDRP_Tests/ProjectSettings/QualitySettings.asset
Labels: HDRP

#4296 Update integration-with-post-processing.md
  com.unity.render-pipelines.lightweight/Documentation~/integration-with-post-processing.md
Labels: needs-backport-2019.2

#4283 [2D] Fix Sprite Mask, Frame Debugger
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderGraph/universalSpriteLitPass.template
  com.unity.render-pipelines.universal/Editor/ShaderGraph/universalSpriteNormalPass.template
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Lit-Default.shader
Labels: Universal, needs-backport-2019.2

#4295 DXR Macro and FrameSetting
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, dxr

#4303 Hdrp/new cached atlas placement post pooling
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#4156 Use UAV API properly for TAA
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/CopyTAAHistory.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/CopyTAAHistory.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntiAliasing.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#4306 Add experimental eye material (useless for now)
  com.unity.render-pipelines.high-definition/Editor/Material/Eye.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/CreateEyeShaderGraph.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/CreateEyeShaderGraph.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeGUI.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyePass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyePass.template.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeSettingsView.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeSubShader.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/IEyeSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/IEyeSubShader.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.hlsl.meta
Labels: HDRP

#4297 Fixed resource reloader error
  com.unity.render-pipelines.universal/Runtime/ForwardRendererData.cs
Labels: Universal

#4234 Universal RP fix for issue #1161116
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/038_Shader_TerrainBlend.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/038_Shader_TerrainBlend.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/038_Shader_TerrainBlend.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/038_Shader_TerrainBlend.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/038_Shader_TerrainBlend.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/038_Shader_TerrainBlend.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/038_Shader_TerrainBlend.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/038_Shader_TerrainBlend.png.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend.unity.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer01.terrainlayer
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer01.terrainlayer.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer02.terrainlayer
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer02.terrainlayer.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer03.terrainlayer
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer03.terrainlayer.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer04.terrainlayer
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer04.terrainlayer.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer05.terrainlayer
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer05.terrainlayer.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer06.terrainlayer
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/Layer06.terrainlayer.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/LayerTestTerrain.asset
  TestProjects/UniversalGraphicsTest/Assets/Scenes/038_Shader_TerrainBlend/LayerTestTerrain.asset.meta
  TestProjects/UniversalGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBasemapGen.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitInput.hlsl
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: Universal

#4312 Moving the test of ray tracing support out of editor scope
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
Labels: HDRP, dxr

#4267 fix case 1140924 system locale in gradient node
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Util/GradientUtil.cs
Labels: Shader Graph

#4314 Fix issue on null volume params
  com.unity.render-pipelines.core/Runtime/Volume/VolumeParameter.cs
Labels: HDRP

#4305 Added test 5007_Exponential_Fog
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_ExponentialFog.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_ExponentialFog.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog1.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog1.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog2.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog2.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog3.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog3.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog4.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog4.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog5.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog5.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog6.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_ExponentialFog/5007_NoFog6.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_Exponential_Fog.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5007_Exponential_Fog.unity.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5007_Exponential_Fog.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5007_Exponential_Fog.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#4320 Backport #3986 and #4050 (fix map cap issue with axf)
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Def.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Def_MSAABoth.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Def_MSAAForward.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_FabricConvolutionOn.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Common/RP_Assets/HDRP_Test_Fwd_Shadow_VeryHigh.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2210_ReflectionProbes_CaptureAtVolumeAnchor.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1219_Lit_Light_on_Tesselation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1219_Lit_Light_on_Tesselation.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/PBRValidator.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP

#4321 Fix axf decal
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxFData.hlsl
Labels: HDRP

#4318 Fix reflection probe with XR single-pass and FPTL
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild.compute
Labels: HDRP, XR

#4345 Universal/backport/post processing sceneview
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal

#4304 Fix clearing issue in BoatAttack.
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/008_AdditionalLights.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/008_AdditionalLights.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/008_AdditionalLights.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/008_AdditionalLights.png
  TestProjects/UniversalGraphicsTest/Assets/Scenes/008_AdditionalLights.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/008_AdditionalLights/LightingData.asset
  TestProjects/UniversalGraphicsTest/Assets/Scenes/008_AdditionalLights/LightingData.asset.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/008_AdditionalLights/ReflectionProbe-0.exr
  TestProjects/UniversalGraphicsTest/Assets/Scenes/008_AdditionalLights/ReflectionProbe-0.exr.meta
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/VolumeBlendingPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/VolumeBlendingPass.cs.meta
  com.unity.render-pipelines.universal/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.universal/ShaderLibrary/UnityInput.hlsl
  com.unity.testing.visualeffectgraph/Scenes/005_PlanarPrimitives.unity
  com.unity.testing.visualeffectgraph/Tests/Runtime/Unity.Testing.VisualEffectGraph.Tests.asmdef
  com.unity.testing.visualeffectgraph/Tests/Runtime/VFXGraphicsTests.cs
Labels: Universal

#4300 Manully backported #4283.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightSpriteLitPass.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightSpriteNormalPass.template
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Lit-Default.shader
Labels: Universal

#4348 7.0.2 version update
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/package.json
  com.unity.render-pipelines.high-definition-config/CHANGELOG.md
  com.unity.render-pipelines.high-definition-config/package.json
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/package.json
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/package.json
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/package.json
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/package.json
  com.unity.testframework.graphics/CHANGELOG.md
  com.unity.testframework.graphics/package.json
  com.unity.testing.visualeffectgraph/package.json
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/package.json
Labels: HDRP, SRP, Shader Graph, Universal, vfx

#4350 [Bugfix 1136285]Fixed issue ParticleLit when used with Soft Particles and HDR
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/Particles/ParticlesLitInput.hlsl
Labels: Universal, needs-backport-2019.2, needs-backport-2019.3

#4353 [2019.2] Fix InputView freeze
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph, bug-fix, high-priority

#4349 [Universal RP] bugfix 1175396
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/ScriptableRenderer.cs
Labels: Universal, needs-backport-2019.2, needs-backport-2019.3

#4359 Fixing the UI for directional light screen space shadow
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP, dxr

#4238 Universal/fix case 1163320
  TestProjects/UniversalGraphicsTest/Assets/Scenes/079_GradingColorAdjustmentsLDR.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/091_TonemappingNeutralLDR.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/093_TonemappingACESLDR.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/100_BloomHDR.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/102_SMAA.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/103_GaussianDepthOfField.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/104_BokehDepthOfField.unity
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderPreprocessor.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipelineCore.cs
  com.unity.render-pipelines.universal/Shaders/PostProcessing/FinalPost.shader
  com.unity.render-pipelines.universal/Shaders/PostProcessing/UberPost.shader
  com.unity.testframework.graphics/Runtime/ImageAssert.cs
  com.unity.testframework.graphics/Runtime/ImageComparisonSettings.cs
Labels: Universal

#4352 Universal/fix zero length computebuffer
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/044_Lighting_ReflectionProbe.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/044_Lighting_ReflectionProbe.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/008_AdditionalLights.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/008_AdditionalLights.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/044_Lighting_ReflectionProbe.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/044_Lighting_ReflectionProbe.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/044_Lighting_ReflectionProbe.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/044_Lighting_ReflectionProbe.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/044_Lighting_ReflectionProbe.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/044_Lighting_ReflectionProbe.png.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/044_Lighting_ReflectionProbe.unity
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/005_PlanarPrimitives.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/005_PlanarPrimitives.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/005_PlanarPrimitives.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/005_PlanarPrimitives.png.meta
  com.unity.render-pipelines.universal/Runtime/ForwardLights.cs
  com.unity.render-pipelines.universal/Runtime/RenderingUtils.cs
  com.unity.render-pipelines.universal/ShaderLibrary/Input.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.testing.visualeffectgraph/Scenes/005_PlanarPrimitives.unity
Labels: Universal

#4313 Single-pass instancing support for XR SDK
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs
  com.unity.render-pipelines.core/Runtime/Unity.RenderPipelines.Core.Runtime.asmdef
  com.unity.render-pipelines.core/package.json
  com.unity.render-pipelines.high-definition-config/package.json
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Unity.RenderPipelines.HighDefinition.Runtime.asmdef
  com.unity.render-pipelines.high-definition/Tests/Editor/XRSystemTests.cs
  com.unity.render-pipelines.high-definition/package.json
  com.unity.render-pipelines.lightweight/package.json
  com.unity.render-pipelines.universal/package.json
  com.unity.shadergraph/package.json
  com.unity.testframework.graphics/package.json
  com.unity.testing.visualeffectgraph/package.json
  com.unity.visualeffectgraph/package.json
Labels: HDRP, SRP, XR

#4378 Improving the ray counters & others
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.raytrace.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
Labels: HDRP, dxr

#4381 Fixing the problems related to alpha cutoff in ray tracing
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracingData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingVisibility.hlsl
Labels: HDRP, dxr

#4192 Added an Update virtual call to SkyRenderer class
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky/ProceduralSkyRenderer.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs
Labels: HDRP

#4331 Fix exposure mismatch between baking and frame rendering
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5004_Pbr_Sky_High_Altitude.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5005_Pbr_Sky_Med_Altitude.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/5x_SkyAndFog/5006_Pbr_Sky_Low_Altitude.unity
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky/PhysicallyBasedSkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader
Labels: HDRP

#4333 Hdrp/lit shaders doc correction
  com.unity.render-pipelines.high-definition/Documentation~/Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Ambient-Occlusion.md
Labels: HDRP, docs

#4356 Fix emission node exposure weight label
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/EmissionNode.cs
Labels: HDRP

#4358 Hdrp/fix gizmo enabled on selecting camera
  com.unity.render-pipelines.core/Editor/CameraEditorUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP

#4364 Rename some code to XR single-pass instead of stereo
  com.unity.render-pipelines.core/Runtime/Textures/TextureXR.cs
  com.unity.render-pipelines.core/ShaderLibrary/Filtering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugViewTiles.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/Exposure.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, XR

#4365 Add XR settings to HDRP asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedXRSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedXRSettings.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/scrbound.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/GlobalXRSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/GlobalXRSettings.cs.meta
Labels: HDRP, XR

#4368 HDRP/docs/Updating the getting started doc.
  com.unity.render-pipelines.high-definition/Documentation~/Getting-started-with-HDRP.md
Labels: HDRP, docs

#4372 Hdrp/various fix ui light
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP

#4383 Fixing a pre-exposure issue with ray traced reflections
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.raytrace
Labels: HDRP, dxr

#4386 [6.9.x] Fix InputView freeze
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph, bug-fix, high-priority

#4339 Universal new light gizmos
  com.unity.render-pipelines.core/Editor/Lighting/CoreLightEditorUtilities.cs
  com.unity.render-pipelines.core/Editor/Lighting/CoreLightEditorUtilities.cs.meta
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineLightEditor.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal

#4357 Universal/fix null reference shaders
  com.unity.render-pipelines.universal/Editor/MaterialPostprocessor.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
Labels: Universal, needs-backport-2019.3

#4309 Universal/docs/post processing docs
  com.unity.render-pipelines.universal/Documentation~/2d-index.md
  com.unity.render-pipelines.universal/Documentation~/Images/AssetShots/Beauty/SceneWithPost.png
  com.unity.render-pipelines.universal/Documentation~/Images/AssetShots/Beauty/SceneWithoutPost.png
  com.unity.render-pipelines.universal/Documentation~/LightBlendStyles.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Channel-Mixer.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Color-Adjustments.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Color-Curves.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Film-Grain.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Lens-Distortion.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Lift-Gamma-Gain.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Panini-Projection.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Shadows-Midtones-Highlights.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Split-Toning.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-White-Balance.md
  com.unity.render-pipelines.universal/Documentation~/Setup.md
  com.unity.render-pipelines.universal/Documentation~/ShaderGraph.md
  com.unity.render-pipelines.universal/Documentation~/TableOfContents.md
  com.unity.render-pipelines.universal/Documentation~/baked-lit-shader.md
  com.unity.render-pipelines.universal/Documentation~/configuring-universalrp-for-use.md
  com.unity.render-pipelines.universal/Documentation~/creating-a-new-project-with-universalrp.md
  com.unity.render-pipelines.universal/Documentation~/faq.md
  com.unity.render-pipelines.universal/Documentation~/getting-started-with-universalrp.md
  com.unity.render-pipelines.universal/Documentation~/index.md
  com.unity.render-pipelines.universal/Documentation~/inside-universalrp.md
  com.unity.render-pipelines.universal/Documentation~/installing-universalrp-into-an-existing-project.md
  com.unity.render-pipelines.universal/Documentation~/integration-with-post-processing.md
  com.unity.render-pipelines.universal/Documentation~/lit-shader.md
  com.unity.render-pipelines.universal/Documentation~/particles-lit-shader.md
  com.unity.render-pipelines.universal/Documentation~/particles-simple-lit-shader.md
  com.unity.render-pipelines.universal/Documentation~/particles-unlit-shader.md
  com.unity.render-pipelines.universal/Documentation~/rendering-in-universalrp.md
  com.unity.render-pipelines.universal/Documentation~/shader-stripping.md
  com.unity.render-pipelines.universal/Documentation~/shaders-in-universalrp.md
  com.unity.render-pipelines.universal/Documentation~/shading-model.md
  com.unity.render-pipelines.universal/Documentation~/simple-lit-shader.md
  com.unity.render-pipelines.universal/Documentation~/speedtree.md
  com.unity.render-pipelines.universal/Documentation~/universalrp-asset.md
  com.unity.render-pipelines.universal/Documentation~/universalrp-builtin-feature-comparison.md
  com.unity.render-pipelines.universal/Documentation~/unlit-shader.md
  com.unity.render-pipelines.universal/Documentation~/upgrading-your-shaders.md
Labels: Universal, docs, needs-backport-2019.3

#4393 Solved an issue where lighting compute buffers were resized with the wrong size
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#4388 Fix distance units of the PBR sky
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader
Labels: HDRP

#4389 backport of 4362 system locale issue
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
Labels: Shader Graph

#4009 Implement a diffuse denoiser (Need VFX test approval)
  TestProjects/VisualEffectGraph/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIllumination.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDDiffuseDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDDiffuseDenoiser.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/BilateralFilter.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/BilateralFilter.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/DiffuseDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/DiffuseDenoiser.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineRayTracingResources.asset
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesMatrixDefsHDCamera.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, dxr

#4370 Added undo to the component addition.
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
Labels: Universal

#4373 Hide the UI for object motion blur
  com.unity.render-pipelines.universal/Editor/Overrides/MotionBlurEditor.cs
Labels: Universal, needs-backport-2019.3

#4329 Make PBR sky compile again on xbox
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/InScatteredRadiancePrecomputation.compute
Labels: HDRP

#4367 Updated Frame Settings with new names and added fields
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/MSAA.md
Labels: HDRP, docs

#4382 Hdrp/docs/mask and detail maps
  com.unity.render-pipelines.high-definition/Documentation~/Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Decal-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Glossary.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/HDRPFeatures-LookDev.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/MaskMapAndDetailMap1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/MaskMapAndDetailMap2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/MaskMapAndDetailMap3.png
  com.unity.render-pipelines.high-definition/Documentation~/Layered-Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Mask-Map-and-Detail-Map.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-To-HDRP.md
Labels: HDRP, docs

#4366 Hdrp/framesettings upgrade
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableFrameSettingsArea.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Debugging/FrameSettingsFieldAttribute.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/GBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
Labels: HDRP

#4380 fix decal projector offset at creation
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs
Labels: HDRP

#4384 Rename XR shader macro
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/GPUCopy.compute
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/Deferred.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/builddispatchindirect.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/lightlistbuild.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/materialflags.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAODenoise.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumeVoxelization.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScattering.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomPrefilter.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoC.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoCDilate.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoCReproject.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCombine.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldGather.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldMip.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldMipSafe.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldPrefilter.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/Exposure.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FXAA.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlur.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurMotionVecPrep.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/NaNKiller.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/PaniniProjection.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/ColorPyramid.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/DepthPyramid.compute
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl
Labels: HDRP, XR

#4385 Update HDCamera.GetOrCreate()
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
Labels: HDRP, XR

#4396 Fix RenderGraph with XR SDK
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraphUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/XROcclusionMesh.shader
Labels: HDRP, XR

#4398 Fixing a bug linked to directional light shadow map sampling in ray tracing shaders
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingVisibility.hlsl
Labels: HDRP, dxr

#4399 Don't reset history when changing resolution via dyn res.
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntiAliasing.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#4394 DXR warnings, tooltips and UX
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIllumination.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
Labels: HDRP, dxr

#4369 Get Post-processing working with 2D again
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/059_2D_PixelPerfect_PostProcessing.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/059_2D_PixelPerfect_PostProcessing.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/OpenGLCore/059_2D_PixelPerfect_PostProcessing.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/OpenGLCore/059_2D_PixelPerfect_PostProcessing.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/059_2D_PixelPerfect_PostProcessing.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/059_2D_PixelPerfect_PostProcessing.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/059_2D_PixelPerfect_PostProcessing.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/059_2D_PixelPerfect_PostProcessing.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/059_2D_PixelPerfect_PostProcessing.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/059_2D_PixelPerfect_PostProcessing.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/059_2D_PixelPerfect_PostProcessing.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/059_2D_PixelPerfect_PostProcessing.png.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/056_2D_Lights/2DRendererData.asset
  TestProjects/UniversalGraphicsTest/Assets/Scenes/059_2D_PixelPerfect_PostProcessing.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/059_2D_PixelPerfect_PostProcessing.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/059_2D_PixelPerfect_PostProcessing.unity.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/059_2D_PixelPerfect_PostProcessing/Pixel Perfect Camera Profile.asset
  TestProjects/UniversalGraphicsTest/Assets/Scenes/059_2D_PixelPerfect_PostProcessing/Pixel Perfect Camera Profile.asset.meta
  TestProjects/UniversalGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Runtime/Utilities/ResourceReloader.cs
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/Renderer2DDataEditor.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCamera.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2DData.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/FinalBlitPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
Labels: Universal

#4326 Post process quality settings
  com.unity.render-pipelines.core/Runtime/Volume/VolumeComponent.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/BloomEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/ChromaticAberrationEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/ChromaticAberrationEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/DepthOfFieldEditor.cs
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/MotionBlurEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedPostProcessingQualitySettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedPostProcessingQualitySettings.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/VolumeComponentWithQualityEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/VolumeComponentWithQualityEditor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/DefaultSettingsVolumeProfile.asset
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Bloom.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/ChromaticAberration.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/DepthOfField.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/MotionBlur.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalPostProcessingQualitySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/GlobalPostProcessingQualitySettings.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/VolumeComponentWithQuality.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/VolumeComponentWithQuality.cs.meta
Labels: HDRP

#4400 Use the new temporal filter for directional shadow
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDSimpleDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
Labels: HDRP, dxr

#4374 fix for deleting group and property issue
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph

#4325 Universal RP Asset and Renderer workflow changes
  TestProjects/UniversalGraphicsTest/Assets/CommonAssets/ForwardRenderer.asset
  TestProjects/UniversalGraphicsTest/Assets/CommonAssets/ForwardRenderer.asset.meta
  TestProjects/UniversalGraphicsTest/Assets/CommonAssets/UniversalRPAsset.asset
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/CameraCallbackTests.cs
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/Renderer2DMenus.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.universal/Runtime/Data/PostProcessData.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRendererData.cs
  com.unity.render-pipelines.universal/Runtime/UniversalAdditionalCameraData.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/Tests/Editor/EditorTests.cs
Labels: Universal

#4395 Backported fix for perforce
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
Labels: HDRP, bug-fix, needs-backport-2019.2

#4405 Workaround for AOT errors on xbox player
  com.unity.render-pipelines.core/Runtime/Common/CoreUnsafeUtils.cs
Labels: HDRP

#4417 Hdrp/docs/volumetric fog update
  com.unity.render-pipelines.high-definition/Documentation~/Density-Volume.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricFog1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricFog2.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-VolumetricFogQuality1.png
  com.unity.render-pipelines.high-definition/Documentation~/Override-Contact-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog-Quality.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Fog.md
Labels: HDRP, docs

#4415 Fixed test 2106
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2106_GI_EmissionSG.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2106_GI_EmissionSG.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2106_GI_EmissionSG.png.meta
Labels: HDRP

#4404 Improve time handling in the HDRP in the Play mode
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#4420 Hdrp/docs/doc updates
  com.unity.render-pipelines.high-definition/Documentation~/Creating-and-Editing-HDRP-Shader-Graphs.md
  com.unity.render-pipelines.high-definition/Documentation~/Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/Forward-And-Deferred-Rendering.md
  com.unity.render-pipelines.high-definition/Documentation~/Geometric-Specular-Anti-Aliasing.md
  com.unity.render-pipelines.high-definition/Documentation~/Glossary.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/Override-PhysicallyBasedSky1.png
  com.unity.render-pipelines.high-definition/Documentation~/Layered-Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/MatCap.md
  com.unity.render-pipelines.high-definition/Documentation~/Motion-Vectors.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Physically-Based-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Procedural-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Window.md
  com.unity.render-pipelines.high-definition/Documentation~/Renderer-And-Material-Priority.md
  com.unity.render-pipelines.high-definition/Documentation~/ShaderGraph/Diffusion-Profile-Node.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Documentation~/Unlit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-To-HDRP.md
Labels: HDRP, docs

#4402 Demo smallfixes
  com.unity.render-pipelines.core/ShaderLibrary/Sampling/SampleUVMapping.hlsl
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialEvaluation.hlsl
Labels: HDRP

#4377 Universal/bugfixes
  TestProjects/UniversalGraphicsTest/Assets/CommonAssets/UniversalRPAsset.asset
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Documentation~/universalrp-asset.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineMaterialUpgrader.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/ScriptableRendererFeature.cs
  com.unity.render-pipelines.universal/Runtime/UniversalAdditionalCameraData.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl
  com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl
  com.unity.render-pipelines.universal/Shaders/Shaders.cs
  com.unity.render-pipelines.universal/Shaders/Shaders.cs.meta
  com.unity.render-pipelines.universal/Shaders/Unity.RenderPipelines.Universal.Shaders.asmdef
  com.unity.render-pipelines.universal/Shaders/Unity.RenderPipelines.Universal.Shaders.asmdef.meta
Labels: Universal

#4285 Disable the compilation of the first variant of the shadergraph…
  com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs
Labels: Shader Graph

#4406 Disables shadertag test outside of the editor
  com.unity.render-pipelines.universal/Tests/Runtime/RuntimeTests.cs
Labels: Universal

#4413 Backport of fixes to LWRP.
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineMaterialUpgrader.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardLights.cs
  com.unity.render-pipelines.lightweight/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.lightweight/Runtime/LightweightRenderPipeline.cs
  com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl
Labels: Universal

#4424 Fix test scenes broken by renderer refactor PR #4325
  TestProjects/UniversalGraphicsTest/Assets/CommonAssets/UniversalRPAsset.asset
  TestProjects/UniversalGraphicsTest/Assets/Scenes/045_CustomLWPipe.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/052_LWCallbacks.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/056_2D_Lights-Shadows.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/056_2D_Lights.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/056_2D_Lights_Shader_Graph.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/059_2D_PixelPerfect_PostProcessing.unity
  TestProjects/UniversalGraphicsTest/Assets/Scenes/070_2D_Forward_Shader_Compatibility_2D.unity
Labels: Universal

#4426 Fix for conflicting GUID in LWRP & Universal RP
  com.unity.render-pipelines.lightweight/ShaderLibrary/Deprecated.hlsl
  com.unity.render-pipelines.lightweight/ShaderLibrary/Deprecated.hlsl.meta
  com.unity.render-pipelines.universal/CHANGELOG.md
Labels: Universal

#4302 Manully backported #4283
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightSpriteLitPass.template
  com.unity.render-pipelines.lightweight/Editor/ShaderGraph/lightweightSpriteNormalPass.template
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.lightweight/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.lightweight/Shaders/2D/Sprite-Lit-Default.shader
Labels: Universal

#4412 2d/lightreactor rename
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/CompositeShadowCaster2DEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/CompositeShadowCaster2DEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/2D/ShadowCaster2DEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/ShadowCaster2DEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/2D/ShadowCaster2DShapeTool.cs
  com.unity.render-pipelines.universal/Runtime/2D/CompositeShadowCaster2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/CompositeShadowCaster2D.cs.meta
  com.unity.render-pipelines.universal/Runtime/2D/LightUtility.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Runtime/2D/ShadowCaster2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/ShadowCaster2D.cs.meta
  com.unity.render-pipelines.universal/Runtime/2D/Shadows/ShadowCasterGroup2D.cs
Labels: Universal

#4436 [Yamato] Changing from project.folder back to project.name
  .yamato/upm-ci-hdrp.yml
Labels: SRP

#4437 [Yamato] HDRP Standalone CI fix
  .yamato/upm-ci-hdrp_standalone.yml
Labels: SRP

#4422 Updated 2D Renderer Data Asset page
  com.unity.render-pipelines.universal/Documentation~/2DRendererData_overview.md
  com.unity.render-pipelines.universal/Documentation~/Images/2dRendererData_properties_updated.png
Labels: Universal, docs

#4375 LWRP (Universal) Metal OSX reference images
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/000_MultiOutput.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/000_MultiOutput.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/001_Animator.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/001_Animator.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/002_Gradient.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/002_Gradient.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/003_EventAttribute.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/003_EventAttribute.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/004_Bounds.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/004_Bounds.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/005_PlanarPrimitives.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXEditor/Metal/005_PlanarPrimitives.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/000_MultiOutput.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/000_MultiOutput.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/001_Animator.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/001_Animator.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/002_Gradient.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/002_Gradient.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/003_EventAttribute.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/003_EventAttribute.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/004_Bounds.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/004_Bounds.png.meta
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/005_PlanarPrimitives.png
  TestProjects/VisualEffectGraph_LWRP/Assets/ReferenceImages/Linear/OSXPlayer/Metal/005_PlanarPrimitives.png.meta
  TestProjects/VisualEffectGraph_LWRP/Packages/manifest.json
Labels: Universal

#4332 Switch support
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/Shadow/ShadowSamplingTent.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
Labels: HDRP, SRP

#4439 Removing the primary visibility phrase from the code and replacing it with recursive ray tracing
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/HDRaytracingEnvironmentInspector.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/SerializedHDRaytracingEnvironment.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
Labels: HDRP, dxr

#4429 Work on ray traced screen space shadows
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/SphericalSphere.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/SphericalSphere.hlsl.meta
Labels: HDRP, dxr

#4390 Raytracing Node for HDRP shaders
  LocalTestProjects/HDRP_DXR_Tests/Assets/Common/HDRenderPipelineAsset.asset
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode.meta
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode/M_Standard.mat
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode/M_Standard.mat.meta
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode/New Shader Graph.shadergraph
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode/New Shader Graph.shadergraph.meta
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode/RayTracedReflections.meta
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode/RayTracedReflections.unity
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode/RayTracedReflections.unity.meta
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode/RayTracedReflections/Scene Settings Profile.asset
  LocalTestProjects/HDRP_DXR_Tests/Assets/Scenes/104_RayTracingNode/RayTracedReflections/Scene Settings Profile.asset.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/RayTracingNode.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/RayTracingNode.cs.meta
Labels: HDRP, dxr

#4447 Correcting a wrong path for a ray tracing resource
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
Labels: HDRP, dxr
