Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-10, with the labels that each got.

#4556 Disable PBR sky below ground
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
Labels: HDRP

#4360 Added default implementations of OnPreprocessMaterialDescription for …
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/AutodeskInteractiveMaterialImport.cs
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/AutodeskInteractiveMaterialImport.cs.meta
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/FBXMaterialDescriptionPostprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/FBXMaterialDescriptionPostprocessor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/SketchupMaterialDescriptionPostprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/SketchupMaterialDescriptionPostprocessor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/ThreeDSMaterialDescriptionPostprocessor.cs
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/ThreeDSMaterialDescriptionPostprocessor.cs.meta
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/AutodeskInteractiveMaterialImport.cs
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/AutodeskInteractiveMaterialImport.cs.meta
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/FBXMaterialDescriptionPreprocessor.cs
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/FBXMaterialDescriptionPreprocessor.cs.meta
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/SketchupMaterialDescriptionPostprocessor.cs
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/SketchupMaterialDescriptionPostprocessor.cs.meta
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/ThreeDSMaterialDescriptionPostprocessor.cs
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/ThreeDSMaterialDescriptionPostprocessor.cs.meta
Labels: HDRP, SRP, Universal

#4680 VFXGraph Additions Samples package
  com.unity.visualeffectgraph/Samples~/VFXGraphAdditions/.sample.json
  com.unity.visualeffectgraph/Samples~/VFXGraphAdditions/VFXGraphAdditions.unitypackage
  com.unity.visualeffectgraph/package.json
Labels: needs-backport-2019.3, vfx

#4743 fix material validator DebugMenu enum index
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
Labels: HDRP, needs-backport-2019.2, needs-backport-2019.3

#4734 Increment updateCount for baked cubemaps
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
Labels: HDRP, needs-backport-2019.2

#4741 Fix artifacts on rectangular lights
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1303_StackLitSG_Testers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1303_StackLitSG_Testers.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Area_Light_Meshes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2401_Area_Light_Meshes.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2402_Area_Rect_Shadow.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2402_Area_Rect_Shadow.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2403_Area_TexturedRectLights.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2403_Area_TexturedRectLights.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2404_Area_LightOrientation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2404_Area_LightOrientation.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2501_LightLayers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2501_LightLayers.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9500_LightScripting.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9500_LightScripting.png.meta
  com.unity.render-pipelines.core/ShaderLibrary/AreaLighting.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
Labels: HDRP

#4739 Shadowmaps automation test
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps/Isosphere.fbx
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps/Isosphere.fbx.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps/Separator.fbx
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps/Separator.fbx.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps/disk.fbx
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps/disk.fbx.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps/solidCube.fbx
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps/solidCube.fbx.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2309_ShadowMaps.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2311_ShadowMaps.png
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  TestProjects/HDRP_Tests/ProjectSettings/QualitySettings.asset
  com.unity.testing.hdrp/RP_Assets/HDRP_Test_Def.asset
Labels: HDRP

#4338 Added HDRP test 2007_Light_Volumetrics
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2008_Light_Volumetrics.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2008_Light_Volumetrics.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2008_Light_Volumetrics.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2008_Light_Volumetrics/2008_Light_Volumetrics_Volume.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2008_Light_Volumetrics/2008_Light_Volumetrics_Volume.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2008_Light_Volumetrics.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2008_Light_Volumetrics.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  TestProjects/HDRP_Tests/ProjectSettings/QualitySettings.asset
Labels: HDRP

#4667 2D Renderer Bug Fixes
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/HeaderModifier.cs
  com.unity.render-pipelines.universal/Editor/2D/HeaderModifier.cs.meta
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/Resources/InspectorIcons/FreeformLight.png.meta
  com.unity.render-pipelines.universal/Editor/2D/Resources/InspectorIcons/GlobalLight.png.meta
  com.unity.render-pipelines.universal/Editor/2D/Resources/InspectorIcons/ParametricLight.png.meta
  com.unity.render-pipelines.universal/Editor/2D/Resources/InspectorIcons/PointLight.png.meta
  com.unity.render-pipelines.universal/Editor/2D/Resources/InspectorIcons/SpriteLight.png.meta
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/SpriteLitPass.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/SpriteNormalPass.hlsl
  com.unity.render-pipelines.universal/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/Light2DShape.cs
  com.unity.render-pipelines.universal/Runtime/2D/LightUtility.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/Materials/Sprite-Lit-Default.mat
  com.unity.render-pipelines.universal/Shaders/2D/Light2D-Point-Volumetric.shader
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Fallback.shader
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Fallback.shader.meta
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Lit-Default.shader
Labels: Universal, needs-backport-2019.3

#4731 Fix shader graph samples package
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Samples~/ShaderGraphSamples/ShaderGraphSamples.unitypackage
Labels: HDRP

#4757 Fix decals not affecting GI
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyePass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/PBR/ShaderGraph/HDPBRPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxFData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
Labels: HDRP, needs-backport-2019.2

#4617 [Feature] Added support for vertex skinning
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/VertexAnimation.template.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Templates/BuildVertexDescriptionInputs.template.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalShaderGraphResources.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/CodeGen/GenerationUtils.cs
  com.unity.shadergraph/Editor/CodeGen/ShaderSpliceUtil.cs
  com.unity.shadergraph/Editor/Data/Graphs/ShaderGraphRequirements.cs
  com.unity.shadergraph/Editor/Data/Interfaces/IMayRequireVertexSkinning.cs
  com.unity.shadergraph/Editor/Data/Interfaces/IMayRequireVertexSkinning.cs.meta
  com.unity.shadergraph/Editor/Data/Nodes/Vertex Skinning.meta
  com.unity.shadergraph/Editor/Data/Nodes/Vertex Skinning/LinearBlendSkinningNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Vertex Skinning/LinearBlendSkinningNode.cs.meta
Labels: Universal

#4661 Fix zBufferParams with XR single-pass rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
Labels: HDRP, XR, needs-backport-2019.2, needs-backport-2019.3

#4614 Vfx/2019.2 staging
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/SubgraphEventTransmission/VFXContainer.vfx
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/07_UnityLogo.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/14_DecalsFlipBook.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/Collision.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/14_DecalsFlipBook.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/Collision.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/HDRPFog.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/SimpleLit.png
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/Compiler/VFXShaderWriter.cs
  com.unity.visualeffectgraph/Editor/Compiler/VFXUniformMapper.cs
  com.unity.visualeffectgraph/Editor/Models/Blocks/VFXSubgraphBlock.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXBasicCubeOutput.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXLineOutput.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/Implementations/VFXPointOutput.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/VFXContext.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/VFXSubgraphContext.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/VFXSubgraphOperator.cs
  com.unity.visualeffectgraph/Shaders/ParticleDecals/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticleHexahedron/PassBasicForward.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/Pass.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassDepth.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassForward.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassMotionVectors.template
  com.unity.visualeffectgraph/Shaders/ParticlePoints/PassShadowCaster.template
  com.unity.visualeffectgraph/Shaders/VFXCommon.cginc
  com.unity.visualeffectgraph/Shaders/VFXCommonOutput.cginc
  com.unity.visualeffectgraph/Shaders/VFXParticleCommon.template
Labels: vfx

#4750 Custom pass improvements
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassFullScreenShader.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassVolumeEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassInjectionPoint.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassRenderers.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/DrawRenderersCustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/FullScreenCustomPass.cs
Labels: HDRP

#4761 Added Wiki content to repo and did a quick edit
  com.unity.render-pipelines.core/Documentation~/Culling-in-SRP.md
  com.unity.render-pipelines.core/Documentation~/Drawing-in-SRP.md
  com.unity.render-pipelines.core/Documentation~/Problems-That-SRP-Solves.md
  com.unity.render-pipelines.core/Documentation~/SRP-Asset.md
  com.unity.render-pipelines.core/Documentation~/SRP-Context.md
  com.unity.render-pipelines.core/Documentation~/SRP-Instance.md
  com.unity.render-pipelines.core/Documentation~/SRP-Overview.md
  com.unity.render-pipelines.core/Documentation~/TableOfContents.md
  com.unity.render-pipelines.core/Documentation~/XR-in-SRP.md
  com.unity.render-pipelines.core/Documentation~/index.md
Labels: SRP, docs, needs-backport-2019.2, needs-backport-2019.3

#4764 Run generate hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Builtin/BuiltinData.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassInjectionPoint.cs.hlsl
Labels: HDRP

#4765 Fix player build with HDRP_RuntimeTests
  com.unity.testing.hdrp/TestRunner/HDRP_TestSettings.cs
Labels: HDRP, XR

#4458 Add reflection fade distance
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedProbeSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettings.cs
Labels: HDRP

#4648 Alloc ao history when not available (fix for 19.2)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
Labels: HDRP, backported-2019.2

#4568 [VFX] Improve Motion Vector Test
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/4013_TransparentMotionVector.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/4013_TransparentMotionVector.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/4013_TransparentMotionVector.png
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/24_MotionVector.unity
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/24_MotionVector_Local.controller
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/ForceDebugMotionVector.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/ForceDebugMotionVector.cs.meta
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/24_MotionVector.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/24_MotionVector.png.meta
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/24_MotionVector.png
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugFullScreen.shader
  com.unity.testing.visualeffectgraph/Tests/Runtime/VFXGraphicsTestSettings.cs
  com.unity.testing.visualeffectgraph/Tests/Runtime/VFXGraphicsTestSettings.cs.meta
  com.unity.testing.visualeffectgraph/Tests/Runtime/VFXGraphicsTests.cs
Labels: HDRP, vfx

#4603 Reworked how matcap view is triggered to avoid having it in game view when scene lighting toggle is off
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraphUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.2

#4728 Documentation fixes for menu traversals
  com.unity.render-pipelines.universal/Documentation~/CreateNewProjectFromTemplate.md
  com.unity.render-pipelines.universal/Documentation~/InstallURPIntoAProject.md
  com.unity.render-pipelines.universal/Documentation~/Post-Processing-Motion-Blur.md
  com.unity.render-pipelines.universal/Documentation~/VolumeOverrides.md
  com.unity.render-pipelines.universal/Documentation~/VolumeProfile.md
  com.unity.render-pipelines.universal/Documentation~/Volumes.md
  com.unity.render-pipelines.universal/Documentation~/configuring-universalrp-for-use.md
Labels: Universal, docs

#4712 Assign the default volume profile when creating a new HDRP Asset.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDAssetFactory.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/EditorDefaultSettings.cs
Labels: HDRP

#4713 Fix planar probe fov 0 breaking projection matrix
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP

#4692 Fix animated preview
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
Labels: Shader Graph, needs-backport-2019.2

#4725 Fix bugs with shadow caching
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
Labels: HDRP

#4754 Hdrp/persistent cameras for realtime probes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraCache.cs.meta
  com.unity.render-pipelines.high-definition/Tests/Editor/Utilities/CameraCacheTest.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/Utilities/CameraCacheTest.cs.meta
Labels: HDRP

#4753 Better behaviour when no normal map OS, but detail map is present
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitDataIndividualLayer.hlsl
Labels: HDRP, needs-backport-2019.2

#4769 fix for PatchInputExpression Slot Square
  com.unity.visualeffectgraph/Editor/Models/Contexts/VFXSubgraphContext.cs
Labels: vfx

#4770 fix for PacthInputExpression Slot Square
  com.unity.visualeffectgraph/Editor/Models/Contexts/VFXSubgraphContext.cs
Labels: vfx

#4771 fix for PatchInputExpression Slot Square
  com.unity.visualeffectgraph/Editor/Models/Contexts/VFXSubgraphContext.cs
Labels: vfx

#4752 Hdrp decal htile buffer (new)
  com.unity.render-pipelines.core/ShaderLibrary/API/D3D11.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Metal.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/Vulkan.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ClearPropertyMaskBuffer.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ClearPropertyMaskBuffer.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DBufferManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalUtilities.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/ShaderVariablesDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#4760 Hdrp/docs/getting started qa feedback
  com.unity.render-pipelines.high-definition/Documentation~/Environment-Lighting.md
  com.unity.render-pipelines.high-definition/Documentation~/Getting-started-with-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-To-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumes.md
Labels: HDRP, docs

#4758 Backport #4667
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/HeaderModifier.cs
  com.unity.render-pipelines.universal/Editor/2D/HeaderModifier.cs.meta
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/SpriteLitPass.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/SpriteNormalPass.hlsl
  com.unity.render-pipelines.universal/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/Light2DShape.cs
  com.unity.render-pipelines.universal/Runtime/2D/LightUtility.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/Materials/Sprite-Lit-Default.mat
  com.unity.render-pipelines.universal/Shaders/2D/Light2D-Point-Volumetric.shader
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Fallback.shader
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Fallback.shader.meta
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Lit-Default.shader
Labels: Universal

#4759 Backport #4667
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/HeaderModifier.cs
  com.unity.render-pipelines.universal/Editor/2D/HeaderModifier.cs.meta
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/SpriteLitPass.hlsl
  com.unity.render-pipelines.universal/Editor/ShaderGraph/Includes/SpriteNormalPass.hlsl
  com.unity.render-pipelines.universal/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/Light2DShape.cs
  com.unity.render-pipelines.universal/Runtime/2D/LightUtility.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/Materials/Sprite-Lit-Default.mat
  com.unity.render-pipelines.universal/Shaders/2D/Light2D-Point-Volumetric.shader
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Fallback.shader
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Fallback.shader.meta
  com.unity.render-pipelines.universal/Shaders/2D/Sprite-Lit-Default.shader
Labels: Universal

#4773 Remove non ascii characters
  Tools/locate-non-ascii-characters
  com.unity.render-pipelines.core/Editor/Gizmo/UnlitGizmo.shader
  com.unity.render-pipelines.core/ShaderLibrary/PhysicalCamera.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/VolumeRendering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/VolumeProjection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDIMS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/PreIntegratedFGD_Ward.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/FabricRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/SubpixelMorphologicalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Common/RayBinning.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingIntersectonGBuffer.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/OnlineVariance.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingMacros.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingReflectionFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingMIS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/SphericalQuad.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/ColorPyramidPS.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/EditorShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyCommon.hlsl
  com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl
  com.unity.render-pipelines.universal/Shaders/2D/Include/NormalsRenderingShared.hlsl
  com.unity.render-pipelines.universal/Shaders/PostProcessing/SubpixelMorphologicalAntialiasing.hlsl
  com.unity.shadergraph/ShaderGraphLibrary/GeometricTools.hlsl
Labels: HDRP

#4784 Fix how HDRP assets as dependencies are found.
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
Labels: HDRP, needs-backport-2019.2

#4789 Case 1178480: Fix TerrainLit shader compilation error
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_BasemapGen.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap_Includes.hlsl
Labels: HDRP

#4779 HDRP Wizard fixes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
Labels: HDRP

#4785 Fixed an issue where fog color was not exposed correctly
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1204_Lit_Fog.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5001_Fog_FogFallback.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5007_Exponential_Fog.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/HDRPFog.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/AtmosphericScattering.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
Labels: HDRP

#4679 Testing XR PostFX working on URP
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/013_xr_PostFX_Simple.png
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/013_xr_PostFX_Simple.png.meta
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/014_xr_PostFX_Complex_NoAA.png
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/014_xr_PostFX_Complex_NoAA.png.meta
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/015_xr_PostFX_FXAA.png
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/015_xr_PostFX_FXAA.png.meta
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/016_xr_PostFX_SMAA.png
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/016_xr_PostFX_SMAA.png.meta
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/013_xr_PostFX_Simple.png
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/013_xr_PostFX_Simple.png.meta
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/014_xr_PostFX_Complex_NoAA.png
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/014_xr_PostFX_Complex_NoAA.png.meta
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/015_xr_PostFX_FXAA.png
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/015_xr_PostFX_FXAA.png.meta
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/016_xr_PostFX_SMAA.png
  TestProjects/UniversalGfxTestStereo/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/016_xr_PostFX_SMAA.png.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_PBR.mat
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_PBR.mat.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_PBRGraph.mat
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_PBRGraph.mat.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_PBRGraph.shadergraph
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_PBRGraph.shadergraph.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_PostFX Volume Profile.asset
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_PostFX Volume Profile.asset.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_Unlit.mat
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_Unlit.mat.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_UnlitGraph.mat
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_UnlitGraph.mat.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_UnlitGraph.shadergraph
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX/013_xr_UnlitGraph.shadergraph.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX_Simple.unity
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/013_xr_PostFX_Simple.unity.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/014_xr_PostFX_Complex_NoAA.unity
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/014_xr_PostFX_Complex_NoAA.unity.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/015_xr_PostFX_FXAA.unity
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/015_xr_PostFX_FXAA.unity.meta
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/016_xr_PostFX_SMAA.unity
  TestProjects/UniversalGfxTestStereo/Assets/Scenes/016_xr_PostFX_SMAA.unity.meta
  TestProjects/UniversalGfxTestStereo/ProjectSettings/EditorBuildSettings.asset
Labels: Universal

#4799 Rename max environment light on screen by max reflection probe on screen
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
Labels: HDRP

#4775 Universal/postprocessing fixes
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
Labels: Universal

#4780 Fixed chromatic aberration test & associated reference images
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/LinuxEditor/OpenGLCore/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/LinuxEditor/OpenGLCore/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/LinuxEditor/Vulkan/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/LinuxEditor/Vulkan/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/OpenGLCore/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/OpenGLCore/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Vulkan/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Vulkan/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/071_ChromaticAberration.unity
Labels: Universal

#4809 Fixed EOL for HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#4808 Custom pass fixes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
Labels: HDRP

#4811 Update conflicting metas
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/AutodeskInteractiveMaterialImport.cs.meta
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/FBXMaterialDescriptionPostprocessor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/SketchupMaterialDescriptionPostprocessor.cs.meta
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/ThreeDSMaterialDescriptionPostprocessor.cs.meta
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/AutodeskInteractiveMaterialImport.cs.meta
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/FBXMaterialDescriptionPreprocessor.cs.meta
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/SketchupMaterialDescriptionPostprocessor.cs.meta
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors/ThreeDSMaterialDescriptionPostprocessor.cs.meta
Labels: HDRP, Universal

#4814 Hdrp/docs/shadows, ray tracing, anti aliasing, and master nodes
  com.unity.render-pipelines.high-definition/Documentation~/Anti-Aliasing.md
  com.unity.render-pipelines.high-definition/Documentation~/Creating-and-Editing-HDRP-Shader-Graphs.md
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Camera.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Lighting-Mode-Shadowmask.md
  com.unity.render-pipelines.high-definition/Documentation~/MSAA.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Global-Illumination.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Reflections.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Shadows.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Debug.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Environment.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Getting-Started.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Light-Cluster.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Path-Tracing.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Recursive-Rendering.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Window.md
  com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.3

#4820 Hdrp/fix trunk change drawrange
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP

#4810 Replaced most instances of GraphicsSettings.renderPipelineAsset by GraphicsSettings.currentRenderPipeline
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDSceneManagement.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/DiffusionProfileOverrideEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.ContextualMenu.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ReflectionMenuItem.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/DecalSurfaceInputsUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/PathTracing/PathTracingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RecursiveRenderingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableFrameSettingsArea.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/DiffusionProfileNode.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/AtmosphericScattering/FogEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Upgraders/UpgradeMenuItem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Tonemapping.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.testing.hdrp/Scripts/Editor/DebugViewController_Editor.cs
  com.unity.visualeffectgraph/Editor/Core/VFXLibrary.cs
  com.unity.visualeffectgraph/Editor/Inspector/VisualEffectEditor.cs
Labels: HDRP

#4768 Fixed sorting, sizing, naming, inactive objects, undo
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
Labels: HDRP

#4825 Fix for Realtime GI not working when upgrading
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIlluminationUtils.cs
Labels: HDRP, backported-2019.2, needs-backport-2019.3

#4824 Fix for Screen Space Shadows fallback texture not being an array when XR is off
  com.unity.render-pipelines.core/Runtime/Textures/TextureXR.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
Labels: HDRP, needs-backport-2019.3

#4826 Backport of 4825
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/GlobalIlluminationUtils.cs
Labels: HDRP

#4774 Fix offset in reflections caused by precision error
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/Decal.hlsl
Labels: HDRP, needs-backport-2019.2, needs-backport-2019.3

#4827 Hdrp/make light layer renamable
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Editor/Core/Lighting/LightLayerEnumPropertyDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/Core/Lighting/LightLayerEnumPropertyDrawer.cs.meta
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedRenderPipelineSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
Labels: HDRP, needs-backport-2019.3

#4828 Fixed pyramid lights bounding box
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4786 Removed render graph debug (as it is not finished yet)
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraph.cs
Labels: HDRP

#4747 Add Lane and Quad Swizzling intrinsics
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/Macros.hlsl
Labels: HDRP

#4781 Hdrp/staging pt2
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/PathTracing/PathTracingEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/PathTracing.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingLight.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingMain.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingMaterial.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassPathTracing.hlsl
Labels: HDRP, dxr

#4691 Add explicit exposure for probe rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/ReflectionProbe1.png
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2019.2-to-2019.3.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/PlanarReflectionProbeEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/ProbeSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedHDProbe.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedProbeSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Eye/Eye.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/Fabric.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/FabricReference.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitReference.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/SimpleLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettingsUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP

#4794 SSAO Improvements and non temporal version (Copy of 4787)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOBlurAndUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOBlurAndUpsample.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAODenoise.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP, needs-backport-2019.3

#4751 Fixes for terrain heightmap default/null values and epsilons
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Splatmap.hlsl
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: HDRP, Universal

#4834 Fixed issue where black emission caused unnecessary UI repaints
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderGUI/BaseShaderGUI.cs
Labels: Universal

#4832 [VFX] Update HDRPFog image reference
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/HDRPFog.png
Labels: vfx

#4839 Correcting a bug in the recursive rendering related to directional shadows
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingForward.hlsl
Labels: HDRP, dxr

#4837 Fixes to the custom post-processing effect framework
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing/CustomPostProcessVolumeComponent.cs
Labels: HDRP, needs-backport-2019.3

#4836 Fix XR single-pass rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
Labels: HDRP, XR, needs-backport-2019.3

#4835 Improving the diffuse denoiser when the pixel footprint is bigger than the filtering radius
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/PathTracing.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDDiffuseDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/DiffuseDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
Labels: HDRP, dxr

#4537 Use opacity instead of the scattering distance to parametrize the PBR sky
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5004_Pbr_Sky_High_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5005_Pbr_Sky_Med_Altitude.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/5006_Pbr_Sky_Low_Altitude.png.meta
  com.unity.render-pipelines.high-definition/Editor/Sky/PhysicallyBasedSky/PhysicallyBasedSkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.cs
Labels: HDRP

#4778 Refactor sky lighting system
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/CaptureRenderTarget.renderTexture
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/CaptureRenderTarget.renderTexture.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/LightingData.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/LightingData.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Lightmap-0_comp_dir.png
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Lightmap-0_comp_dir.png.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Lightmap-0_comp_light.exr
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Lightmap-0_comp_light.exr.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/ShowCapture.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/ShowCapture.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Sky_Green.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Sky_Green.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Sky_Red.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Sky_Red.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Sky_Static.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2009_MultipleSkies/Sky_Static.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2210_ReflectionProbes_CaptureAtVolumeAnchor.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2008_Light_Volumetrics.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2009_MultipleSkies.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2009_MultipleSkies.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2210_ReflectionProbes_CaptureAtVolumeAnchor.png
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSky.cs
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky.cs
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky.cs.meta
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSkyRenderer.cs
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSkyRenderer.cs.meta
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky.shader
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/Resources/ProceduralSky.shader.meta
  com.unity.render-pipelines.core/Runtime/Common/DynamicArray.cs
  com.unity.render-pipelines.core/Runtime/Common/DynamicArray.cs.meta
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraphResourceRegistry.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraphUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyRenderingContext.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkySettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyUpdateContext.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSky.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSkyRenderer.cs
Labels: HDRP, needs-backport-2019.3

#4847 Custom post process doc
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Post-Process.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/CustomPostProcess_CustomEditor.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/PostProcessOrder_ProjectSettings.png
Labels: HDRP

#4846 Fix flickering shadows when multiple camera and multiple volume overrides are there.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#4850 Fixing issue related to refactor in the sky texture
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/PathTracing.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
Labels: HDRP, dxr

#4854 Fixing a problem with the world to tangent matrix build and a bug with time parameters in shader graph
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitRaytracingPass.template
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingFragInputs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
Labels: HDRP, dxr

#4853 Fixed some meta files
  com.unity.render-pipelines.high-definition/Editor/Core/Lighting.meta
  com.unity.render-pipelines.universal/Editor/AssetPostProcessors.meta
  com.unity.visualeffectgraph/Editor/Models/Blocks/Implementations/Test.meta
Labels: HDRP

#4859 Go inside the loop if we have planar probes but no light
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP

#4851 Fix a number of issues with prefab isolation mode.
  com.unity.render-pipelines.core/Runtime/Volume/VolumeManager.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.Gizmos.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedProbeSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettingsUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/HDAdditionalReflectionData.MigrationTests.cs
  com.unity.render-pipelines.high-definition/Tests/Editor/PlanarReflectionProbe.MigrationTests.cs
Labels: HDRP

#4863 Fixed an issue with fog volume component upgrade not working properly
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
Labels: HDRP

#4861 Move RequestShadowMapRendering to public API
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP, needs-backport-2019.3

#4849 Adding an automatic fix for the config package change for ray tracing
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Window.cs
Labels: HDRP, dxr

#4838 Hdrp/dxr stats
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Window.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/CountTracedRays.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingGBuffer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingRenderer.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
Labels: HDRP, dxr

#4868 Fix AO upsampling when using XR
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOBlurAndUpsample.compute
Labels: HDRP, needs-backport-2019.3

#4867 Fix default material values
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Material/DefaultHDMaterial.mat
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Material/DefaultHDMirrorMaterial.mat
Labels: HDRP

#4866 Fix grayscale example and image in custom post process doc
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Post-Process.md
Labels: HDRP

#4869 Fix plurial issues in HDRP asset ui
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
Labels: HDRP

#4872 Fixed compilation issue with 19.3
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP, needs-backport-2019.3

#4876 sky is not black when no sky is specified.
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP

#4881 Fix camera without HDAdditionalCameraData not rendering
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP

#4873 Removing the usage of ENABLE_RAYTRACING except for the shader macro
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/SurfaceOptionUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/PathTracing/PathTracingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RecursiveRenderingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderQueue.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/PathTracing.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDDiffuseDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingDeferredLightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDSimpleDenoiser.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, dxr

#4891 Batch of fixes for custom pass
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/FullScreenCustomPass_Inspector.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/HDRPFeatures-CustomPass.gif
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/DrawRenderersCustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/FullScreenCustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/DrawRenderersCustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/FullScreenCustomPass.cs
Labels: HDRP

#4888 Update HDRP-Camera.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Camera.md
Labels: HDRP, docs, needs-backport-2019.3

#4884 Add dirty for asset modified by wizard
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
Labels: HDRP, needs-backport-2019.3

#4885 Hdrp/docs/removing raytracing environment
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Ambient-Occlusion.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Global-Illumination.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Reflections.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Environment.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Getting-Started.md
  com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Recursive-Rendering.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Wizard.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.3

#4874 Fix triplanar node using camera relative position in HDRP
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/UV/TriplanarNode.cs
Labels: Shader Graph, needs-backport-2019.3

#4889 Modification 2205_LightLoopCullWOblique to contain specular term reflection on planar reflection probe
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique/Dark_Metallic.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique/Dark_Metallic.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique/Dark_MetallicAndSmooth.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique/Dark_MetallicAndSmooth.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique/Dark_Smooth.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2205_LightLoopCullWOblique/Dark_Smooth.mat.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/2205_LightLoopCullWOblique.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/2205_LightLoopCullWOblique.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/2205_LightLoopCullWOblique.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/2205_LightLoopCullWOblique.png.meta
Labels: HDRP

#4886 2313_Shadow_Mask_Spotlight_Shapes test scene modification to include Pyramid light aspect ratios
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2313_Shadow_Mask_Spotlight_Shapes.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/2313_Shadow_Mask_Spotlight_Shapes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2313_Shadow_Mask_Spotlight_Shapes.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/2313_Shadow_Mask_Spotlight_Shapes.png
Labels: HDRP

#4880 Backport 19.2 of 4374. Fix for case 1182083 deleting property…
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph

#4890 HDRP/Workaround on camera prefab reload loop
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/SerializedHDCamera.cs
Labels: HDRP, needs-backport-2019.2, needs-backport-2019.3

#4718 Ray Traced Contact Shadows
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightDefinition.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ContactShadows.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingAmbientOcclusion.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP, dxr

#4894 Hdrp/fix potential crash on light explorer and typos
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Types.cs
Labels: HDRP, needs-backport-2019.3

#4887 Fix NaN issues with normals if scale of the Z is set to 0
  com.unity.render-pipelines.core/ShaderLibrary/NormalSurfaceGradient.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/SpaceTransforms.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariablesFunctions.hlsl
Labels: HDRP

#4898 Add HDRenderPipeline tag to DXR subshaders
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
Labels: HDRP, bug-fix, dxr, needs-backport-2019.3

#4900 Small AO fixes
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute
Labels: HDRP

#4895 Fix ambient probe backing first frame
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/IntegrateHDRISky.shader
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/Resources/ProceduralSky.shader
Labels: HDRP

#4897 Add support lod crossfade shadergraph
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyePass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSettingsView.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitSubShader.cs
Labels: HDRP

#4875 Case 1176497: Fix shader error spammed in the console when selecting terrain in HDRP/SRP
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit_Basemap.shader
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLit.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBase.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitInput.hlsl
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: HDRP, Universal, needs-backport-2019.3

#4909 Fixing issue with contact shadows
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, bug-fix

#4910 Changing and enabling the ForwardMSAAOnly Test (also changing the screenshots for the 3 platforms)
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9401_MSAAForwardOnly/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9401_MSAAForwardOnly.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9401_MSAAForwardOnly.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9401_MSAAForwardOnly.png
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP

#4913 [Universal] Timeline dependency fix
  TestProjects/UniversalGfxTestStereo/Packages/manifest.json
  TestProjects/UniversalGraphicsTest/Packages/manifest.json
Labels: Universal, backported-2019.3

#4902 Replace constant depth bias with slope-scale bias for shadows
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2311_ShadowMaps.unity
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1207_Lit_Displacement.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1215_Lit_SubSurfaceScattering.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1301_StackLitSG.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1351_Fabric.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1401_HairGraph.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/1601_TerrainLit.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2106_GI_EmissionSG.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2205_LightLoopCullWOblique.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2311_ShadowMaps.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2315_Shadow_Cascades.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2501_LightLayers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8101_Opaque.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8201_VertexAnimation.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/8204_CustomSpecOcclusion.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9004_MultiViewport.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9007_CameraAlphaComposition.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9601_SkinnedMeshBatching-Off.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9602_SkinnedMeshBatching-On.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9603_MeshRendererBatching-Off.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9604_MeshRendererBatching-On.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/Shadows1.png
  com.unity.render-pipelines.high-definition/Documentation~/Light-Component.md
  com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2019.2-to-2019.3.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/AdditionalShadowData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowUtils.cs
Labels: HDRP

#4918 Stack lit and DXR Fixes
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2403_Area_TexturedRectLights.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2403_Area_TexturedRectLights/M_SLSmoothness_0.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2403_Area_TexturedRectLights/M_SLSmoothness_0.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2403_Area_TexturedRectLights/M_SLSmoothness_1.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2403_Area_TexturedRectLights/M_SLSmoothness_1.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2403_Area_TexturedRectLights/M_SLSmoothness_2.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2403_Area_TexturedRectLights/M_SLSmoothness_2.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2403_Area_TexturedRectLights/S_StackLitGraph.shadergraph
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/2x_Lighting/2403_Area_TexturedRectLights/S_StackLitGraph.shadergraph.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2403_Area_TexturedRectLights.png
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
Labels: HDRP

#4915 Fix the render queue not updated when switching between HDRP and a custom shader
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/SurfaceOptionUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/HDShaderGUI.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Editor/Upgraders/UpgradeMenuItem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.testing.hdrp/Scripts/Editor/ResetShaderGraphMaterialProperties.cs
Labels: HDRP

#4917 [Yamato] Add fast ABV
  .yamato/upm-ci-abv.yml
  .yamato/upm-ci-hdrp.yml
  .yamato/upm-ci-hdrp_standalone.yml
  .yamato/upm-ci-shadergraph.yml
  .yamato/upm-ci-shadergraph_stereo.yml
  .yamato/upm-ci-universal.yml
  .yamato/upm-ci-universal_stereo.yml
  .yamato/upm-ci-vfx_lwrp.yml
  .yamato/upm-ci-vfxmain.yml
Labels: needs-backport-2019.3

#4923 Fixing a problem in the culling for ray traced directional (front instead of back)
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
Labels: HDRP, dxr

#4924 Fix HDRP Shader Graph default values with SSS
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/BaseLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/SurfaceOptionUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
Labels: HDRP

#4892 [Shader Graph] Fix Various Bugs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalPBRSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalUnlitSubShader.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/ColorMaterialSlot.cs
  com.unity.shadergraph/Editor/Data/Nodes/MasterNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Vector/TransformNode.cs
  com.unity.shadergraph/Editor/Resources/Shaders/FallbackError.shader
  com.unity.shadergraph/Editor/Resources/Shaders/FallbackError.shader.meta
Labels: Shader Graph, Universal, bug-fix, needs-backport-2019.3

#4925 Fix vfx standalonetests
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/08_Shadows.png
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Types.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP

#4893 case 1194021 Removing the log warning
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipelineCore.cs
Labels: Universal

#4929 Fix a small bug in the shadow caching system
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
Labels: HDRP, needs-backport-2019.3

#4930 Fixed a number of issues with full screen debug modes not reseting correctly when setting another mutually exclusive mode
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
Labels: HDRP, needs-backport-2019.3

#4928 Disabled test 8102 for XR
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/8x_ShaderGraph/8102_Transparent.unity
Labels: HDRP

#4926 Fix issue 1189196
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/Unity.Testing.SRP.Universal.Editor.asmdef
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/UniversalProjectEditorTests.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/UniversalProjectEditorTests.cs.meta
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
Labels: Universal, needs-backport-2019.3

#4577 Fixed linear to sRGB conversion happening twice on some Android devices.
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
Labels: Universal

#4841 Fixed LUT sampling
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/Passes/ColorGradingLutPass.cs
  com.unity.render-pipelines.universal/Shaders/PostProcessing/Common.hlsl
Labels: Universal, needs-backport-2019.3

#4796 Fixed material leak + added lifetime feature
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal, needs-backport-2019.3

#4939 Don't run AO in async if it is disabled
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
Labels: HDRP

#4943 Fixed an issue where a texture containing garbage would be set for AO in some cases.
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
Labels: HDRP, needs-backport-2019.3

#4937 Fixed editor & runtime unit tests on staging
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal

#4935 Batch of PRs
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/Unity.Testing.SRP.Universal.Editor.asmdef
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/UniversalProjectEditorTests.cs
  TestProjects/UniversalGraphicsTest/Assets/Test/Editor/UniversalProjectEditorTests.cs.meta
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/ColorGradingLutPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/Shaders/PostProcessing/Common.hlsl
Labels: Universal, needs-backport-2019.3
