Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2019-12, with the labels that each got.

#5240 Fix reflection probe texture missing message
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.Preview.cs
Labels: HDRP, docs, needs-backport-2019.3

#5242 Fixed compilation issue
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDReflectionProbeEditor.Preview.cs
Labels: HDRP, needs-backport-2019.3

#5148 Universal/fix/035 shader terrainshaders
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/OpenGLCore/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Vulkan/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/Billboard.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD0/Branches_0.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD0/Leaves_1.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD1/Branches_0.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD1/Leaves_1.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD2/Branches_0.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD2/Leaves_1.mat
Labels: Universal, bug-fix, needs-backport-2019.3

#5225 Missing entry point for stencil override.
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Templates/PassMesh.template
Labels: Universal, bug-fix

#5226 Fixed missing normalize operation on vertex normals.
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/Nature/SpeedTree7CommonPasses.hlsl
  com.unity.render-pipelines.universal/Shaders/Nature/SpeedTree8Passes.hlsl
Labels: Universal, bug-fix

#5232 Fix the custom pass doc outline scripting example in VR
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
Labels: HDRP, docs, needs-backport-2019.3

#5231 Bugfix: Unable to delete shader passes in the custom renderer feature list (1201664)
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/RendererFeatures/RenderObjectsPassFeatureEditor.cs
Labels: Universal, needs-backport-2019.3

#5216 Universal/bugfix 1199812 particle outlines
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/ShaderLibrary/Particles.hlsl
  com.unity.render-pipelines.universal/Shaders/Particles/ParticlesLitInput.hlsl
  com.unity.render-pipelines.universal/Shaders/Particles/ParticlesUnlitForwardPass.hlsl
Labels: Universal, needs-backport-2019.3

#5061 Add XR multipass rendering for Universal pipeline (version 2)
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/Passes/DepthOnlyPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/ScriptableRenderPass.cs
  com.unity.render-pipelines.universal/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipelineCore.cs
Labels: Universal, XR, needs-backport-2019.3

#5241 Enable RWTexture# in gles 3.1
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
Labels: Universal, needs-backport-2019.3

#5258 2019.3/rwtex es3.1
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/API/GLES3.hlsl
Labels: Universal

#5261 Rename eye (experimental) as eye (Preview)
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
Labels: HDRP, needs-backport-2019.3

#5227 Fixed camera inverse view-proj matrix in XR mode.
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/ShaderLibrary/Input.hlsl
  com.unity.render-pipelines.universal/ShaderLibrary/UnityInput.hlsl
  com.unity.render-pipelines.universal/Shaders/Utils/Blit.shader
  com.unity.render-pipelines.universal/Shaders/Utils/CopyDepthPass.hlsl
Labels: Universal, needs-backport-2019.3

#5235 Fixing an inconsistency between ray tracing shadows and shadow maps for culling
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
Labels: HDRP, dxr, needs-backport-2019.3

#5222 Recursive Rendering not working anymore
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
Labels: HDRP, dxr

#5236 Hdrp/fix api documentation
  com.unity.render-pipelines.core/Editor/CoreEditorDrawers.cs
  com.unity.render-pipelines.core/Editor/CoreEditorStyles.cs
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/EditorPrefBoolFlags.cs
  com.unity.render-pipelines.core/Editor/ExpandedState.cs
  com.unity.render-pipelines.core/Editor/LookDev/CameraState.cs
  com.unity.render-pipelines.core/Editor/LookDev/ComparisonGizmoState.cs
  com.unity.render-pipelines.core/Editor/LookDev/Context.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.EnvironmentLibrarySidePanel.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDevRenderer.cs
  com.unity.render-pipelines.core/Editor/LookDev/Stage.cs
  com.unity.render-pipelines.core/Editor/Utilities/SerializedBitArray.cs
Labels: HDRP

#5270 Ray Traced Shadow Denoising Issues
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
Labels: HDRP, dxr, needs-backport-2019.3

#5271 Updated xml doc
  com.unity.render-pipelines.high-definition/Editor/Core/Lighting/LightLayerEnumPropertyDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/QualitySettingsPanel.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/GlobalLightLoopSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.Legacy.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/ProxyVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/ProxyVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/ReflectionProxyVolumeComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/ShapeType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequest.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestBuilder.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/AOV/AOVRequestDataCollection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/CaptureSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/ScalableSetting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/ScalableSettingSchema.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/ScalableSettingSchemaId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/ScalableSettingValue.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraPositionSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/HDRenderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeCapturePositionSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettingsUtilities.cs
Labels: HDRP, docs, needs-backport-2019.3

#5263 Core API documentation update.
  com.unity.render-pipelines.core/Editor/ShaderGenerator/CSharpToHLSL.cs
  com.unity.render-pipelines.core/Editor/ShaderGenerator/ShaderGeneratorMenu.cs
  com.unity.render-pipelines.core/Runtime/Camera/CameraSwitcher.cs
  com.unity.render-pipelines.core/Runtime/Camera/FreeCamera.cs
  com.unity.render-pipelines.core/Runtime/Common/CommandBufferPool.cs
  com.unity.render-pipelines.core/Runtime/ShaderGenerator/ShaderGeneratorAttributes.cs
Labels: HDRP, docs, needs-backport-2019.3

#5264 Various scripting API doc update.
  com.unity.render-pipelines.core/Editor/Debugging/DebugState.cs
  com.unity.render-pipelines.core/Editor/Debugging/DebugUIDrawer.Builtins.cs
  com.unity.render-pipelines.core/Editor/Debugging/DebugUIDrawer.cs
  com.unity.render-pipelines.core/Editor/Debugging/DebugUIHandlerCanvasEditor.cs
  com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs
  com.unity.render-pipelines.core/Runtime/AssemblyInfo.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugManager.Actions.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugManager.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugUI.Containers.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugUI.Fields.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugUI.Panel.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugUI.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerBitField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerButton.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerCanvas.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerColor.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerContainer.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerEnumField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerEnumHistory.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerFloatField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerFoldout.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerGroup.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerHBox.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerIndirectFloatField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerIndirectToggle.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerIntField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerPanel.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerPersistentCanvas.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerToggle.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerToggleHistory.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerUIntField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerVBox.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerValue.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerVector2.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerVector3.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerVector4.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerWidget.cs
  com.unity.render-pipelines.core/Runtime/Textures/BufferedRTHandleSystem.cs
  com.unity.render-pipelines.core/Runtime/Textures/RTHandle.cs
  com.unity.render-pipelines.core/Runtime/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.core/Runtime/Textures/RTHandles.cs
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP, docs, needs-backport-2019.3

#5245 Fix shader warning for XboxOne
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Common/RayBinning.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Deferred/RaytracingDeferred.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/DiffuseDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/ReflectionDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/IndirectDiffuse/RaytracingIndirectDiffuse.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingFlagMask.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingLightCluster.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Reflections/RaytracingReflections.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/Sky/AmbientProbeConvolution.compute
Labels: HDRP, needs-backport-2019.3

#5272 [Yamato] Fix HDRP DXR yml file
  .yamato/upm-ci-hdrp_dxr.yml
Labels: needs-backport-2019.3

#5279 Fixed issues with the debug menu caused by a previous PR.
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerBitField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerButton.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerCanvas.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerColor.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerContainer.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerEnumField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerFloatField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerFoldout.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerGroup.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerIndirectFloatField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerIndirectToggle.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerIntField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerPanel.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerToggle.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerUIntField.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerValue.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerVector2.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerVector3.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/DebugUIHandlerVector4.cs
Labels: HDRP, needs-backport-2019.3

#5276 Universal/backport/pr 5205 5201
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderGUI/Shaders/LitShader.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2DData.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRendererData.cs
Labels: Universal

#5274 Fixing spot light cookies not working in ray traced reflections and GI
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
Labels: HDRP, dxr

#5292 Restored wrongly removed SetRenderTarget API
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
Labels: HDRP, needs-backport-2019.3

#5290 Hdrp/docs/procedural sky
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Master-Node-Unlit.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Procedural-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-Emission.md
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-Exposure.md
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-HD-Scene-Color.md
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-Parallax-Occlusion-Mapping.md
  com.unity.render-pipelines.high-definition/Documentation~/Scalability-Manual.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.3

#5287 Remove leftover code for stencil handling
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
Labels: HDRP, needs-backport-2019.3

#5285 Fix an inverted handling of CoatSmoothness for SSR in StackLit. (was …
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/StackLit/StackLit.hlsl
Labels: HDRP, needs-backport-2019.3

#5273 Updated missing API doc
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraph.cs
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraphResource.cs
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraphResourceRegistry.cs
  com.unity.render-pipelines.core/Runtime/RendererList/RendererList.cs
Labels: HDRP, needs-backport-2019.3

#5275 Dynamic resolution Doc update
  com.unity.render-pipelines.core/Runtime/Common/DynamicResolutionHandler.cs
  com.unity.render-pipelines.core/Runtime/Common/GlobalDynamicResolutionSettings.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Dynamic-Resolution.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5281 Added Reflection Probe cache info.
  com.unity.render-pipelines.high-definition/Documentation~/Creating-and-Editing-HDRP-Shader-Graphs.md
  com.unity.render-pipelines.high-definition/Documentation~/Default-Settings-Window.md
  com.unity.render-pipelines.high-definition/Documentation~/Environment-Lighting.md
  com.unity.render-pipelines.high-definition/Documentation~/Forward-And-Deferred-Rendering.md
  com.unity.render-pipelines.high-definition/Documentation~/Getting-started-with-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Gradient-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Override-Physically-Based-Sky.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Refraction-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Window.md
  com.unity.render-pipelines.high-definition/Documentation~/VR-in-HDRP.md
  com.unity.render-pipelines.high-definition/Documentation~/Volumes.md
Labels: HDRP, docs, needs-backport-2019.3

#5230 Re-add distortion inputs in material UI
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/LayeringOptionsUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/TransparencyUIBlock.cs
Labels: HDRP, needs-backport-2019.3

#5218 Stop the NaNs in Exposure to avoid it being propagate through time
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/Exposure.compute
Labels: HDRP, needs-backport-2019.3

#5211 Updated PLU description and HDRP Asset for terrain holes
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Documentation~/Physical-Light-Units.md
Labels: HDRP, docs, needs-backport-2019.3

#5204 Psvr fixes
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/UnityInstancing.hlsl
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Nodes/Input/Scene/CameraNode.cs
Labels: SRP, Shader Graph, XR, needs-backport-2019.3

#5210 Bloom thresholding
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Bloom.md
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/BloomEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Components/Bloom.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomCommon.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/BloomPrefilter.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, needs-backport-2019.3

#5282 Reinstate the second TAA pass (for the exclude from TAA)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP, needs-backport-2019.3

#4980 Analytics for shadergraph
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/ShaderGraphAnalytics.cs
  com.unity.shadergraph/Editor/ShaderGraphAnalytics.cs.meta
Labels: Shader Graph

#5269 Fixing ray traced reflections exposure issue
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, dxr, needs-backport-2019.3

#5080 Hide unused settings in legacy Quality Settings panel
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, backported-2019.3

#5295 Fix issue with vbufferparams not being initialized
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, needs-backport-2019.3

#5266 [Automation] Quality of Life improvements
  .github/PULL_REQUEST_TEMPLATE.md
  .github/labeler.yml
  .github/workflows/greetings.yml
  .github/workflows/labeler.yml
  .yamato/upm-ci-abv.yml
  .yamato/upm-ci-hdrp.yml
  .yamato/upm-ci-hdrp_dxr.yml
  .yamato/upm-ci-hdrp_standalone.yml
  .yamato/upm-ci-shadergraph.yml
  .yamato/upm-ci-shadergraph_stereo.yml
  .yamato/upm-ci-universal.yml
  .yamato/upm-ci-universal_stereo.yml
  .yamato/upm-ci-vfx_lwrp.yml
  .yamato/upm-ci-vfxmain.yml
  TestProjects/HDRP_RuntimeTests/Packages/manifest.json
  TestProjects/HDRP_Tests/Packages/manifest.json
  TestProjects/ShaderGraph/Packages/manifest.json
  TestProjects/ShaderGraphUniversalStereo/Packages/manifest.json
  TestProjects/UniversalGfxTestStereo/Packages/manifest.json
  TestProjects/UniversalGraphicsTest/Packages/manifest.json
  TestProjects/VisualEffectGraph/Packages/manifest.json
  TestProjects/VisualEffectGraph_LWRP/Packages/manifest.json
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.high-definition-config/CHANGELOG.md
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.shadergraph/CHANGELOG.md
Labels: HDRP, SRP, Shader Graph, Universal, testing, vfx, yamato

#5302 Add ENABLE_VR_MODULE to #if ENABLE_VR
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
Labels: Universal, backported-2019.3

#5305 Added comparison doc
  com.unity.render-pipelines.high-definition/Documentation~/Feature-Comparison.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.3

#5289 RT Denoiser fixes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/DiffuseDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
Labels: HDRP, dxr, needs-backport-2019.3

#4906 Implementing Ray Traced Color Shadows and Semi-Transparent Shadows
  com.unity.render-pipelines.core/ShaderLibrary/CommonLighting.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/SerializedHDLight.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedHDShadowInitParameters.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightEvaluation.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoopDef.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/SurfaceShading.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingVisibility.hlsl
  com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl
Labels: HDRP, dxr

#5307 Fixing the visibility of methods (ray tracing)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
Labels: HDRP, dxr

#5286 Null-check SceneView.lastActiveSceneView before attempting to access it
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineLightEditor.cs
Labels: Universal, needs-backport-2019.3

#5277 [Yamato] More custom Unity revision work
  .yamato/upm-ci-abv.yml
  .yamato/upm-ci-hdrp.yml
  .yamato/upm-ci-hdrp_dxr.yml
  .yamato/upm-ci-hdrp_standalone.yml
  .yamato/upm-ci-shadergraph.yml
  .yamato/upm-ci-shadergraph_stereo.yml
  .yamato/upm-ci-universal.yml
  .yamato/upm-ci-universal_stereo.yml
  .yamato/upm-ci-vfx_lwrp.yml
  .yamato/upm-ci-vfxmain.yml
Labels: yamato

#5310 Diffusion profile list not saved
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
Labels: HDRP

#5309 Hdrp/docs/shader update and fixes
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Master-Node-Hair.md
  com.unity.render-pipelines.high-definition/Documentation~/Unlit-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/Upgrading-To-HDRP.md
Labels: HDRP, docs, needs-backport-2019.3

#5306 Fixing crash when bounce count is > 1 for ray traced indirect
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingIndirect.hlsl
Labels: HDRP, dxr

#5213 Scale PCSS filter size with light distance occluder
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
Labels: HDRP, needs-backport-2019.3

#5268 Fixing exposure for path tracing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/Shaders/PathTracingMain.raytrace
Labels: HDRP, dxr

#5299 Fix for Two Reordering Bugs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GraphData.cs
Labels: Shader Graph, high-priority

#5318 Revert "Add ENABLE_VR_MODULE to #if ENABLE_VR (#5302)"
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
Labels: Universal

#5319 Bugfix: 'Depth Texture' drop down in the camera inspector incorrectly disabled
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
Labels: Universal, needs-backport-2019.3

#5321 Fix Lightweight API validation
  com.unity.render-pipelines.lightweight/Tests/Editor/Unity.Testing.Lightweight.EditorTests.asmdef
Labels: Universal, needs-backport-2019.3

#5293 [Yamato] Split build and run
  .yamato/upm-ci-hdrp_standalone.yml
  .yamato/upm-ci-shadergraph.yml
  .yamato/upm-ci-shadergraph_stereo.yml
  .yamato/upm-ci-universal.yml
  .yamato/upm-ci-universal_stereo.yml
  .yamato/upm-ci-vfx_lwrp.yml
  .yamato/upm-ci-vfxmain.yml
  TestProjects/HDRP_RuntimeTests/Packages/manifest.json
  TestProjects/SRP_SmokeTest/Packages/manifest.json
  TestProjects/ShaderGraph/Packages/manifest.json
  TestProjects/ShaderGraphUniversalStereo/Packages/manifest.json
  TestProjects/UniversalGfxTestStereo/Packages/manifest.json
  TestProjects/UniversalGraphicsTest/Packages/manifest.json
  TestProjects/VisualEffectGraph/Packages/manifest.json
  TestProjects/VisualEffectGraph_LWRP/Packages/manifest.json
  com.unity.testframework.graphics/Runtime/Newtonsoft.Json.dll
  com.unity.testframework.graphics/Runtime/Newtonsoft.Json.dll.meta
  com.unity.testframework.graphics/Runtime/Unity.TestProtocol.dll
  com.unity.testframework.graphics/Runtime/Unity.TestProtocol.dll.meta
  com.unity.testframework.graphics/package.json
Labels: needs-backport-2019.3

#5325 Fix AxF UI showing two times the advanced options
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/AxF/AxFGUI.cs
Labels: HDRP

#5311 [Yamato] Move HDRP-based tests back to 1080 cards [skip ci]
  .yamato/upm-ci-hdrp.yml
  .yamato/upm-ci-vfxmain.yml
Labels: yamato

#5233 Fixed an issue where cached sky contexts were being destroyed wrongly, breaking rendering in the LookDev
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/2211_Probes_Specular.png
  com.unity.render-pipelines.core/Editor/LookDev/Compositor.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDev.cs
  com.unity.render-pipelines.core/Editor/LookDev/LookDevRenderer.cs
  com.unity.render-pipelines.core/Editor/LookDev/Stage.cs
  com.unity.render-pipelines.core/Runtime/LookDev/IDataProvider.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LookDev.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, needs-backport-2019.3

#5317 Fix issue with premature softness clamping (before distance scale)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
Labels: HDRP, backported-2019.3

#5329 More API doc update
  com.unity.render-pipelines.core/Editor/LookDev/EnvironmentLibrary.cs
  com.unity.render-pipelines.core/Editor/PropertyFetcher.cs
  com.unity.render-pipelines.core/Editor/Utilities/SerializedBitArray.cs
  com.unity.render-pipelines.core/Runtime/Common/CommonStructs.cs
  com.unity.render-pipelines.core/Runtime/Common/ComponentSingleton.cs
  com.unity.render-pipelines.core/Runtime/Common/CoreUnsafeUtils.cs
  com.unity.render-pipelines.core/Runtime/Common/DynamicArray.cs
  com.unity.render-pipelines.core/Runtime/Common/ObjectPools.cs
  com.unity.render-pipelines.core/Runtime/Documentation.cs
Labels: SRP, needs-backport-2019.3

#5328 Hdrp/fix/fog affect transparency unlit master node
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
Labels: HDRP

#5327 Fix shader not included in build bug in custom pass doc example
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
Labels: HDRP

#5324 Improve a bit the custom post process template
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/Templates/CustomPostProcessingVolume.template
Labels: HDRP

#5323 Fix custom post processes re-ordering not saved.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
Labels: HDRP, needs-backport-2019.3

#5322 Fix NPE when using scalable settings and first editor start
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/ScalableSettingValue.cs
Labels: HDRP

#5320 Fixed an issue where PBR sky precomputed buffers would be recomputed when they should not.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyUpdateContext.cs
Labels: HDRP, needs-backport-2019.3

#5278 Add ENABLE_VR_MODULE to #if ENABLE_VR
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/UniversalGraphicsTests.cs
  TestProjects/UniversalGraphicsTest/Packages/manifest.json
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Unity.RenderPipelines.Universal.Runtime.asmdef
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal, high-priority, needs-backport-2019.3

#5316 [2019.3 Backport][XR] Add XR multipass rendering for Universal pipeline
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/Passes/DepthOnlyPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/ScriptableRenderPass.cs
  com.unity.render-pipelines.universal/Runtime/ScriptableRenderer.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipelineCore.cs
Labels: Universal

#5326 2d/lwrp fix
  com.unity.render-pipelines.lightweight/CHANGELOG.md
  com.unity.render-pipelines.lightweight/Shaders/2D/Include/CombinedShapeLightShared.hlsl
Labels: 2d, Universal, needs-backport-2019.3

#5346 [Yamato] Remove file change triggers
  .yamato/upm-ci-hdrp.yml
  .yamato/upm-ci-hdrp_standalone.yml
  .yamato/upm-ci-shadergraph.yml
  .yamato/upm-ci-shadergraph_stereo.yml
  .yamato/upm-ci-universal.yml
  .yamato/upm-ci-universal_stereo.yml
  .yamato/upm-ci-vfx_lwrp.yml
  .yamato/upm-ci-vfxmain.yml
Labels: yamato

#5341 fixed GLES2 compilation error
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/CommonDeprecated.hlsl
Labels: SRP, needs-backport-2019.3

#5348 Backport Fixing temporal denoiser #5340
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
Labels: HDRP, dxr

#5340 Fixing temporal denoiser
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
Labels: HDRP, dxr

#5350 Fixed a null ref exception caused by a previous PR
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyUpdateContext.cs
Labels: HDRP, needs-backport-2019.3

#5345 Hdrp/api doc update 4 [Skip CI]
  com.unity.render-pipelines.core/Editor/MaterialUpgrader.cs
  com.unity.render-pipelines.core/Editor/Utilities/EditorMaterialQuality.cs
  com.unity.render-pipelines.core/Runtime/Common/ObservableList.cs
  com.unity.render-pipelines.core/Runtime/Common/RectInt.cs
  com.unity.render-pipelines.core/Runtime/Common/RectInt.cs.meta
  com.unity.render-pipelines.core/Runtime/Common/SerializedDictionary.cs
  com.unity.render-pipelines.core/Runtime/Common/XRGraphics.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugUI.Fields.cs
  com.unity.render-pipelines.core/Runtime/Debugging/MousePositionDebug.cs
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingSample.cs
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraphResource.cs
  com.unity.render-pipelines.core/Runtime/Script/Profiler/MiniProfiler.cs
  com.unity.render-pipelines.core/Runtime/Script/Profiler/MiniProfiler.cs.meta
  com.unity.render-pipelines.core/Runtime/Textures/DepthBits.cs
  com.unity.render-pipelines.core/Runtime/Textures/MSAASamples.cs
  com.unity.render-pipelines.core/Runtime/Textures/TextureXR.cs
  com.unity.render-pipelines.core/Runtime/Utilities/BitArray.cs
  com.unity.render-pipelines.core/Runtime/Utilities/CameraCaptureBridge.cs
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.core/Runtime/Utilities/DelegateUtility.cs
  com.unity.render-pipelines.core/Runtime/Utilities/MaterialQuality.cs
  com.unity.render-pipelines.core/Runtime/Utilities/SceneRenderPipeline.cs
  com.unity.render-pipelines.core/Runtime/Utilities/TileLayoutUtils.cs
  com.unity.render-pipelines.core/Runtime/Utilities/XRUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/CoreResources/GPUCopy.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP, SRP, needs-backport-2019.3

#5336 Added note to contact shadows
  com.unity.render-pipelines.high-definition/Documentation~/Override-Contact-Shadows.md
Labels: HDRP, docs, needs-backport-2019.3

#5347 First batch of reviewed VFX Graph docs
  com.unity.visualeffectgraph/Documentation~/Attributes.md
  com.unity.visualeffectgraph/Documentation~/Blackboard.md
  com.unity.visualeffectgraph/Documentation~/Blocks.md
  com.unity.visualeffectgraph/Documentation~/ComponentAPI.md
  com.unity.visualeffectgraph/Documentation~/Contexts.md
  com.unity.visualeffectgraph/Documentation~/EventBinders.md
  com.unity.visualeffectgraph/Documentation~/Events.md
  com.unity.visualeffectgraph/Documentation~/GettingStarted.md
  com.unity.visualeffectgraph/Documentation~/GraphLogicAndPhilosophy.md
  com.unity.visualeffectgraph/Documentation~/Images/SystemDrawBox.png
  com.unity.visualeffectgraph/Documentation~/Operators.md
  com.unity.visualeffectgraph/Documentation~/PointCacheBakeTool.md
  com.unity.visualeffectgraph/Documentation~/PointCaches.md
  com.unity.visualeffectgraph/Documentation~/Properties.md
  com.unity.visualeffectgraph/Documentation~/Subgraph.md
  com.unity.visualeffectgraph/Documentation~/Systems.md
  com.unity.visualeffectgraph/Documentation~/Timeline.md
  com.unity.visualeffectgraph/Documentation~/VectorFields.md
  com.unity.visualeffectgraph/Documentation~/VisualEffectComponent.md
  com.unity.visualeffectgraph/Documentation~/VisualEffectGraphAsset.md
  com.unity.visualeffectgraph/Documentation~/VisualEffectGraphWindow.md
  com.unity.visualeffectgraph/Documentation~/VisualEffectPreferences.md
  com.unity.visualeffectgraph/Documentation~/index.md
Labels: docs, needs-backport-2019.3, vfx

#5351 Vfx/2019.3 staging
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/PositionDepthOperator/Position(Depth) - Camera.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/PositionDepthOperator/Position(Depth) - Cull Mode.vfx
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/PositionDepthOperator/Position(Depth) - Mode.vfx
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXConvertSubgraph.cs
  com.unity.visualeffectgraph/Editor/Models/Blocks/Implementations/CameraHelper.cs
  com.unity.visualeffectgraph/Editor/Models/Blocks/Implementations/Collision/CollisionDepth.cs
  com.unity.visualeffectgraph/Editor/Models/Blocks/Implementations/Position/PositionDepth.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/PositionDepth.cs
  com.unity.visualeffectgraph/Editor/ShaderGraph/VFXShaderGraphParticleOutput.cs
Labels: vfx

#5338 Move AO rendering down the pipe to make sure normal buffer is set
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5237 Move TextureCombiner class to proper namespace and add doc.
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Core/TextureCombiner/TextureCombiner.cs
Labels: HDRP, docs, needs-backport-2019.3

#5352 Fix Redo for Shader Graph
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph

#5357 Fixed Redo for Shader Graph [Backport]
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
Labels: Shader Graph

#5358 Fix URP Terrain Material Using per-vertex normals (Bug 1110520)
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/Materials/TerrainLit.mat
Labels: 2d, Universal, needs-backport-2019.3

#5294 [VFX] Fix editor test
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXComponentTest.cs
Labels: vfx

#5366 More api doc [Skip CI]
  com.unity.render-pipelines.core/Editor/FilterWindow.cs
Labels: HDRP, SRP

#5370 Fix a migration issue with project that still had Very High as shadow filtering quality [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
Labels: HDRP, needs-backport-2019.3

#5371 Hide near plane from directional shadow UI [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
Labels: HDRP, needs-backport-2019.3

#5365 Better custom pass culling
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
Labels: HDRP

#5356 Hdrp/fix missing editor documentation
  com.unity.render-pipelines.core/Editor/CameraEditorUtils.cs
  com.unity.render-pipelines.core/Editor/ContextualMenuDispatcher.cs
  com.unity.render-pipelines.core/Editor/CoreEditorDrawers.cs
  com.unity.render-pipelines.core/Editor/CoreEditorUtils.cs
  com.unity.render-pipelines.core/Editor/EditorPrefBoolFlags.cs
  com.unity.render-pipelines.core/Editor/Gizmo/HierarchicalBox.cs
  com.unity.render-pipelines.core/Editor/Gizmo/HierarchicalSphere.cs
  com.unity.render-pipelines.core/Editor/Lighting/CoreLightEditorUtilities.cs
  com.unity.render-pipelines.core/Editor/QuaternionPropertyDrawer.cs
  com.unity.render-pipelines.core/Runtime/Common/CoreUnsafeUtils.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugManager.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugShapes.cs
  com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Scripts/UIFoldout.cs
  com.unity.render-pipelines.core/Runtime/LookDev/IDataProvider.cs
  com.unity.render-pipelines.core/Runtime/Utilities/TileLayoutUtils.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.Handles.cs
Labels: HDRP, SRP

#5361 Make default URP terrain shader compile without errors or warnings
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBasemapGen.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitMetaPass.hlsl
Labels: Universal, needs-backport-2019.3

#5363 [Backport] Make default URP terrain shader compile without errors or warnings
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitBasemapGen.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitMetaPass.hlsl
Labels: Universal

#5376 Hide Distortion from Lit UI again [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
Labels: HDRP, needs-backport-2019.3

#5375 Fix issues of decals duplicating and baking into the scene when editing
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs
Labels: HDRP, needs-backport-2019.3

#5373 Fix and simplify initialization of volumetric buffer params
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/Fog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5369 Fixed an issue where frame count was reset incorrectly every frame for the game view, resulting in temporal processes breaking.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5374 Added support for physical parameters in the scene view camera
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, needs-backport-2019.3

#5393 Fix warning on vulkan and metal due to DebugLightCluster.shader not having a fallback
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/DebugLightCluster.shader
Labels: HDRP, needs-backport-2019.3

#5394 Fix TerrainLitGUI when per-pixel normal property is not present.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/TerrainLit/TerrainLitGUI.cs
Labels: HDRP, needs-backport-2019.3

#5386 Hdrp/docs/sg nodes
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-Diffusion-Profile.md
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-Emission.md
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-Exposure.md
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-HD-Scene-Color.md
  com.unity.render-pipelines.high-definition/Documentation~/SGNode-Parallax-Occlusion-Mapping.md
Labels: HDRP, docs, needs-backport-2019.3

#5401 Fix Culling group error
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#5384 Change the space where reflection filtering is done to avoid artifacts when intensities are high
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/ReflectionDenoiser.compute
Labels: HDRP, dxr

#5400 Split the SceneMapIdSceneAsset to its own file.
  com.unity.render-pipelines.high-definition/Runtime/Utilities/SceneObjectIDMap.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/SceneObjectIDMapSceneAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/SceneObjectIDMapSceneAsset.cs.meta
Labels: HDRP, needs-backport-2019.3

#5402 Expose debug overlay ratio
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
Labels: HDRP
