Repository Unity-Technologies/ScriptableRenderPipeline, pull requests merged in 2020-01, with the labels that each got.

#5391 Avoid UINT gathers in AO code
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOBlurAndUpsample.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAODenoise.compute
Labels: HDRP, needs-backport-2019.3

#5413 Fix culling group was not disposed error V2
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbeSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP

#5380 Fixed ambient probe not initialize for one frame after domain reload [Require C++ PR]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, needs-backport-2019.3

#5367 Separate frame settings for tonemapping and color grading
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/LutBuilder3D.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, needs-backport-2019.3

#4990 Refactor of Profiling in SRP to prepare for GPU profiling.
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingSample.cs
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingScope.cs
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingScope.cs.meta
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraph.cs
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraphProfileId.cs
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraphProfileId.cs.meta
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraphResourceRegistry.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugLightVolumes.cs
  com.unity.render-pipelines.high-definition/Runtime/Debug/RayCountManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbeCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/ReflectionProbeCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAtlas.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Fabric/IBLFilterCharlie.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/GGXConvolution/IBLFilterGGX.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/PreIntegratedFGD/PreIntegratedFGD.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SharedRTManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDProfileId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDProfileId.cs.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Debug.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.SubsurfaceScattering.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MipGenerator.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSkyRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.universal/Runtime/Passes/AdditionalLightsShadowCasterPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/DepthOnlyPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/DrawObjectsPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/MainLightShadowCasterPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPass.cs
  com.unity.render-pipelines.universal/Runtime/Passes/RenderObjectsPass.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipelineCore.cs
Labels: HDRP, SRP, Universal

#5312 Fix scene visibility of decal projector and density volume
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolumeManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.cs
Labels: HDRP

#5331 Expose fog transparent material
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyePass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitMasterNode.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitPass.template
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
Labels: HDRP, needs-backport-2019.3

#5342 [skip CI] Add visible in scene view property in Custom Post Process API
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing/CustomPostProcessVolumeComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP, needs-backport-2019.3

#5349 Custom pass materials editor in the Custom Pass Volume component
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassVolumeEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/DrawRenderersCustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/FullScreenCustomPass.cs
Labels: HDRP, needs-backport-2019.3

#5408 2019.3/universal/fix/035 shader terrainshaders
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/OpenGLCore/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Vulkan/035_Shader_TerrainShaders.png
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/Billboard.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD0/Branches_0.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD0/Leaves_1.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD1/Branches_0.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD1/Leaves_1.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD2/Branches_0.mat
  TestProjects/UniversalGraphicsTest/Assets/Scenes/035_Shader_TerrainShaders/Free_SpeedTrees/Broadleaf_Mobile Materials/LOD2/Leaves_1.mat
Labels: Universal

#5409 Fixed a leak in the sky system.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyUpdateContext.cs
Labels: HDRP, needs-backport-2019.3

#5398 Fixed an issue where entering playmode while the light editor is opened would produce null reference exceptions.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5303 Hdrp/fix search preference settings
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/OverridableFrameSettingsArea.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/QualitySettingsPanel.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/SerializedScalableSetting.cs
Labels: HDRP, needs-backport-2019.3

#5412 Fix debug menu overlap
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Debug-Window.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
Labels: HDRP, needs-backport-2019.3

#5423 Fix for the frame count when newtime < m_Time (when reloading the scene)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, dxr, needs-backport-2019.3

#5419 Only assign the reflection system when an HDRP asset is assigned
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDRuntimeReflectionSystem.cs
Labels: HDRP, needs-backport-2019.3

#5381 Disable Refraction and transmissionmap keywords when lit opaque
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
Labels: HDRP, dxr

#5343 Fix invalid near and far plane values
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/CameraSettingsUI.Drawers.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/SerializedCameraSettings.cs
  com.unity.render-pipelines.high-definition/Editor/Upgraders/UpgradeMenuItem.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/CameraSettings.cs
Labels: HDRP, needs-backport-2019.3

#5428 Hdrp/profiling 19 3
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingScope.cs
Labels: HDRP, SRP, needs-backport-2019.3

#4985 Properties starts as collapsed
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
Labels: Shader Graph

#5425 backport of system locale gradient prop issue
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
Labels: Shader Graph

#5195 Fix issues with conflicting internal names
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.EnvironmentLibrarySidePanel.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/EnvironmentLibrary.cs
  com.unity.render-pipelines.core/Editor/LookDev/ToolbarRadio.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.UIElement.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/Nodes/DiffusionProfileNode.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettingsHistory.cs
Labels: HDRP

#5217 Automate resources checking button with reflection
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRayTracingResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
Labels: HDRP

#5372 Fix issue with Motion Blur sample weighting
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlur.compute
Labels: HDRP, needs-backport-2019.3

#5389 Make motion vectors work properly in MSAA
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/SharedRTManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/MSAA/DepthValues.shader
Labels: HDRP, needs-backport-2019.3

#5436 [Yamato] Fix builds failing when running custom revision [skip ci]
  .yamato/upm-ci-hdrp.yml
  .yamato/upm-ci-hdrp_standalone.yml
  .yamato/upm-ci-shadergraph.yml
  .yamato/upm-ci-shadergraph_stereo.yml
  .yamato/upm-ci-universal.yml
  .yamato/upm-ci-universal_stereo.yml
  .yamato/upm-ci-vfx_lwrp.yml
  .yamato/upm-ci-vfxmain.yml
Labels: yamato

#5422 backport fix collapse uncollapse
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
Labels: Shader Graph

#5452 Small fixes for the PBR sky
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.shader
Labels: HDRP, needs-backport-2019.3

#5377 Fix ray traced screen space shadows
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCameraFrameHistoryType.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
Labels: HDRP, dxr

#5464 Added decal master node doc and removed mention of mobile platforms
  com.unity.render-pipelines.high-definition/Documentation~/Images/MasterNodeDecal1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/MasterNodeDecal2.png
  com.unity.render-pipelines.high-definition/Documentation~/Master-Node-Decal.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Documentation~/index.md
Labels: HDRP, docs, needs-backport-2019.3

#5458 Fix for a possible memory leak caused by a material not being disposed [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5453 Updated error message for invalid reflection system assigned
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDBakedReflectionSystem.cs
Labels: HDRP, needs-backport-2019.3

#5448 Update MSAA doc
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Anti-Aliasing.md
Labels: HDRP

#5442 Cleanup GC alloc fixes for 2019.3
  TestProjects/HDRP_Tests/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky/ProceduralSky.cs
  TestProjects/VisualEffectGraph/Assets/Samples/High Definition RP/Procedural Sky/Runtime/ProceduralSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/GradientSky/GradientSky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/HDRISky/HDRISky.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/PhysicallyBasedSky/PhysicallyBasedSky.cs
  com.unity.render-pipelines.high-definition/Samples~/ProceduralSky/Runtime/ProceduralSky/ProceduralSky.cs
  com.unity.testframework.graphics/Runtime/ImageAssert.cs
  com.unity.testing.hdrp/TestRunner/HDRP_GraphicTestRunner.cs
Labels: HDRP, needs-backport-2019.3, testing, vfx

#5437 Update culling data for reflection probe at runtime
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.Legacy.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDRuntimeReflectionSystem.cs
Labels: HDRP, needs-backport-2019.3

#5435 Added missing API doc.
  com.unity.render-pipelines.core/Editor/CameraEditorUtils.cs
  com.unity.render-pipelines.core/Runtime/Common/ObjectPools.cs
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingScope.cs
  com.unity.render-pipelines.core/Runtime/RenderGraph/RenderGraph.cs
Labels: SRP, needs-backport-2019.3

#5385 Lighting explorer fixes
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
Labels: HDRP, needs-backport-2019.3

#5364 Fixed a nullref in the volume framework [Skip CI]
  com.unity.render-pipelines.core/Editor/Volume/VolumeComponentListEditor.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP, SRP, needs-backport-2019.3

#5259 Fix issues with decals flickering or having missing parts on PS4 especially in VR.
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
Labels: HDRP, SRP, needs-backport-2019.3

#5265 New shader preprocessor compatibility
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/ShaderLibrary/Macros.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/UnityInstancing.hlsl
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitProperties.hlsl
  com.unity.visualeffectgraph/Shaders/VFXCommon.hlsl
Labels: HDRP, SRP

#5224 Shader use for Runtime Debug Display are now correctly strippep in release
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
Labels: HDRP, needs-backport-2019.3

#5469 Hdrp/fix 1207364 truncated labels
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/DefaultSettingsPanel.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, needs-backport-2019.3

#5430 Fixed Default post process Alpha [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, needs-backport-2019.3

#5471 Fix SSR test that got broken after the MSAA Motion Vector fix
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5454 Fix PCSS on directional shadows when punctual shadow atlas was not allocated yet
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowSampling.hlsl
Labels: HDRP, needs-backport-2019.3

#5383 HDRP Volume System update refactor [skip CI]
  com.unity.render-pipelines.core/Runtime/Volume/VolumeManager.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/AtmosphericScattering/Fog.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricLighting.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/SubsurfaceScattering/SubsurfaceScatteringManager.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDProfileId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.Prepass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/PathTracing/PathTracing.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingIndirectDiffuse.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingRecursiveRenderer.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingReflection.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkyManager.cs
Labels: HDRP, needs-backport-2019.3

#5467 Fix PCSS softness issue that used wrong softness for all cascades but the first
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl
Labels: HDRP, needs-backport-2019.3

#5466 Custom post process default asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP, needs-backport-2019.3

#5470 Fix invalid probe gizmo id
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDProbeUI.Skin.cs
Labels: HDRP, needs-backport-2019.3

#5474 Fix a warning in the raytracig shadow filter compute shader
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
Labels: HDRP, dxr

#5432 Fix issue with AO and small near plane
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAODenoise.compute
Labels: HDRP, needs-backport-2019.3

#5390 Fixed cleanup of custom post process
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/CustomPostProcessing/CustomPostProcessVolumeComponent.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
Labels: HDRP, needs-backport-2019.3

#5434 Fix issue that can cause light list to be invalid with multiple cameras and no lights in scene
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, needs-backport-2019.3

#5475 Fix shader warning in ao code [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAO.compute
Labels: HDRP, needs-backport-2019.3

#5477 Fixed a warning in simpledenoiser.compute
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/SimpleDenoiser.compute
Labels: HDRP, dxr

#5459 Fixed Tube/Rectangle light culling [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
Labels: HDRP, needs-backport-2019.3

#5463 Added a menu option that checks scene issues with ray tracing.
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineMenuItems.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
Labels: HDRP, SRP, dxr

#5482 Revert PR (#5434) "Fix issue that can cause light list to be invalid with multiple camera"
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, needs-backport-2019.3

#5484 Fix Profile marker mistmatch, gc alloc for sky and fix light explorer
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingScope.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
  com.unity.render-pipelines.high-definition/Runtime/Sky/SkySettings.cs
Labels: HDRP, SRP, backported-2019.3

#5468 Added API to update probe settings at runtime
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDProbe.cs
Labels: HDRP, needs-backport-2019.3

#5457 Disable Async for SSR, SSAO and Contact shadow when aggregated ray tracing frame setting is on
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, dxr, needs-backport-2019.3

#5415 Avoid uint gather in motion blur code
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/MotionBlurTilePass.compute
Labels: HDRP, needs-backport-2019.3

#5238 Contrast Adaptive Sharpen Integration
  com.unity.render-pipelines.core/Runtime/Common/GlobalDynamicResolutionSettings.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ContrastAdaptiveSharpen.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ContrastAdaptiveSharpen.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ffx_a.h
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ffx_a.h.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ffx_cas.h
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ffx_cas.h.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ffx_lpm.h
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ffx_lpm.h.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDProfileId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP

#5414 Improve play mode change speed
  com.unity.render-pipelines.core/Runtime/Utilities/CoreUtils.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureCache2D.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Textures/TextureCacheCubemap.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/PlanarReflectionProbeCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/ReflectionProbeCache.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/LTCAreaLight/LTCAreaLightCookieManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, SRP, needs-backport-2019.3

#5486 Fix name of profiling samplers (related to last fix PR for them) [Skip CI]
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingScope.cs
Labels: HDRP, SRP, needs-backport-2019.3

#5473 Documentation fixes
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Post-Process.md
Labels: HDRP, docs

#5476 Camera debug name
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Debug/DebugDisplay.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDProfileId.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5416 Fix issue with AO and Dynamic Resolution
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/AmbientOcclusion.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAOCommon.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/GTAODenoise.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
Labels: HDRP, needs-backport-2019.3

#5489 Remove some possible NaNs sources in DoF
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoC.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCoCReproject.compute
Labels: HDRP, needs-backport-2019.3

#5429 Improve custom pass
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassVolumeEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
Labels: HDRP, needs-backport-2019.3

#5440 Fixed particle lights null ref [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Types.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP, needs-backport-2019.3

#5396 Support for alpha channel in some post-processing passes (DoF, TAA, Uber)
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Asset.md
  com.unity.render-pipelines.high-definition/Editor/PostProcessing/SerializedGlobalPostProcessSettings.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.Skin.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDRenderPipelineUI.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/GlobalPostProcessSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldCombine.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldGather.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldMip.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldMipSafe.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/DepthOfFieldPrefilter.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/FinalPass.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/PostProcessDefines.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/PostProcessDefines.hlsl.meta
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/RTUpscale.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntiAliasing.shader
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/TemporalAntialiasing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPost.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPostFeatures.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/UberPostFeatures.cs.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/RenderPipelineSettings.cs
Labels: HDRP, needs-backport-2019.3

#5478 Improved behavior of lights and probe going over the HDRP asset limits. [Skip CI]
  com.unity.render-pipelines.core/Runtime/Common/DynamicArray.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingLightCluster.cs
Labels: HDRP, SRP, needs-backport-2019.3

#5492 Clear Light list one we enter the "don't build light list" mode
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ClearLightLists.compute
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/ClearLightLists.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP, needs-backport-2019.3

#5496 Rename FrameSetting RoughRefraction to Refraction and add default particle material
  com.unity.render-pipelines.high-definition/Documentation~/Frame-Settings.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/HDRenderPipelineEditorResources.asset
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Material/DefaultHDParticleMaterial.mat
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Material/DefaultHDParticleMaterial.mat.meta
  com.unity.render-pipelines.high-definition/Tests/Editor/FrameSettingsTest.cs
Labels: HDRP, SRP, needs-backport-2019.3

#5449 Add test scenes for Custom Passes
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/BeforeOpaqueDepthAndNormal.shader
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/BeforeOpaqueDepthAndNormal.shader.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/FullScreen_BeforeOpaqueDepthAndNormal.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/FullScreen_BeforeOpaqueDepthAndNormal.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Opaque.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Opaque.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Outline.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Outline/Outline.cs
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Outline/Outline.cs.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Outline/Outline.shader
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Outline/Outline.shader.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Transparent.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Transparent.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreenSettings.lighting
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreenSettings.lighting.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers.unity.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers/BackgroundCube.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers/BackgroundCube.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers/Renderers_Renderers_Test.mat
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers/Renderers_Renderers_Test.mat.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers/Renderers_Test.shader
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers/Renderers_Test.shader.meta
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers/Scene Settings Profile.asset
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9701_CustomPass_DrawRenderers/Scene Settings Profile.asset.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9701_CustomPass_DrawRenderers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9701_CustomPass_DrawRenderers.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9701_CustomPass_DrawRenderers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9701_CustomPass_DrawRenderers.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9701_CustomPass_DrawRenderers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9701_CustomPass_DrawRenderers.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9701_CustomPass_DrawRenderers.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9701_CustomPass_DrawRenderers.png.meta
  TestProjects/HDRP_Tests/ProjectSettings/EditorBuildSettings.asset
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
Labels: HDRP, needs-backport-2019.3

#5497 Removed Black1x1.jpg as it's not used and causing a package validation issue.
  com.unity.render-pipelines.universal/Textures/2D.meta
  com.unity.render-pipelines.universal/Textures/2D/Black1x1.jpg
  com.unity.render-pipelines.universal/Textures/2D/Black1x1.jpg.meta
Labels: 2d, Universal, needs-backport-2019.3

#5500 Removed unused function
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
Labels: HDRP

#5417 Disable vsync on the main display when rendering to a XR device
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRSystem.cs
Labels: HDRP, XR, needs-backport-2019.3

#5507 Custom pass cleanup
  com.unity.render-pipelines.core/Runtime/Textures/RTHandleSystem.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
Labels: HDRP, SRP, needs-backport-2019.3

#5508 Testing/disable scene005
  TestProjects/UniversalGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  TestProjects/VisualEffectGraph_LWRP/Assets/ForwardRenderer.asset
  TestProjects/VisualEffectGraph_LWRP/Assets/LWRP.asset
  TestProjects/VisualEffectGraph_LWRP/ProjectSettings/EditorBuildSettings.asset
Labels: Universal, testing, vfx

#5283 Delay discard of fragments during decal projection
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLitData.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassDecal.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassForward.hlsl
Labels: HDRP, Shader Graph, needs-backport-2019.3

#5510 Change the default volume used by the ray tracing tests to make them work again
  TestProjects/HDRP_DXR_Tests/Assets/Common/HDRenderPipelineAsset.asset
  TestProjects/HDRP_DXR_Tests/Assets/HDRPDefaultResources/DefaultPostprocessingSettings.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
Labels: HDRP, dxr, testing

#5511 Missing term in the ray tracing frame index access
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingAmbientOcclusion.cs
Labels: HDRP, dxr

#5445 backport for #5444 duplicate property name issue
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
Labels: Shader Graph

#5501 Backport Universal 2D Renderer Improvements #5169
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/2D/Light2DEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/Renderer2DDataEditor.cs
  com.unity.render-pipelines.universal/Editor/2D/Renderer2DUpgrader.cs
  com.unity.render-pipelines.universal/Editor/2D/SortingLayerDropDown.cs
  com.unity.render-pipelines.universal/Runtime/2D/Light2D.cs
  com.unity.render-pipelines.universal/Runtime/2D/Light2DBlendStyle.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs
  com.unity.render-pipelines.universal/Runtime/2D/Passes/Utility/RendererLighting.cs
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCamera.cs
  com.unity.render-pipelines.universal/Runtime/2D/PixelPerfectCameraInternal.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2DData.cs
  com.unity.render-pipelines.universal/Runtime/Materials/Sprite-Unlit-Default.mat
  com.unity.render-pipelines.universal/Runtime/Materials/Sprite-Unlit-Default.mat.meta
  com.unity.render-pipelines.universal/Tests/Runtime/PixelPerfectCameraTests.cs
Labels: 2d, Universal

#5062 Fix for: "Properties from the Blackboard can be dragged into the Graph when Blackboard is disabled"
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph, needs-backport-2019.3

#5517 Fix colum headers
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightExplorerExtension.cs
Labels: HDRP, needs-backport-2019.3

#5505 Rename post formats
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/GlobalPostProcessSettings.cs
Labels: HDRP, needs-backport-2019.3

#5491 Fixed the first frame flash with auto exposure
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/PostProcessSystem.cs
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ApplyExposure.compute
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ApplyExposure.compute.meta
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/HDRenderPipelineResources.asset
Labels: HDRP, needs-backport-2019.3

#5493 Hdrp/small enhencements for DXR
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.Configuration.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/FrameSettingsUI.Drawers.cs
Labels: HDRP, needs-backport-2019.3

#5485 Hdrp/update default scenes
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/DXR Settings.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/DXR Settings.asset.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/DefaultSceneRoot.prefab
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/DefaultSceneRoot.prefab.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/Scene PostProcess Profile.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/Sky and Fog Settings Profile.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultDXRScene/Sky and Fog Settings Profile.asset.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultSceneRoot.prefab
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/DefaultSceneRoot.prefab.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDWizard.UIElement.cs
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/Scene PostProcess Profile.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/Scene PostProcess Profile.asset.meta
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/Sky and Fog Settings Profile.asset
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/Sky and Fog Settings Profile.asset.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/DefaultSettingsVolumeProfile.asset
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/DefaultSettingsVolumeProfile.asset.meta
  com.unity.render-pipelines.high-definition/Editor/RenderPipelineResources/HDRenderPipelineEditorResources.asset
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Settings/FrameSettings.cs
Labels: HDRP, needs-backport-2019.3

#5527 [Backport] Fixed chromatic aberration test & associated ref images
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/Metal/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/OpenGLCore/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXEditor/OpenGLCore/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/Metal/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/OSXPlayer/OpenGLCore/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Vulkan/071_ChromaticAberration.png
  TestProjects/UniversalGraphicsTest/Assets/ReferenceImages/Linear/WindowsPlayer/Vulkan/071_ChromaticAberration.png.meta
  TestProjects/UniversalGraphicsTest/Assets/Scenes/071_ChromaticAberration.unity
Labels: Universal

#5528 Remove lwrp files added by mistake.
  com.unity.render-pipelines.lightweight/Editor/Gizmos/Camera_Base.png
  com.unity.render-pipelines.lightweight/Editor/Gizmos/Camera_Base.png.meta
  com.unity.render-pipelines.lightweight/Editor/Gizmos/Camera_Offscreen.png
  com.unity.render-pipelines.lightweight/Editor/Gizmos/Camera_Offscreen.png.meta
  com.unity.render-pipelines.lightweight/Editor/Gizmos/Camera_Overlay.png
  com.unity.render-pipelines.lightweight/Editor/Gizmos/Camera_Overlay.png.meta
  com.unity.render-pipelines.lightweight/Editor/Gizmos/Camera_UI.png
  com.unity.render-pipelines.lightweight/Editor/Gizmos/Camera_UI.png.meta
  com.unity.render-pipelines.lightweight/Editor/LightweightRenderPipelineCameraEditor.cs
Labels: Universal

#5509 Hdrp/staging thin
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitPass.template
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/RefractionUIBlock.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitPathTracing.hlsl
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
Labels: HDRP, needs-backport-2019.3

#5543 Reverting a change to CopyDepthPass's RenderPassEvent
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
Labels: Universal, needs-backport-2019.3

#5546 Backport -> Reverting a change to CopyDepthPass's RenderPassEvent (#5543)
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
Labels: Universal

#5522 Fixed URP compile errors when vr module is excluded from the project.
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipelineCore.cs
Labels: Universal, XR, needs-backport-2019.3

#5541 Re-enabling the disabled GI tests
  TestProjects/UniversalGraphicsTest/ProjectSettings/EditorBuildSettings.asset
  TestProjects/VisualEffectGraph_LWRP/ProjectSettings/EditorBuildSettings.asset
Labels: Universal, testing, vfx

#5547 [2019.3 Backport] Fixed URP compile errors when vr module is excluded from the project. (#5522)
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipelineCore.cs
Labels: Universal

#5549 Fixed camera stacking warning when using custom renderer
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal, needs-backport-2019.3

#5354 Universal/PPv2 compatibility layer
  com.unity.render-pipelines.universal/Editor/Overrides/BloomEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/ChannelMixerEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/ChromaticAberrationEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/ChromaticAberrationEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/Overrides/ColorAdjustmentsEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/ColorAdjustmentsEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/Overrides/ColorCurvesEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/ColorLookupEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/DepthOfFieldEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/FilmGrainEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/LensDistortionEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/LensDistortionEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/Overrides/LiftGammaGainEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/MotionBlurEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/PaniniProjectionEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/PaniniProjectionEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/Overrides/ShadowsMidtonesHighlightsEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/SplitToningEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/SplitToningEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/Overrides/TonemappingEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/VignetteEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/VignetteEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/Overrides/WhiteBalanceEditor.cs
  com.unity.render-pipelines.universal/Editor/Overrides/WhiteBalanceEditor.cs.meta
  com.unity.render-pipelines.universal/Editor/Unity.RenderPipelines.Universal.Editor.asmdef
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineAssetEditor.cs
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
  com.unity.render-pipelines.universal/Runtime/2D/Renderer2D.cs
  com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPassCompat.cs
  com.unity.render-pipelines.universal/Runtime/Passes/PostProcessPassCompat.cs.meta
  com.unity.render-pipelines.universal/Runtime/Passes/ScriptableRenderPass.cs
  com.unity.render-pipelines.universal/Runtime/RenderingUtils.cs
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal, high-priority

#5550 Fix warning about cameras stacking usage in a custom renderer. (#5549) [Skip CI]
  com.unity.render-pipelines.universal/Runtime/UniversalRenderPipeline.cs
Labels: Universal

#5555 Fixed an issue where passing a null ProfilingSampler would cause a null ref exception.
  com.unity.render-pipelines.core/Runtime/Debugging/ProfilingScope.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: HDRP, SRP, needs-backport-2019.3

#5481 Shader Graph Blackboard: Scientific Notation Fix (+Infinity support)
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Graphs/VectorShaderProperty.cs
  com.unity.shadergraph/Editor/Data/Implementation/NodeUtils.cs
Labels: Shader Graph, needs-backport-2019.3

#5563 [Backport] Shader Graph memory leak plumbing
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Implementation/GraphObject.cs
  com.unity.shadergraph/Editor/Data/Nodes/AbstractMaterialNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/CodeFunctionNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture2DArrayNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture2DLODNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Input/Texture/SampleTexture2DNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSplitNode.cs
  com.unity.shadergraph/Editor/Data/Nodes/UV/FlipbookNode.cs
  com.unity.shadergraph/Editor/Data/Util/PooledList.cs
  com.unity.shadergraph/Editor/Data/Util/PooledList.cs.meta
  com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
  com.unity.shadergraph/Editor/Drawing/PreviewManager.cs
  com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
Labels: Shader Graph

#5570 Corrected the light layers description for reflection probes.
  com.unity.render-pipelines.high-definition/Documentation~/Planar-Reflection-Probe.md
  com.unity.render-pipelines.high-definition/Documentation~/Reflection-Probe.md
Labels: HDRP, docs, needs-backport-2019.3

#5544 Fixing the area shadow denoised test
  TestProjects/HDRP_DXR_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D12/3002_AreaShadows_Denoiser.png
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadowFilter.compute
Labels: HDRP, dxr, testing

#5556 Fix leak in Sky when matcap view
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5569 Move platform specific files to separate package
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/PSSL.hlsl.meta
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl
  com.unity.render-pipelines.core/ShaderLibrary/API/XBoxOne.hlsl.meta
  com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl
Labels: SRP, needs-backport-2019.3

#5574 backport #5278
  TestProjects/UniversalGraphicsTest/Assets/Test/Runtime/UniversalGraphicsTests.cs
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Unity.RenderPipelines.Universal.Runtime.asmdef
Labels: Universal

#5575 Fix compilation issues of ApplyExposure on platforms that don't support VR
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/ApplyExposure.compute
Labels: HDRP, needs-backport-2019.3

#5558 Vfx/2019.3 staging
  TestProjects/VisualEffectGraph/Assets/AllTests/Editor/Tests/VFXSpawnerTest.cs
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/08_ShadowsSettings.lighting.meta
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/Shadergraph/SampleScene/ShadergraphSampleScene.unity
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/Shadergraph/SampleScene/ShadergraphSampleScene/LightingData.asset
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/Timeline.playable
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/Timeline.unity
  TestProjects/VisualEffectGraph/Assets/AllTests/VFXTests/GraphicsTests/Timeline.vfx
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/Timeline.png
  TestProjects/VisualEffectGraph/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/Timeline.png
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/100_Fog.vfx
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/Shadergraph/SampleScene/101_ShadergraphSampleScene.unity
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/Shadergraph/SampleScene/101_ShadergraphSampleScene/LightingData.asset
  TestProjects/VisualEffectGraph_LWRP/Assets/GraphicsTests/Shadergraph/SampleScene/SampleScene.vfx
  TestProjects/VisualEffectGraph_LWRP/ProjectSettings/InputManager.asset
  TestProjects/VisualEffectGraph_LWRP/ProjectSettings/QualitySettings.asset
  com.unity.visualeffectgraph/CHANGELOG.md
  com.unity.visualeffectgraph/Documentation~/Images/PlayControls.png
  com.unity.visualeffectgraph/Documentation~/VisualEffectComponent.md
  com.unity.visualeffectgraph/Editor/Compiler/VFXGraphCompiledData.cs
  com.unity.visualeffectgraph/Editor/GraphView/Elements/Controllers/VFXDataAnchorController.cs
  com.unity.visualeffectgraph/Editor/GraphView/VFXComponentBoard.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXConvertSubgraph.cs
  com.unity.visualeffectgraph/Editor/GraphView/Views/VFXView.cs
  com.unity.visualeffectgraph/Editor/Inspector/AdvancedVisualEffectEditor.cs
  com.unity.visualeffectgraph/Editor/Inspector/VFXAssetEditor.cs
  com.unity.visualeffectgraph/Editor/Inspector/VisualEffectEditor.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/VFXContext.cs
  com.unity.visualeffectgraph/Editor/Models/Contexts/VFXSubgraphContext.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Ceiling.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Cosine.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Discretize.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Exp.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Floor.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Fractional.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Length.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Log.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Power.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Random.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Reciprocal.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Round.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Saturate.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Sine.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/SquareRoot.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/Implementations/Step.cs
  com.unity.visualeffectgraph/Editor/Models/Operators/VFXAbstractOperatorNew.cs
  com.unity.visualeffectgraph/Editor/Utilities/EventTester/VFXEventTesterWindow.cs
  com.unity.visualeffectgraph/Editor/Utils/VFXResources.cs
  com.unity.visualeffectgraph/Runtime/CustomSpawners/IncrementStripIndexOnStart.cs
  com.unity.visualeffectgraph/Runtime/Utilities/EventBinding/Implementation/VFXMouseEventBinder.cs
  com.unity.visualeffectgraph/Runtime/Utilities/EventBinding/Implementation/VFXRigidBodyCollisionEventBinder.cs
  com.unity.visualeffectgraph/Runtime/Utilities/EventBinding/Implementation/VFXTriggerEventBinder.cs
  com.unity.visualeffectgraph/Runtime/Utilities/PropertyBinding/ExposedProperty.cs
  com.unity.visualeffectgraph/Runtime/Utilities/PropertyBinding/Implementation/VFXSphereBinder.cs
  com.unity.visualeffectgraph/Shaders/Sort.compute
Labels: testing, vfx

#5580 HDRP asset migration
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
Labels: HDRP, needs-backport-2019.3

#5583 Docs/srp nda compliance
  com.unity.render-pipelines.high-definition/Documentation~/Building-For-Consoles.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.universal/Documentation~/Building-For-Consoles.md
  com.unity.render-pipelines.universal/Documentation~/TableOfContents.md
Labels: docs

#5515 [Shader Graph][Skip CI] Bug Fixes
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalPBRSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalUnlitSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalShaderGraphResources.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/ShaderGUI/PBRMasterGUI.cs
  com.unity.shadergraph/ShaderGraphLibrary/ShaderVariablesFunctions.hlsl
Labels: HDRP, Shader Graph, Universal, needs-backport-2019.3

#5564 [19.3][Shader Graph][Skip CI] Bug Fixes
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/UnlitSubShader.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalPBRSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/SubShaders/UniversalUnlitSubShader.cs
  com.unity.render-pipelines.universal/Editor/ShaderGraph/UniversalShaderGraphResources.cs
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/ShaderGUI/PBRMasterGUI.cs
  com.unity.shadergraph/ShaderGraphLibrary/ShaderVariablesFunctions.hlsl
Labels: HDRP, Shader Graph, Universal

#5444 Duplicate property name issue
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
Labels: Shader Graph

#5424 Sg/fix system locale gradient property
  com.unity.shadergraph/CHANGELOG.md
  com.unity.shadergraph/Editor/Data/Graphs/GradientShaderProperty.cs
Labels: Shader Graph, needs-backport-2019.3

#5577 Fix editor null ref exception.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
Labels: HDRP, needs-backport-2019.3

#5582 Fixed a null reference exception in the probe UI when no HDRP asset is present.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
Labels: HDRP, needs-backport-2019.3

#5590 Fix custom pass outline
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Outline/Outline.shader
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9700_CustomPass_FullScreen.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
Labels: HDRP, testing

#5596 Fixed a null reference exception in the HDRI Sky editor when no HDRP asset is present
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Sky/HDRISky/HDRISkyEditor.cs
Labels: HDRP, needs-backport-2019.3

#5599 Bugfix 1176131: Editor Crash when using additional lights
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs
  com.unity.render-pipelines.universal/Runtime/Passes/AdditionalLightsShadowCasterPass.cs
Labels: Universal, high-priority, needs-backport-2019.3

#5602 Lit Tessellation Shader doc
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Config-Package.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/LitTessellationShader1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LitTessellationShader2.png
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Tessellation-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
Labels: HDRP, docs, needs-backport-2019.3

#5592 Fix decal orientation when created from script.
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1601_TerrainLit.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1701_Decals.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1703_Decals-ReorientedNormals.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1704_Decals-Settings.unity
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDProjectSettings.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalMenuItems.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/MigrationDescription.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/ProxyVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/TypeInfo.cs
Labels: HDRP, needs-backport-2019.3, testing

#5548 Refactor of HDCamera (accesibility mostly) [Skip CI]
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, needs-backport-2019.3

#5595 forward port Docs/srp nda compliance (#5583) [Skip CI]
  com.unity.render-pipelines.high-definition/Documentation~/Building-For-Consoles.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.universal/Documentation~/Building-For-Consoles.md
  com.unity.render-pipelines.universal/Documentation~/TableOfContents.md
Labels: HDRP, SRP, Universal, docs

#5589 Fix visibility of Density Volumes in reflections [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Core/Utilities/GeometryUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
Labels: HDRP, needs-backport-2019.3

#5597 Fixed null ref exception in various editors.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/PathTracing/PathTracingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RecursiveRenderingEditor.cs
Labels: HDRP, needs-backport-2019.3

#5554 Fix dispatcher to only perform remove Camera if no component depends on it
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/ContextualMenuDispatcher.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraEditor.cs
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
Labels: HDRP, SRP, Universal, needs-backport-2019.3

#5606 Merge Hdrp/staging
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1601_TerrainLit.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1701_Decals.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1703_Decals-ReorientedNormals.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1704_Decals-Settings.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Outline/Outline.shader
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9700_CustomPass_FullScreen.png.meta
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDProjectSettings.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/PathTracing/PathTracingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RecursiveRenderingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/HDRISky/HDRISkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/MigrationDescription.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Utilities/GeometryUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/ProxyVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/TypeInfo.cs
Labels: HDRP, needs-backport-2019.3

#5604 Fix ray tracing tests and add a test scene for lights and cookies in ray tracing
  TestProjects/HDRP_DXR_Tests/Assets/Common/Texture.meta
  TestProjects/HDRP_DXR_Tests/Assets/Common/Texture/3DNoise.psd
  TestProjects/HDRP_DXR_Tests/Assets/Common/Texture/3DNoise.psd.meta
  TestProjects/HDRP_DXR_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D12/7001_LightCluster.png
  TestProjects/HDRP_DXR_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D12/7001_LightCluster.png.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster.unity
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster.unity.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster/Global Volume Profile.asset
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster/Global Volume Profile.asset.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster/M_Chrome.mat
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster/M_Chrome.mat.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster/M_Mirror.mat
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster/M_Mirror.mat.meta
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster/M_Rough.mat
  TestProjects/HDRP_DXR_Tests/Assets/Scenes/7001_LightCluster/M_Rough.mat.meta
  TestProjects/HDRP_DXR_Tests/ProjectSettings/EditorBuildSettings.asset
Labels: HDRP, dxr, testing

#5605 Expose StartSinglePass() and StopSinglePass() as public interface
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/XR/XRPass.cs
Labels: HDRP, XR, needs-backport-2019.3

#5530 Add missing custom pass API documentation
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassCSharpScript.template
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawer.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassDrawerAttribute.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassInjectionPoint.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPassVolume.cs
Labels: HDRP

#5607 Backport HDRP / SRP PR #5602, #5583, #5606, #5554
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1601_TerrainLit.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1701_Decals.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1703_Decals-ReorientedNormals.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/1x_Materials/1704_Decals-Settings.unity
  TestProjects/HDRP_Tests/Assets/GraphicTests/Scenes/9x_Other/9700_CustomPass_FullScreen/Outline/Outline.shader
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/OSXEditor/Metal/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Direct3D11/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsEditor/Vulkan/9700_CustomPass_FullScreen.png.meta
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9700_CustomPass_FullScreen.png
  TestProjects/HDRP_Tests/Assets/ReferenceImages/Linear/WindowsPlayer/Direct3D11/9700_CustomPass_FullScreen.png.meta
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/ContextualMenuDispatcher.cs
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Documentation~/Building-For-Consoles.md
  com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass.md
  com.unity.render-pipelines.high-definition/Documentation~/HDRP-Config-Package.md
  com.unity.render-pipelines.high-definition/Documentation~/Images/LitTessellationShader1.png
  com.unity.render-pipelines.high-definition/Documentation~/Images/LitTessellationShader2.png
  com.unity.render-pipelines.high-definition/Documentation~/Lit-Tessellation-Shader.md
  com.unity.render-pipelines.high-definition/Documentation~/TableOfContents.md
  com.unity.render-pipelines.high-definition/Editor/DefaultScene/HDProjectSettings.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/AmbientOcclusionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/HDLightUI.cs
  com.unity.render-pipelines.high-definition/Editor/Lighting/Reflection/HDScreenSpaceReflectionEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalMenuItems.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Camera/HDCameraEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/HDEditorUtils.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/PathTracing/PathTracingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/GlobalIlluminationEditor.cs
  com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Raytracing/RecursiveRenderingEditor.cs
  com.unity.render-pipelines.high-definition/Editor/Sky/HDRISky/HDRISkyEditor.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Migration/MigrationDescription.cs
  com.unity.render-pipelines.high-definition/Runtime/Core/Utilities/GeometryUtils.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Light/HDAdditionalLightData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/InfluenceVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/Volume/ProxyVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/DensityVolume.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/Decal/DecalProjector.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/DiffusionProfile/DiffusionProfileSettings.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineAsset.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineEditorResources.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPass/CustomPass/CustomPass.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/RenderPipelineResources.Migration.cs
  com.unity.render-pipelines.high-definition/Runtime/Utilities/TypeInfo.cs
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Documentation~/Building-For-Consoles.md
  com.unity.render-pipelines.universal/Documentation~/TableOfContents.md
  com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineCameraEditor.cs
Labels: HDRP, SRP, testing

#5560 Fix1189718
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Editor/ShaderGUI/TerrainLitShaderGUI.cs
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitInput.hlsl
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: Universal, needs-backport-2019.3

#5552 Disable the new input system for runtime debug menu
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs
  com.unity.render-pipelines.core/Runtime/Debugging/DebugManager.Actions.cs
  com.unity.render-pipelines.core/Runtime/Unity.RenderPipelines.Core.Runtime.asmdef
  com.unity.render-pipelines.high-definition/CHANGELOG.md
Labels: SRP, needs-backport-2019.3

#5587 Fixed XR Terrain rendering and shader compile issues
  com.unity.render-pipelines.universal/CHANGELOG.md
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainDetailLit.shader
  com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitPasses.hlsl
Labels: Universal, needs-backport-2019.3

#5614 Added Package Validation Config File
  com.unity.render-pipelines.core/ValidationConfig.json
  com.unity.render-pipelines.core/ValidationConfig.json.meta
Labels: SRP

#5584 added vulkan to shader multiview keyword check
  com.unity.render-pipelines.universal/ShaderLibrary/UnityInput.hlsl
Labels: Universal, needs-backport-2019.3

#5617 Push updated hdrp version in test project
  TestProjects/HDRP_Tests/ProjectSettings/HDRPProjectSettings.asset
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/MaterialPostProcessor.cs
Labels: HDRP, testing

#5620 Run the reimport check during editor update rather than on domain reload [Skip CI]
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/MaterialPostProcessor.cs
Labels: HDRP, needs-backport-2019.3

#5616 Make user stencil bits public
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStencilUsage.cs
Labels: HDRP

#5532 Implement history rejection based on object velocity
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/ScreenSpaceShadowManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDCamera.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRaytracingManager.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDTemporalFilter.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Denoising/TemporalFilter.compute
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/RaytracingIntersection.hlsl
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/Shadows/RaytracingShadow.raytrace
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassRaytracingVisibility.hlsl
Labels: HDRP, dxr, needs-backport-2019.3

#5603 Fixed initial state of material created through the context menu.
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/ShaderGraph/DecalGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Eye/ShaderGraph/EyeGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Fabric/ShaderGraph/FabricGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Hair/ShaderGraph/HairGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/LayeredLit/LayeredLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/LitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Lit/ShaderGraph/HDLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/StackLit/ShaderGraph/StackLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/TerrainLit/TerrainLitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/HDShaderGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/ShaderGraph/HDUnlitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/UnlitGUI.cs
Labels: HDRP, needs-backport-2019.3

#5621 Fix default material transparent created with ZWrite enabled
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/AssetProcessors/MaterialPostProcessor.cs
  com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/SurfaceOptionUIBlock.cs
  com.unity.render-pipelines.high-definition/Editor/Material/Unlit/BaseUnlitGUI.cs
  com.unity.render-pipelines.high-definition/Editor/ShaderGraph/HDSubShaderUtilities.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/AxF/AxF.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/LayeredLit/LayeredLitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/Lit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitTessellation.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/MaterialExtension.cs
  com.unity.render-pipelines.high-definition/Runtime/Material/TerrainLit/TerrainLit.shader
  com.unity.render-pipelines.high-definition/Runtime/Material/Unlit/Unlit.shader
  com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDStringConstants.cs
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Material/DefaultHDDecalMaterial.mat
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Material/DefaultHDMaterial.mat
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Material/DefaultHDMirrorMaterial.mat
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Material/DefaultHDParticleMaterial.mat
  com.unity.render-pipelines.high-definition/Runtime/RenderPipelineResources/Material/DefaultHDTerrainMaterial.mat
  com.unity.testing.hdrp/Scripts/Editor/ResetShaderGraphMaterialProperties.cs
Labels: HDRP

#5626 Hdrp/fix decal gizmo mouseover
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Editor/Material/Decal/DecalProjectorEditor.cs
Labels: HDRP, needs-backport-2019.3

#5619 Hdrp/smallfixes lookdev
  com.unity.render-pipelines.core/CHANGELOG.md
  com.unity.render-pipelines.core/Editor/LookDev/CameraController.cs
  com.unity.render-pipelines.core/Editor/LookDev/Context.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.EnvironmentLibrarySidePanel.cs
  com.unity.render-pipelines.core/Editor/LookDev/DisplayWindow.cs
  com.unity.render-pipelines.core/Editor/LookDev/EnvironmentLibrary.cs
Labels: SRP, needs-backport-2019.3

#5627 Mask was never set for some debug pixel deferred shaders [Skip CI]
  com.unity.render-pipelines.high-definition/CHANGELOG.md
  com.unity.render-pipelines.high-definition/Runtime/Lighting/Deferred.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/DeferredTile.shader
  com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
Labels: HDRP
